### ISSUE TITLE
Initial cards selection: please consider allowing all cards to be selected

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#1400]
Currently, the interface permits too few cards to be selected -- giving an error if you try to start -- but will not permit too many cards to be selected -- for example 3 preludes or 2 corporations.

However, for me, and I *think* for many other players, our process of deciding our initial cards is much more a process of progressively ruling OUT cards until the right number are left. That is, I would strongly prefer to begin by selecting ALL corps/preludes/projects, and then keep unclicking them until I'm down to the right number.

If I'm unusual in doing it this way, then of course there's no need to change anything here!

**Comment by nwai90** [comment]
@kevinb9n I'm not sure that this is the norm actually. It seems somewhat strange to me but this is definitely a matter of personal preference. I believe https://github.com/bafolts/terraforming-mars/issues/1285 which is being worked on right now would be quite helpful in that regard.

**Comment by kevinb9n** [comment]
I equally am not sure whether it is common, so we'll see what others have to say.

Example thought process: I have no VP icons, so I'll throw out Vitor. Next, I have no expensive cards, so I can throw out Excentric Sponsor. Let's also throw out all the project cards with late-game requirements. Now I can ponder what to do about everything that's left.

**Comment by kevinb9n** [comment]
I'd also question whether this change has any real downside? The card counts need to be checked when clicking "Start" anyway [currently, post-click, but ideally the button would just not be clickable]. And another error condition is "can't afford all these cards". This would just be another kind of "you selected too much" that could happen.

**Comment by kberg** [comment]
I thought I commented on this one earlier -- I also would prefer to select more cards than allowed, and be told to reduce them.

**Comment by kevinb9n** [comment]
At the risk of shocking everyone, I would even start by clicking a "select all cards" button if one were present. It's just how I roll....

**Comment by kberg** [comment]
This is fixed at head. To enable it use the Experimental UI option.

**Comment by kevinb9n** [comment]
Well that's pretty neat. Thanks, Rob.
