### ISSUE TITLE
Feature request: Play with some expansion cards but not rules

### ISSUE THREAD

**Issue by samyelias** [terraforming-mars/terraforming-mars#1445]
We often play without the Venus and Colonies expansions, but add in all the non-Venus/floater/colony related cards (and of course don't use the Venus and colony boards). It would be nice to have an option to do this.

**Comment by kevinb9n** [comment]
See #1440

**Comment by bafolts** [comment]
Using the same UI we use for including and excluding corporation cards would be simplest method to get this implemented. Could then expand upon it from there.

**Comment by Lynesth** [comment]
SInce I closed a duplicate here is what it was about: "include the project cards from the Prelude expansion, without using the Prelude cards".

**Comment by kevinb9n** [comment]
A few thoughts

* The ability to add individual cards would make this possible but not very user-friendly at all
* When adding even a single Venus-tag card with no Venus Next, what does that imply for Interplanetary Trade behavior? Likewise, Moon tags.
* Colonies has the most cards (by far) that are truly independent of the expansion they come with. Roughly half of those are floater cards, and including those with a Venus-no-Colonies game might make floater synergies a bit stronger (though gated a bit by the venus/jovian divide).
* And note that this ability already exists for corporation cards, where it introduces a few bugs, and they're the kind of bugs that aren't super motivating for anyone to fix: #2225

**Comment by kberg** [comment]
An update: This has recently been implemented. I need to add some warning that says "Look, incompatibility when you add your own cards is at your own risk." But, this feature is basically done.
