### ISSUE TITLE
I think tag requirements should show the icons

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#1457]
When viewing a card that requires a Jovian tag, there should be *some* way to find out what a Jovian tag looks like.

(I'm hoping to use this app to teach friends who don't already know the game, so I'm looking for interface elements that may trip them up.)

If this isn't possible on the card itself, then there should be *something* you can use to find out the icon-name correspondence for tags, such as clicking a tag in the tag tracker.

**Comment by vsrisuknimit** [comment]
@kevinb9n would alt text on the icons in the tags overview table help?

**Comment by alrusdi** [comment]
We have small Jovian icon. Why not to use it in requirements box instead of text?

**Comment by kevinb9n** [comment]
As long as there is *some* way to find this correspondence for both desktop and mobile users then I think the bug is probably resolved.

It still seems inconsistent that only in the case of requirements the cards diverge from their physical counterparts and choose text over icons. That text is then just duplicated below. If icons were used in requirement boxes, then you would know both icon form and word form from just looking at the card itself.

**Comment by vsrisuknimit** [comment]
@kevinb9n Does this help with your issue? http://terraforming-mars.herokuapp.com/help-iconology

I will work on integrating tags into the requirement box next.

**Comment by kevinb9n** [comment]
That guide is excellent - how can we make that available for players to pop up as needed?
I have minor suggestions about it if you want them somewhere. :-)

**Comment by vsrisuknimit** [comment]
Hi @kevinb9n here is fine.
- I hope to edit the help page further. Add a few more things.
- I would like to add a shortcut to the help page on the side bar. A question mark button.

**Comment by kevinb9n** [comment]
Ah, well, I already did put them onto the PR before I saw this. And it's a lot, but LMK if you want me to make em myself. (I should really start being useful around here.)

A ? in the sidebar is great - so the user can pull it up as they need it.

**Comment by kevinb9n** [comment]
I still wonder why we use text for requirements.

One weird effect of the current decision is that Celestic is claiming it won't draw the card Aerosport Tournament, but it actually does.
https://ssimeonoff.github.io/cards-list#CORP14#214

**Comment by kberg** [comment]
I basically agree with this request. Commenting to make it unstale.

**Comment by kberg** [comment]
I really want to implement this, it's bubbling up near the top of my list.

**Comment by kberg** [comment]
This is fixed!

**Comment by kevinb9n** [comment]
FWIW, I really like the results.
