### ISSUE TITLE
Bug: Pharmacy Union + Reds interaction

### ISSUE THREAD

**Issue by Lynesth** [terraforming-mars/terraforming-mars#1670]
With Reds ruling, playing a science card with PU that would leave you with less than needed to pay the Reds tax (either because you increase TR by 1 or by 3) is an **invalid** action, and you cannot play the card (or build a colony on Leavitt for example).
Triggers from playing a card are part of the effects of the card and all of them must be resolved (with the 3 exceptions).

If anyone need a source to read about this, [there you go](https://boardgamegeek.com/thread/2298086/reds-ruling-not-having-3-me-raising-tr#33274228).

**Comment by kberg** [comment]
Reopening this because there are TODOs that depend on this.

**Comment by kberg** [comment]
`TurmoilHandler.computeTerraformRatingBump` helps a lot here, but it doesn't have the card being computed. Or, in `Player.canPlay` by changing the card.tr value accordingly, but it would be pretty important to move that out of `Player.canPlay` so as to not clog things up.

I think this is now elegantly solveable. Amazing how much of an outlier this is, but it'll be fun to fix.

**Comment by kberg** [comment]
There's a few changes that are being made to centralize a lot more `canPlay` behavior, and slowly but surely this can take part in it.

**Comment by Borbarad2** [comment]
Is this now solved? 
In the last there was so many updates/PR about these kind of issue.

**Comment by kberg** [comment]
Upd

**Comment by kberg** [comment]
I accidentally deleted @Borbarad2's comment.

No, it's not fixed yet. More in the next comment

**Comment by kberg** [comment]
At this point, when evaluating if a card can be played, it takes into account how much TR a player will get from the action. It's not very accurate. Ares was significantly improved by predicting if a player would be able to afford placing a tile in any spaces; perhaps the only spaces are next to hazards.

The same thing can apply here. When computing the necessary TR, it's possible we can predict whether Pharmacy Union will trigger a TR. Question is, how many other places could this be? Interesting.

**Comment by kberg** [comment]
I'll stop here for now, but dealing with Reds costs and building colonies applies to Venus and Europa too comes next. Then when those are solid, this can also be resolved, and closed.
