### ISSUE TITLE
Tile resolution order is unreasonably harsh (I think?)

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#1753]
This was due to rewriting addTile with Ares.

Forcing a player to pay $ costs before getting bonuses, even though the bonuses could pay the adjacency costs is probably the wrong way to go. I wonder whether lysenth's `deferredActions` refactoring could help.

**Comment by Lynesth** [comment]
It depends, what cost are you refering to that the player is forced to pay before getting the bonuses ?

**Comment by kberg** [comment]
FAQ addresses this a bit, particularly regarding the costs for the Hellas ocean space. Specifically:

> D. Placement bonuses
> 
> * Resources granted by tile placement (steel, titanium, plants, heat.)
> * Money gained from placing a tile next to (a) water tile(s.)
> * Cards granted by a placement bonus.
> * Paying 6 MC for placing a tile on the south pole of the Hellas board and obtaining an ocean tile (if any are remaining.)
>
> Category D effects ... can only be obtained once a specific event occurs – namely a tile is placed.

But this mostly talks about how the activities of placing the tile are only addressed after placing the tile. Other adjacency costs (e.g. -2MC) might be offset by oceans or other Ares tiles, and Hazard adjacencies could be offset by the very peculiar case where you place a greenery which raises the oxygen, which raises temperature which gives the player the heat production to pay off placing next to the hazard.

I'm gonna close this one. I've lost most of the detailed context of the original, and my understanding of effects has changed greatly. What a naive coder I was!
