### ISSUE TITLE
I wish there was more logging from Turmoil

### ISSUE THREAD

**Issue by otolabqu** [terraforming-mars/terraforming-mars#1797]
The log should tell more basic info, like which party became ruling, which party got a neutral delegate, etc. 

Also the Gui components could be improved by forexample darkening the "consumed" neutral delegate parts of event cards, such that it's easier to quickly tell which party is getting a neutral delegate next time, and such.

**Comment by kberg** [comment]
There's another issue asking for more logging. I'd like more too. Someone mentioned yesterday to me that one factor was a matter of storage and bandwidth, keeping Heroku costs down. If that wasn't a big factor, I'd add a second level of logging, where details would be logged, and they would only be visible upon some form of conscious expansion. But still, thanks for the suggestion.

**Comment by Lynesth** [comment]
From closed issue:
> The running log of game events is helpful, particularly as I am learning the site and the interface. It would make sense to me to include the Turmoil ruling bonus effects in the log as well. Thanks for considering.

**Comment by kberg** [comment]
I think this addresses the first two items in the OP description. I'm considering that sufficient and closing the bug. If there's more to be done, yes, please reopen this.
