### ISSUE TITLE
[Ares] Bug - placing tile with no placement possibilities 

### ISSUE THREAD

**Issue by sienmich** [terraforming-mars/terraforming-mars#1823]
Hi,
during my game I played Research Outpost card. Only places without tiles next to it were Dust Storms, which require 8 / 16 $ to place there. However I do not have that much money. Currently I'm stuck inside this action.
Here is this my turn: https://terraforming-mars.herokuapp.com/player?id=a862fa2596d2

Here are some screenshots (im not sure if link above will work):
![Screenshot from 2020-11-04 00-25-24](https://user-images.githubusercontent.com/19472604/98051502-5483f980-1e34-11eb-9e3b-e1aa7ada70d4.png)
![Screenshot from 2020-11-04 00-25-34](https://user-images.githubusercontent.com/19472604/98051508-551c9000-1e34-11eb-8c34-c8da9cec2077.png)

Thanks for your awesome work!

**Comment by Lynesth** [comment]
It is a bug indeed as you shouldn't have been able to play that card if you couldn't place it. Thanks for reporting it.

**Comment by kberg** [comment]
Not stale, stalebot.

**Comment by kberg** [comment]
This is now fixed.
