### ISSUE TITLE
Rule errors with endgame plant conversion in both solo modes

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#2055]
**[EDIT: much of this turned out to be wrong, based on some very confused BGG threads, and a comment from Jacob that he later repudiated – see later comments for the real story]**

Partial reference - which is somewhat self-contradictory
https://boardgamegeek.com/thread/2054524/article/36461789#36461789

I'll lay out how I have concluded this is supposed to work – some of it does already and some doesn't.

1. In both solo modes, victory is decided immediately after the gen 14(12) production phase. The goal is to terraform within the time span of these generations, only. I am told on good authority (my kid) that she has won multiple times by placing an endgame greenery on a hazard tile for 2 TR, so that sounds like a bug to me.

2. Endgame plant conversion happens either way, but cannot change a loss into a win by any means.

**[EDIT: Again, I hope you're ignoring this. It's archival interest only.]**

3. In TR63 mode, it's been officially ruled that each convert-plants operation DOES try to raise O2, and a successful O2 raise DOES award TR. If you already won, this gets you more points; if you already lost, the purpose is just to annoy you, I guess, but this is apparently the rule. I think the app may not currently do this.

4. In the original TM rulebook (when there was only one solo mode), it is written that endgame plant conversion works differently and only places Greenery tiles *without* raising the oxygen. This is of little consequence since you lost anyway, and was perhaps done just to try to avoid people *thinking* they won whey they didn't. I believe this strange tweak isn't worth it and this app should house-rule it away, so that there is just one way that convert-plants always works.

5. This also implies that during endgame plant conversion on Hellas you can indeed place on the south pole to place an ocean and end up getting 2 TR together, so you can have the special joy of ending with 64+ TR and still losing.

6. I think it would be a very good idea to inform the user of their win/loss before plant conversion:

"You won! You may convert plants to greenery tiles for even more points"
or
"You lost! You may convert plants to greenery tiles for fun"

**Comment by kberg** [comment]
I have to admit that this has happened to me once or twice in the official app and it really surprised me and annoyed me. I am glad to know there's a reason. I agree that better communication would matter here.

**Comment by bafolts** [comment]
If victory is decided immediately after the final production phase I find it odd that in a solo game the greenery placement even takes place. The final greenery placement seems it is used to see how high of a score you can get assuming you have won and not to end up winning.

We always ignore oxygen increase when placing final greenery tiles.

https://github.com/bafolts/terraforming-mars/blob/main/src/Player.ts#L1773

If you have lost we could ignore the final greenery placement to not add insult to injury. If you have won we could ask if you even want to bother with final greenery placement.

@kberg which app are you referencing as "the official app"?

**Comment by kberg** [comment]
@bafolts I mean the steam app.

Yes, I think going a small step further in guiding unwary solo players would be a nice bit of help.

**Comment by kevinb9n** [comment]
Scratch all the above. The real deal is

1. "Only games you win are scored (after the extra placement of greenery tiles)." (https://boardgamegeek.com/thread/1705209/official-faq-rules-clarifications)

App should probably not report VP for a loss (it can be easily found anyway), nor do the endgame greenery round.

2. If you did win, you can still get more TR (e.g. from hazards or an ocean on Hellas). The only change is that greenery no longer raises O2 during the endgame (as it also doesn't during solo game setup).
(https://boardgamegeek.com/thread/2611160/article/37132579#37132579)

**Comment by kevinb9n** [comment]
So I would lightly propose that the user is shown a you-lost message immediately at the game-end check (just after final production), is not invited to place more tiles, and the summary page should not show VP. I know it seems harmless to have that "information" there but (a) they can just click back to the in-game interface to see it anyway, and (b) it really is misinformation and can give the user slightly corrupted incentives as they play the next time.

**Comment by kberg** [comment]
Do you still think this is the correct approach?

**Comment by kevinb9n** [comment]
Indeed my understanding hasn't changed since https://boardgamegeek.com/thread/2611160/article/37329843#37329843 and I would *probably* have seen any newer bgg posts that contradict it.

I do think some users might not like being told their score is 0, but based on the links I think it's what their score really is; that or "N/A".

**Comment by kevinb9n** [comment]
It would also help fix what is probably a very widely held misconception if the app gives a "you won" message right at the end of the last gen, and _then_ says (if applicable) that you can place greenery tiles to increase your score further (maybe even with "this will not raise oxygen").

**Comment by kberg** [comment]
OK, so how about this as a solution:

After passing for the final generation in a solo game, you are presented with a dialog explaining the situation. It either says, and these are up for wordsmithing,

> Congratulations. You have won the solo game! Place any final greeneries and look at the end-result.

or

> I'm sorry, you have lost. You needed to "requirement" but have not completed it in "x" generations. At this point your score is technically zero, and you are not allowed to add final greeneries. However, you may still complete the action."

I don't know how what the game end page says when losing. (I lose often, I just don't read it.) If it presents a score, then we'll also come up with something there to indicate, "this is a number, but your score is zero."

**Comment by kevinb9n** [comment]
Looks good

* Not sure the "score is zero" part is necessary here; if so, "the game will not be scored" might just go over better.
* "There is no final greenery placement round" might just go over better than "not allowed".
* What is "you may still complete the action"?
* I might suggest "You needed to complete all global parameters within $x generations." and "You needed a terraform rating of 63 or higher at the end of $x generations." (The first is simplified, relying on the fact that a maxed global param can never be reduced again, which I at least take to be a universal rule, whereas I expect a fan card could reduce TR at any time. However, both could be worded in the latter style.)

Your continued devotion to this app is amazing and appreciated.

**Comment by kberg** [comment]
> What is "you may still complete the action"?

I mean that as a matter of empathy, just give the player a chance to place the final greeneries and get the number which _could have been_ their score. Possibly cold comfort, /shrug

**Comment by kevinb9n** [comment]
Meh? I mean, the game is over at that point, so it's sort of akin to also saying we'll let you play more cards from your hand etc. I think it could just be confusing, but your call for sure.

**Comment by kberg** [comment]
I don't know if you're still on discord, but I've moved the question to https://discord.com/channels/737945098695999559/738006783955697704/1016026593304510494 for more active feedback.
