### ISSUE TITLE
I predict the RNG reuses numbers after reloading a game from the database

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#2132]
If I create and restore a game, the any RNG will start with a zero seed.A single RNG should be serialized with game, and restored. This probably subverts peoples' expectations. I bet in reality most people won't see the effect of this, but I think we should consider what to do with an RNG. This includes its behavior after serializing, or even, undoing an action.

Is a custom-made RNG really better for this kind of game? Probably not helpful as a "better random number generator," we're not really trying to solve that kind of problem. Is the goal of this RNG to provide a reusable RNG, as mentioned in a prior, now closed, pull request? Once again, how should this then deal with undo? If the goal is to provide fully repeatable tests, that requires a commitment which, as I mentioned in that PR, isn't really something I want to debug very much. :D

In my opinion, the best thing this RNG does is, when used, remove determinism from tests.

As for behavior,

1. one RNG per game, passed down when needed.
2. serialize the RNG's seed. The game's initial seed is unnecesary once the game goes live.
3. During undo, save the current RNG seed, restore the game, AND THEN restore the seed. This means undo maintains some randomness.
4. Whether undo should be allowed after a random event (or an event that reveals hidden information) is another topic entirely, not the point here.

**Comment by kberg** [comment]
As I think about it, this only applies to two cases:
1. Reshuffling the deck
2. The upcoming political agendas expansios -- under two conditions agendas are randomly selected.

**Comment by SliceOfBread** [comment]
Which RNG is seeded to 0? The internal JS Math.random() certainly is not.

**Comment by kberg** [comment]
> Which RNG is seeded to 0? The internal JS Math.random() certainly is not.

Poor writing on my part, mea culpa. I meant that it will restore the original seed.

**Comment by SliceOfBread** [comment]
> > Which RNG is seeded to 0? The internal JS Math.random() certainly is not.
> 
> Poor writing on my part, mea culpa. I meant that it will restore the original seed.

Ah, OK.

When I was looking at this stuff, the only thing that used the seedable RNG was the randomized tiles board. The JS random() is not seedable so unless something else has changed (entirely possible) I don't think this is an issue.

**Comment by kberg** [comment]
There's an issue in there, it's just _really minor._ I wanted a place to write my thoughts about it and this seemed to be the best place for documentation  on the matter.

I don't think this is an issue with the game running - except in the case of an undo of a redeal, and now, when using the Political Agendas expansion.

**Comment by SliceOfBread** [comment]
If random events are allowed to be undone then there could be an issue in using unseeded RNGs.
Example: say there is only one card left in the project deck and the player uses AI Central to gain 2 cards. This would cause a reshuffle of the discards. If the player can undo this and the reshuffle is removed, they could undo/redo they got a card they liked. This can be solved by not allowing the undo, not allowing the undo to undo the reshuffle or using a seeded RNG so the reshuffle would be the same every time.

I don't about the Political Agendas and so won't comment on them.

**Comment by kberg** [comment]
Agreed across the board (except Political Agendas, NBD)

>
