### ISSUE TITLE
Pharmacy Union interaction

### ISSUE THREAD

**Issue by ch0ka** [terraforming-mars/terraforming-mars#2191]
I was sitting at 0 MC and played Virus (got the discount). I had Media Group played earlier. Reds were not rulling.
What happened is that I got the 3 MC from Media group and then lost them to Corp action. 
Shouldn't it be the other way around - Adding a microbe, losing 4MC (in this case lose zero) and then get the Media group bonus? 
Not sure if this is a coding issue or it is supposed to happen like this. 
Game ID : 79bee9d5b74d

**Comment by gbfree** [comment]
If you hadn't played media group before you would not have been able to play virus : the effect removing your own ressource is mandatory (removing the ressource of any player isn't). If you can't pay, you are not able to play the card/do the action.
The active player (in the board game) choose the order of the effects, so you could (and had to) earn credits with the effect of media group before paying for the microbe.

**Comment by kevinb9n** [comment]
note this is the text on the kickstarter image:

<img width=400 src=https://user-images.githubusercontent.com/934551/105520329-6d5fb680-5c8f-11eb-965f-e8dd18cda0d9.png>

**Comment by kevinb9n** [comment]
To be more clear, I think this IS a bug as @ch0ka says.

@gbfree would be basically correct given the TEXT we are currently using on the card, but that text is wrong. Filed #2829 about that.

**Comment by kevinb9n** [comment]
I'm going to remove "non-critical" from bugs that get game rules wrong, which is not to say that they're CRITICAL, but I think "non-critical" is meant for more minor things that don't have even a tiny chance of throwing a game the wrong way.
