### ISSUE TITLE
Bug when Reds are on charge

### ISSUE THREAD

**Issue by Zolib80** [terraforming-mars/terraforming-mars#2193]
I was able to go down to -3MC when I got the bonus TR from the Venus board. See picture attached:
![bug](https://user-images.githubusercontent.com/68651711/103177778-4f13c000-4875-11eb-9578-45d4cd50234d.PNG)

**Comment by Zolib80** [comment]
It is still an issue...
![bug](https://user-images.githubusercontent.com/68651711/104857783-b53eb080-5912-11eb-9418-108126682f05.PNG)

**Comment by Lynesth** [comment]
Please know that we are more than aware about this, and that there's a lot more issues surrounding Reds.
Unfortunatly, it will stay unresolved for some time again.

**Comment by kberg** [comment]
This has been fixed. ref: https://github.com/terraforming-mars/terraforming-mars/blob/main/src/turmoil/TurmoilHandler.ts#L242

**Comment by kberg** [comment]
(That felt **good** to close.)
