### ISSUE TITLE
Next batch of small card iconography issues

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#2355]
@chosta 

* Ecoline is missing the oxygen reminder icon

* Celestic: Floater icons should be square

* Arcadian Communities: missing "Effect" banner (space?). Also does it want to use an actual player cube icon perhaps?

* MIssing asterisk: Factorum (action 1), Capital (ocean icon), Zeppelins (city icon)

* Commercial District, Martian Rails: missing red outline and asterisk

* Decomposers has extra slash

* Recruitment and Vote of No Confidence: each should have both a minus and a plus (or skip the plus for both if you prefer).

* This small black icon is only showing up in "max" requirement boxes
<img width=500 src=https://user-images.githubusercontent.com/934551/104382585-377a3f80-54e3-11eb-8bcd-6e4f1612e6e6.png>

* Using a yellow box here suggests that it has something to do with "min" requirements specifically (not "max"):
<img width=250 src=https://user-images.githubusercontent.com/934551/104382913-d737cd80-54e3-11eb-8ae3-2e2ac9c598f2.png>

It could perhaps do something more like this, or just leave out the color entirely?
<img width=170 height=30 src=https://user-images.githubusercontent.com/934551/104383095-1a923c00-54e4-11eb-9034-765b7540a7f2.png>

Applies to Inventrix, Adaptation Tech, Special Design, Morning Star, and Cutting Edge Tech. And Ecology Experts (but maybe that one should just be text-only like the card. I missed that last time, but there really is no icon with the meaning "play a card from hand").

* Not clear why Standard Tech is using a yellow box (that nearly resembles a min-requirement) at all.

* The Trade Fleet icon usually looks like this, is there a reason we don't use it?

<img width="50" alt="Trade Fleet Symbol" src="https://user-images.githubusercontent.com/934551/104407921-9eb1e700-5517-11eb-8a5d-eae590601e02.png">

* On cards like Aquifer Pumping, it would be cool if the resource-icon-in-parens could be a smaller superscript kinda thing.

**Comment by kevinb9n** [comment]
> * Ecoline is missing the oxygen reminder icon
confirmed fixed

> * Celestic: Floater icons should be square
Not fixed because round is supported and square isn't yet.
Cutting Edge has a rectangular one tho, howzat work?


> * Arcadian Communities: missing "Effect" banner (space?). Also does it want to use an actual player cube icon perhaps?
a) Not fixed because not supported and only 1-2 corps would use it
b) Was the second part considered? People know what a player cube looks like so it's odd that this doesn't look like that. It would also want to be a neutral color though – orange has become a player color.

> * MIssing asterisk: Factorum (action 1), Capital (ocean icon), Zeppelins (city icon)
understood only third one being fixed for now.

> * Commercial District, Martian Rails: missing red outline and asterisk
understood CD doesn't have a way to have its asterisk yet

> * Decomposers has extra slash
confirmed

> * Recruitment and Vote of No Confidence: each should have both a minus and a plus (or skip the plus for both if you prefer).
confirmed

> * This small black icon is only showing up in "max" requirement boxes
> 
> <img alt="" width="500" src="https://user-images.githubusercontent.com/934551/104382585-377a3f80-54e3-11eb-8bcd-6e4f1612e6e6.png">

It's better that it's consistent now. I was surprised the consistency was by removing it from all instead of adding it to all (like it is on the print cards). But if that was the intentional choice I surely have no problem with it!


> * Using a yellow box here suggests that it has something to do with "min" requirements specifically (not "max"):
> 
> <img alt="" width="250" src="https://user-images.githubusercontent.com/934551/104382913-d737cd80-54e3-11eb-8ae3-2e2ac9c598f2.png">
> 
> It could perhaps do something more like this, or just leave out the color entirely?
> <img alt="" width="170" height="30" src="https://user-images.githubusercontent.com/934551/104383095-1a923c00-54e4-11eb-9034-765b7540a7f2.png">
> 
> Applies to Inventrix, Adaptation Tech, Special Design, Morning Star,
Now looks less like a requirement box (corners are more rounder).
It still isn't clear what these things have in common with Standard Tech that makes them all want to have the same big yellow rounded box around them at all, but this isn't a "bug", just a visual quirk.

> and Cutting Edge Tech.
dropping this since print card has the same issue

> And Ecology Experts (but maybe that one should just be text-only like the card. I missed that last time, but there really is no icon with the meaning "play a card from hand").
Still _should_ be textified, but just saying it for the record, not important.

> * Not clear why Standard Tech is using a yellow box (that nearly resembles a min-requirement) at all.
whoops, commented on this just above.

> * The Trade Fleet icon usually looks like this, is there a reason we don't use it?
> 
> <img alt="Trade Fleet Symbol" width="50" src="https://user-images.githubusercontent.com/934551/104407921-9eb1e700-5517-11eb-8a5d-eae590601e02.png">
> 
> * On cards like Aquifer Pumping, it would be cool if the resource-icon-in-parens could be a smaller superscript kinda thing.
acknowledged that these two are for some other time.

**Comment by kberg** [comment]
> > * Celestic: Floater icons should be square
> 
> Not fixed because round is supported and square isn't yet. Cutting Edge has a rectangular one tho, howzat work?

Fixed
 
> > * Arcadian Communities: missing "Effect" banner (space?). Also does it want to use an actual player cube icon perhaps?
> 
> a) Not fixed because not supported and only 1-2 corps would use it b) Was the second part considered? People know what a player cube looks like so it's odd that this doesn't look like that. It would also want to be a neutral color though – orange has become a player color.

Player cubes are on other cards now, so this in theory should be easy to fix.

> > * Commercial District, Martian Rails: missing red outline and asterisk
> 
> understood CD doesn't have a way to have its asterisk yet

Ares Commercial District didn't have red border around the city. So that's fixed.

**Comment by kevinb9n** [comment]
> > > * Celestic: Floater icons should be square
> 
> Fixed

Nice, thanks

**Comment by Borbarad2** [comment]
What else is to do here? Could this issue already be closed? Old issue?

**Comment by kberg** [comment]
> Arcadian and others: would be nice to have both Effect and Action banners (this now applies to quite a few more than just 2 cards)

We're so crammed for space on these cards. Without a significant rehaul, don't hold out too much hope for this one. Not that I think you are, just saying.

> Arcadian: should use player cube icon

Perhaps, though it matches the image.
![image](https://user-images.githubusercontent.com/413481/218892574-264356d0-cc32-4046-aff1-52e820e06e16.png)

> Eco Experts: well, the iconography still doesn't really make sense imho...
Reference: ![image](https://user-images.githubusercontent.com/413481/218893142-0c4036c5-5843-47c1-9b76-f9f709b682a5.png)

What should it be?

> Standard Tech: well, the yellow box still doesn't really make sense imho...
Reference: ![image](https://user-images.githubusercontent.com/413481/218893254-0b09ba94-efb0-4c81-996b-4f25ae3cc0e3.png)

What should it be?

> cards with Trade Fleet icon: this seems to be the only significant case where the app uses a different icon from the printed cards...

Reference: ![image](https://user-images.githubusercontent.com/413481/218893489-ebe155d3-e028-40e8-9d2b-4bc266b84bf1.png)
![image](https://user-images.githubusercontent.com/413481/218893531-a31417c8-6813-46eb-8ff2-74b1d4b1b6db.png)

**Comment by kevinb9n** [comment]
I'll spare you any exceedingly boring responses because none of this matters and I have no motive to try to be "persuasive" about any of it. AFAIC this could be closed.

**Comment by kberg** [comment]
That's fine. I'd like to keep it open as a reference.

**Comment by kevinb9n** [comment]
Okay, in that case...

I take most of your points. I'll summarize what looks still worth having (even if not worth *doing*).

Factorum: action 1 needs asterisk
Capital: ocean icon needs asterisk
Commercial District: city icon needs asterisk
Eco Experts: would just do the allcaps text, same as the card
Trade Fleet icon: would use that "white up arrow" icon

**Comment by kberg** [comment]
Factorum already seems correct.
Trade fleet icon: already seems correct.

Capital is finishing up
Commercial District is finishing up
Ecology Experts: is finishing up
