### ISSUE TITLE
Agendas: proposed alternative chairperson variant

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#2423]
Here's an idea for a different chairperson variant for the Agendas expansion. @nwai90 

In this variant:

* When the game starts, each party has an initial ruling bonus and ruling policy, randomly chosen just like in the default variant.
* The incoming chairperson gets to change *either* the bonus or policy; the other remains the same.
* A neutral chairperson changes nothing.

We rarely have time to play over-the-table anymore so I can't say I have had a chance to test this idea out yet. But I *think* it would make for more interesting gameplay, and a *little* bit of continuity from generation to generation. It also preserves the quality, shared by all official expansions, that there is no in-game randomness except for the card decks.

**Comment by nwai90** [comment]
Sounds good @kevinb9n, I like the idea of the new chairman having limited influence

**Comment by nwai90** [comment]
Closed as already implemented
