### ISSUE TITLE
Feature Request - Full 10 cards at initial draft

### ISSUE THREAD

**Issue by markanarmi** [terraforming-mars/terraforming-mars#2514]
Can we have an alternate to the initial draft in which all 10 cards are drafted as one set?

**Comment by markanarmi** [comment]
I believe this is how it was done initially so perhaps the code still exists in the archives

**Comment by vsrisuknimit** [comment]
Last time @vincentneko looked into this. He said it was not easy to have two draft modes.

**Comment by vsrisuknimit** [comment]
![image](https://user-images.githubusercontent.com/14239220/110875115-09c33400-82a3-11eb-9ccf-0bc3f6d76bf4.png)

**Comment by kberg** [comment]
I am going to close this one as there remains no action or interest on it. Feel free to comment if you have anything to add.
