### ISSUE TITLE
Download a game's full history for forensic analysis

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#2553]
I would really like to figure out a way to take a game that has finished and download all the saves, in order to be able to recreate a player's bug report. This would be in the admin API so as to be controlled.

My concern, though, is what it would take to perform such a game export. If it were to become one massive JSON file, that'll be a heck of an internal string built up. More likely the response would be open and responses streamed down one at a time.

But before I take any of this on, does anyone have any other ideas? (Perhaps a command-line tool that just knows how to read postgres is better. I don't know, tips welcome.)

**Comment by bafolts** [comment]
Once a game has made it to the end of the game we call to `cleanSaves` which deletes the interim saves.

https://github.com/bafolts/terraforming-mars/blob/main/src/Game.ts#L978

With the smaller size of the JSON per save we most likely don't need to do this anymore. We would have been doing it as an optimization when our JSON was much larger.

Node can keep a response open and send the response in chunks so sending even a very large payload shouldn't be a problem. If there were an API route added to the server which used the generated server id as security I don't see this route being a problem. I do think heroku limits the response time to 30 seconds so it would have to complete within that time.

The command-line tool approach could probably use an `npm run get-game-data` or some other script.

**Comment by bafolts** [comment]
There are a set number of cards in the serialized JSON which will move around. It is probably easy to guess the average size of a save state. Can probably come up with an estimate for how large the response body size would be. If it were 10MB then the 30 second restriction is probably fine. If it were 100MB we would be pushing our luck that heroku wouldn't cut it off.

**Comment by kberg** [comment]
This is already done, except saving a game for a while even after it completes.
