### ISSUE TITLE
Log board resources on tile placement

### ISSUE THREAD

**Issue by puuj** [terraforming-mars/terraforming-mars#2586]
Currently, when a player places the tile, the log shows where the tile was placed, but the resources collected as a result are a matter of memorizing the board state (especially for random boards). I believe there have been visual representations that have been suggested, but a simple fix would be to log.
E.g.,
Red placed ocean tile on row 6 position 5
would become
Red placed ocean tile on row 6 position 5 and collected 1 steel

**Comment by chosta** [comment]
This, too, is part of #1233 and will be done in the upcoming months.

**Comment by vsrisuknimit** [comment]
Better log from chosta will help this. But #2626 should work on the mean time.

**Comment by kberg** [comment]
This will be done in a couple of days.

**Comment by kberg** [comment]
The only one missing now AFAICT is energy production from Arabia Terra, so closing after that is fixed.
