### ISSUE TITLE
RFC: Big problems we can solve with logging

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#2598]
After getting some time to read #1233 -- I really like where everything in this project is going, including that design.

There were a few places that I wanted to start taking the project, particularly as it pertains to logging, and all of it is related to the two underlying changes I started last month, introducing `Units` and removing `Game` where it is not necessary. It includes  @kevinb9n's notion of having a complete log. Although not a complete log in the technical sense, more in the experiential sense.

This is a lot of stuff, but I think it touches on all the pieces. Sorry about how long it is.

So now that 'game' has been removed from all the cards, the next step is to hide all the interesting player state behind methods. That means a couple of things:

1. Replacing the publicly accessible megaCredits, et cetera with property equivalents, and underneath, represent all of them by a `Units` instance.
2. Remove `game` from `player.setResource` and `player.setProduction`. `game` is only passed to indicate that the unit/production change is meant to be logged. So, ALWAYS log.
3. Units changes in 1 are also logged.

That can make a noisy log, I'll get to the log later.

3. Update the `player.setResource` and `player.setProduction` methods with `Units`-compatlble versions. This makes the code which does all those variable-resource and variable-production type changes much simpler to read, and easier to cluster into a single update (and a single log message -- eg `Robert reduced plant production 1 step and raised megacredit production 1 step.`
3a. @sienmich expressed interest in this refactoring. IMO now's a good time for it.
4. Define two more game log levels. Right now there are two: intergenerational, and everything else. The four levels might be "generation", "turn/action", "important action details", "minute action details".  Like what @Lynesth is doing with action priorities, this will take some discussion.
5. To deal with all this logging information, make these changes to the UI:
5a. Make the log bigger, a more vital part of the UI.
5b. Make it possible to collapse the 'minute action details' level like an IDE collapses blocks of code (maybe just for other players)
5c. Add a filter box that finds entries in the log

More logging information is also a scaling issue, so accordingly, I would make the following changes:
6. Server-side, put logging in its own table. It will reduce overall storage meaningfully, and make it easier to save the game much more frequently. Each log entry has an increasing number.
7. A client, when sending a request to the server, sends a number representing the last log entry it knows about. Server responses will only contain log entries newer than that log entry. This will reduce network bandwidth.
8. NOW, whatever the Undo operation does, the historical log stuff doesn't change. In other words, add a log entry "Player did an undo."
9. Now that storage has been significantly reduced (yay!) and will be further reduced by changing how logs are stored, save the game state much more often! In fact, save the game state upon every player decision.

And finally,
10. With saving the game state, include a boolean indicating whether the saved state included a card draw (or other unrevokable behavior.)
11. Undos may only go backward until they hit a row that can't be undone.
12. Make undo globally available.
13. When a game completes, don't delete it, make a version of the UI that makes the game replayable, step by step. Which is a much more interesting and detailed experience when changes are so carefully laid out.

**Comment by sienmich** [comment]
Tagging @chosta, he is working on the log, right?

For the `Units` let's discuss them in https://github.com/bafolts/terraforming-mars/issues/2599.

> 3a. @sienmich expressed interest in this refactoring. IMO now's a good time for it.

Yep, I'll gladly do that, once we agree on new Units idea in #2599.

>5b. Make it possible to collapse the 'minute action details' level like an IDE collapses blocks of code (maybe just for other players)

I like this one. Just to be sure, like this (?) :
```
[+] Red played ACQUIRED COMPANY
```
After clicking the `[+]`:
```
[-] Red played ACQUIRED COMPANY
       -10 MC
       +3 MC Prod
       Red draw a card from POINT LUNA
```

**Comment by chosta** [comment]
@sienmich I've not started working on it. There are things that need to happen in the correct order. I'll probably begin with some cosmetic overhaul.
@kberg this is the direction I was also hoping for. We can coordinate this with back and front-end work but I propose breaking it in to small and concrete tasks and assigning one or more devs to them.

**Comment by kberg** [comment]
@Danmir, if the general path is good, I'd probably start my next effort on
separating the log into its own table, and introducing the client-side
request to get log entries in pieces, as doing this first means adding more
logs won't have as much of an impact.

>

**Comment by chosta** [comment]
Great. Just keep me in the loop :)

**Comment by kevinb9n** [comment]
> 8. NOW, whatever the Undo operation does, the historical log stuff doesn't change. In other words, add a log entry "Player did an undo."

It's confusing in one way when the log messages go away, and confusing in a different way when they don't go away. An ideal compromise might be if, somehow, the undone messages could be surrounded with a box or shaded background. Sounds hard though. Barring that, I think the current confusion of things just disappearing is more *short-term* confusing, but the confusion of them sticking around can be more long-term. I think of undo like a time machine - the undone stuff just never happens.


> 10. With saving the game state, include a boolean indicating whether the saved state included a card draw (or other unrevokable behavior.)

As far as I know, I think the only unrevokables are seeing a formerly hidden card, and any time an opponent has a chance to do something during your action (main example being Philares).


> 11. Undos may only go backward until they hit a row that can't be undone.

Which would resolve #1846.

Note that sometimes it is fun to do an open-deck solo puzzle, where you replay a seed with full knowledge of the deck contents, and undoing even card draws is harmless. So it is something that would be lost, but not sure how many people besides me would care. #2106 talks about making it an explicit feature.


> 12. Make undo globally available.

Does this mean removing it as an option? I've learned that the competitive players here want to keep it off even when it can't be abused, just 'cause. It's sort of a culture thing, I think. Now, if UI commit points are less granular, then more things can just be "cancelled" instead of "undone" and no one has to even know. But that makes things more boring for opponents just sitting there for a while with nothing seeming to happen.


> 13. When a game completes, don't delete it, make a version of the UI that makes the game replayable, step by step. Which is a much more interesting and detailed experience when changes are so carefully laid out.

Would be lovely.

**Comment by bafolts** [comment]
@kevinb9n has great points in regards to the short term confusion and long term confusion. If we log that a user performed an undo we don't necessarily know what the state of the game is when the next log message is logged. This solution is most likely the simplest to implement and the hardest for user's to understand. The solution to show a box around the messages the disappear with the undo is probably the simplest user experience but the hardest to implement. I think the time traveling solution may be a goldilock's zone solution which is moderately hard to implement and good enough user experience.

I am going to see what the time travel approach would involve.

**Comment by kberg** [comment]
Or, just don't show those actions. Also I don't think the UI for showing
undone operations is difficult, we've seen it in quite a few UIs. But
either  way, we can still keep track of log entries even in the face of
undo.

>

**Comment by kberg** [comment]
I'm gonna close this. Undo is being dealt with separately. It's not going to fix the experiential ability to replay a game, at least not yet.
