### ISSUE TITLE
Save a game before returning the initial URL?

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#2737]
Can't be sure this is what happened exactly, and I can check the code myself, but I had an incident where we got links to choose our starting cards, but then the app restarted (the daily 10AM push) and the game was lost.

**Comment by robot297** [comment]
I've seen something kind of like this, some background, I'm running this on a free heroku instance.  When there's a new generation started, and we're in the researching phase, if one player hasn't completed the research phase and the instance goes down, we all have to rebuy cards.

Not sure if this is a related issue or not but wanted to share this with you.

**Comment by kberg** [comment]
@robot297 that is an expected (and unfortunate) behavior. Probably exactly the same.

**Comment by kberg** [comment]
Game seems to be saved before initial url passes, which makes sense. @robot297 is talking about something different.
