### ISSUE TITLE
Strat Birds automatically ate a Dirigible when player also had 4 floaters on Celestic

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#2763]
Reported on discord by `@Gorg`

* Player had some number of floaters on Dirigibles
* Player had 4 floaters on Celestic
* I think player had no other floaters
* Venus was at or above 12%
* Player paid for Strat Birds, leaving at least one Dirigible unspent
    * Not sure whether player spent any Dirigibles at all
    * Not sure whether the interface prevented the choice of spending ALL Dirigibles (which would just be another manifestation of the bug below, if so)
* Now executing the body of Strat Birds, player expected to be asked whether to lose a floater from Dirigibles or Celestic
* A floater was automatically taken from Dirigibles instead
* D'oh

**Comment by kevinb9n** [comment]
id=c068cf531b52 but that may be garbage-collected now?

**Comment by kevinb9n** [comment]
I assume the `question` label is because we haven't repro'd yet so we don't know precisely what triggers the behavior.

**Comment by kberg** [comment]
There is most definitely client code for paying for stratospheric birds which has cleaned this up a fair bit. I'd be surprised if this was still an issue. However, this should be validated on the server side too.

**Comment by kberg** [comment]
I'm going to close this. A fair bit of work has been done regarding Stratospheric Birds, and the Dirigibles case in recent months. If this reoccurs, this can be reopened.
