### ISSUE TITLE
Solo game is dramatically easier to win with Ares in

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#2848]
My daughter has played hundreds of solo games, many with Ares and many without. She reports that her win rate for Ares games is easily 50 percentage points higher than for non-Ares games. She wins non-Ares games almost half the time, but she wins Ares games almost ALL the time.

I figure the main reason for this is that you get to collect all of your own adjacency bonuses, and with the whole entire board at your disposal, you can avoid the hazards relatively easily.

Prelude and Colonies have this effect too, but compensate for it (-2 generations / -2 mc production). If others have had similar experiences to my daughter than I think Ares merits this treatment too. But, not sure what the best remedy is. Reducing mc production would be problematic when combining with Colonies/Prelude; you can bottom all the way out easily.

And if adjacency bonuses are the main power source, it would be best if the change stayed closely related to them somehow. Otherwise games where you don't happen to see many of them will be much harder to win.

Crazy ideas:

- what if adjacency-based tiles can only be placed near hazards (for some definition of near)?
- what if new hazards come out not with full randomness, but are attracted to your existing tiles in some way?
- what if the cards that place these special tiles just cost a lot more in solo, or make you lose a TR or something? (no, not TR, that affects the two solo modes disproportionately to each other)

**Comment by kberg** [comment]
This is entirely reasonable. I really ought to look at the database to
start collating information like this.

I can't remember off the top of my head how many hazards are in play in a
solo game. I think I defaulted it to the same as a two-player game (3
hazards.)

Other options:
* Four or five hazards for an opening solo game. But even then, you can
focus on putting them out with 8MC, with a TR for your effort. (So wiping
out a hazard early is actually probably a good deal.)
* I'm reluctant to suggest removing a generation. There's already Prelude
(and The Moon, which is trying out a +2 generation to complete all the
parameters.)
* Remove n resources each generation of your choice as your first action?
(Could even be progressive, n = generation number) (This has an interesting
effect of changing the game to one where you're almost exchanging
resources. But a savvy player will just have plenty of extra heat or steel.)

In my mind, the most important thing is to force a tight space where
hazards make things complicated. So my suggestion is to start with option
#1 (5 hazards) and see how it plays.

You can test this locally by changing src/ares/AresSetup.ts, line 39 to read

if (playerCount >= 5) {
_AresHazardPlacement.randomlyPlaceHazard(game, TileType.DUST_STORM_MILD, 1);
} else if (playerCount === 4) {
_AresHazardPlacement.randomlyPlaceHazard(game, TileType.DUST_STORM_MILD, 1);
_AresHazardPlacement.randomlyPlaceHazard(game, TileType.DUST_STORM_MILD, -1
);
} else if (playerCount === 3 || playerCount === 2) {
_AresHazardPlacement.randomlyPlaceHazard(game, TileType.DUST_STORM_MILD, 1);
_AresHazardPlacement.randomlyPlaceHazard(game, TileType.DUST_STORM_MILD, 1);
_AresHazardPlacement.randomlyPlaceHazard(game, TileType.DUST_STORM_MILD, -1
);
} else if (playerCount === 1) {
_AresHazardPlacement.randomlyPlaceHazard(game, TileType.DUST_STORM_MILD, 1);
_AresHazardPlacement.randomlyPlaceHazard(game, TileType.DUST_STORM_MILD, 1);
_AresHazardPlacement.randomlyPlaceHazard(game, TileType.DUST_STORM_MILD, -1
);
_AresHazardPlacement.randomlyPlaceHazard(game, TileType.DUST_STORM_MILD, -1
);
_AresHazardPlacement.randomlyPlaceHazard(game, TileType.DUST_STORM_MILD, 1);
}

**Comment by kberg** [comment]
I am happy to adjust Ares but can't do it without suggestions / feedback. Should this stay open?

**Comment by kberg** [comment]
I'm going to consider this addressed now that Ares Extreme is available.
