### ISSUE TITLE
Request - Autoscroll up to board when project or action requires tile placement

### ISSUE THREAD

**Issue by andystager** [terraforming-mars/terraforming-mars#2854]
I'm not sure if this has been considered, but it would reduce a minor amount of scrolling for numerous cards that require plant/ocean/special tile placement.

**Comment by kberg** [comment]
Have you seen the keyboard shortcuts? (A/S/D/F will get you a fair way there.)

**Comment by kberg** [comment]
@andystager I'm looking at this one, now. So I'll get back to my original question from last year: Do you use the keyboard shortcuts? 

What do you think of this?

![image](https://user-images.githubusercontent.com/413481/187343596-cb399528-66fa-4dcb-a8a4-67524ad87244.png)

**Comment by kberg** [comment]
This was fixed a while ago, wups, closing.
