### ISSUE TITLE
Active player indication

### ISSUE THREAD

**Issue by daniel-sousa-me** [terraforming-mars/terraforming-mars#2855]
There is no obvious way to see that it's my turn just by looking at the page. Taking inspiration from 18xx.games I made a modification on the server I'm running so that the left bar shows in a different color if it's your turn.

![image](https://user-images.githubusercontent.com/3337865/109355411-15603500-7877-11eb-947d-84053d1ce2fb.png)

Would you like me to make a PR with this change? (or some adaptation of it)

**Comment by vsrisuknimit** [comment]
@daniel-sousa-me This looks cool but it may or may not be necessary. We current have three ways to tell someone it is their turn to take an action.

1) The browser title has a little clock running when it is your turn.
![image](https://user-images.githubusercontent.com/14239220/109367052-0a9ba500-7863-11eb-9af6-3d79b60cbe88.png)
2) The pop-up browser notification
![image](https://user-images.githubusercontent.com/14239220/109367081-21da9280-7863-11eb-9d43-dbfa607cc861.png)
3) The label on your player mat
![image](https://user-images.githubusercontent.com/14239220/109367118-37e85300-7863-11eb-90c9-251828400922.png)

Two things that I would consider before adding this feature: (A) will the bright color sidebar be too distracting? Perhaps that it is the point to know it is your turn, but (1) and (2) should already help with that. (B) Green/red color sidebar might not work well with the green checkmark.

I personally think we have enough ways to tell someone when it is their turn. But we could still add this feature or something along this line if you think that there are something missing in (1), (2) and (3) that could be helpful for the users.

**Comment by kberg** [comment]
Thanks for the idea. I actually would have preferred that where the solid
purple square goes shows the active player. Your color is easy to remember
after a couple of rounds. It's certainly a better use of space than a
constant reminder of a piece of data that doesn't change all game.

**Comment by vsrisuknimit** [comment]
> Your color is easy to remember after a couple of rounds.

You will be surprised how often people forgot their colors. Especially when they don't get to play their favorite colors. It is a frequent occurrence on Discord. I believe it is needed.

**Comment by ssimeonoff** [comment]
When the whole sidebar is in a player colour  - it is a bit intrusive, tried that before and instead added the the "player cube" as a more subtle solution.

**Comment by kevinb9n** [comment]
I will speak for the positive value of doing something obtrusive.  That is, I think there is some positive value in doing something that makes it *hard to not notice* it's your turn. It is already true that IF I suspect it might be my turn, I can find out pretty easily; the problem is more that I might just still think I'm waiting.

If it's too obtrusive, we could think about

* maybe it doesn't happen until after N seconds have gone by on your timer?
* maybe it goes away once you *start* doing your turn stuff?
* maybe we allow it to be disabled in options?

**Comment by puuj** [comment]
My two cents are that I really like the proposed color change and have mirrored it on my private server. Thanks @daniel-sousa-me 

@kberg I would also be a fan of having the color square in the Preferences bar to mirror the currently active player (except when drafting). Sometimes it's nice to quickly see when the game state has updated even if it's not your turn, and updating the color square would do that without scrolling below the fold.

@vsrisuknimit I think one way of making player color easier to remember is to have the top player summary bar be in the player color too. Note that if we make the color square the active player, any time a player can act, it will show their color so there is no difference there.

**Comment by vsrisuknimit** [comment]
@puuj @ssimeonoff What do you think of making this square blink when it is the player turn?

![image](https://user-images.githubusercontent.com/14239220/111222510-51530400-85b2-11eb-8c78-78e89220c4d3.png)

**Comment by daniel-sousa-me** [comment]
> 1. The browser title has a little clock running when it is your turn.
>    ![image](https://user-images.githubusercontent.com/14239220/109367052-0a9ba500-7863-11eb-9af6-3d79b60cbe88.png)

I can't see the clock because I have way too many tab open 😂

> 2. The pop-up browser notification
>    ![image](https://user-images.githubusercontent.com/14239220/109367081-21da9280-7863-11eb-9d43-dbfa607cc861.png)
> 3. The label on your player mat
>    ![image](https://user-images.githubusercontent.com/14239220/109367118-37e85300-7863-11eb-90c9-251828400922.png)

When playing live, neither of these methods is particularly useful. I disable the browser notifications, because they trigger when I have the window open. I can't see the label if I'm looking at a different part of the page (although, maybe a cool option would be to put the label and the timer on the sticky player mat)

> Two things that I would consider before adding this feature: (A) will the bright color sidebar be too distracting?

I made it like this, because it's how we have it in 18xx.games (a few thousands of active users) and I haven't ever seen a complaint about it

> What do you think of making this square blink when it is the player turn?

Personally I don't like blinking stuff.

**Comment by daniel-sousa-me** [comment]
For me just changing the square thing would also be ok, but I actually find it useful to have a more noticeable change.

> My two cents are that I really like the proposed color change and have mirrored it on my private server. Thanks @daniel-sousa-me

You cloned it from my repo? It's been only working intermittently and I don't understand why.

**Comment by puuj** [comment]
I semi-cloned it from your repo. I discovered the reason it wasn't working -- you need to have the line:
`this.setPreferencesCSS(this.active_player, 'active_player');`
in syncPreferences -- update is only called when settings change.

> 
> 
> For me just changing the square thing would also be ok, but I actually find it useful to have a more noticeable change.
> 
> > My two cents are that I really like the proposed color change and have mirrored it on my private server. Thanks @daniel-sousa-me
> 
> You cloned it from my repo? It's been only working intermittently and I don't understand why.

**Comment by puuj** [comment]
> 
> 
Hm, the blink doesn't show up in the png. I'm not wholly opposed to it, but it might also be overkill.  I do have a working version where the square is current player color -- I can open a pull request and we can debate it there if that makes sense.

> @puuj @ssimeonoff What do you think of making this square blink when it is the player turn?
> 
> ![image](https://user-images.githubusercontent.com/14239220/111222510-51530400-85b2-11eb-8c78-78e89220c4d3.png)

**Comment by daniel-sousa-me** [comment]
> I semi-cloned it from your repo. I discovered the reason it wasn't working -- you need to have the line:
> `this.setPreferencesCSS(this.active_player, 'active_player');`
> in syncPreferences -- update is only called when settings change.

Thanks lol
I think it may have been lost during a rebase. But in any case, I was going to rewrite it before submitting a PR. This has nothing to do with preferences, but was the first place I found in the code where I could shove this (well, there should be a preference, but that completely unrelated)

**Comment by nwai90** [comment]
Blinking is probably not a good idea here as it can be quite distracting. @ssimeonoff 's clock animation on the browser tab and push notification with sound should suffice here for indicating player turn.

**Comment by vsrisuknimit** [comment]
Yeah now that I think more about it. Blinking is bad.

We could try the lighted up side bar. I think it would not be bad if the color is more tone down (closer to gray like #4a4033). Here is an example below.

![image](https://user-images.githubusercontent.com/14239220/111245263-bfabbc80-85da-11eb-8a93-3f30ee6cca0c.png)

@puuj @daniel-sousa-me does anyone want to make a PR if you have a working version?

**Comment by puuj** [comment]
I can take this on.
Let me just go over several changes I've made and double-check which ones should be in the request:
- Preference bar changes color for active player (see first image)
- Top bar CSS is player color, removing override grey color (both first and second image)
- Color square is the color of the currently active player (second image)
![image](https://user-images.githubusercontent.com/58322/111250600-d9dd9e80-85ca-11eb-8934-9476cdb3e126.png)
![image](https://user-images.githubusercontent.com/58322/111250635-e6fa8d80-85ca-11eb-8e41-3da90f8290c7.png)

**Comment by daniel-sousa-me** [comment]
This is cool ^^
Thanks!

**Comment by vsrisuknimit** [comment]
@puuj  If you want to hear more feedback from the users, Discord will be a better place to gather opinions.

- Point 1, I think that color is still too bright. Check the hex code I mentioned above.
- I and a few people I know don't use top bar, so I personally would not do like point 2 and 3 as it will be confusing. The green player in the example might be confused and think they are now red. It is good enough to know whether it is your turn or not. If you need to find out whose turn it is, you can look at the player mat table.

Alternatively, we can utilize the top right of the screen which is not currently in used. It could be a small sticky tab that say whose turn it is. Or another indicator on the side bar, leaving the rectangle intact.

**Comment by ssimeonoff** [comment]
Keep in mind that the top bar can be turned off or simply collapsed (my default choice) - and as such there is no other static element indicating the player colour.
Making the whole status bar into the player colour is much of bright colours (you have felt that and thus added opacity). 
Using opacity tones down the colour, but then it is hard to tell which is which - e.g. the side bar looks orange, not red, and we have an orange player.

**Comment by puuj** [comment]
See PR #2969 with the sidebar change. 

On the other notes, my opinion is that scrolling down to the player mat display is annoying, and any time it's your turn the color square will be your color, so no one should be confused. But personally, I"ll just support those mods on my server, so not a huge deal for me.

**Comment by kberg** [comment]
This looks resolved. Feel free to reopen if necessary.
