### ISSUE TITLE
Solo mode is part of the Corporate Era expansion (selecting CorpEra should be mandatory)

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#2861]
The published rule is that solo mode only exists when using the Corporate Era expansion. The reason is that the developers feel that solo without CorpEra [makes for a bad game](https://boardgamegeek.com/thread/1663126/article/24081575#24081575).

Scanning a few threads suggests also that solo made is actually harder (!) without CorpEra, which is opposite to what players who choose this surely expect.

The app allows solo without CorpEra. I'm not sure if it is intentional. Allowing it may not be "free", because new players will be likely to assume that's how they want to play, not knowing any of the above. It is intuitively "obvious" that this would make for an easier learning curve, but surprisingly, virtually every game concept is encountered somewhere in the base deck alone anyway.

**Comment by kevinb9n** [comment]
Hello thumb! I would welcome the counterarguments.

I think it's fair to frame it like this: of the infinite unofficial variants that could be supported, why should this one make the cut?

I do think the standard to meet should be a bit higher than "some people want to play this way sometimes". The fact that it's very intentionally not an official variant should have *some* amount of weight.

**Comment by SliceOfBread** [comment]
What is the benefit and what is the effort to gain that benefit? In this case, the benefit is fleetingly small and the effort is not.

OTOH, if this were already the status quo, I would make the same exact argument against adding a Solo w/o Corp Era mode.

In the interest of fairness, I will try this mode out and see how bad a game it makes for.

**Comment by SliceOfBread** [comment]
I played the Beginner Corp and won with 124 pts. so I don't think this will be challenging to anyone but a real beginner. I don't see any reason not to allow it though.

**Comment by kevinb9n** [comment]
(this issue isn't related to Beginner Corp)

The *main* issue here isn't offering a variant that the fryxfolks intentionally didn't want; it's that unsuspecting players are getting that variant without having any idea they're going outside those bounds.

**Comment by bafolts** [comment]
I have a funny story here which helps to prove @kevinb9n 's point. I didn't realize corporate era was a thing for solo games. When I first wrote this game and I would test solo mode I was wondering how anyone could ever win. Will update this to only show the corporate era option when more than one player. Jonathan Fryxelius' word is always final.

**Comment by kberg** [comment]
My basic perspective is this is worth keeping open, but is a low return on effort versus reward. Unless, perhaps, it was kept simple by having the UI show a warning on the page that beginner players may find that combination challenging. Or if they want to be purist about the message from Fryxgames, that it's an unrecommended way to play. But I'll leave the verbiage up to others.

As an aside, this is one of those cases where I wish we had a clear sense of where the product should go: friendly toward beginners or friendly toward experienced players? I'd rather we chose one and made it possible for a fork to choose the other.

**Comment by bafolts** [comment]
Trying to tailor to beginner versus experienced may be challenging. I had played multi-player games at a game night at work at least 30 times. I would have considered myself experienced but I wasn't familiar with single player games. Even an experienced player in one aspect of the game could benefit from having the UI show a warning that solo mode is recommended to have corporate era.

**Comment by kevinb9n** [comment]
> As an aside, this is one of those cases where I wish we had a clear sense of where the product should go: friendly toward beginners or friendly toward experienced players?

An argument that you might or might not see value in.

1. Experienced players might sometimes run their own server or even fork
2. Beginner players will virtually never run their own server or fork
3. So maybe the main branch / demo server should be more beginner-oriented

**Comment by bafolts** [comment]
The differences between beginner and experienced players I would think are mostly minor user interface decisions like we have here. When playing a multi-player game I assume the player with the most experience is going to be on the create game form and then send out the links to players which may be beginners. For this situation here if a beginner player is on the create game form the warning should be of value.

If these warnings are in the way for experienced players (perhaps running the server locally) we could hide them behind a flag we set on the server. If we added a `SHOW_WARNINGS` flag that had to be set to show the warnings this would allow experienced players to not have to ever see these warnings. With this warning flag in place I would then think this project goes towards more experienced players who want to customize the game to their liking. The warning flag is then there to help those experienced players bring more people into the game. At some point we are all beginners! It is easy to spot a beginner when they are given the beginner corporation card. Difficult to know they are a beginner on the create game screen.

**Comment by kberg** [comment]
I didn't want to quite turn this into that discussion, as I think it merits
a proper conversation. But I'm glad we're having some of it, and welcome
back, Kevin!

>

**Comment by kberg** [comment]
How would players feel about a warning in the same vein as the one that pops up when you don't pick any project cards during the initial draft? So it would just be a warning.

**Comment by kberg** [comment]
Could also pick "Corp era" by default when choosing solo.

In both cases, if the player wants to turn it off, they can.

**Comment by kevinb9n** [comment]
Yeah, I think my report was overstated. This is a good fix and I think a mild warning would be cool too. It was never *really* about stopping people from playing an unorthodox way, just making sure they were doing it intentionally.

**Comment by kberg** [comment]
I want to close this one out, but can also consider adding a warning if you're playing solo without Corp Era. If this is good enough, feel free to close. Otherwise I may add the dialog warning sometime this weekend.

**Comment by kberg** [comment]
It is out, but now I see it's insufficient.

1. 2-player turn of Corporate Era
![image](https://user-images.githubusercontent.com/413481/166079282-bc2845fb-4384-46c4-9649-0ea8636f774e.png)

2. Click 1 player.
![image](https://user-images.githubusercontent.com/413481/166079294-c4efe825-16da-4843-8353-d2294525f5bb.png)

**Comment by kberg** [comment]
I am closing this now that a warning will be produced once this gets pushed.
