### ISSUE TITLE
Feature request: trigger data

### ISSUE THREAD

**Issue by aws0m** [terraforming-mars/terraforming-mars#2964]
seeing how many times for example a Corp cards effect has been triggered; for example how many times has Saturn System been triggered this game.

**Comment by kberg** [comment]
What are you trying to achieve here? This seems like such a special request. There's certainly some room for great data collection which we never did. But this feels a bit like something we wouldn't implement, at least not in isolation.

**Comment by kberg** [comment]
Closing this since there was no response. If you respond @aws0m we can reopen the issue.
