### ISSUE TITLE
Feature request: Improve cards list page to be more functional

### ISSUE THREAD

**Issue by vsrisuknimit** [terraforming-mars/terraforming-mars#2972]
Make `http://terraforming-mars.herokuapp.com/cards` to be more like @ssimeonoff 's [card list](https://ssimeonoff.github.io/cards-list).

- Filter for expansion and tag (no need to filter by production and resource)
- Search not just for names but card text
- Add Colonies and Global Events

**Comment by AndrewSav** [comment]
Uhm... https://github.com/bafolts/terraforming-mars/commit/73eceae8ea2e2e6f6215171499e7d1408669b3dc ?

**Comment by kberg** [comment]
Colonies and Global Events are in the cards list page. Filter by expansion, too.
Searching for card text will be surprisingly tricky.
Filter by tag, yeah, interesting.

**Comment by AndrewSav** [comment]
@kberg did it not use to work and then were removed in the said commit?

**Comment by kberg** [comment]
> @kberg did it not use to work and then were removed in the said commit?

The former cards list linked to Simon's beautiful self-hosted app. It does not contain the community cards, or the fan expansion cards. It's too bad, because that sure is gorgeous.

**Comment by kberg** [comment]
Added a filter by tag. It isn't pretty, but it can be prettier later.

**Comment by kberg** [comment]
#4409 added both simplicity and power. Plus, wow it's much faster.

**Comment by kberg** [comment]
The only thing missing is card text. I tried that in the past, and it's messy. I'll close this one for now. It's in solid shape.
