### ISSUE TITLE
FR: Rename buttons and how Business Network works

### ISSUE THREAD

**Issue by vsrisuknimit** [terraforming-mars/terraforming-mars#3010]
![image](https://user-images.githubusercontent.com/14239220/112148386-3553f180-8bb4-11eb-9b9f-6d8b5ac1c0c5.png)

**Comment by kberg** [comment]
There a couple of buttons that could use this kind of repair. There's a bit
of arbitrary button naming that could use a little tightening.

>

**Comment by kberg** [comment]
I believe this has been fixed for some time. Please reopen if it is an issue.
