### ISSUE TITLE
Feature: seeing how much res a card has when a player places more on it.

### ISSUE THREAD

**Issue by aws0m** [terraforming-mars/terraforming-mars#3028]
When you look at the log and you see that an opponent has place x amount of resource/s on card x: would it be possible to when you click card x to see it that you could also see the amount it now has on it?

or

that the log tells you the update information. Like this for example;

Awsöm added 1 floater(s) to RED SPOT OBSERVATORY updating its total from 2 to 3

**Comment by kberg** [comment]
This has been fixed for some time. When clicking on a card in the log, it shows the resource count.
