### ISSUE TITLE
Feature request: reduce number of click for Helion

### ISSUE THREAD

**Issue by vsrisuknimit** [terraforming-mars/terraforming-mars#3038]
This suggestion

![image](https://user-images.githubusercontent.com/14239220/112699205-b4ba1d00-8e61-11eb-9dc9-1d61de041c8e.png)

or alternatively a button just for Helion such that mc will always be spent before while this button is toggled.

**Comment by nwai90** [comment]
The button is a better approach if this is to be done as it avoids additional custom deck manipulation. There are also several other reasons why you would want to spend heat before MC, e.g. endgame MC tiebreaker.

**Comment by kberg** [comment]
A max for the MC button is reasonablel, at the very least.
