### ISSUE TITLE
Feature request: see what cards you have used or hasnt used for putting res on them

### ISSUE THREAD

**Issue by aws0m** [terraforming-mars/terraforming-mars#3046]
It would be awesome if when you for example need to put floaters on your cards that among your res-order options it would be clear what cards you have used this gen (and can thu not be used this gen).

As it is now you have do keep track of it in your mind or scroll down to your played cards to see what cards are "greyed-out" or not.

**Comment by kberg** [comment]
During physical game play, I manage this by putting a player marker on my card, so I get it.

**Comment by kberg** [comment]
Like this:

![image](https://user-images.githubusercontent.com/413481/164740398-19dfb790-8a0f-4b94-88bb-2c36aeeb3e74.png)

**Comment by kberg** [comment]
Works in the played cards arena too

![image](https://user-images.githubusercontent.com/413481/164741945-224532d3-35ec-4076-99fc-8be649d344a8.png)

**Comment by kberg** [comment]
This will go out in the next deployment.
