### ISSUE TITLE
RFC: Add game JSON to game_results, review old games?

### ISSUE THREAD

**Issue by puuj** [terraforming-mars/terraforming-mars#3125]
Currently, the game_results table is fairly minimal. Additionally, the game end page disappears on server restarts. One idea would be to add the final, serialized game state to the game_results table. Games that have ended could continue to be browsed across server restarts, and it would allow many different types of analysis.  I can understand how a popular instance running on the free Heroku tier might not want to do this to avoid filling up the DB, but for personal servers this should be fine. Thoughts on any potential snags?

**Comment by kberg** [comment]
The last step of a game is stored in the game table ongoing, and can be scanned for results.

**Comment by bafolts** [comment]
This is probably related to #3132 . This suggestion of storing the full JSON may be the way to go. It would avoid having to add columns for each data we may want to track.

**Comment by bafolts** [comment]
The `terraforming-mars.herokuapp.com` uses the "Hobby Basic" postgres plan which has 10GB storage for heroku. When I looked this weekend we had used 2.4GB of the storage with our process to purge. Each game in JSON I believe is 50kb or so. Eventually we would run out of space but it would take time. We passed 100k rows in the `game_results` table recently. I don't think we have had the `game_results` table for even a year.

```
terraforming-mars::DATABASE=> select count(*) from game_results;
 count  
--------
 101842
(1 row)
```

**Comment by kberg** [comment]
@puuj I was wrong, the last game is deleted after 15 days. On a personal server, though, I think all you'll need to do is not set `MAX_GAME_DAYS` if you're using SQLite, and a really huge number if you're using PostgreSQL. (Frankly, I think those should be consistent. I'd be happy to change PostgreSQL to stay consistent.

But, I do think there's no bug here. At least not today. Please add comments if I am mistaken.
