### ISSUE TITLE
Super Edge Case Bug: Reds, Pharma Union, Microbe+Science tags, Splice

### ISSUE THREAD

**Issue by vsrisuknimit** [terraforming-mars/terraforming-mars#3126]
![image](https://user-images.githubusercontent.com/14239220/114285131-abfd4580-9a22-11eb-9448-546c1fd20178.png)

The stars have to quite align for this to happen but it can.

We still need a long term way to deal with the Reds. We need to finish/update the Priority queue that Lynesth created.

**Comment by vsrisuknimit** [comment]
Priority queue link: https://docs.google.com/spreadsheets/d/e/2PACX-1vQLseQ6JruRdWKNvCE4oFpss6_Blb81TgzGNIHja6ylqVn6J5vDiH6tn3v4_Zmu2bj1ql2vLo3YOfNG/pubhtml

**Comment by kberg** [comment]
Here's one possible solution:

When computing an `onCardPlayed` on a card with a microbe and the active player is Pharmacy Union:
1. List all of your cards *1 that have an `onCardPlayed` effect.
2.  Present player with a list of those cards, and let the player choose resolution in order.
3. Player selects a card, its onCardPlayed is resolved.
4. Player is presented with the list of remaining cards.

Issues with this approach:
1. As-is, it will present _all cards_ with an `onCardPlayed` effect, even if it does not apply. Reducing this would mean changing some of the meaningful structure of how cards describe onCardPlayed.
2. A card's `onCardPlayed` can have multiple effects, which don't need to be resolved in order. (e.g. player might choose to resolve part of Pharmacy Union now, and more later.) Resolving _this_ would require further structural changes.
3. Eventually this could devolve into player's choosing all their effects orders all the time. Which isn't bad, but this might make it painful / slow / etc.
4. Player might be able to take advantage of this when Reds are in power by gaining TR they should have paid for. (I haven't thought very seriously about this one.)

*1: There is also a turmoil effect when using the fan-made agendas, but set that aside for now.
There's also an interesting CEO effect (Faraday) which let's set aside right now.

IIRC, the active player gets to resolve all effects, even those that apply to other players. That simplifies things a little (though could an even further burden on the active player.)

**Comment by kberg** [comment]
The current behavior now is a little tricky. Because there was an attempt to be stricter about Reds costs, this case actually throws an error, which we will need to avoid. So next step is to at least resolve that case; that's worse.

**Comment by kberg** [comment]
Finally fixed. I thought this one would be impossible. :D :D :D
