### ISSUE TITLE
feature requesti: Resources amount of Self Replicating Robot

### ISSUE THREAD

**Issue by aws0m** [terraforming-mars/terraforming-mars#3129]
It would be so nice if when you are about to double your resources on Self Replicating Robot that you see what your current Resource on the card is instead of needing to scroll down to the bottom of the page. I also wouldnt mind if the log was more clear with the amount of resources on cards. For example saying something like Germansamurai94 used Birds, Birds now have 4 resources on it.

**Comment by kberg** [comment]
I was thinking the same thing.

**Comment by kberg** [comment]
A year later:

![image](https://user-images.githubusercontent.com/413481/165982857-df8f0030-c042-4292-b6d6-be81d8c5c615.png)

This is a WIP. I plan to include the resource count below.
