### ISSUE TITLE
Displayed Card Order Differences Between Performing an Action and Adding a Resource

### ISSUE THREAD

**Issue by andystager** [terraforming-mars/terraforming-mars#3181]
I've noticed this behavior a lot - the order of card display for selecting an action to take does not at all match the order of card display when choosing where to place a resource. Can these be standardized?

![image](https://user-images.githubusercontent.com/72101041/115618185-56e1ef00-a2c0-11eb-92b7-bd9ce22da8bd.png)
![image](https://user-images.githubusercontent.com/72101041/115618207-619c8400-a2c0-11eb-96f9-1c7229eb9b86.png)

**Comment by bafolts** [comment]
This is by design from #1606.

**Comment by andystager** [comment]
Apologies, but after reading that issue and its closure in #2365 I'm not clear on the design. Is there a different sorting strategy between choosing an action and playing a resource?

**Comment by kberg** [comment]
This is an interesting bug. Hope you've had a good 18 months. This looks like a good one to peek at.

**Comment by kberg** [comment]
Turns out this was easy to fix. When selecting cards, sometimes they're in the order of [corporations, other cards] and sometimes they're in the order of [other cards, corporations]. This has been becoming consistent over the last month, and this was another reasonable case.

**Comment by andystager** [comment]
Thanks for coming back to this one and finding a fix!

**Comment by kberg** [comment]
👍 my pleasure.
