### ISSUE TITLE
Four (or so) of the *default* values for local preferences are "backwards"

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#3259]
Every time I teach a new player, the first thing we have to do is go into their gear icon to turn on a few settings:

- Learner mode
- Enable sounds
- Magnify cards on hover
- Show in-game alerts

Should these be the defaults for new players?

**Comment by kberg** [comment]
I believe they should be.

**Comment by bafolts** [comment]
For these new players are they setup with the beginner corporation? I also believe they should be defaults and wondering how to detect these players.

**Comment by kberg** [comment]
The ones I play with are not. But also, those are two different dimensions:
one is about setting up for the game, the other is about the player's
literal preferences for all games.

>

**Comment by kevinb9n** [comment]
Probably by "new players" here I mean "they have no cookies" or something.

(Beginner Corp is unrelated; the game creator has to choose for them, but it will be cool if in the future players arrive at a page where they get to set their own name and color pref, and that's where they could pick BC too.)

**Comment by bafolts** [comment]
Unrelated but we could probably always allow a player to select from their dealt corporation cards or the beginner corporation card. Makes more sense now that these are the default preferences for anyone who has never set them.

**Comment by kevinb9n** [comment]
(on the tangent: it would be a rules error to let them pick BC after seeing any of their other cards. Then players can pick it opportunistically just because their other cards happened to be bad. The Fryx stance is that BC is really not supposed to be used by anyone who knows the game well. Jacob even stated that to be the "official rule" even though obviously there's no clear dividing line between who knows the game and who doesn't.)

**Comment by kberg** [comment]
I'm going to implement this. There are many players who care a lot about high-speed playing but a) those people are not actively on the discord, and b) play often enough that they can change the settings once per machine.

**Comment by kevinb9n** [comment]
thank you
