### ISSUE TITLE
Don't hide the award running totals even though three awards were funded

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#3272]
![image](https://user-images.githubusercontent.com/413481/117586898-1c15ee80-b0e9-11eb-9c70-3360efe3a6d7.png)

A constant source of conversation in our games is about the award _not funded._ It needs the right visualization cue, though. Either white text instead of black, or a gray pall over the unfundable awards and their running totals.

**Comment by kevinb9n** [comment]
previous attempt to discuss "gray pall" https://github.com/bafolts/terraforming-mars/issues/1607#issuecomment-711534524

For what it's worth, I would be surprised if the trackers still appeared at all, since the UI is already crammed so full of information that has relevance/importance to the game.
