### ISSUE TITLE
[suggestion] Make an option to exclude negative effects

### ISSUE THREAD

**Issue by PetrGasparik** [terraforming-mars/terraforming-mars#3316]
A suggestion: Similar to option for turmoil:
- make an option for new game "Exclude cards with negative effects"
- or an option "Deal negative effects clockwise 1 to each player" (meaning in 3 players, -4 plants means everyone get -1 and player to the left -2)

**Comment by kevinb9n** [comment]
see bug 1492, closed "wontfix"

**Comment by bafolts** [comment]
Excluding cars with negative effects could be accomplished by providing a custom card list.

For the AoE option would first have to decide how the cards would act when this option was enabled. The would have to update all those cards. Implementing should be straight forward but would need consensus on which cards would be included and how they would act under this option.

**Comment by kberg** [comment]
The custom card list does solve the problem.
