### ISSUE TITLE
Save game state in between card drafts

### ISSUE THREAD

**Issue by enigmaticcam** [terraforming-mars/terraforming-mars#3363]
My group plays using the free version of the Heroku app. For the most part it works fine, but during research phase when we all select our cards, if the server goes offline, sometimes we all have to reselect again. Is there any way to fix it so card selection persists?

**Comment by kberg** [comment]
It's a great question. We could probably do something about this, but it's
probably going to significantly increase the storage size of a single game
(I'm guessing 80-90% larger.)

>

**Comment by enigmaticcam** [comment]
You guys have the greater exposure to possible ramifications of increasing everyone's storage size, so I'll let you decide if it's worth it. Obviously I'm the first to mention it, so issue probably not too ubiquitous. Thank you!

**Comment by kberg** [comment]
Oh, it's happened to me, too.

>

**Comment by bafolts** [comment]
> My group plays using the free version of the Heroku app.

Is this on the heroku free plan or a hosted site like terraforming-mars.herokuapp.com ?

**Comment by enigmaticcam** [comment]
> > My group plays using the free version of the Heroku app.
> 
> Is this on the heroku free plan or a hosted site like terraforming-mars.herokuapp.com ?

It's a free plan, my own account.

**Comment by bafolts** [comment]
The point @kberg brings up is accurate that having to store more state will use more memory. Let's put that problem aside for a moment and assume we have plenty of memory. The other challenge is there are some objects we can't serialize. Whenever the server is waiting for a player to take action we rely on an instance of `PlayerInput`. We don't serialize these instances when saving state today and strategically save state when we can populate these instances when the server starts.

As an example of one of the problems let's look at `SelectPlayer`. This `PlayerInput` has a `cb` which is a `Function`. We can't serialize `Function` so this data is lost when we serialize an instance of `Player`. If we could refactor both `PlayerInput` and `DeferredAction` to avoid relying on the callback functions this would allow us to serialize an instance of `Player` without losing any state.

For the time being to implement the change requested here we will need a way to repopulate the `PlayerInput` for any players who have not selected their project cards during a research phase. While deserializing we would have to spot that we were in the research phase and then check who hasn't selected their cards and populate their research phase `PlayerInput`.

On a free heroku account there is probably plenty of memory even for these new rows. On the popular sites like terraforming-mars.herokuapp.com I still think we have plenty of database storage left. Today on terraforming-mars.herokuapp.com we have used 269,275 of 10,000,000 rows available. Even if we assume there were double rows involved here that would put us at 500,000 which is will within 10,000,000. We also have a 10gb storage limit and are at 2.4gb today. Doubling this we would be at 5gb. If this storage size became a problem we could also make other optimizations to the size of one game state saved.

The heroku free account has a 10,000 row limit and a 1gb storage limit. As long as users of the free heroku were only playing with a few of their friends I would also think they are fine. They will need to purge old games more regularly than terraforming-mars.herokuapp.com but this can be configured with the game server.

**Comment by kberg** [comment]
I forgot about the unserializable nature of player inputs. That's a
solvable problem, but it is a lot of work.

>

**Comment by enigmaticcam** [comment]
Apparently Heroku will still reboot a server once a day, so even set to Hobby card selection can still restart.

**Comment by bafolts** [comment]
I do see on my heroku plan that some days there will be a "daily restart" listed. I don't see this run every day. Not sure what interval it runs.

**Comment by BeriAlpha** [comment]
This comes up a lot for us too; not a critical issue, but some of our players can get distracted by life, so it makes larger asynchronous games difficult.

Could it be an option during setup to have the research phase be serial? Where the first player would decide what cards to keep, confirm, then the next player, then the next player, with each player's research turn being locked in just like the action phase. So that even with much slower players, we would eventually finish the research phase. It would be a gameplay compromise, but not critical.

As a concession, this option could also make it so that the log doesn't report how many cards each player kept during research. (If players want to keep careful notes of how many cards players had, and compare that to the new numbers to see how many they purchased, and they think that knowledge is enough of an advantage to be worth the time...well, more power to them.)

**Comment by kberg** [comment]
This was fixed recently.
