### ISSUE TITLE
Create a beta instance

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#3441]
The one reason a beta instance isn't quite so great is because people might be less inclined to use it: if something's wrong, their game is hosed.

https://stackoverflow.com/questions/5981508/share-database-between-2-apps-in-heroku shows how to share a database between two instances. If a second instance (like the freshly-registered terraforming-mars-beta) had access to the same database as the main server, many players would be willing to play on the beta instance, report any issues, and switch over to the main instance.

We could resume more frequent pushes to beta, and less frequent pushes to main.

**Comment by bafolts** [comment]
Sharing the database instance will require both versions to share the same database schema. How do we know which version is the last stable version for main? With the nature of this application a bug that is discovered that prevents a game from being finished is very frustrating. The hosted terraforming-mars.herokuapp.com should already be considered as a demo. Users could run the game locally if they want the most reliable experience. Now this leads to the same dilemma. How does someone running a commit locally know their version is stable? Instead of a beta instance we could consider introducing a version to the package.json and tagging versions when we feel they are stable.

**Comment by kberg** [comment]
> terraforming-mars.herokuapp.com should already be considered as a demo

What on that site would make someone think it's a demo? I don't think
that's clear to the person stopping by. I'd suggest that we host a demo
version for that reason only. And provide something stable at the namesake
URL.

>

**Comment by bafolts** [comment]
Putting only a stable version on terraforming-mars.herokuapp.com makes sense to me as at this point it has proven to be a popular destination. Wondering now how we mark versions as stable. If we then utilize modifying the package.json version when we feel a build is stable we could deploy to terraforming-mars.herokuapp.com only when the package.json version is incremented.

**Comment by nwai90** [comment]
@bafolts Using git tags to mark stable versions on the main url is probably a good approach. The beta url could host the most recently introduced changes that need some playtesting

**Comment by kberg** [comment]
Better than another branch, which was my first thought. (Of course, a
branch can also reference the stable release and still get one-off patches.)

>

**Comment by bafolts** [comment]
If I tag a version to get things started which commit should I started?

**Comment by nwai90** [comment]
The tags that make sense to me at the current stage are (1) pre-SFC and (2) per batch of SFC changes

**Comment by kberg** [comment]
So I'm clear: is the plan to keep these tags in the same branch? eg if the
production instance needs an immediate patch, that's doable with the
approach you suggest?

>

**Comment by nwai90** [comment]
@kberg It's doable, we would restore the last `prod` git tag and add a new patch commit with its own tag. Having separate branches for `beta` and `prod` would be less error-prone here. The `beta` branch could remain as `main` while `prod` has its own branch. Each branch can be tagged separately with ENV-TIMESTAMP (e.g. `beta-20210719094916`) or other convention. Any patch made to the production instance can either be merged back directly to `main` or have an equivalent PR to `main`.

**Comment by kberg** [comment]
Sounds like the two of you know what to do. I have to go learn about git
tags.

>
