### ISSUE TITLE
Renaming player model types and variables

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#3459]
Having stared at the player model and the over-heavy model we used to have, and doing my best to continue to detach public and private information, I suggest an updated structure:

Current:

```
player: PlayerModel extends PublicPlayerModel
|-> game
|-> players: PublicPlayerModel[]
```

Problems:
* `player` is double-used. Sometimes it has private data, some times it does not.
* `PublicPlayerModel` was a bad name. Sorry.

I've described something like this before, but only in pieces. Here's what I propose:

```
playerView: PlayerViewModel
|-> game
|-> players: PlayerModel[]
|-> thisPlayer: PlayerModel ** see below
|-> privateData: PrivatePlayerModel
```

`players` still contains all the public data related to each player, including the player whose view this represents. `thisPlayer` is the same data in `players[x]` where `x` is the index within `players` representing this player. However -- it is **not** generated by the server. Instead, it is calculated by the browser. That the JSON isn't repeated in the call down, and it saves memory on the browser.

`privateData` moves most of the fields from the top level `playerView` into a separate object. It just seems appropriate for private game information to be stored on a separate level from game, player, etc.

Alternatively, we could do this

```
playerView: PlayerViewModel
|-> game
|-> players: PlayerModel[]
 |-> privateData: PrivatePlayerModel | undefined
|-> thisPlayer: PlayerModel ** see below
```

`privateData` would be undefined for the player models representing other people, and so it would only be accessed in `thisPlayer`.

I'm so sorry that `PlayerModel` would a reused term.

**Comment by kberg** [comment]
From this you can infer a pretty useful `SpectatorModel`:

```
spectatorView: SpectatorViewModel
| -> game
| -> players: PlayerModel[]
```

where all insatnces of `privateData` are undefined and no fields it shouldn't have are even part of it.

**Comment by kberg** [comment]
Ah, right -- a pice of this that's useful is the disambiguation of what "player" means in the components. I meant to put that in the first post.

**Comment by kberg** [comment]
https://github.com/bafolts/terraforming-mars/pull/3461

This is a prototype of what a completed implementation would look like, best read one commit at a time. It doesn't WORK just because I was focusing on structure and prototyping. But it's not terribly far. Plus, more tests.

**Comment by bafolts** [comment]
With the last of the single file components this change should involve less manual checking of templates on client side.

**Comment by kberg** [comment]
This was done long ago.
