### ISSUE TITLE
Feature request: prelude draft optional

### ISSUE THREAD

**Issue by PetrGasparik** [terraforming-mars/terraforming-mars#3513]
Feature request: separate initial draft for cards and preludes.

Motivation: initial draft is great mechanism. Prelude draft can break good combo easily.

**Comment by kberg** [comment]
Today is "make sure every open bug has a comment" day!
This is a reasonable request, but I don't want to clutter the game selection UI more. If we rewrite the new game UI (#3755) this could be a fast-follow.

**Comment by kberg** [comment]
I'm fixing this today. Should be published in a day or two.
