### ISSUE TITLE
Don't let player trade with colony tile if they haven't selected a colony tile to trade.

### ISSUE THREAD

**Issue by Jenjenn** [terraforming-mars/terraforming-mars#3541]
Through some combination of "Titan Floating Launch Pads" and "Cryo Sleep", I'm no longer able to take the "trade with a colony tile" action. Every trade fee option results in HTTP400 with message: "ERROR WITH INPUT Incorrect options provided (nested)"

![image](https://user-images.githubusercontent.com/8846978/131030735-393dfb81-a567-4210-813c-6fe7a0a65fb4.png)

![image](https://user-images.githubusercontent.com/8846978/131031745-f9dcbd3b-8362-47f4-8d2c-124a3d751467.png)

I played "Titan Floating Launch Pads" before "Cryo Sleep", not sure if that makes a difference.

(Playing solo challenge on the demo server so this game ID will be gone soon.)

**Comment by kberg** [comment]
![image](https://user-images.githubusercontent.com/413481/187096971-d190e03c-289e-4627-8446-57abc05261ab.png)
There is a better error now. Closing
