### ISSUE TITLE
Solo game - Full Terraforming should not count TM points for greenery tiles after 14th/12th generation

### ISSUE THREAD

**Issue by erisalke** [terraforming-mars/terraforming-mars#3556]
When playing solo game: ~~in the standard game mode "Terraform it All" (not the reach 63 points mode)~~
with both modes selected +63 VP AND "Terraform it All"

After the last generation ends (independently from if it's a prelude game that goes to 12 generation or no-prelude game to 14 generations) the last greenery tiles that are being placed AFTER the last generation ended should NOT rise the oxygen level (even there's still room for those) and should NOT grant the TM points for the player.

Rules snippet:
<img width="959" alt="Screenshot 2021-09-01 at 02 23 51" src="https://user-images.githubusercontent.com/15717649/131592431-da800564-c920-4b65-bf51-17896af92d90.png">

Currently the game behaves correctly, but the game victory condition seems to be checked after the last step, which may result in improper "You won" screen.

How to reproduce it: play the solo game with both mode one and complete everything but one last step of oxygen (so oceans, temperature and venus are all done) and finish the last generation with at least 8 plants. To be able to place last greenery after the 12th/14th generation. According to the rule snippet posted above, the game should result in a LOSS, however it shows a WINing screen
![Screenshot 2021-09-03 at 15 12 57](https://user-images.githubusercontent.com/15717649/132011723-424d28c4-04bf-4d85-b482-7401dc04149e.png)

**Comment by kevinb9n** [comment]
Huh, I really didn't think it had this particular problem. You're certain this happened as you describe, and you weren't possibly in TR63 mode?

If there is a problem then addressing https://github.com/bafolts/terraforming-mars/issues/2055#issuecomment-820689063 might be one way to make it go away.

**Comment by erisalke** [comment]
Now I'm no longer sure about that. 😊
I've seen you can't reproduce it. If I happen to hit same thing again I will document it correctly with screenshots. 
Meanwhile this can probably go to the bin :)

**Comment by vsrisuknimit** [comment]
@erisalke There is no 'both solo mode'. You pick one.

If you turn on '63 TR solo mode', you win at 63 TR regardless of whether you finish the terraforming parameters.
If you don't turn it on, then it is TR-all mode. You need to terraform all parameters.

So in the picture above, you already won because you had enough TR.

**Comment by vsrisuknimit** [comment]
Some players try to win both modes by turning on '63 TR' mode and manually force themselves to finish all the parameters as well. That however is not in the official rules.

**Comment by kberg** [comment]
Looks like there's nothing to fix here.
