### ISSUE TITLE
VP progression in logs

### ISSUE THREAD

**Issue by rogerta** [terraforming-mars/terraforming-mars#3603]
It would be nice to show the VP of each player in the logs, either at the start or end of each generation.  For example, for each generation the log starts like:
```
Generation X
🕑 Roger bought 1 card(s)
💬 You drew XXXXX
🕑 George bought 0 card(s)
🕑 Blaise bought 2 card(s)
🕑 Norm bought 1 card(s)
```

Maybe this could changed to something like:
```
Generation X
Roger starts with 25 VP
George starts with 28 VP
Blaise starts with 30 VP
Norm starts with 32 VP
🕑 Roger bought 1 card(s)
💬 You drew XXXXX
🕑 George bought 0 card(s)
🕑 Blaise bought 2 card(s)
🕑 Norm bought 1 card(s)
```

Or possibly show VP at the end of the generation with something like `Roger ends with 25 VP`.  Some folks I play with think it would be interesting to see the VP progression from one generation to another.  Thanks.

**Comment by nwai90** [comment]
@rogerta This feature already exists on some servers including mine. We will be looking to port it over in the coming months

**Comment by kberg** [comment]
Is this still worth doing if we add the end-game graph?

**Comment by rogerta** [comment]
An end game graph works too. This is mostly something we were interested to look at once the game is over.

**Comment by kberg** [comment]
> An end game graph works too. This is mostly something we were interested to look at once the game is over.

Great, then I'll close this out!
