### ISSUE TITLE
Alt Venus 30% bonus is a little easy to misuse

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#3646]
Since all of these are currently true:

* you get the any-resource bonus first before the standard-resource-only
* it won't offer a card resource as the second choice even if a standard resource was chosen first (... or did I just get confused there?)
* the any-resource bonus has "I want to choose from standard resources" selected by default

I think these three things work together to make it easy to accidentally screw oneself out of a card resource.

**Comment by kberg** [comment]
Agree. I've done that myself.

>
