### ISSUE TITLE
FR: Don't hide the expansion icon with resource count.

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#3661]

**Comment by kevinb9n** [comment]
There are even cards with actual words covered up by it, too. They are words that no longer matter by that time, but if that could be solved then it would be nice for the resource dingus to just become a permanent part of the card in all contexts.

**Comment by kberg** [comment]
This gives me a different idea: toggle whether all cards show just text,
just icons, or both. That's got nothing to do with where the resource
counter goes, but it would solve a lot of small things.

>

**Comment by kberg** [comment]
Actually, this is fixed!

![image](https://github.com/user-attachments/assets/ab5b5993-3163-405a-893d-4a31a27ea571)
