### ISSUE TITLE
'Pathfinder' error, play cards multiple times without losing them from hand

### ISSUE THREAD

**Issue by BeriAlpha** [terraforming-mars/terraforming-mars#3678]
https://terraforming-mars.herokuapp.com/player?id=pc123d0862a16

It appears that I was able to play Io Mining Industries twice and Beam from a Thorium Asteroid without them actually leaving my hand or requiring an action. I got an error message each time, something about 'Pathfinder not defined'. Pathfinder was definitely in there.

**Comment by kberg** [comment]
Ugh, I'll fix that immediately.

**Comment by kberg** [comment]
Just spent an hour trying to recreate it. I copied your game locally but cannot. This implies it might already be fixed.

Would you like me to unwind the game a couple of steps for you so you can continue, or have you abandoned the game?

**Comment by BeriAlpha** [comment]
Yes, please rewind the game, to the start of my turn (Barry) or however far
back you need to go.

**Comment by kberg** [comment]
k. Never done it before, so fingers crossed. :D

**Comment by kberg** [comment]
Are you on the discord? I would like to be in some sort of chat with you while you re-execute your steps.

**Comment by BeriAlpha** [comment]
Yes, I'm BeriAlpha on Discord. I'm not active on the server, but I am there.

**Comment by GamerforGod** [comment]
https://terraforming-mars.herokuapp.com/player?id=pc839ac7b5aa9

Good morning!!!!  I've been having the exact same problem with Imported Nitrogen and Nitrogen from Titan.  It will spend the resources for them, but then it gives the Pathfinders not defined error.  It also does not play the card from my hand, it does not take an action, and it does not give me any benefits of the played card.  It only spends the resources.  I had the same problem with the extremophiles card earlier in this generation, but it eventually played it, however it does appear in my tableau three times. However, it seems to only recognize it as one card. I only have the points from it once as far as I can tell, and anytime I go to add resources to it, it checks all three cards at the same time.  Is there any way this can be fixed?  Thanks so much, and have a blessed day!!!!

     In Christ's Love,
           Cody Alan Rushing :)
-Psalm 19:14

**Comment by kberg** [comment]
I know this has been fixed for some time.
