### ISSUE TITLE
Asteroid event should allow removing one's own plants

### ISSUE THREAD

**Issue by lizthegrey** [terraforming-mars/terraforming-mars#3737]

**Comment by kberg** [comment]
I've looked at a few references, et cetera, and in the end have to agree with @nwai90's question. I mean, the rules say you can do that. But is there a case where you would want to do that? Without a tactical benefit, providing that option seems to run the risk of players accidentally removing their own plants when they didn't want to.

![image](https://user-images.githubusercontent.com/413481/138030562-6bdddd79-abc5-4480-84b1-1fbb1f324701.png)

**Comment by lizthegrey** [comment]
Yup, the use case was crash site cleanup (but then I failed to read it carefully to say that you had to remove _another_ player's)

there already is an option to choose which player's production to reduce for other cards, so it seems at least consistent/not an oversight to explicitly show...

**Comment by kberg** [comment]
Here's a use case courtesy @memories90:

> memories90: Here is a far fetched edge case
> memories90: Haha
> memories90: I know my opponent has Crash site cleanup and a plant removal card
> memories90: I don't have enough plants to place a greenery and the game is ending this gen, so I want to remove my own plants
> k9: Because..... spite?
> memories90: To prevent them from being able to play Crash site cleanup and gain a cheap VP
> memories90: 🤣
> memories90: So that their plant removal card cannot target me and hence they cannot play Crash site for a very cheap VP
> k9: :standing ovation:

**Comment by kberg** [comment]
I realize these edge cases are _edgy_ but that's what I've been working on lately.

Here's what I propose when being asked to remove a players' plants. (This could apply to other resources, and might apply to #3931)

```
Select A Player To Remove Plants
  [X] Remove as many as possible
  ( ) opponent has 5 plants
  ( ) opponent has 3 plants
  **( ) YOU HAVE 6 PLANTS**
```
Instead of a checkbox it could be the normal OrOptions thing "Remove All The Plants" / "Let me choose how many plants" with "Remove All The Plants" as the default. And if the player chooses "Let me choose" they'll be presented with another dialog.

You as the self-target will be either bolded, or red, or will say "Hey that's you!". We can get that detail right later.

**Comment by kberg** [comment]
One never knows whether silence means assent or dissent, but I'm taking it assent.

**Comment by kberg** [comment]
Now that we have warnings, I'm considering this:

```
Select A Player To Remove Plants
  ( ) opponent has 5 plants
  ( ) opponent has 3 plants
  ( ) Do not remove plants
  ( ) Remove 3 plants from You.
    ** This removes plants from yourself **
```

It's at the end of the list so you really have to reach for it.

**Comment by kberg** [comment]
WIP is https://github.com/terraforming-mars/terraforming-mars/commit/b28d9969ba2c8cb899d8c8d96631b2c9fb541d1a

**Comment by kberg** [comment]
2.5 years later, here's a fix
