### ISSUE TITLE
License could be changed to AGPL

### ISSUE THREAD

**Issue by mwestphal** [terraforming-mars/terraforming-mars#3754]
tmweb license is currently under GPL license, which has basically no effect regarding hosting closed-source fork of the game.
I do not know why GPL was chosen as a license but it does not seems to be adapted.
AGPL would be a much better suited license.

See here for more info about GPL and AGPL licenses:
https://plausible.io/blog/open-source-licenses
https://www.gnu.org/licenses/why-affero-gpl.html

Using AGPL would prevent people from hosting a server running a private fork.

As for the technicalities, a few possibilities:

-  Actually relicensing the code. This require an agreement of all main contributors, while possible, may be lengthy (14 people as far as I can see). One time small contributions from contributoirs not willing to switch could be reimplemented  I suppose ?
- Relicensing some core module or even a single important file in the code. This will require people willing to host a closed source version of the code to remove this part, which can be  quite hard.
-  Just stating in the license that starting from a certain commit, all code is now AGPL. This is the simplest solution in terms of effort and will render any new version fully unusable by closed source fork, and over time, all part of the code would become AGPL. This should be doable if the maintainer agree.

This issue is mainly to open the discussion and see if their is any good arguments against going AGPL. Feel free to close if this has been already discussed somewhere else.

**Comment by kberg** [comment]
Thanks for the suggestion. This isn't the first time it's been mentioned.

**Comment by kberg** [comment]
I want to thank you for raising the issue. At this point, if we do decide to consider such a change, we can easily reopen the ticket.
