### ISSUE TITLE
Pathfinders: Ensure that Lava Flows is limited to volcanic spaces on Arabia Terra

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#3771]
From Discord:

>  Bug report for Arabia map: I played "Lava flows" and it was offered that i can placed the tile everywhere on the map, but it should only be placeable on the four volcanic spots!!!

**Comment by bafolts** [comment]
I can't recreate. I started a game with Lava Flows and was only able to select the correct spaces.
