### ISSUE TITLE
Incorrect MC production value after playing preludes

### ISSUE THREAD

**Issue by mrkam2** [terraforming-mars/terraforming-mars#3777]
Played Research Network (+1 MC production) and Allied Banks (+4 MC production), got +3 MC production total. See screenshot.

![Screenshot_20211107-213623_Chrome](https://user-images.githubusercontent.com/28267638/141059813-b65d0309-c201-4241-92b0-29f1a7ef0496.jpg)

**Comment by kberg** [comment]
Solo with Colonies starts with -2 Megacredit production.

**Comment by mrkam2** [comment]
Got it, thanks!
