### ISSUE TITLE
Pristar not showing preservation resources?

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#3782]
Bug report from Discord:

> It seems like Pristar doesn't have a display for the number of Preservation resources on it, was this intended?

**Comment by epsalon** [comment]
This is a problem for all corporations that have resources (Pristar, Pharmacy Union, Arklight, Astrodrill). In all of these cases the resource count is not shown in the "played cards" section, but does show in the "Actions" section if applicable.

**Comment by epsalon** [comment]
I figured out the fix.
Add:
```typescript
      resourceType: player.corporationCard.resourceType,
```
before line 204 in `src/models/ServerModel.ts`

**Comment by kberg** [comment]
Thanks, Alon. I sent out this change this morning:
https://github.com/terraforming-mars/terraforming-mars/pull/3791

>
