### ISSUE TITLE
When trading with a colony that gives resources, adds a resource even if tradeQuantity equals zero 

### ISSUE THREAD

**Issue by dennishorte** [terraforming-mars/terraforming-mars#3805]
<img width="328" alt="Screen Shot 2021-11-24 at 2 18 46 PM" src="https://user-images.githubusercontent.com/5265132/143319856-d0bbd998-f729-4d8a-9843-c292f1437d5e.png">

In the colony in the screenshot, if green were to trade with it now (forgetting that someone has already traded there this turn), green would place 1 resource for the colony and then be prompted to add zero resources for trading, but in fact, one additional resource will be added.

Seems to be caused by [this line of code](https://github.com/terraforming-mars/terraforming-mars/blob/22e51f4f21cd5809c09c94d18892ee129daaf944/src/deferredActions/AddResourcesToCard.ts#L29).

**Comment by kberg** [comment]
HAHA! Classic `||` vs `??` OK, I'll fix it.

**Comment by kberg** [comment]
Thank you for the report! Fixed.
