### ISSUE TITLE
Spectators should be able to see the cards played by all players

### ISSUE THREAD

**Issue by Cruncher999** [terraforming-mars/terraforming-mars#3860]
Spectator links on the server terraforming-mars.herokuapp.com cannot see any played cards by any player, the violet "show/hide" buttons appear to be without function. They only seem to work for regular players.

Google Chrome 94.0.4606.71 Linux, but I think I also tried Windows.

**Comment by kberg** [comment]
Thanks for the report. I spent 20 minutes digging into this and I don't have the answer yet but I'm sure it'll reveal itself to me.
