### ISSUE TITLE
Clarify Moon tags on The Archaic Foundation Institute corp do not count for ability?

### ISSUE THREAD

**Issue by puuj** [terraforming-mars/terraforming-mars#3873]
In almost every case, tags on corporations trigger that corp ability (e.g., Saturn Systems, Point Luna, Pharmacy Union). While The Archaic Foundation Institute does not have "including this" in its description since it departs from what normally happens in the game, it is probably worth calling this out explicitly (or changing the behavior).

**Comment by kberg** [comment]
Good spot. I'll add "including this" which of course makes it more
valuable, but I'm changing its starting MC for it.
