### ISSUE TITLE
Aridor Starting Action refuses to add colonies not in the game

### ISSUE THREAD

**Issue by dcmoyer** [terraforming-mars/terraforming-mars#3882]
At the start of the game, playing the Aridor Corp should add another colony tile. The game displays unused colony tiles correctly, but then when I choose one and click "Add Colony Tile", I get the following error (also in attached screenshot): 
Unknown colony "Europa"

![Screenshot from 2021-12-18 22-41-56](https://user-images.githubusercontent.com/4807477/146663224-7803d59b-5eed-440c-babe-c37f186247ab.png)

with Europa being a placeholder for any {colony}.

Eventually I modified the POST and sent a colony that's in the game already, and this added a second copy of the same tile to the game, see second screenshot.

![Screenshot from 2021-12-18 22-45-50](https://user-images.githubusercontent.com/4807477/146663229-d2de5141-41c5-4934-89e3-76fe71078102.png)

I think this has to do with the SelectColony method in:
https://github.com/terraforming-mars/terraforming-mars/blob/2813f10e9cdc8d262e73adedef64fce916ba3aca/src/Player.ts#1014

where in 1014 we get a list of the colonies in this.game, while in 1015 we check if the selected name is in that list (which it should not be for the game to proceed correctly).

Anyway, bug seems game breaking. I can PR a fix if you want, but this is my first game with this project so I'm probably not the person you want for this. (Love the rest of it btw, thank you for dev.)

**Comment by kberg** [comment]
Thanks for this report. I'm looking at this right now.

**Comment by kberg** [comment]
Probably broken by #3870
