### ISSUE TITLE
Potatoes not correctly removing plants

### ISSUE THREAD

**Issue by mwestphal** [terraforming-mars/terraforming-mars#3890]
The potatoes card is not removing plants correctly.

I was able to play it with only one plant. It removed only my single plant.

**Comment by nwai90** [comment]
Did you have Viral Enhancers in play?

**Comment by kberg** [comment]
Yeah I would like a little more detail about the game itself. Do you have a link to it?

**Comment by mwestphal** [comment]
> Did you have Viral Enhancers in play?

That was it ! thanks.


> Do you have a link to it?

self hosted, so nope :)
