### ISSUE TITLE
The action for Water Import From Europa shows as available even when all ocean tiles are placed - correct behavior?

### ISSUE THREAD

**Issue by scarson** [terraforming-mars/terraforming-mars#3891]
While playing a game today I noticed that the Water Import From Europa card action (Pay 12MC to place an ocean tile) always showed as available even after all oceans were placed. The Aquifer standard project was greyed out. I didn't actually try playing the card action at that point for fear of potentially breaking the game so I can't report on the behavior if chosen.

I'm not sure what the actual game rule is about this action. 
Page 11 of the [base rules ](https://www.fryxgames.se/TerraformingMars/TMRULESFINAL.pdf) says "When you use an action on a blue card, you must first pay any cost stated to the left of the arrow. You get whatever the arrow points to, and place a player marker on the card to indicate that it has been used during this generation."
Are you still able to pay the cost but unable to place the tile because there aren't any left for you to get?

If the action is unplayable, it would be nice to automatically mark it as unavailable so it doesn't keep showing up in the card actions list.

![chrome_knrqtwmrbi](https://user-images.githubusercontent.com/9357767/147203424-2c944ca0-062d-44ac-aa91-1f78da42771b.png)

**Comment by kberg** [comment]
It is playable, even though it's not too likely. There is at least one
thread out on BGG somewhere that discusses this, which I can find if you
like. But basically as a player who might want to delay the game an action
or two waiting for others to pass, they can take that action. Yes, it costs
them some money or titanium, but it's allowed.

**Comment by scarson** [comment]
Ah, gotcha. That makes sense. I looked at BBG threads before filing this but those were mostly around what happened when there were no ocean tiles left.

Is there any kind of warning or confirmation dialog for actions like this where you would pay the cost but not receive some/all of the benefit?

**Comment by kberg** [comment]
There is none. There was some discussion earlier on about possibly finding
those things that are easy gotchas you can miss but it didn't get too far.
