### ISSUE TITLE
[BUG] Android Chrome notifications

### ISSUE THREAD

**Issue by Billos** [terraforming-mars/terraforming-mars#3899]
The "new Notification" constructor is deprecated on chrome Android. 
Notifications should be performed with Web Workers

**Comment by bafolts** [comment]
Does this throw a `TypeError`? For now we should put this inside a try...catch since the thrown error could interrupt the game.

**Comment by Billos** [comment]
It seems that there is a TypeError thrown, but it doesn't interrupt the games.

To be more precise : 
I haven't tried to see the terraforming-mars code logs on my phone.
It's just noticing that there is no notification sent, and some quick tests with the old Notification API.
![image](https://user-images.githubusercontent.com/5809662/147787181-103f740b-082a-4bff-af91-93ac0ebec07f.png)
