### ISSUE TITLE
Scientists P4 not giving science tag bonus

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#3919]
As reported on Discord, and verified locally. @nwai90 I'll send you the copy of the production game which recreates it. In that case `player.hasTurmoilScienceTagBonus` is false.

**Comment by daniel-sousa-me** [comment]
In `src/cards/CardRequirement.ts` I converted the `player.hasTurmoilScienceTagBonus` into a stupidly named `player.getHasTurmoilScienceTagBonus()`

Then on `src/Player.ts` I added:
```  public getHasTurmoilScienceTagBonus(): boolean {
    return PartyHooks.shouldApplyPolicy(this.game, PartyName.SCIENTISTS, TurmoilPolicy.SCIENTISTS_POLICY_4);
  }
```

This seems to be working, but probably there's a better way to do this.

**Comment by kberg** [comment]
Hi @daniel-sousa-me, https://github.com/terraforming-mars/terraforming-mars/pull/3927 is what will immediately fix the issue, but I agree your change makes more sense. I'll follow up with that later. If you would like to submit such a PR (with a test of some kind?) I'd be grateful.
