### ISSUE TITLE
Asteroid Mining Consortium - prevent from self-stealing automatically

### ISSUE THREAD

**Issue by vpoiesz** [terraforming-mars/terraforming-mars#3931]
When you play a card like "Asteroid Mining Consortium" it requires you to decrease titanium production from any other player.

If there are more than 1 players with >0 titatanium production, the active user is presented with a choice of which player to affect with the card. When there is only one player with >0 production, the game automatically selects that player to decrement.

Well, if you happen to be the only player with titanium production, the game automatically decreases your own production then increases it... This can be frustrating if you accidentally played the card, or misread the other players' production levels.

I would vote to have the game always present the player selection menu even if there is only one player available to choose. But in lieu of that, if you are going to be the player automatically selected then it would be nice to have a warning step.

**Comment by kberg** [comment]
I agree that the current user experience could be better.

**Comment by kberg** [comment]
Fixed with #7c49916
