### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by AndrewSav** [terraforming-mars/terraforming-mars#3963]
Running:

```
docker build . -t terraforming-mars
```

Result:

```
Sending build context to Docker daemon  70.42MB
Step 1/11 : FROM node:lts-alpine
 ---> 23990429c0d7
Step 2/11 : EXPOSE 8080
 ---> Using cache
 ---> 15be070800f8
Step 3/11 : LABEL maintainer="bafolts"       name="terraforming-mars"       Version="1.0"
 ---> Using cache
 ---> 24fc93149ed2
Step 4/11 : RUN mkdir -p /usr/src/app/db    && addgroup -S tfm    && adduser -S -D -h /usr/src/app tfm tfm    && apk add --no-cache --virtual .gyp git python make g++
 ---> Running in f1e9537cbeeb
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  python (no such package):
    required by: .gyp-20220120.030443[python]
The command '/bin/sh -c mkdir -p /usr/src/app/db    && addgroup -S tfm    && adduser -S -D -h /usr/src/app tfm tfm    && apk add --no-cache --virtual .gyp git python make g++' returned a non-zero code: 2
```

**Comment by kberg** [comment]
Docker isn't explicitly supported, but we'll see if someone can help.

Also: ![image](https://user-images.githubusercontent.com/413481/150265843-109d1157-e2c9-4b02-a794-ce68049efa60.png)

**Comment by AndrewSav** [comment]
@kberg sorry about the discord. 

>Docker isn't explicitly supported, but we'll see if someone can help.

Well this is a community project run by volontures, everything is supported on "if there is anyone intereted in fixing this" basis. Since @bafolts using docker to run the heroku instance, I would image this is something that he would be keen to share [as he did before]

I think what happened is that node:lts-alpine image is now a different version so everything breaks. It's better not to put "sliding" labels in Dockerfile to avoid breakage. An explicit label is better. Fixing this temporary is as easy as changed the label to an older base image, unfortunately I'm not sure what it was.

**Comment by AndrewSav** [comment]
The below worked for me _if_ sqlite is upgrade to 5.x:

```
FROM node:16-alpine3.15

EXPOSE 8080

LABEL maintainer="bafolts" \
      name="terraforming-mars" \
      Version="1.0"

RUN mkdir -p /usr/src/app/db \
  && adduser -S -D -h /usr/src/app tfm \
  && apk add --no-cache --virtual .gyp git python3 make g++

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY --chown=tfm:nogroup . .

USER tfm

RUN npm run build

USER 0

RUN rm -rf .git \
   && apk del .gyp git python3 make g++

USER tfm

CMD [ "npm", "run", "start" ]
```

**Comment by kberg** [comment]
You can certainly fork the repo and use sqlite5 for the time being.

**Comment by AndrewSav** [comment]
I know. I'm just running bleeding edge - compiling this repo daily and build and push the image. Yesterday I made a mistake of cleaning up the dist of old images, so the old `node:lts-alpine` was gone, and the new refused to build the Dockerfile.

I'll just wait for https://github.com/terraforming-mars/terraforming-mars/issues/3965 I guess

**Comment by AndrewSav** [comment]
Okay, just replacing the FROM image with `node:14-alpine3.11` allows it to compile. May be when can apply that patch as an interim measure.

**Comment by zwrss** [comment]
Hello, just got here and wanted to try to build the docker image and had the same issue. Came here to check if it is already worked on.

> Okay, just replacing the FROM image with `node:14-alpine3.11` allows it to compile. May be when can apply that patch as an interim measure.

This is called version pinning and is a common (good) practice. Should not be considered interim. 

Vide :
https://nickjanetakis.com/blog/docker-tip-18-please-pin-your-docker-image-versions
https://www.balena.io/blog/our-dockerfile-tips-tricks/

**Comment by AndrewSav** [comment]
> This is called version pinning and is a common (good) practice. Should not be considered interim.

@zwrss interim in my comment was not with regards to base image version policy. Node 14 is old and won't stay like this long (hopefully). Also I wanted to propose a quick fix right now, as opposed to re-working the Docker file as in my comment about.
