### ISSUE TITLE
[Moon][PA] Add Moon parameters with Reds Policy 03

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#3969]
Reds policy lets a player reduce any global parameter. Should it take moon into account?

**Comment by HenrikSteenbock** [comment]
I would argue it should. Thematically, there is no reason why it wouldn't. My group counts Moon parameters like any others for all turmoil purposes when we play irl and it was a big quality of life improvement to not have to worry about what global parameters truly are considered global parameters.
