### ISSUE TITLE
[Bug] Game setup should not allow player to select a limited set of corps when those corps aren't compatible with the game.

### ISSUE THREAD

**Issue by ap3h3ad** [terraforming-mars/terraforming-mars#3994]
Hi,

I started a game today and included Pathfinder for the first time. One of the players played Ecoline and we noticed that the player got a plant production of 6. The log states "player x played Ecoline" three times. So I think the plant production of Ecoline gehts applied three times. Since Pathfinder is the only new thing in this game we think that it most definately has to do with this expansion.

One of the players picked a Turmoil corporation although the Turmoil expansion wasn't available at all. Maybe this triggered the bug.

**Comment by kberg** [comment]
Do you have a link to the game?

**Comment by ap3h3ad** [comment]
Sadly the game is gone.

I was informed by another player that this bug indeed happend before so I removed the "Pathfinder" part in the title. In both cases one player chose the corporation Incite without Turmoil being present in the game. The result was in both cases that every corporation got announced three times in the log and every corporation regarding production or resources were handles three times. So this might have to do with Incite specifically.

**Comment by kberg** [comment]
OK. What server?

**Comment by ap3h3ad** [comment]
Hi.

I was able to reconstruct the error case so that everyone can have a look at it on his own server. I used this settings:

https://abload.de/img/settingsyejth.png

to make sure it is possible to pick Incite for one of the players.

Then I picked Incite with the one player and Thorgate with the other one. I got prompted with this error message:

https://abload.de/img/error4mk8m.png

Seems reasonable, since Turmoil was indeed not active. But then I had a look at the log:

https://abload.de/img/thorgatebrokenxtj24.png

You can see that Thorgate gets mentioned two times and that the energy production got assigned two times. That incite is played isn't mentioned at all in the log. So I think the game doesn't handle the case "Turmoil corporation gets played without turmoiil in the game" correctly.

This might be due to the fact that the game (sometimes or always?) doesn't remove the Turmoil corporations from the custom corporation list when the Turmoil option is enabled and then disabled (so the Turmoil corporations come into the game in the first place).

I hope I delivered enough detail to shoot that bug. :)

**Comment by kberg** [comment]
@ap3h3ad what server is this?

**Comment by ap3h3ad** [comment]
@kberg 

This happened on my private server, not the public one (heroku?). If you want to know the URL - I'm sorry but I'm uncomfortable with sharing the IP of my server in this publicly accessible part of the internet.

**Comment by kberg** [comment]
That's fine. I recreated this locally, and in general you're right: the
corporation filter could provide better warnings.

**Comment by kberg** [comment]
The simplest approach is to reject any game that uses an incompatible corp.
Doing that is a little harder than expected. For instance, look at
Turmoil's corps Utopia Invest and Septum Tribus.

The former solely deals with resource production, while the latter deals
with political parties. But right now it's expected that both corps will be
available only when Turmoil is selected. We have no special indicator on
Septum Tribus that you need Turmoil to play it, it is implied. Does that
mean we have to annotate all the corps in expansions to indicate they're
playable with that expansion? Argh, I guess we can. It's on the order of
20-30 corps.

**Comment by kberg** [comment]
Changing the UI to be a little more helpful is a little more work, so I'll
probably stop at the part where we reject the erroneous case.

**Comment by kberg** [comment]
This is tightly related to #2225

**Comment by kberg** [comment]
@ap3h3ad unless you have strong feelings, I'd like to close this issue once a new release goes out, hoping the warnings is more than enough to detract a bad setup.

**Comment by kberg** [comment]
Closing, thanks!
