### ISSUE TITLE
[PF] Interaction with Private Security

### ISSUE THREAD

**Issue by Vulptrix** [terraforming-mars/terraforming-mars#4013]
Biomass Combuster supposed to decrease 1 plant production.
When my friend played it.
I'm the only one with plant production however I'm also have Private Security.
The problem is Biomass can be played without the need to reduce plant production.
![Terraforming Mars](https://user-images.githubusercontent.com/98706136/151710855-95642b88-6df6-4477-b91e-c4a8fa11b622.png)

**Comment by kberg** [comment]
Good catch. Thanks, I'll look at it.

**Comment by kberg** [comment]
Fix is simple and is out for review.

**Comment by kberg** [comment]
Fixed and deployed.
