### ISSUE TITLE
Docker build broken in recent commit

### ISSUE THREAD

**Issue by AndrewSav** [terraforming-mars/terraforming-mars#4015]
This commit https://github.com/terraforming-mars/terraforming-mars/commit/ff760848a78490b0b72b006fdde92e1e73e7c4ae has broken the docker build:

![log1](https://user-images.githubusercontent.com/658865/151893897-f9fcdc33-733c-4ba6-a744-935a735c2f5a.png)

This results in missing versioning info on the site:

![log2](https://user-images.githubusercontent.com/658865/151893924-c45729a8-7a5d-4ab1-aaa2-ab253e633333.png)

Can the be reverted? @kberg @jholm117

**Comment by jholm117** [comment]
Sorry about that, should be able to just take .git/ out of the dockerignore. Ill test it out one sec
