### ISSUE TITLE
Stratospheric Birds wont utilize all floaters from Dirigibles

### ISSUE THREAD

**Issue by xigarete** [terraforming-mars/terraforming-mars#4052]
Game has 3 floaters on dirigbles and 1 on another card.  Only allows me to use 2.  Suspect related to the 1 Stratospheric birds wants to eat, but the other one exists.

g12fe2fa3add4
<img width="1273" alt="Screen Shot 2022-02-07 at 12 53 46 AM" src="https://user-images.githubusercontent.com/40496447/152739458-3c0df6ce-6f56-4870-ade3-1a814bbccee3.png">

**Comment by kberg** [comment]
What happens if you click "MAX"?

**Comment by xigarete** [comment]
My recollection is that I clicked Max first and it didn't do what expected
and then I tried to click + and it also didn't do what was expected.

Buying a different card worked as expected; only stratospheric birds was
wrong... leading me to believe the negative floater was the problem... like
it assumed my negative floater had to come from dirigbles.

**Comment by kberg** [comment]
Gotcha. Found it. Fix is out.

**Comment by xigarete** [comment]
hi, so... I haven't been paying much attention.

no expectations.

-----
https://terraforming-mars.herokuapp.com/new-game is down r/n, maybe that's
dead?

https://tfm-community.herokuapp.com/new-game is up looks very similar -- is
that also you?  Maybe someone forked it.

If it IS you, can I petition to re-enable a feature that was removed?
 Because for us, playing with all the corps is preferred.  (e.g. 22 solo,
11 in 2 player)
