### ISSUE TITLE
Plants not spent when turning to greenery

### ISSUE THREAD

**Issue by grandsbor** [terraforming-mars/terraforming-mars#4122]
Cannot provide a lot of detail, but the game is [here](http://terraforming-mars.herokuapp.com/the-end?id=p4f11913a4b66).

One specific thing I can think of is that the turn which must have spent 8 plants to greenery was the final turn, i.e. it pushed oxygen to max while all the other parameters had already been maxed.

**Comment by kberg** [comment]
I just played a solo game as a test, and plants were deducted as expected.

**Comment by grandsbor** [comment]
I guess there must have been a specific set of conditions which might be hard to reproduce, that's why I included the link (idk if anyone can see the logs though)

**Comment by kberg** [comment]
Closing this as unreproducible. Thanks for the report though - I'll keep my eyes open.
