### ISSUE TITLE
Ambiguous card design "Medical Lab"

### ISSUE THREAD

**Issue by ap3h3ad** [terraforming-mars/terraforming-mars#4149]
Hi,

I think the Medical Lab card should be redesigned because the symbols are ambiguous. This is the current design:

https://abload.de/img/laberrkjw6.png

In my opinion this translates to "Get 1 MC production per 2 steel production you have", because the building tags on the brown background indicate steel production. In the card's text it's stated very clearly that you indeed get the MC production per 2 building tags. But imagine you are someone that has bad eyesight or has to rely on the symbols because of other reasons. Than this card symbols get very unclear. I think it would be clearer with a design like this ( obviously with the correct assets and not badly photoshopped like this example ):

https://abload.de/img/laber2d7jmw.png

**Comment by ap3h3ad** [comment]
I totally switched steel production and building tags

**Comment by kberg** [comment]
That said, I do wonder why the tags are inside the production box.
