### ISSUE TITLE
[Pathfinder] Terraforming Control Station discount not displayed in tag list

### ISSUE THREAD

**Issue by HenrikSteenbock** [terraforming-mars/terraforming-mars#4153]
![grafik](https://user-images.githubusercontent.com/44550180/155830114-b305ef57-f0f9-42df-b067-3e70752bdad8.png)
When playing Terraforming Control Station (Pathfinder), BOTH discounts are NOT shown in the list of tags as shown in the screenshot. The Venus discount that is shown in the screenshot is from Venus Waystation.

**Comment by kberg** [comment]
This was fixed in #4077. Are you hosting a server yourself?

**Comment by HenrikSteenbock** [comment]
No, this is happening in a game live right now on the public server. 

Spectator Link in case you look at this in time:
https://terraforming-mars.herokuapp.com/spectator?id=s74aa105f04bb

**Comment by kberg** [comment]
Deploying now.
