### ISSUE TITLE
Political Event Cloud Societies Bugged

### ISSUE THREAD

**Issue by NimitzH** [terraforming-mars/terraforming-mars#4187]
Event only gives floaters based on influence and doesn't add floaters to cards that can accept them as the event says it should.

**Comment by kberg** [comment]
Thanks for the report. I would like some more evidence, though. Because I'm pretty confident it does that, even if it's not logged. This code is most definitely run.

```
      const resourceCards = player.getResourceCards(ResourceType.FLOATER);
      resourceCards.forEach((card) => {
        player.addResourceTo(card, 1);
      });
```

**Comment by kberg** [comment]
If you have more information, I'm happy to reopen this issue, but I don't have enough to go on - sorry!
