### ISSUE TITLE
Botanical Experience affects MC stealing with Air Raid

### ISSUE THREAD

**Issue by Maelstrom1** [terraforming-mars/terraforming-mars#4188]
What it says on the tin
![image](https://user-images.githubusercontent.com/20371049/156965341-530339c3-7d18-417d-8693-880f93314570.png)
![image](https://user-images.githubusercontent.com/20371049/156965355-c37debf4-138f-4e11-ad74-24c9ef682e85.png)
![image](https://user-images.githubusercontent.com/20371049/156965371-93201d34-9c24-4779-8331-63189435c223.png)

**Comment by kberg** [comment]
Oh good catch. Sorry about that! A fix is out for review.
