### ISSUE TITLE
Confusing wording on Oumuamua Type Object Survey

### ISSUE THREAD

**Issue by Maelstrom1** [terraforming-mars/terraforming-mars#4189]
The wording implies that you draw two cards and share them face up, and keep them. The effect discarded them afterwards (because there was no effect) in the game that we played.

**Comment by kberg** [comment]
It's pretty hard to fit more text on that card. There was a short debate about it here: https://discord.com/channels/737945098695999559/891004790589517875/940692662925787177

**Comment by kberg** [comment]
Actually looking at Search for Life

![image](https://user-images.githubusercontent.com/413481/156968902-d22c8648-32e3-417e-82d9-f34cd81620d9.png)

it uses Reveal instead of Draw. Hmm.. OK I'm convinced.

**Comment by kberg** [comment]
Fixed by #4191
