### ISSUE TITLE
[Pathfinder] Crescent Research Association Moon discount not shown

### ISSUE THREAD

**Issue by HenrikSteenbock** [terraforming-mars/terraforming-mars#4212]
The corporation "Crescent Research Association" has a moon discount of 1/moon tag played, but that discount is not displayed:
![grafik](https://user-images.githubusercontent.com/44550180/158005096-c646eb1e-e14e-487b-bef0-deb4eb8f58bc.png)

For reference, the corporation:
![grafik](https://user-images.githubusercontent.com/44550180/158005155-9a2f78d3-d822-4c26-a636-4481ffee4ff4.png)

This occured on the public server.

**Comment by kberg** [comment]
Thanks for this report! I have just sent out a fix.
