### ISSUE TITLE
[PF] Valuable Gases

### ISSUE THREAD

**Issue by Vulptrix** [terraforming-mars/terraforming-mars#4213]
Pathfinder plelude Valuable Gases says play an active floater card ignore it "global requirement".
On one of my game I used it. It allow Stratopolis that required 2 science to play right there so it should be a bug I guess?
And another thing about it. If you don't have any active floater card. It seems to keep it resource somehow
because when my friend used this plelude only for it tags and ME.
During his action phase he played a card that can collect resource (this time it's Asteroid Right). It gains additional 5 resources.

**Comment by nwai90** [comment]
Thanks for the report! Note that Science tags are not a global parameter requirement

**Comment by kberg** [comment]
Thanks for this report! I sent out a fix.
