### ISSUE TITLE
Missing temp/money icons on VB map

### ISSUE THREAD

**Issue by SliceOfBread** [terraforming-mars/terraforming-mars#4215]
Playing the VB map and when I placed a tile in the center it increased the temp and (as Helion) asked me how I wanted to pay. Apparently this is as intended but there are no icons on the map to indicate this.

![vb](https://user-images.githubusercontent.com/13003705/158870323-74fa621f-e667-446e-9f72-967395809362.jpg)

**Comment by SliceOfBread** [comment]
I don't know who or when this got fixed but it is.

**Comment by kberg** [comment]
:partying_face:
