### ISSUE TITLE
[Ares] Ecological Survey not given credit for microbes

### ISSUE THREAD

**Issue by HenrikSteenbock** [terraforming-mars/terraforming-mars#4235]
![grafik](https://user-images.githubusercontent.com/44550180/160053018-cff2651b-08b3-4237-ae03-ea2e1bed07a8.png)

As seen in the log, geological survey gives itself credit for awarding the bonus steel/titanium, and ecological survey gives itself thet same credit when awarding an additional plant. However, the second microbe I got does NOT give that credit, when it really should say

[Player] added 1 microbe to [Card] because of Ecological Survey

This issue may also be the case for the extra animal awarded by ecological survey.

Issue observed on public main version.

**Comment by kberg** [comment]
Thanks for this report. I see where it is happening, and I can probably fix it.
