### ISSUE TITLE
French translations

### ISSUE THREAD

**Issue by 1GodRage** [terraforming-mars/terraforming-mars#4240]
Some texts are still in English when playing in French language.
![image](https://user-images.githubusercontent.com/63362446/160249365-4d20648e-e036-4dcf-9327-6adaa48ac1f2.png)

**IU:**
Select card(s) to buy >>> Choix de cartes à acheter.
Buy 2 >>> Acheter 2
Skip this action >>> Passer cette action

**Card:**
Look at the top 4 cards from the deck. Take 2 of them into hand and discard the other 2. >>> Regardez les 4 cartes du dessus de la pioche. Prenez 2 d'entre elles et défaussez les 2 autres.

**Comment by kberg** [comment]
Thank you for this report. This is a general known problem with the
translations, that they are partially done.

I can submit a patch for that specific translation, but it certainly won't
fix all the others.

**Comment by 1GodRage** [comment]
![image](https://user-images.githubusercontent.com/63362446/160255603-80f9410b-8d2b-4808-aff8-0f66cb12a227.png)
Other card found. >>> Regardez les 3 cartes du dessus de la pioche. Prenez 1 d'entre elles et défaussez les 2 autres.

**Comment by kberg** [comment]
I can't do one-off translations like this often, but  I thank you for these.
