### ISSUE TITLE
Icons calculating incorrect

### ISSUE THREAD

**Issue by Buheda** [terraforming-mars/terraforming-mars#4249]
Calculating icons count is incorrect. Looks like Events icons not counting
earth, science, star
![image](https://user-images.githubusercontent.com/5812181/160303924-1cc69a23-99dc-43ba-9016-b7cfe8b2af2f.png)
https://terraforming-mars.herokuapp.com/player?id=pee6705223596

**Comment by nwai90** [comment]
@Buheda It's correct. Tags on event cards do not count as per official rules

**Comment by Buheda** [comment]
@nwai90  ou.. You are right. I didn't notice this moment. Thank you
