### ISSUE TITLE
Venus: 12 generation instead of 14 in solo

### ISSUE THREAD

**Issue by Buheda** [terraforming-mars/terraforming-mars#4260]
According to rules
![image](https://user-images.githubusercontent.com/5812181/160954172-251a61a0-9fee-468d-9b03-1b5d75f1144c.png)
! You still start at 14 TR and **have 14 generations**
but my game was finished after 12
![image](https://user-images.githubusercontent.com/5812181/160954283-417778e0-accb-4a5b-a6d1-a6b3577493f8.png)
https://terraforming-mars.herokuapp.com/the-end?id=p7f58aafdeeba

**Comment by nwai90** [comment]
You played with Prelude, so it's 12 generations instead of 14
