### ISSUE TITLE
Venus: Finishing with calculating Venus scale

### ISSUE THREAD

**Issue by Buheda** [terraforming-mars/terraforming-mars#4262]
![image](https://user-images.githubusercontent.com/5812181/161062185-44cd6117-af7b-41fc-a607-ed55d515895b.png)

According to rules I can see that
It offers more opportunities to get Terraform Ratings (TR) and bonus steps, and, like other global parameters, it stops giving
TR when maxed out. **But the Venus scale is not an end game condition** – y**ou still only need temperature, oxygen, and oceans to be maxed out to end the game**, meaning that some games will see the Venus scale completed well before the end, while at other times it will hardly be touched at all.
![image](https://user-images.githubusercontent.com/5812181/161063186-d0eb3f1b-8dec-4450-83b4-cc5be6d57666.png)
![image](https://user-images.githubusercontent.com/5812181/161063300-390f1408-cb71-4698-a04d-697e53e2bef1.png)
https://terraforming-mars.herokuapp.com/the-end?id=p7f58aafdeeba

**Comment by nwai90** [comment]
@Buheda This rule only applies to multiplayer games. For solo with Venus expansion, you have to max out Venus as well since there is World Government Terraforming to help

**Comment by Buheda** [comment]
@nwai90 Argh... I read rules, but missed this. They should bold such differents. So many details easy to miss smth. Sorry for disturbing.  
Thank you
