### ISSUE TITLE
Payment dialog for nonexistent resource

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#4274]
<img width="426" alt="image" src="https://user-images.githubusercontent.com/934551/161385352-23a8eb59-df5d-4ec2-8a77-cdf285cf6d99.png">

**Comment by kberg** [comment]
OK, I can't get to it until tonight.

**Comment by kberg** [comment]
> <img alt="image" width="426" src="https://user-images.githubusercontent.com/934551/161385352-23a8eb59-df5d-4ec2-8a77-cdf285cf6d99.png">

scroll to the bottom of the game and click "spectator link" Can you share that, please?

**Comment by kberg** [comment]
(I can't recreate the issue.)

**Comment by kevinb9n** [comment]
Sorry - if I see it again I'll reopen.
