### ISSUE TITLE
"Prototype" font does not support Polish characters

### ISSUE THREAD

**Issue by Argeento** [terraforming-mars/terraforming-mars#4276]
![image](https://user-images.githubusercontent.com/13007891/161425221-fe709fb8-ee6f-498c-ab4e-caa6dbc23aab.png)

**Comment by kberg** [comment]
Is the written text wrong, or is it just a matter of how they are drawn? It looks like the latter but it's good to confirm.

**Comment by kberg** [comment]
Roboto 700 Bold might do the job.

![image](https://user-images.githubusercontent.com/413481/162590442-26640266-53a7-4fc2-90b9-25d74203e237.png)

It's one of the fonts on https://www.whatfontis.com/Prototype.similar

**Comment by kberg** [comment]
Play is nice too ![image](https://user-images.githubusercontent.com/413481/162590509-ff72364f-ef3e-4835-897e-0607452aaab3.png)

**Comment by kberg** [comment]
![image](https://user-images.githubusercontent.com/413481/162590568-def13172-4e23-42a8-9e08-6b3aa43bdc20.png)

**Comment by kberg** [comment]
These are all free Google fonts.

**Comment by Argeento** [comment]
The glyphs are missing. 

Mostly we need cover for ["European Latin"](https://maximilian.schalch.de/2018/05/complete-list-of-european-special-characters/) (every font: ✔️)

`Exo` is missing [Slavic Cyrillic](https://en.wikipedia.org/wiki/Cyrillic_script)

Imo `Play` looks good 🚀

**Comment by kberg** [comment]
@Argeento if this is something you'd like to implement, feel free. I could get to this in the coming weeks.

Could be an automatic selection based on having selected Polish. Or could be part of the experimental UI (still while lang === polish).

**Comment by Pyzdra** [comment]
[Prototype.zip](https://github.com/terraforming-mars/terraforming-mars/files/9950127/Prototype.zip)
I found Prototype font with polish characters on forum: https://www.gry-planszowe.pl/forum/viewtopic.php?f=55&t=74422&start=200.
Could you replace the font with the one provided? (It's zip cause github does not accept .ttf as attachement).

**Comment by rafalszampera** [comment]
Based on the font licensing: "Copyright 2001, free for personal use, freely distributed with Prototype.txt" So the license is the same as the original Prototype font.
@Pyzdra Your font is resolving problems with a lack of all European Latin chars, I create PR with this font: https://github.com/terraforming-mars/terraforming-mars/pull/5118

**Comment by kberg** [comment]
> [Prototype.zip](https://github.com/terraforming-mars/terraforming-mars/files/9950127/Prototype.zip) I found Prototype font with polish characters on forum: https://www.gry-planszowe.pl/forum/viewtopic.php?f=55&t=74422&start=200. Could you replace the font with the one provided? (It's zip cause github does not accept .ttf as attachement).

@rafalszampera thanks for the comment. I'm sorry I didn't respond to this earlier.

I don't think it's correct to completely replace the Prototype font. It's not known if this implementation of Prototype is compatible with the other languages. So I'd consider an implementation that only provides this version only when Polish is selected.

**Comment by kberg** [comment]
Fixed at head
