### ISSUE TITLE
Worms cardNumber is 130

### ISSUE THREAD

**Issue by skluyskens** [terraforming-mars/terraforming-mars#4278]
See also https://boardgamegeek.com/image/3169324/milenaguberinic

Maybe you should add a unit test to validate that all cards have unique cardNumber's?

**Comment by skluyskens** [comment]
Space elevator is 13
https://www.fryxgames.se/wp-content/uploads/2016/01/TM013spaceelevator.ai_1.jpg

**Comment by skluyskens** [comment]
Heather is 88
https://entropymag.org/wp-content/uploads/2017/11/IMG_6241.jpg

**Comment by kberg** [comment]
> Maybe you should add a unit test to validate that all cards have unique cardNumber's?

We've talked about that. It'll be a bear of an effort because card numbers are currently corrected by best effort.

Thanks for the report.

**Comment by kberg** [comment]
The card number is no longer a visual component. Closing this bug.
