### ISSUE TITLE
[PF] Economic Help interaction with maxed PF tracks

### ISSUE THREAD

**Issue by HenrikSteenbock** [terraforming-mars/terraforming-mars#4323]
Economic Help increases the lowest planetary track a few steps, but some tracks are shorter than others. If the jovian track is already maxed and the moon track (and presumably any other longer track) is currently beyond the maximum of the jovian track, playing this card has no effect on planetary tracks, because the lowest planetary track cannot advance any further. While it is not explicitly stated, I feel like the card should not increase the lowest planetary track, but the lowest NOT maxed planetary track.

**Comment by kberg** [comment]
OK. That seems fair.

**Comment by kberg** [comment]
If you can get some corroboration of that on bgg, I'd be grateful.
Otherwise, I think the card is correct as the rules themselves apply. Not
sure I want to house rule this one.

Even if you can't get an official ruling, others can talk about how they
see that card.
