### ISSUE TITLE
In solo, "Undo" is regularly undoing two actions at once

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#4356]
This probably started more than a day but less than a week ago?
Just start a solo game with undo enabled, do some things and then undo. 

URL: https://terraforming-mars.herokuapp.com/player?id=pde95f5755358
Player color: spectator  <-- hmm that's odd
Version: 912b775 Sat, 23 Apr 2022 01:16:32 GMT
Browser: Chrome 100

**Comment by kevinb9n** [comment]
It appears that if you've done an odd number of actions that generation then it will undo only one.

**Comment by kberg** [comment]
The bug report dialog needs more work, including that player color.

**Comment by kberg** [comment]
This is peculiar. I will rollback the save change until it's better
understood.
