### ISSUE TITLE
PlayerTag display reversed -- hideZeroTags logic wrong

### ISSUE THREAD

**Issue by puuj** [terraforming-mars/terraforming-mars#4362]
Recent changes seem to have removed the preference allowing the PlayerTag display to show all tags (rather than just played tags). In addition, the logic seems to be reversed -- `hideZeroTags` should really be `showZeroTags`. The relevant code in `src/client/components/overview/PlayerTags.vue` reads:
```
        if (entry.count === 0) {
          return this.hideZeroTags || (Shared.isTagsViewConcise(this.$root) ?? true);
        }
```
As a result if `hideZeroTags` is true, the tag is shown.  In the Heroku instance, this results in all tags being shown in the player's top bar, and only active tags shown in the player overview display.

I assume the reason for this construction is that the zero tags should be forced off in the top bar, but should be controllable in the player display. That being the case, this clause should only return `true` when hideZeroTags is false and concise is false, and the logic should really be:

```
        if (entry.count === 0) {
          return !(this.hideZeroTags || (Shared.isTagsViewConcise(this.$root) ?? true));
        }
```

This is also a confusing construction, so perhaps it is better to simplify as:

```
        if (entry.count === 0) {
          return !this.hideZeroTags && !(Shared.isTagsViewConcise(this.$root) ?? true);
        }
```

I don't fully understand all that happened in the rewrite of the Preferences Dialog, but `isTagsViewConcise` doesn't have an option and so is not really controllable. I personally like the full tag display particularly since it's easier to compare tag counts across all players, so I support having an option in Preferences.

**Comment by kberg** [comment]
Thanks for this thorough analysis. Sorry about that! I'll fix it in the
next day or two. :/

**Comment by kberg** [comment]
You're right. I did something a little easier to read, I think:

```
if (entry.count === 0) {
  if (this.hideZeroTags) return false;
  if (Shared.isTagsViewConcise(this.$root) ?? true) return false;
}
```
