### ISSUE TITLE
Red Influence Turmoil event took more money than it should

### ISSUE THREAD

**Issue by JeremyDietrich** [terraforming-mars/terraforming-mars#4375]
![TMError](https://user-images.githubusercontent.com/67653347/165678375-112a7af4-22e8-4e0d-8b61-c1b1f6e7440b.png)

This should only decrease Red's money by 15 max because of the wording saying max 5 sets, but as Red was at 59 TR it was instead decreased by 27 (9 sets).

**Comment by kberg** [comment]
Thanks. A fix is out.
