### ISSUE TITLE
[PF] Geological Expedition does not give bonus resources on hazards during final greenery placement.

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#4400]
From Discord:
>  Geological Expedition  has very minor bug, it does not give bonus resource(plant at least) when placing at "final greenery placement phase" after the regular gens are ended. Although i only got to try this when placing on hazard tile so might be that instead that blocked it , dunno.
> Played another gen and it was due to hazard.

**Comment by kberg** [comment]
Manual test verifies that it is correct.

**Comment by Borbarad2** [comment]
What is left to close this bug?
