### ISSUE TITLE
Game didn't allow Aridor's first action new colony to be placed

### ISSUE THREAD

**Issue by JeremyDietrich** [terraforming-mars/terraforming-mars#4410]
Clicked on the button to use Aridor's first action to add a colony tile, but it was just skipped and no new colony was added - sorry, no screenshots to show anything that happened

**Comment by kberg** [comment]
This is what I need -- otherwise I'll have to close this as not reproducible.

1. Click the gear icon on the bottom
2. Click "Report a bug"
3. Copy that content into this issue.

**Comment by JeremyDietrich** [comment]
I'm sorry, I'm not sure what you mean by this. I'm hosting the game on the Heroku server, and when I click on the gear icon on the bottom it doesn't have an option for "Report a bug". I just came here from the "report a bug" redirect on the Readme.

![image](https://user-images.githubusercontent.com/67653347/167036522-5ab26a74-2452-446a-a20c-fd2ed6b5a89e.png)

However, I can show you the before and after of what happens when I try this, with a cloned version of the game. I'm sorry, I don't know what else I can provide 😞 

![image](https://user-images.githubusercontent.com/67653347/167037162-b6074860-0ca2-4893-b11c-7fa18c881445.png)
![image](https://user-images.githubusercontent.com/67653347/167037251-9fe3b785-0631-4e43-91f9-a2b8dd5ffb8c.png)

**Comment by JeremyDietrich** [comment]
However, it does work on the general instance that is up at terraforming-mars.herokuapp.com, so maybe there's something up with the specific instance I have downloaded. Sorry!

**Comment by nwai90** [comment]
Closing as issue is not reproducible

**Comment by kberg** [comment]
I will add, also, that I think this has been fixed in the latest version of
the repo. If you get a fresh pull and try again and that still happens, had
a comment here, please.
