### ISSUE TITLE
Asteroid Mining Consortium is not eligible to be played in Solo mode

### ISSUE THREAD

**Issue by GitDavid** [terraforming-mars/terraforming-mars#4420]
Requirements for playing Asteroid Mining Consortium are:
13 creds
Having at least 1 titanium production

At this stage in game player has:
7 creds
2 titanium production
2 titanium resources (should give -6 cred discount to the cost)

The player has sufficient resources to play Asteroid Mining Consortium since requirements are met.  Also, per page 13 of original rulebook, for solo mode:

```
4) You have a neutral opponent that you can steal from, or
reduce any kind of resources and production from.
```

Game where this occurred
```
URL: https://terraforming-mars.herokuapp.com/spectator?id=s3229432412e3
Player color: red
Step: 10
Version: ce850d0, built at Sat, 07 May 2022 03:54:04 GMT
Browser: Chrome 101
```

**Comment by kberg** [comment]
Thanks for the report! Asteroid Mining Consortium has a Jovian tag, not a Space tag, so the titanium rule does not apply.

![image](https://user-images.githubusercontent.com/413481/167280460-804c4ea7-0af6-4975-988b-c58d211e6128.png)

Closing this, but feel free to respond if you have any further questions.
