### ISSUE TITLE
Victory points details improvement

### ISSUE THREAD

**Issue by rogerta** [terraforming-mars/terraforming-mars#4432]
Love the new "Victory points details" graph at the end of the game!

Small suggestion: Include the point differential from the previous generation when I mouse over a point in the graph.  Today I see something like:

```
7
[] Roger: 43
```
maybe it show differential something like:
```
7
[] Roger: 43 (+7)
```

**Comment by kberg** [comment]
@rogerta thanks for the suggestion. My general thought here is that it's not really adding much. We have a pretty crowded UI.

If you have more supporting information about why this is useful, it would help. Actually, what would help is knowing why it's necessary.

I know it's a small change. Let me know.

I'm going to close this, but if there's compelling new information, I'll reopen it, or better, implement it.
