### ISSUE TITLE
Adding url query string to card list page

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#4434]
### Discussed in https://github.com/terraforming-mars/terraforming-mars/discussions/4427

<div type='discussions-op-text'>

<sup>Originally posted by **sickerin** May  8, 2022</sup>
Will make it easier if people want to share a group of cards, etc.

`http://terraforming-mars.herokuapp.com/cards`  -> 
`http://terraforming-mars.herokuapp.com/cards/search?keyword=test` (for the keyword in the search/ filter bar)
`http://terraforming-mars.herokuapp.com/cards/filter?keyword=test` (for buttons you can click that want to be included)
`http://terraforming-mars.herokuapp.com/cards/unfilter?keyword=test` (for buttons you can click that want to be included) 

Need to figure out how to make the URL not very long, i.e if we default to deselection in the URL, then it will be very long. I think the default assumption should be all filters are selected. When we unselect some tags, we'll use the `unfiltered` query. However, if the everything is unselected, and only base, event, space tag are selected, the URL will then be also long, in that case, maybe the URL will have its `unfiltered` query will be  'all' and `filtered` be base, event, space tag. 

Maybe having the URL being long is a big deal, and we just use the `unfilter` query 

I'll research more on how other websites do this.

For tags, we could use letters. i.e "s" for space tag. 

</div>

**Comment by kberg** [comment]
This already existed, but it didn't work very well, and it also slowed down the page quite a lot. It could be restored.

**Comment by 707090** [comment]
I haven't looked at the code for this project yet, but just a general idea, I think a nice way of encoding different filter settings would be as a mask. For example, if the user had only "global events", "milestones", and "awards" selected from the middle row, a query param like "types=7" could summarize that well. With the logic being that there are 11 different types, which correspond to 11 different bits in a number. And 7 corresponds to -> 00000000111 (the last three being selected). This way you could summarize each row with one mask and its only 3 parameters. 
`http://terraforming-mars.herokuapp.com/cards?search=test&expansions=321&types=87183&tags=820485682`

Pros:
This would allow link sharing again with relatively short URLs
It would be fast/easy to separate out the mask back into a list of active filters

Cons:
It would not be a very human readable URL. I don't think this is a big issue as I am pretty sure users hand-crafting URLs is relatively rare.

**Comment by kberg** [comment]
Thanks for the suggestion. Fuller filters in URL is good. IMO bit sets isn't particularly necessary.

The reason the filter isn't fully functional is for a long time the filter was very slow. A recent change made fuller filters faster, so I could see tossing those back in.
