### ISSUE TITLE
[i18n] Card List: Sorting does not respect localization

### ISSUE THREAD

**Issue by pczyk** [terraforming-mars/terraforming-mars#4443]
The card list (/cards) does not respect the localization chosen by the user when sorting cards but sorts cards by their English title. I've attached an example as screenshots. You see that in English, they are sorted alphabetically

1. Acquired Company
2. Adaptation Technology
3. Adapted Lichen
4. Advanced Alloys
5. Advanced Ecosystems

<img width="1859" alt="card_list_en" src="https://user-images.githubusercontent.com/16086991/168087016-b8afc75d-1042-4155-b68c-d96fa1e887b5.png">

while in the German localization, they appear to be somewhat random because the same card user is used, but the cards are just translated:

1. Übernommenes Unternehmen
2. Adaptionstechnologie
3. Angepasste Flechten
4. Verbesserte Legierungen
5. Fortgeschrittenes Ökosystem

<img width="1834" alt="card_list_de" src="https://user-images.githubusercontent.com/16086991/168087074-3c11b1f6-e440-4fe6-bde3-24a4bc12e68d.png">

**Comment by kberg** [comment]
This was fixed a month ago.
