### ISSUE TITLE
Buying additional delegates doesn't decrease ME reserves 

### ISSUE THREAD

**Issue by Bascule** [terraforming-mars/terraforming-mars#4486]
Think i found a bug. Had 12 ME left and used it to buy two extra delegates, then found I still had 12 ME left!

**Comment by kberg** [comment]
Please use the "Report a bug" feature available from the gear box on the lower left corner of the app, which will provide a little more information.

**Comment by Bascule** [comment]
Apologies
URL: https://terraforming-mars.herokuapp.com/spectator?id=s1db9798a56d1#cards
Player color: red
Step: 30
Version: fd4b2cb, built at Tue, 10 May 2022 04:50:43 GMT
Browser: Chrome 101

**Comment by kberg** [comment]
I don't see this issue, nor have I heard of it being reported elsewhere. I'm going to close this, and if it happens again, I'll pay close attention.
