### ISSUE TITLE
Attempting to Undo causes "Unable to perform undo operation. Error retrieving game from database. Please try again." Error

### ISSUE THREAD

**Issue by nimbusscale** [terraforming-mars/terraforming-mars#4505]
When trying to undo in a game we just started fails and the error "Unable to perform undo operation. Error retrieving game from database. Please try again." is displayed in the log.  It happens for other players in the game as well.

URL: https://terraforming-mars.herokuapp.com/spectator?id=s8518e62f04c1
Player color: red
Step: 27
Version: b54550a, built at Thu, 26 May 2022 03:33:32 GMT
Browser: Chrome 98

**Comment by harkovs** [comment]
Same here on version: 2943c5356 running under docker with a postgresql database.

**Comment by harkovs** [comment]
The game logs the following error:
`[2022-06-28 08:08:20 GMT+0000] [ 'TRACKING:', 'ga937fdaeabee', 'restore to', 4 ]`
`[2022-06-28 08:08:20 GMT+0000] PostgreSQL:restoreGame Game ga937fdaeabee not found`
`[2022-06-28 08:08:20 GMT+0000] game not found while restoring game undefined`

Then when I query the database:
`SELECT 
	game_id,
	players,
	save_id,
	game,
	status,
	created_time
FROM public.games
where game_id = 'ga937fdaeabee'
order by save_id desc
;`

save_id 4 is indeed missing:
![image](https://user-images.githubusercontent.com/18922776/176129051-ba48bee0-3587-44ba-979a-f29843b0405d.png)

**Comment by kberg** [comment]
Yeah, I'm really really sorry about this one. I'm trying to fix it.

Tell me, do those happen after a server restart?

**Comment by harkovs** [comment]
It happens both with games started before a server restart and games that were started after a restart.

**Comment by nimbusscale** [comment]
Hi, @kberg I wanted to thank you and everyone else who has made this a reality. You are all awesome and I hope you have a great day!

**Comment by kberg** [comment]
> Hi, @kberg I wanted to thank you and everyone else who has made this a reality. You are all awesome and I hope you have a great day!

On behalf of everyone else - my pleasure.
