### ISSUE TITLE
Add the timer on the card/corp/prelude selection

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#4518]
> It's a bit annoying not knowing how much time you're wasting with your indecision lol

**Comment by StaticBR** [comment]
I actually think it is good that the timer is not yet started. Because players are not all arrive on the same time and some of them already started the  selection to kill the time, not because they are taking this long to decide.
So I like it that the timer only starts after the game starts.

**Comment by kberg** [comment]
> I actually think it is good that the timer is not yet started. Because players are not all arrive on the same time and some of them already started the selection to kill the time, not because they are taking this long to decide. So I like it that the timer only starts after the game starts.

Trying to figure out how this works, I started a test game and looked at what the spectator sees.

When both players are drafting, the timer counts up.

Then when one player drafts, their timer seems to get reset to 0:

![image](https://user-images.githubusercontent.com/413481/172541010-d9c13559-7de4-4f5d-8795-530b40645958.png)

When the other player drafts, their timer is also reset to 0:

![image](https://user-images.githubusercontent.com/413481/172541150-fae465ec-6502-4cdd-bdb7-a0c15c03a5cf.png)

So huh. Looks like @StaticBR is right, there is no real cost.

**Comment by kberg** [comment]
Happy to reopen this if anything changes.
