### ISSUE TITLE
Aridor: mandatory first action does not work, does not place new colony

### ISSUE THREAD

**Issue by BeriAlpha** [terraforming-mars/terraforming-mars#4522]
Playing Aridor, I am given the option to take their mandatory first action (place a new colony tile) but the app does not offer a colony selection, place a colony, it acknowledge the selection in any way.

URL: https://terraforming-mars.herokuapp.com/spectator?id=sa23502a794c7
Player color: blue
Step: 8
Version: b54550a, built at Thu, 26 May 2022 03:33:32 GMT
Browser: Chrome 102

Reproduction: Use my player link,
https://terraforming-mars.herokuapp.com/player?id=pf80ed0c3a196
Under Actions, select 'Take first action of Aridor corporation' then 'Place a colony tile'. Observe that the game moves on and no new colonies are placed.

**Comment by kberg** [comment]
> @BeriAlpha Do you know if a custom colonies list was used for this game?

It wasn't:

```
  "gameOptions": {
    "boardName": "hellas",
    "undoOption": true,
    "showTimers": false,
    "fastModeOption": true,
    "showOtherPlayersVP": true,
    "corporateEra": true,
    "venusNextExtension": true,
    "coloniesExtension": true,
    "preludeExtension": true,
    "turmoilExtension": false,
    "aresExtension": false,
    "aresHazards": true,
    "politicalAgendasExtension": "Standard",
    "moonExpansion": false,
    "pathfindersExpansion": false,
    "promoCardsOption": true,
    "communityCardsOption": false,
    "solarPhaseOption": true,
    "removeNegativeGlobalEventsOption": false,
    "includeVenusMA": true,
    "draftVariant": false,
    "initialDraftVariant": false,
    "startingCorporations": "3",
    "shuffleMapOption": false,
    "randomMA": "Limited synergy",
    "soloTR": false,
    "customCorporationsList": [],
    "cardsBlackList": [],
    "customColoniesList": [],
    "requiresVenusTrackCompletion": true,
    "requiresMoonTrackCompletion": false,
    "moonStandardProjectVariant": false,
    "altVenusBoard": false,
    "escapeVelocityMode": false
  },
```

**Comment by kberg** [comment]
**FOUND IT.**

I'll fix it immediately.

**Comment by kberg** [comment]
This is great. Thank you! Hopefully I can catch this one now.
