### ISSUE TITLE
Undo Last Action went back to beginning of previous generation

### ISSUE THREAD

**Issue by justin-dupre** [terraforming-mars/terraforming-mars#4533]
After clicking on "Undo Last Action" button in the middle of placing a greenery tile action, the game reverted back to the beginning of the previous generation. Two generations later, we recieved a 503 error and the gamer reverted back ~ 2 or 3 generations back to where it reverted the first time.

URL: https://terraforming-mars.herokuapp.com/spectator?id=sfdd45ed24e2e
Player color: red
Step: 93
Version: 2bf20be, built at Fri, 03 Jun 2022 05:03:31 GMT
Browser: Chrome 101

**Comment by kberg** [comment]
Thanks for the report. While there is a general Undo issue that I'm working on, we also had an unannounced outage from Heroku that seemed pretty icky. Nothing to do, sorry.

**Comment by justin-dupre** [comment]
@kberg No problem, thanks for the response. Darn Heroku

**Comment by kberg** [comment]
I'm still working on the basic undo problem though.
