### ISSUE TITLE
[Colonies] Productive Outpost and Pluto compatibility

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#4536]
Report by user (rewritten for clarity)

> when we play Productive Outpost on with several colonies on Pluto, i think that we first draw all the cards then discard as many, whereas i think it should be a sequence of draw+discard

According to the unofficial FAQ:

> When playing this card, you choose the order to collect each of your colony bonuses in. Note that if you have multiple colonies on Pluto, each colony bonus must be resolved separately (draw 1 card, discard 1 card for each colony, one draw/discard at a time).

**Comment by kevinb9n** [comment]
FWIW, I theorized that "draw then discard" is a single atomic operation here, but didn't get an official response.
https://boardgamegeek.com/thread/2626062/article/37312912#37312912

**Comment by kberg** [comment]
I think there's a path to solving this issue, which is to just have colony bonuses report back when they're complete. The API is there now.
