### ISSUE TITLE
Philares bonuses not granted during final greenery placement

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#4538]
From discord:
>  Sometimes you don't get adjacency bonus for final greenery placement.   Ie this game i placed next to ocean santuary in the end but it didnt grant me animal https://terraforming-mars.herokuapp.com/the-end?id=p3e2816506346
>  yeah it was the same with philares iirc

![image](https://user-images.githubusercontent.com/413481/172205644-9e87f02a-4fe1-4124-84f7-6fc02e814a18.png)

**Comment by Borbarad2** [comment]
Yes, i can confirm that kind of issue: no placement bonus with Philares in the final greenery placement phase

**Comment by kberg** [comment]
I've been able to identify a root cause. It's a little tricky to fix, unfortunately, but I'm on it.

The short, technical version is that both Philares and Final Greenery Placement both directly call `setWaitingFor`. Both should be deferred actions. Unfortunately, making Final Greenery Placement a deferred action doesn't seem to pick up the request, so more debugging is necessary.

**Comment by kberg** [comment]
Ares placement works just fine.
