### ISSUE TITLE
Commercial district : no million when placed adjacent to an ocean

### ISSUE THREAD

**Issue by boohrebooh** [terraforming-mars/terraforming-mars#4539]
Hi,

I have a bug in the following game :

> URL: https://terraforming-mars.herokuapp.com/spectator?id=se85d8fc05b9a#cards
> Player color: green
> Step: 141
> Version: 2bf20be, built at Fri, 03 Jun 2022 05:03:31 GMT
> Browser: Firefox 101

When i place the commercial district, i didn't get the 2 million bonus for the adjacent ocean : 

![image](https://user-images.githubusercontent.com/107004637/172251008-7cca5a16-eae8-4519-b826-e7ef8408f17f.png)
![image](https://user-images.githubusercontent.com/107004637/172251095-63f5480d-ee18-4e08-affb-5ca8ba06b94d.png)

Regards

**Comment by kberg** [comment]
Thanks for the explanation. What makes you suspect you didn't get the
credit for placing next to an ocean?

**Comment by kberg** [comment]
@boohrebooh I'm waiting on you for a response. I'll otherwise close this as not reproducible.
