### ISSUE TITLE
Market Manipulation action prompt changes

### ISSUE THREAD

**Issue by justin-dupre** [terraforming-mars/terraforming-mars#4541]
Whenever I play the Market Manipulation card, it can be jarring to read the many lines of text that appear to choose which tracker tile to increase and decrease. 

Solution: Prompt the user using the `SelectColony` input.

Functionality is complete, just need to finish cleaning up and writing unit tests. Is this something acceptable to open a PR for?

Before: 
<img width="769" alt="Screen Shot 2022-06-07 at 1 24 24 AM" src="https://user-images.githubusercontent.com/42753529/172310337-5466839b-b91d-4327-b3c5-714a0c539017.png">

After:
<img width="1352" alt="Screen Shot 2022-06-07 at 12 51 54 AM" src="https://user-images.githubusercontent.com/42753529/172309540-02899ca6-f728-4044-89a6-9f75186e0a24.png">
and then
<img width="1372" alt="Screen Shot 2022-06-07 at 12 52 01 AM" src="https://user-images.githubusercontent.com/42753529/172309528-66c8bb71-3a9f-49e0-acea-083922b8d501.png">

**Comment by nwai90** [comment]
Absolutely, feel free to go ahead and raise a PR for it!
