### ISSUE TITLE
bug with regolith eaters 

### ISSUE THREAD

**Issue by chaosido** [terraforming-mars/terraforming-mars#4596]
Please include:
1. A clear and concise description of the bug.
game is not giving me the option for regolith eaters to use the 2 bacteria on there for 1 oxygen, even though there is 2 bacteria on there

3. Clear steps to reproduce, and the expected behavior.
played regolith eaters --> play imported hydrogen the same turn --> use 2 bacteria for oxygen and it works --> next turn add 1 bacteria to card by action (so it has 2 again) --> next turn attempt to use the action to exchange the bacteria for oxygen, game automatically (so without giving me an option prompt) adds a third bacteria

5. Any screenshots

7. Any information from  the Bug Report Dialog
?

![Capture1](https://user-images.githubusercontent.com/108172401/175763786-838bad28-54cf-4985-b3e0-df451dc30c4a.PNG)
![Capture2](https://user-images.githubusercontent.com/108172401/175763787-877c7fff-cef7-42d4-b435-84bef05f561e.PNG)

**Comment by nwai90** [comment]
@chaosido Is this a Turmoil game? Are the Reds ruling? It looks like you cannot afford the 3 MC Reds cost

**Comment by chaosido** [comment]
@nwai90 ofcourse that is it. I thought I checked everything but I must've missed that.
