### ISSUE TITLE
Aquifer Pumping action

### ISSUE THREAD

**Issue by Engmostafam** [terraforming-mars/terraforming-mars#4597]
I can still use this action even if there are no available ocean tiles. I wonder if this is the right behaviour? 

URL: https://terraforming-mars.herokuapp.com/spectator?id=s96cbec11a0de
Player color: green
Step: 455
Version: 61bdfa9, built at Fri, 24 Jun 2022 06:12:45 GMT
Browser: Firefox 101

**Comment by kberg** [comment]
Sorry for not responding earlier. That _is_ allowable. There are a few sets of blue actions that are considered playable even though they would have no effect.

The strategic value is that you can use it to delay until your opponents pass.
