### ISSUE TITLE
Networker milestone is not tracked correctly

### ISSUE THREAD

**Issue by olafurkarl** [terraforming-mars/terraforming-mars#4614]
Red player should have 3 adjacent tiles and qualify for 'Networker' but only has 2, see screenshot.

URL: https://privately-hosted/spectator?id=s161a099a8c46#board
Player color: blue
Step: 117
Version: 02481690c, built at Wed, 29 Jun 2022 01:48:13 -0400
Browser: Firefox 101

![screenshot-1656556677](https://user-images.githubusercontent.com/57147108/176580990-1f79ca72-4fdc-4b76-b492-ab13fffeb448.png)

**Comment by olafurkarl** [comment]
After looking up some erratas for 'Networker', I think this is actually working as intended. It just confused those of us playing since there technically wasn't a way to track the state of the milestone on the board without extra measures.

**Comment by kberg** [comment]
Well, that happens. No worries.
