### ISSUE TITLE
Duplicate Capital city placement

### ISSUE THREAD

**Issue by olafurkarl** [terraforming-mars/terraforming-mars#4616]
URL: redacted
Player color: red
Step: 90
Version: 02481690c, built at Wed, 29 Jun 2022 01:48:13 -0400
Browser: Chrome 102
![screenshot-1656677853](https://user-images.githubusercontent.com/57147108/176893059-62513392-70dd-40d5-8ddd-69338d07647c.png)

Not sure why this happened, but we managed to place 2 capital cities during an error.

🕑Tutface played CAPITAL
🕑Tutface placed Capital tile on row 7 position 6
🕑Tutface placed Capital tile on row 4 position 3

**Comment by kberg** [comment]
Thanks for the report. Some questions: Is this from a private server? Is the code customized at all? And you say "during an error." Did some other error occur?

**Comment by olafurkarl** [comment]
> Thanks for the report. Some questions: Is this from a private server? Is the code customized at all? And you say "during an error." Did some other error occur?

It is on a private server, the code is not customized although it is using the later `andrewsev` docker image.
We had the error a couple of more times, it said 'Error code 7' or something to that effect. I'm kicking myself for not screenshotting it.

Game settings are here:
![screenshot-1656684710](https://user-images.githubusercontent.com/57147108/176911136-60166c00-d542-4dd0-9022-4cff3ace0e22.png)

**Comment by kberg** [comment]
Oof. Can you see if it happens again? I'm going to close this for the moment, but if it happens again just add to this issue.

**Comment by olafurkarl** [comment]
It happened several times more in the same game, actually. 
Once more with (I think) a greenery, and another time with Restricted Area. You can see 2 restricted areas and 2 capitals here:
![screenshot-1656970661](https://user-images.githubusercontent.com/57147108/177218562-6ee8c407-9d00-4fd2-bba1-9eb22653f9a8.png)

**Comment by olafurkarl** [comment]
BTW I'd be happy to give you the direct link to the game, but I'd prefer not to post it on a public forum.

**Comment by kberg** [comment]
It probably won't help in that case. Since it's your own server, the best way to get the game to me is by exporting the game white it's underway. I have instructions on how to do that with PostgreSQL on Heroku. But even then -- that's weird.
