### ISSUE TITLE
Velocity Skips 3 minutes. Git hub page and error reporting not open for public

### ISSUE THREAD

**Issue by Engmostafam** [terraforming-mars/terraforming-mars#4617]
URL: https://terraforming-mars.herokuapp.com/spectator?id=s826565db671c
Player color: green
Step: 217
Version: 0bf83ce, built at Tue, 28 Jun 2022 06:34:40 GMT
Browser: Firefox 101

Hi, 
I think the velocity feature is skipping some time for both players. Also, The git hub server has only two channels open for public so it's not really possible to report a bug there or look for a game to join. 

Thank you so much. 

<img width="1344" alt="Screenshot 2022-07-02 at 8 10 27 pm" src="https://user-images.githubusercontent.com/5734914/177013532-159c0656-5783-4abe-8deb-e43540b9961b.png">

<img width="1344" alt="Screenshot 2022-07-02 at 8 09 04 pm" src="https://user-images.githubusercontent.com/5734914/177013524-0771890e-737d-40ce-99a7-2dd40dc348c2.png">
<img width="1344" alt="Screenshot 2022-07-02 at 8 09 53 pm" src="https://user-images.githubusercontent.com/5734914/177013529-d7c19d8b-ae30-4dac-8022-741461e9feb3.png">

<img width="1344" alt="Screenshot 2022-07-02 at 8 07 38 pm" src="https://user-images.githubusercontent.com/5734914/177013520-16961cf0-08b2-4ae5-9a7a-4e56327446e2.png">

**Comment by nwai90** [comment]
> URL: https://terraforming-mars.herokuapp.com/spectator?id=s826565db671c Player color: green Step: 217 Version: [0bf83ce](https://github.com/terraforming-mars/terraforming-mars/commit/0bf83cee456629e3a9cb969e15631dd76f7e31aa), built at Tue, 28 Jun 2022 06:34:40 GMT Browser: Firefox 101
> 
> Hi, I think the velocity feature is skipping some time for both players. Also, The git hub server has only two channels open for public so it's not really possible to report a bug there or look for a game to join.
> 
> Thank you so much.
> 
> <img alt="Screenshot 2022-07-02 at 8 10 27 pm" width="1344" src="https://user-images.githubusercontent.com/5734914/177013532-159c0656-5783-4abe-8deb-e43540b9961b.png">
> 
> <img alt="Screenshot 2022-07-02 at 8 09 04 pm" width="1344" src="https://user-images.githubusercontent.com/5734914/177013524-0771890e-737d-40ce-99a7-2dd40dc348c2.png">
> 
> <img alt="Screenshot 2022-07-02 at 8 09 53 pm" width="1344" src="https://user-images.githubusercontent.com/5734914/177013529-d7c19d8b-ae30-4dac-8022-741461e9feb3.png">
> 
> <img alt="Screenshot 2022-07-02 at 8 07 38 pm" width="1344" src="https://user-images.githubusercontent.com/5734914/177013520-16961cf0-08b2-4ae5-9a7a-4e56327446e2.png">

You have to assign yourself a role in #guidelines channel to unlock the rest of the server
