### ISSUE TITLE
Sprite layer error for "Search For Life" (visual bug)

### ISSUE THREAD

**Issue by samsa1** [terraforming-mars/terraforming-mars#4618]
The sprite printed on the card "Search For Life" (to represent that it has a science on it) is not on the good layer. It is printed above the player info bar. However this does not happen when the card is magnified or when it is another player looking at the card.

<img width="276" alt="Screenshot 2022-07-03 at 12 35 56" src="https://user-images.githubusercontent.com/65660384/177043840-b2bd8880-d05e-4211-bd0a-a5913625c505.png">

Impact : non breaking bug, just visual
Version : 993ce0d8600eaa74b28d0b408cb1cacc78eaeef3 and 636f30b066d73d5da383c3814e48d3298ab49a72
Browser: Firefox 102
Host : game run locally on macOs  12.4
Settings (none of them should have an impact): Prelude, Colonies, Corporate era, allow undo, LOCAL_FS_DB=on, random Milestones/Award, 2 players, no timers.

As a developer I can try to correct this bug myself. But I'll need someone to give me a hint on where to look as I'm not used to web development and to this project

**Comment by kberg** [comment]
Hi! If your CSS is good, and you know how to handle a browser's DOM tooling, then have at it. You don't even need to change the source code -- you can just update this bug with what you expect the new setting to be.

Or, I'll take a shot at it in the next few days.

Thanks for the report.

**Comment by kberg** [comment]
![image](https://user-images.githubusercontent.com/413481/177435156-45d1b522-c357-46c6-81c9-078a88f3f49b.png)

This is on Chrome Linux.

![image](https://user-images.githubusercontent.com/413481/177435294-86140bda-ec8e-45a9-af03-a17019898a68.png)

This is Firefox on Linux.
