### ISSUE TITLE
Curator award non functionning ?

### ISSUE THREAD

**Issue by Albinouze** [terraforming-mars/terraforming-mars#4620]
1. We think the curator Award does not work, or maybe its phrasing is not good and we have no idea on what criteria CURATOR works.
2. It was on a 2 players games, played on Google Chrome for Android smartphone
3. screenshot attached, you can see that the Award is financed but no player takes any advantage
4. No information from  the Bug Report Dialog
![image](https://user-images.githubusercontent.com/108677806/177166490-861a0d81-6d38-4484-8d93-22a372e2c9c3.png)

**Comment by kberg** [comment]
Yep that looks pretty broken to me. Next time, though, paste the information from the bug dialog, please.

**Comment by Albinouze** [comment]
Hi. There was no big report,it seemed like it worked but didn't.
Thank you for your work

Envoyé de mon Galaxy S10e Orange
Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
