### ISSUE TITLE
During async, if server sleeps during card buying (etc), you have to buy again

### ISSUE THREAD

**Issue by Seth0326** [terraforming-mars/terraforming-mars#4650]
During async games, when there's a lot of time between turns, there are some situations where, if the server goes to sleep (due to inactivity) before the situation is resolved, the players have to redo the actions:
- Choosing cards at beginning of game
- Buying cards at the beginning of each generation
- Placing greeneries at the end of the game

For example, in a 4p game, if three people buy cards at the beginning of a generation, but the server sleeps before the fourth buys their cards, it resets and everyone has to buy cards again.

One solution is just to fix it. But maybe an easier solution is to add an option to choose cards in turn order, instead of everyone doing it at the same time. That way, the game will register each player's card buying as a completed action, so a sleeping server won't affect it. This wouldn't fix the end-game greenery placement problem, though.

**Comment by kberg** [comment]
Yeah. This is a known issue.  I agree that changing turn order would help; but there are some other plans to mitigate this.

Your suggestion is interesting, but we still just have a larger issue to contend with regarding getting the most use out of all the resources Heroku gives. Working on it though. I really am.

I'm going to close this but rest assured we are fully aware.

**Comment by Seth0326** [comment]
Thanks so much! I'm really so impressed with everything y'all have done with this app, it's so appreciated. My friends and I love it. Thanks for it all, really.

**Comment by kberg** [comment]
You're very welcome. There have been many of us. I'm just the current custodian.
