### ISSUE TITLE
Frequent "server unavailable" during games

### ISSUE THREAD

**Issue by Albinouze** [terraforming-mars/terraforming-mars#4655]
1. Impossible to reach or refresh the page during a game. (Unexpected server response: Service Unavailable)
2. I do not know what triggers this but it happenned several times during my 3 last games. It stays this way a few minutes or hours and then you can play again as if nothing happened. Nothing on the game history when the game resumes

**Comment by kberg** [comment]
This happens when the server restarts. Yesterday we had a couple of planned restarts while trying to diagnose some big issues. Sorry about this. This is a known issue, particularly that game state is only _mostly_ preserved during restart.
