### ISSUE TITLE
Error: Internal server error: Object.fromEntries is not a function

### ISSUE THREAD

**Issue by ap3h3ad** [terraforming-mars/terraforming-mars#4733]
Hi,

after updating the project and starting the server I only get:

Internal server error: Object.fromEntries is not a function

I cannot do anything, no UI, nothing. What is the problem?

Cheers!

**Comment by kberg** [comment]
1. What are you running the server on? 2. Run `npm ci` for a clean install?

**Comment by ap3h3ad** [comment]
I'm running the application on a shared cloud server space. I tried npm ci without any errors. This is what the console says:

https://abload.de/img/error02k99.png

**Comment by kberg** [comment]
What version of node are you using?

**Comment by kberg** [comment]
I ask that because
https://namespaceit.com/blog/object-from-entries-is-not-a-function-error-when-using-chakra-ui-and-nextjs
talks about a similar issue related to the version of node that you have
installed.

**Comment by ap3h3ad** [comment]
Yes, old node js version was the problem, thanks!
