### ISSUE TITLE
Card on Self-Replicating Robots is also in hand

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#4735]
I hadn't played SRR in a while, and this time I noticed what I think is a bug.

The card played onto SRR is considered NOT in the player's hand for all gameplay purposes (the only thing you can do with it, per SRR, is to play it "AS IF" from hand). But it is showing up as being in the hand.

<img width="333" alt="Screen Shot 2022-07-30 at 9 01 13 AM" src="https://user-images.githubusercontent.com/934551/181925321-9cba02cb-9858-468b-b0bc-c53700576570.png">

**Comment by kevinb9n** [comment]
Oh, and there's also this

<img width="1058" alt="Screen Shot 2022-07-30 at 9 08 56 AM" src="https://user-images.githubusercontent.com/934551/181925566-a210740c-90f5-4ca6-a482-f4f50e2b571d.png">

**Comment by 167kamon** [comment]
I've encountered that bug myself. It's not just staying in your hand while being linked, it's actually overwriting a different card in your hand. One of those Nitrogen-Rich Asteroids used to be a different card, but got turned into a copy of the NRA you linked. Playing one copied card plays both, and you only get the effects of playing one, so you essentially lost a card when you linked something with SRR.

**Comment by 167kamon** [comment]
It's not just staying in your hand, it's actually overwriting one of your other cards. Notice that Solar Power disappears from my hand when I link Imported Nitrogen. That card is gone forever. Playing either copy of Imported Nitrogen removes the other from my hand.

![srr1](https://user-images.githubusercontent.com/8723722/182917894-a7d309e7-6708-4c6a-8778-aee30ef31594.png)
![srr2](https://user-images.githubusercontent.com/8723722/182917900-777f7085-cd8a-4d67-94ac-186162e287e0.png)
![srr3](https://user-images.githubusercontent.com/8723722/182917901-1b8a5a82-3cb5-472c-b571-5a8e56cf78cd.png)

**Comment by kevinb9n** [comment]
Nice work... so #4739 is indeed a duplicate of this bug.

**Comment by bafolts** [comment]
I am glad this was narrowed down. The #4739 was scarier when not isolated to one card.

**Comment by kberg** [comment]
This is fixed. Sorry about that!
