### ISSUE TITLE
Preliminary: cards are *possibly* disappearing from hand

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#4739]
This could be pilot error, but it has happened twice in the same game, and isn't something I usually experience, so I'm going to start this off.

In this game (which I'm abandoning): https://terraforming-mars.herokuapp.com/player?id=p55bcef09ceed

On two occasions now I've looked for a card I had *believed* was in my hand and found that it is gone.

These were Robotic Workforce and Quantum Extractor, both of which I *thought* I had kept in the initial draft (you might be able to check that, dunno), and which I noticed at different times were gone.

It is possible that one vanished each time I linked a card to Self-Replicating Robots. Since there is some bug that is seeing those cards as still in hand, I might be seeing the correct *count* of cards in hand but the wrong ones. This is fanciful guess though.

Again, could be pilot error -- I could have accidentally sold the cards -- but it seems fishy.

**Comment by kberg** [comment]
I have download a copy of the game and will take a look before too long.

**Comment by kevinb9n** [comment]
This is a dup of #4735.
