### ISSUE TITLE
Merger: initially discarded corporations were shuffled back in?

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#4746]
Sorry, I know this is extremely minor.

I think in an over-the-table game players would not shuffle initially-discarded corporations back in to the corp deck before playing the Merger prelude, unless/until the corporation deck was actually empty. So you wouldn't have to redraw a corp you had already discarded once.

I could have missed a ruling about this though.

Again, small, sorry.

**Comment by motoyugota** [comment]
I would agree that this is how it should work. Same goes for Valley Trust and New Partner with Preludes.

**Comment by kberg** [comment]
This is fixed.

**Comment by kberg** [comment]
Agreed. Thanks.
