### ISSUE TITLE
Cannot play the Prelude Card "Acquired Space Agency"

### ISSUE THREAD

**Issue by adamwhurd** [terraforming-mars/terraforming-mars#4754]
URL: https://terraforming-mars.herokuapp.com/spectator?id=s903a4418ebf8
Player color: green
Step: 0
Version: 9b4e1f3, built at Thu, 04 Aug 2022 02:10:41 GMT
Browser: Chrome 104

Bug: Cannot play the Prelude Card "Acquired Space Agency". It seems like the card draw mechanism is still working because upon page refresh I have multiple space cards for each attempted play, but the game will not actually recognize the prelude card as "played" and gets stuck.

https://imgur.com/egl9Tvb

https://imgur.com/Wl2mTZA (Note the "25 cards")

**Comment by kberg** [comment]
Thanks for this. I'll fix this next.

**Comment by kberg** [comment]
I don't think I'll be able to recreate this. I suspect this is due to server restart. Nonetheless, I'll have to keep a close eye out.
