### ISSUE TITLE
Merger compatibility errors

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#4763]
~~* Helion & Robinson Industries: Robinson Industries will trigger if there's heat but no money. But it will not use the heat.~~

**Comment by nwai90** [comment]
Helion & Stormcraft: Helion is not able to use floaters as 2 heat each

**Comment by kberg** [comment]
Unsubstantiated: Manutech + Odyssey, using Project Inspection to use Odyssey's Corpration

**Comment by kberg** [comment]
unsubstantiated: 
> I played Curiosity with merger and didn't get those 2 steel productions from the corp

**Comment by kberg** [comment]
Luna First Incorporated assigns steel and titanium like so:

    player.steel = 2;
    player.titanium = 2;

which means it overrides any steel and titanium gained before the Merger prelude came out.

**Comment by kberg** [comment]
All the known Merger issues have been addressed, so I'm going to close this. We can open new ones as is necessary, of course.
