### ISSUE TITLE
[PF] AURORAI Corporation "unlimited money" bug

### ISSUE THREAD

**Issue by HenrikSteenbock** [terraforming-mars/terraforming-mars#4780]
The Pathfinder corporation AURORAI is supposed to receive 1 data per TR increase (this part works). Secondly, you can use data there to pay for standard projects with each data worth 3 MC. When buying standard projects, data is never actually removed after paying. Consequently, once you reach a certain amount of data, you can get any number of standard projects without paying for them. As reference, when paying for the standard projects, there is NO prompt to select how to pay for it (data and/or MC), it seems to take as much money as possible and then use data for the rest.

**Comment by kberg** [comment]
Yes, I see this. This isn't good. Thank you.
