### ISSUE TITLE
Player could place Immigrant City twice

### ISSUE THREAD

**Issue by ap3h3ad** [terraforming-mars/terraforming-mars#4788]
Hi,

a player could place the Immigrant City twice:

https://abload.de/img/immigrant_cityypesf.png

https://abload.de/img/maptpdpg.png

We think that this has to do with the map ("Amazonis P."), because the player got a weird message after placing the first city that something went wrong with the placement bonus and he could only continue the game with placing the city a second time.

Cheers!

**Comment by kberg** [comment]
Do you remember anything about the weird message?

I'm sorry for not responding earlier. I'd like to look at this. But that weird message is probably vital.

**Comment by ap3h3ad** [comment]
It was something about placement bonus. Either on the place itself or on one of the sorrounding fields. I'm sorry, he didn't note or screenshot it. If this is too little to work with, feel free to just close the issue.

**Comment by kberg** [comment]
I see it now. Fix coming shortly. Thank you!

**Comment by kberg** [comment]
Interesting, you're playing on a server that is not running in production mode. Otherwise you wouldn't have seen the error.

Anyway, thank you!
