### ISSUE TITLE
game stuck

### ISSUE THREAD

**Issue by Shaydie** [terraforming-mars/terraforming-mars#4824]
Please include:
1. A clear and concise description of the bug.
2. Clear steps to reproduce, and the expected behavior.
3. Any screenshots
4. Any information from  the Bug Report Dialog

Hi. I played Lava Tube Settlement and the only tile available was an erosion tile and it required I pay 16 mc to place. I didn't have the money so I couldn't place, and it won't let me go forward without placing. I'm unable to undo or anything at this point.

Here's what I got from the bug report. 

URL: http://terraforming-mars.herokuapp.com/spectator?id=s285682d8edda
Player color: yellow
Step: 382
Version: 3700419, built at Thu, 25 Aug 2022 14:44:37 GMT
Browser: Chrome 104

**Comment by kberg** [comment]
Hi -- I _think_ I did a one-step rollback for you.  Can you take a look and let me know?

**Comment by Shaydie** [comment]
Yes! Thank you so much 🙏

Juliet Violette

Sent from my iPhone

On Aug 26, 2022, at 8:35 AM, Robert Konigsberg ***@***.***> wrote:

﻿

Hi -- I think I did a one-step rollback for you. Can you take a look and let me know?

**Comment by kberg** [comment]
You are welcome. I'm trying to add a fix that will prevent that entirely.

**Comment by Shaydie** [comment]
That would be great. This game gives us hours and hours of fun! We love it! 🙏


Sent from my iPhone

On Aug 26, 2022, at 10:35 PM, Robert Konigsberg ***@***.***> wrote:

﻿

You are welcome. I'm trying to add a fix that will prevent that entirely.
