### ISSUE TITLE
Solo: consider advance signal of victory/loss

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#4873]
Just an idea following on to #2055; close if unconvinced!

In the final generation of a solo game, what about replacing the "Pass this generation" button label with "Pass the final generation (you $result!)"

Occasionally that message will be a surprise:

* The user missed the fact that the game is ending, e.g. if they're used to playing without Prelude
* The user accidentally forgets to actually do their final bit of terraforming in the midst of all their gleeful city-placing (speaking pure hypothetically, you understand)
* The user believed their final greeneries could still nudge them to victory

Of course the greatest benefit is when they have undo enabled; they can still rethink their final moves. But even without it, this could be a helpful reminder. And the idea of submitting a terraforming move and watching the label flip from "lose" to "win" just sounds kinda fun doesn't it?

**Comment by kberg** [comment]
I'm not entirely convinced. How about this: when the game will end after this generation, give a visual cue on the top left?

![image](https://user-images.githubusercontent.com/413481/191155198-21befb6c-0a7e-4e20-957b-06948aad246b.png) **->** ![image](https://user-images.githubusercontent.com/413481/191155470-34089aa0-5d34-41b4-92d6-594749e01bd1.png)

Not that specific art or style, but /shrug?

**Comment by kberg** [comment]
Any thoughts?

**Comment by kberg** [comment]
I'm going to close, as I am unconvinced, as per your first comment.
