### ISSUE TITLE
Unable to progress past initial corporation action

### ISSUE THREAD

**Issue by Alusarion** [terraforming-mars/terraforming-mars#4895]
URL: https://terraforming-mars.herokuapp.com/spectator?id=sf130a0f0f59b
Player color: orange
Step: 19
Version: c630e1f, built at Mon, 05 Sep 2022 21:15:37 GMT
Browser: Chrome 105

![image](https://user-images.githubusercontent.com/112906513/188513802-288246fa-68ed-4d79-bfd0-4e33c4b18c1d.png)

**Comment by kberg** [comment]
I just restarted the server. Is it still happening?

**Comment by Alusarion** [comment]
Yes, it still puts up that error with input message.

**Comment by kberg** [comment]
Alright. Looking now.

**Comment by kberg** [comment]
I see it. It'll be fixed in about 20 to 30 minutes.

**Comment by kberg** [comment]
Try again in about five minutes. Sorry for the break!

**Comment by Alusarion** [comment]
No problem, thanks for working on it!
