### ISSUE TITLE
Make Odyssey compatible with "next card" cards

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#4907]
From Discord: https://discord.com/channels/737945098695999559/742721510376210583/1017183396482519162

[5:23 PM]Arvishhh: Hello! It seems that conscription don't work when you play it with Odyssey action. Thank you!
[6:03 PM]Borbarad: Same for Indentured Workers and Conscription. Seems similar issue.

*UPDATE* All the cards under consideration are:

* Conscription: the next card you play costs 16M€ less
* Indentured Servants: the next card you play costs 8M€ less
* Last Resort Ingenuity: The next card you play this generation can be paid for with steel or titanium despite its tags.
* Special Design: The next card you paly this generation is +2 or -2 steps in global requirements, your choice.

**Comment by kberg** [comment]
Some notes: What seems to happen is that lastPlayedCard is set correctly, but because the card was discarded, it's not iterated through to find discounts.

**Comment by puuj** [comment]
We encountered this too, and there may be more complexity in the case that someone plays Conscription and then immediately uses Odyssey to discard Conscription. Theoretically there would be two discounts. One potential idea I was kicking around was to have Odyssey have it's own lastPlayedCard handler that could track the actual lastPlayedCard as well as the Odyssey discarded card effect. Not sure if this would work and haven't had time to mess with it.

**Comment by kberg** [comment]
If you use Odyssey to discard Conscription, the first discount applies to it.

The lastPlayedCard handler is not a bad idea, but since Playwrights needs the same thing, and Playwrights pulls from _any player's event deck (my goodness)_ perhaps it's best not to tie it to a single card.

@puuj what other good stuff do you have in your server that might be worth sharing? (I think we've discussed this already but it doesn't hurt to ask again.)

**Comment by kberg** [comment]
But you have me thinking. I have an idea.

**Comment by kberg** [comment]
Oh wait, there's this!

```
  // For Playwrights corp.
  // removedFromPlayCards is a bit of a misname: it's a temporary storage for
  // cards that provide 'next card' discounts. This will clear between turns.
  public removedFromPlayCards: Array<IProjectCard> = [];
```

The fix is to get Odyssey to use this field.
