### ISSUE TITLE
New Partner selects duplicate preludes

### ISSUE THREAD

**Issue by motoyugota** [terraforming-mars/terraforming-mars#4920]
Game ID: ge6fd824eb788

![Screenshot_20220909-233031_Chrome](https://user-images.githubusercontent.com/889269/189509076-6e6f1901-1161-43b5-af6c-7714b7de8fa0.jpg)

In the screenshot, you can see that i already played Aquifier Turbines but it has come up again as an option with New Partner.

**Comment by kberg** [comment]
Yeah, Merger needs work. Thanks.
