### ISSUE TITLE
Solo game isn't allowing placing greenery at the end of the game

### ISSUE THREAD

**Issue by motoyugota** [terraforming-mars/terraforming-mars#4922]
Solo game isn't allowing placing greenery at the end of the game now. See screenshot - I ended the game with 10 plants and didn't get to place them. 

![Screenshot_20220910_231650](https://user-images.githubusercontent.com/889269/189512223-d1c0bcdc-9ed3-431e-b157-883b8225956e.jpg)

**Comment by kberg** [comment]
Hi. This is a very recent change, and is correct as far as the rules go. This comes from https://github.com/terraforming-mars/terraforming-mars/issues/2055

In solo mode, victory is decided immediately at the end of the last generation. If you have won, then you have earned a score, and the final greeneries would serve as extra points. In your game, Venus and Heat were not maximized, and so , roughly, final greeneries serve no purpose. The game is just a loss.

I'm closing this, but of course, expect some sort of response.
