### ISSUE TITLE
[Community] Playwrights allows replaying cards placing special tiles which should not be allowed

### ISSUE THREAD

**Issue by HenrikSteenbock** [terraforming-mars/terraforming-mars#4929]
Events that place a tile (Deimos Down, Metallic Asteroid, etc.) can be re-played using the Playwrights corporation action. The special tile should only be allowed to be placed once, and playing it should be mandatory, so those cards should not be allowed to be re-played.

**Comment by HenrikSteenbock** [comment]
I imagine it will be the same case for the corporation Odyssey (Pathfinder).

**Comment by kberg** [comment]
Yes, it would be.

So, why shouldn't it be allowed? I see your point, but why not allow it in a web game?

Some references:

https://discord.com/channels/737945098695999559/737945098695999562/869601868056244286: 
>  Playwright allows double playing some special-event tiles. That is really not a problem  with web app and it is intuitively correct, but would obiviously be different in real life play since you don't have 2 copies of the tiles

https://discord.com/channels/737945098695999559/742721510376210583/843924586425090108
> apart from whether it's OP it's just not the way the card would work in a real life game, no one's printing out second copies of their tiles -- and note it would literally break the game if Mohole Area just happened to be an event

That second argument is the strongest for your point. Fair point about Mohole Area.

**Comment by HenrikSteenbock** [comment]
I can only think of 2 events that place special tiles (Deimos Down and Metallic Asteroid). For Metallic Asteroid it wouldn't be an issue to have just another asteroid, but at least for Deimos Down it thematically doesn't make sense.

In general, while I absolutely see the advantages a web app has over the physical copy and I know we are outside of official territory anyway, being consistent with the physical copy seems more appropriate to me.

**Comment by kberg** [comment]
Yeah. As you can see I'm on the fence here, and Discord no longer has the community to discuss it in detail. But I am starting to lean toward your perspective, except that the other perspective means no work for me. ;)

There's another option: play the card, deny the additional special tile. What do you think about that?

**Comment by HenrikSteenbock** [comment]
Personally, I don't like the idea of playing the card without placing the tile because other cards placing tiles (city/special) MUST place that tile (except oceans) or may not be played. Having tile placement not mandatory only is inconsistent with the rules.
I'd rather play the event twice and "only" violate the thematic background. Afterall, it's only a niche case that isn't game breaking.

**Comment by kevinb9n** [comment]
I'm impressed that my old discord comment was dug up and quoted. :-) I would still cast a "vote" that the web app should behave the way the physical game would (so agreeing with Henrik), but Rob gets 1 million votes...

**Comment by kberg** [comment]
OK so let's say this happens. Does the card text need to change? If it does need to change, how's this?

![image](https://user-images.githubusercontent.com/413481/191411904-96d0bdb0-dd12-4789-ae96-a3fe9e4ccb05.png)

**Comment by kberg** [comment]
(both cards would need to change.)

**Comment by kberg** [comment]
OK, so now let's talk about pretend. :D Pretend that these cards existed. Why wouldn't the cards come with extra special tiles to fulfil their use? Ares does this, for example, by providing double the required Mining Area/Mining Rights tiles to accommodate which alloy the tile should grant to adjacent placements.

This basically says that the argument that there wouldn't be tiles in a real game isn't quite so airtight.

Mohole Area could be a nasty situation, but it fortunately isn't. (I don't think you were making a strong point out of it, just working through the mechanics in your head.)

**Comment by HenrikSteenbock** [comment]
My "only" reason is thematic immersion and consistency.

Deimos can only come down once -> Deimos Down tile can only be placed once -> same should could for other special tiles to be consistent OR we change text on Deimos Down to specify it cannot be re-played. 

Capital is similar to Deimos Down, thematically there can only be one. Aside from those two, all other special tiles are generic enough that there's no logical reason why there shouldn't be more than one. Realistically, an actually civilized Mars will have more than 1 Industrial Zone and Restricted Area etc.

Since my only objection is to re-playing unique tiles, why not change text on cards placing truly one-of-a-kind special tiles so that these specifically cannot be re-played.

**Comment by kberg** [comment]
As a matter of policy, we hadn't changed text on official cards, and I agree with that, particularly to satisfy fan cards.

I empathize with the thematic immersion point. I hate when a game condition breaks me out of thematic immersion.

It's not too difficult to make weak pedantic arguments that there thematic circumstances that would make both of those cases true (political schism resulting in two Capitals, only a portion of Diemos hurled to Mars's surface) but I don't rest my position on them.

Obviously, the default position is that the behavior remains as is until there's enough convincing perspective to change it. But I have pretty limited data (you + kevinb9n, the player on Discord who thinks this isn't a problem, and another person who privately DMed me their perspective.) 

If I wanted to say "no" I'd have done it a while ago and not strung you along. I'm just not yet convinced this is the right choice. Until then,  I think this stands.

**Comment by HenrikSteenbock** [comment]
If we maintain the status quo then I'd like to suggest that text on Odyssey and Playwrights is changed to explicitly state events placing special tiles are included, because that is not obvious to me or the other 2 veterans in my group. I dare say we are not the only ones, but who knows. Either way, that would make it clear to everyone.

**Comment by kberg** [comment]
That seems reasonable.

**Comment by kberg** [comment]
That's also acceptable, and at the very least better than doing nothing.
