### ISSUE TITLE
Energy Market gave me 2 energy for 2 megabucks

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#4930]
I'm trying to buy *1* energy for 2 megabucks and I seem to be getting a free one along with it?

![image](https://user-images.githubusercontent.com/934551/189830357-917c12d3-60bf-434b-a29e-8e82b047fd05.png)

![Screen Shot 2022-09-12 at 11 48 54 PM](https://user-images.githubusercontent.com/934551/189830418-1e0258a0-3f93-44a1-af55-1056542d3d62.png)

**Comment by kevinb9n** [comment]
If I go back and try to buy 3, I get 6. It seems to be crediting me the energy twice (and not logging it one of the times).

**Comment by kberg** [comment]
I see it. OK. Thanks.
