### ISSUE TITLE
Project Workshop not compatible with Conscription, Special Design, and Indentured Workers

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#4940]
Project Workshop replays an event card, and then discards it. Conscription, Special Design, and Indentured Workers, all rely on being in the tableau for its effect to work.

Replaying Conscription, for instance, will have the effect of removing the discount entirely, and not doubling it, as the player might expect.

**Comment by nwai90** [comment]
Not sure I get this - why would it ever double? When you replay an event, you are playing that card, so the first discount is already consumed.

**Comment by kberg** [comment]
Oh yeah, you're right.
