### ISSUE TITLE
[Ares, Pathfinder] Arcadian Communities counts claimed hazard tiles as owned

### ISSUE THREAD

**Issue by HenrikSteenbock** [terraforming-mars/terraforming-mars#4947]
When a community marker for Arcadian Communities is placed on a Duststorm or Erosion (which technically is legal because they are not reserved, but thematically I don't think it should be possible) that tile is considered owned for effects that count special tiles. Specifically, we observed it during the event "Space Race to Mars" which I think is from Pathfinder. I don't think hazards should count as owned since the whole thematic point is to create uncontrollable bad tiles on Mars. Plus Arcadian Communities only reserves hexes, it should not claim tiles.

**Comment by kberg** [comment]
Wow, nice one.
