### ISSUE TITLE
Merger played twice (once by each player)

### ISSUE THREAD

**Issue by nabby101** [terraforming-mars/terraforming-mars#4952]
I was dealt and played Merger as one of my starting preludes, then my opponent used the New Partner prelude and somehow also hit Merger, so now we both have a copy in play, and two corporations each.

Also, while I'm here, Merger always pulls from the full list of (official and expansion-legal) corporations, rather than the selected corporations for the game. Not sure if that is intended.

URL: https://terraforming-mars.herokuapp.com/spectator?id=s548f23b36a92
Player color: orange
Step: 16
Version: bf83309, built at Thu, 15 Sep 2022 23:16:55 GMT
Browser: Firefox 104

![image](https://user-images.githubusercontent.com/12789345/190566543-99f01ff3-2087-4c2c-9e48-407576c4805b.png)
![image](https://user-images.githubusercontent.com/12789345/190566508-64a921ed-45f8-41b8-aadc-24df976c1bb5.png)

**Comment by kberg** [comment]
Thanks for the report. There's a fix for this already and I'm waiting on a
review to make sure I didn't bungle anything.

**Comment by nabby101** [comment]
Great to hear, thanks for the work you all do!
