### ISSUE TITLE
Cannot play a card or enhance temperature

### ISSUE THREAD

**Issue by BenoitBeg** [terraforming-mars/terraforming-mars#4959]
URL: https://terraforming-mars.herokuapp.com/spectator?id=sb5d823836899
Player color: blue
Step: 54
Version: bf83309, built at Thu, 15 Sep 2022 23:16:55 GMT
Browser: Chrome 104

Impossible to play the card small asteroide and to  rise temperature. 

https://user-images.githubusercontent.com/113839398/190903475-46928bd0-73d4-42fd-a1bc-803192c6fcfa.mp4

Another bug With valley trust à friend had the same prelude card as me.

**Comment by kberg** [comment]
Thanks for this report. What do you mean that it's impossible to play the card?

A fix for the prelude issue is ready to go, waiting on review.

**Comment by kberg** [comment]
This is working as intended. Reds were in power, and you needed an additional 3M€ to pay for the TR you would gain from raising the temperature. Since you only had 2M€, the card was not playable.

**Comment by BenoitBeg** [comment]
You're right! I didn't pay attention to that, thank you 🙂. Thank you for the prelude fix.
________________________________
De : Robert Konigsberg ***@***.***>
Envoyé : dimanche 18 septembre 2022 14:18
À : terraforming-mars/terraforming-mars ***@***.***>
Cc : BenoitBeg ***@***.***>; Author ***@***.***>
Objet : Re: [terraforming-mars/terraforming-mars] Cannot play a card or enhance temperature (Issue #4959)


This is working as intended. Reds were in power, and you needed an additional 3M€ to pay for the TR you would gain from raising the temperature. Since you only had 2M€, the card was not playable.
