### ISSUE TITLE
Unsure why I lost when I had all global params filled by gen 12

### ISSUE THREAD

**Issue by sllang** [terraforming-mars/terraforming-mars#4966]
Game ID g38fbf021b743

Did I miss something somewhere in the game?  I have maxed out the O2, the temp, and the water.
Thanks, SL

**Comment by kberg** [comment]
![image](https://user-images.githubusercontent.com/413481/191160413-9ab7f27c-99c0-454d-b891-5c255b3fc761.png)

You were playing the 63 TR variant 

![image](https://user-images.githubusercontent.com/413481/191160461-7169f17f-5ba5-494d-981f-30e39fdbda40.png)

And you had 60 TR. Sorry!
