### ISSUE TITLE
Merger not drawing from custom corp list

### ISSUE THREAD

**Issue by andystager** [terraforming-mars/terraforming-mars#4967]
I would like to have the Merger prelude only draw from the custom corporation list, but it seems to be drawing from the full pool. Is this intended behavior?

**Comment by kberg** [comment]
What I did was put the entire set of cards in the deck, sticking the specified custom ones on top. Those should be the ones drawn, and if they're exhausted, the others should soon follow. Is that not what's happening?

**Comment by andystager** [comment]
In limited testing, it was not. I will try a bit more to see if I can identify any behavior.

Ideally for me, I would prefer that only the custom corps appear even if the corp draw pile is exhausted - they are just shuffled back into a new draw deck.

**Comment by kberg** [comment]
I can see that.

**Comment by andystager** [comment]
Ok, the specified ones are showing up. I was just expecting it to only draw from the custom list even after the list was exhausted. Thoughts on this interpretation?

**Comment by kberg** [comment]
It's not an unreasonable interpretation.

**Comment by andystager** [comment]
Thanks. I'll close this for now as it's working as currently intended. Appreciate all of your work!
