### ISSUE TITLE
Custom Prelude List not loading from settings file.

### ISSUE THREAD

**Issue by andystager** [terraforming-mars/terraforming-mars#4968]
Here is the text of my file:

> {
>     "players": [
>         {
>             "index": 1,
>             "name": "You",
>             "color": "red",
>             "beginner": false,
>             "handicap": 10,
>             "first": true
>         }
>     ],
>     "corporateEra": true,
>     "prelude": true,
>     "draftVariant": true,
>     "showOtherPlayersVP": false,
>     "venusNext": true,
>     "colonies": true,
>     "turmoil": false,
>     "customCorporationsList": [
>         "Point Luna",
>         "Valley Trust",
>         "Poseidon",
>         "Morning Star Inc.",
>         "Interplanetary Cinematics"
>     ],
>     "customColoniesList": [
>         "Callisto",
>         "Pluto",
>         "Titan",
>         "Iapetus"
>     ],
>     "customPreludes": [
>         "Merger",
>         "New Partner",
>         "Research Network",
>         "UNMI Contractor",
>         "Power Generation",
>         "Aerospace Mission"
>     ],
>     "bannedCards": [],
>     "board": "random official",
>     "seed": 0.8549694995006338,
>     "solarPhaseOption": true,
>     "promoCardsOption": true,
>     "communityCardsOption": false,
>     "aresExtension": false,
>     "politicalAgendasExtension": "Standard",
>     "moonExpansion": false,
>     "pathfindersExpansion": false,
>     "undoOption": true,
>     "showTimers": true,
>     "fastModeOption": false,
>     "removeNegativeGlobalEventsOption": false,
>     "includeVenusMA": true,
>     "startingCorporations": "5",
>     "soloTR": true,
>     "initialDraft": false,
>     "corporationsDraft": false,
>     "randomMA": "No randomization",
>     "shuffleMapOption": false,
>     "randomFirstPlayer": true,
>     "requiresVenusTrackCompletion": false,
>     "requiresMoonTrackCompletion": false,
>     "moonStandardProjectVariant": false,
>     "altVenusBoard": true,
>     "escapeVelocityMode": false
> }

**Comment by kberg** [comment]
Andy, can you provide some more details please? What did you expect to happen, and what actually did happen? Perhaps you have a screenshot that might make the explanation more clear?

**Comment by andystager** [comment]
I saved a settings file with certain preludes selected. Upon loading the settings file, the default prelude list was shown:
1: selected preludes saved:
![image](https://user-images.githubusercontent.com/72101041/191166732-a9b93cf3-deb6-4872-9a26-467b04dc3c80.png)
2: saved file loaded:
![image](https://user-images.githubusercontent.com/72101041/191166811-90c223f4-10ab-4274-8f9c-2eeb7da59b55.png)

**Comment by kberg** [comment]
Huh. No preludes? And did this work before?

The import/export has zero tests, so it can be tricky.

**Comment by andystager** [comment]
I think it worked ok on a previous build, but I'm not 100% as I just started playing around with custom preludes - it does work fine for custom corps and colonies though (outside of the merger behavior I submitted separately)

**Comment by andystager** [comment]
I had a previous similar issue #4228 - could be related?
