### ISSUE TITLE
An Offer You Can't Refuse behavior for multiple delegates of Party Leader player

### ISSUE THREAD

**Issue by puuj** [terraforming-mars/terraforming-mars#4971]
The "An Offer You Can't Refuse" card states:  Exchange a NON-NEUTRAL NON-LEADER delegate with one of your own from the reserve. You may then move your delegate to another party.

My interpretation is that if the Green player has 3 delegates in Unity, one of those three is the leader and the other two are non-leaders, and can be removed. 

The current behavior will not allow you to select those non-leader delegates. Likely this is because the partyLeader field identifies the player not a delegate. 

The logic could be updated to check if (they are the leader and have more than 1 delegate) or (they are not a leader and have at least 1 delegate).

**Comment by kberg** [comment]
Yeah, I might have interpreted that as "you cannot usurp a leader." Why then isn't the card written as "Exchange any non-neutral delegate with one of your own from the reserve?"

**Comment by puuj** [comment]
Well, if all players have a single delegate, a player ONLY has a leader delegate in the party and thus can’t be usurped. I don’t exactly know why it’s phrased as it is, just thought from a strict reading there was a bug.

**Comment by kberg** [comment]
Now I understand what you're asking. And it's a good point.

I've raised it on bgg: https://boardgamegeek.com/thread/2273194/article/40849528#40849528

and I'll email the designer to find out their original intention. The former might get a response in a week, the latter in a month. ;)

**Comment by kberg** [comment]
Here's the designer's response:

> The intention is to be able to replace a delegate, but it should not allow the player playing this to get hold of the party lead. It has been a while since I've played TM, so rules are a bit fuzzy for me at the moment, that remark is to prevent a party leader change, for example, I am the red player, and I have zero delagates in the said party, and blue and yellow has 2, with blue leading the party. If I am allowed to replace his leader, I, with one delegate only will be sitting as party leader, however it should be yellow, since the situation changed from; 2B 2Y 0R to 1B 2Y 1R. I am not sure if the game updates this right after a players turn or a majority change immediately. If it does, I have overdone myself, by putting that remark, because it is already a reminder of the existing rule.
>
> Another case may be as follows, instead of two delegates each, the other players may have 1 delegate each, like 1B 1Y, again blue leading the party. In this scenario, when you replace, you cannot replace blue but only yellow. So the situation changes from 1B 1Y 0R to 1B 0Y 1R, and the leader stays the same.
>
> I hope I managed to clarify my intention, the card itself is already powerful, so allowing it to gain the leadership in a party without majority would be too much, I just wanted to prevent that by keeping the party leader delegate -who sits at the very from of the party- to be immune to the effect of this card.

**Comment by kberg** [comment]
So I suspect my interpretation seems to capture the spirit of the designer's intent. Do you agree? If so, now it's just a matter of crafting text so it makes sense. You're not the only one to have asked about this recently.

**Comment by kberg** [comment]
Wait, I might be wrong. Yeah. I'm wrong.

Anyway, what do you think about this for text?

(Exchange a NON-NEUTRAL delegate with one of your own from the reserve. (This may NOT change the party leader.) You may then move your delegate to another party.)

**Comment by HenrikSteenbock** [comment]
I believe the same thing should happen for the card Banned Delegate, but there the opposite is currently the case. If the leader has multiple delegates in a party, you can still remove one of them which changes the party leader, even though the card explicitly states a NON-LEADER must be removed. One way or another, both cards should be consistent in terms of how they work and in terms of writing.

**Comment by HenrikSteenbock** [comment]
> (Exchange a NON-NEUTRAL delegate with one of your own from the reserve. (This may NOT change the party leader.) You may then move your delegate to another party.)

I like that as text, it makes it very clear

**Comment by kberg** [comment]
> I believe the same thing should happen for the card Banned Delegate, but there the opposite is currently the case. If the leader has multiple delegates in a party, you can still remove one of them which changes the party leader, even though the card explicitly states a NON-LEADER must be removed. One way or another, both cards should be consistent in terms of how they work and in terms of writing.

According to https://github.com/kberg/terraforming-mars-faq/wiki#banned-delegate-t02-t

> This card may cause the Party Leader to change (i.e., a different player has MORE delegates in the party than the current Party Leader.) This would take effect immediately.
>
>If playing this card causes two or more players to have more delegates than the current Party Leader (in a tie), then the Party Leader switches to the player closest to the active player in clockwise order (the active player is considered “first” for this purpose, the neutral player is considered “last”.)

**Comment by kberg** [comment]
What's the point of adding the delegate to one party just to move it to another one ... if you can't change party leadership for the first one?

**Comment by kberg** [comment]
In other words, why is this any different from adding a delegate to any party?

**Comment by HenrikSteenbock** [comment]
> In other words, why is this any different from adding a delegate to any party?

Because the wording for Banned Delegate is exactly the same as in the card above (An Offer You Can't Refuse) where you and the original designer agreed that the intention is to NOT usurp a leader, so it shouldn't be able to change party leadership. Additionally, the official sources listed in your unofficial FAQ don't actually make a ruling regarding change of leadership, they only clarify other questions.
