### ISSUE TITLE
[Moon] Tempest Consultancy action available even without delegates

### ISSUE THREAD

**Issue by HenrikSteenbock** [terraforming-mars/terraforming-mars#4989]
Tempest Consultancy action shows up as available even when there are no delegates in the reserve. Using it in that case doesn't do anything, but it's a free action that shouldn't be available, especially relevant when someone is trying to stall to wait and see what others are doing

**Comment by kberg** [comment]
Reading https://github.com/kberg/terraforming-mars-faq/wiki#what-cardaction-effects-or-requirements-are-mandatory-and-which-are-not I concur this is not working. I do not think this is a regression, but a bug as old as the card itself.

**Comment by kberg** [comment]
Oh look, it was even written as if it was intentional:

```
  it('can act, not enough delegates', () => {
    player.tagsForTest = {moon: 5};
    expect(card.canAct(player)).is.true;
    turmoil.delegateReserve = [];
    // Can still play, just ... no delegates
    expect(card.canAct(player)).is.true;
  });
```

**Comment by kberg** [comment]
Thanks. Do you think that is a regression?
