### ISSUE TITLE
Did not receive final Greenery placement (with 6 plants and 2 production)

### ISSUE THREAD

**Issue by BeriAlpha** [terraforming-mars/terraforming-mars#4990]
At the end of the game, I did not get an opportunity for final greenery placement.

I had 6 plants on hand and 2 production, so I should have been given the option to do a final conversion.

Unfortunately, now that the game is advanced to the ending VP screen, I can't step back and confirm this, but it was my plan for the entire final generation, and would have won the game on the tiebreaker.

https://terraforming-mars.herokuapp.com/the-end?id=pc24c6c3b1b63
Game ID: g97697be343a5

Game Log:
Good luck green!
Good luck yellow!
Good luck red!
Good luck blue!
Generation 1
blue played Valley Trust
blue kept 5 project cards
green played Astrodrill
green kept 3 project cards
yellow played Celestic
yellow kept 5 project cards
red played Poseidon
red kept 5 project cards
blue played Merger
You drew Helion, Aridor, Point Luna and Manutech
blue played Manutech
blue played Supplier
green played Metal-Rich Asteroid
green played Loan
yellow played New Partner
You drew Research Network and Power Generation
yellow played Power Generation
yellow played Metals Company
red played Great Aquifer
red placed ocean tile on row 1 position 3
red drew 1 card(s)
You drew Solar Wind Power
red placed ocean tile on row 1 position 2
red's titanium amount increased by 1
red played Orbital Construction Yard
blue played Acquired Space Agency
12 card(s) were discarded
blue drew Directed Impactors and Interstellar Colony Ship
blue played Development Center
green used Colony standard project
green built a colony on Luna
green's megacredits production increased by 2
green played Research Colony
green drew 2 card(s)
You drew Standard Technology and Strip Mine
green built a colony on Luna
green's megacredits production increased by 2
19 card(s) were discarded
yellow drew Floater Prototypes and Stratopolis
yellow played Deuterium Export
red built a colony on Pluto
red drew 2 card(s)
You drew Lunar Exports and Solar Reflectors
red played Interplanetary Colony Ship
red built a colony on Luna
red's megacredits production increased by 2
blue used Development Center action
blue drew 1 card(s)
You drew Atmo Collectors
blue played Research
blue drew 2 card(s)
You drew Toll Station and Thermophiles
green played Asteroid Hollowing
green used Astrodrill action
green removed 1 asteroid(s) from Astrodrill to gain 3 titanium
yellow played Floater Prototypes
yellow added 2 floater(s) to Deuterium Export
yellow played Deep Well Heating
red played Solar Wind Power
red played Lunar Exports
red's plants production increased by 2
blue played Directed Impactors
blue used Directed Impactors action
blue added 1 asteroid(s) to Directed Impactors
green spent 3 titanium to trade with Luna
green's megacredits amount increased by 7
green's megacredits amount increased by 2
green's megacredits amount increased by 2
red's megacredits amount increased by 2
green played Standard Technology
yellow used Deuterium Export action
yellow played Project Inspection
yellow used Deuterium Export action with Project Inspection
red passed
blue passed
green used Colony standard project
green built a colony on Pluto
green drew 2 card(s)
You drew Imported Nitrogen and Urban Decomposers
green used Asteroid Hollowing action
green added 1 asteroid(s) to Asteroid Hollowing
yellow used Celestic action
yellow added 1 floater(s) to Celestic
yellow passed
green passed
Generation 2
blue bought 2 card(s)
You drew Artificial Photosynthesis and Quantum Extractor
yellow bought 3 card(s)
You drew Flooding, Convoy From Europa and Aerosport Tournament
green bought 0 card(s)
You drew no cards
red bought 2 card(s)
You drew Security Fleet and Titanium Mine
green used Astrodrill action
green removed 1 asteroid(s) from Astrodrill to gain 3 titanium
green spent 3 titanium to trade with Luna
green's megacredits amount increased by 10
green's megacredits amount increased by 2
green's megacredits amount increased by 2
red's megacredits amount increased by 2
yellow claimed Energizer milestone
yellow spent 3 energy to trade with Pluto
yellow drew 2 card(s)
You drew Underground Detonations and Magnetic Shield
red drew 1 card(s)
You drew Asteroid Deflection System
green drew 1 card(s)
You drew Martian Survey
red played Electro Catapult
red used Electro Catapult action
red spent 1 plants to gain 7 Mâ‚¬
blue used Development Center action
blue drew 1 card(s)
You drew Terraforming Contract
blue used Directed Impactors action
blue removed 1 asteroid(s) from Directed Impactors to raise temperature 1 step
blue's heat production increased by 1
green used City standard project
green placed city tile on row 3 position 7
green drew 3 card(s)
You drew Research Outpost, Eos Chasma National Park and Energy Saving
green played Research Outpost
green placed city tile on row 3 position 1
green's titanium amount increased by 2
yellow played Flooding
yellow placed ocean tile on row 5 position 4
yellow's plants amount increased by 2
yellow used Celestic action
yellow added 1 floater(s) to Deuterium Export
red played Security Fleet
red used Security Fleet action
blue played Artificial Photosynthesis
blue's energy production increased by 2
blue spent 3 energy to trade with Callisto
blue's energy amount increased by 3
green played Martian Survey
green drew 2 card(s)
You drew Small Animals and Deimos Down:promo
green used Asteroid Hollowing action
green added 1 asteroid(s) to Asteroid Hollowing
yellow used Deuterium Export action
yellow passed
red played Titanium Mine
red passed
blue played Toll Station
blue's megacredits production increased by 8
blue played Quantum Extractor
green passed
blue passed
Generation 3
blue bought 1 card(s)
You drew Water Splitting Plant
green bought 2 card(s)
You drew Imported GHG and Floating Habs
red bought 1 card(s)
You drew Ecological Zone
yellow bought 1 card(s)
You drew Bio Printing Facility
yellow spent 3 energy to trade with Luna
yellow's megacredits amount increased by 10
green's megacredits amount increased by 2
green's megacredits amount increased by 2
red's megacredits amount increased by 2
yellow played Bio Printing Facility
red used Electro Catapult action
red spent 1 plants to gain 7 Mâ‚¬
red used Security Fleet action
blue used Development Center action
blue drew 1 card(s)
You drew Titan Floating Launch-pad
blue played Water Splitting Plant
green played Floating Habs
green used Colony standard project
green built a colony on Titan
green added 3 floater(s) to Floating Habs
yellow played Convoy From Europa
yellow drew 1 card(s)
You drew Investment Loan
yellow placed ocean tile on row 4 position 4
yellow's plants amount increased by 2
yellow used Colony standard project
yellow built a colony on Titan
yellow added 3 floater(s) to Deuterium Export
red spent 3 titanium to trade with Pluto
red drew 2 card(s)
You drew Heat Trappers and Ishtar Mining
red drew 1 card(s)
You drew Water to Venus
green drew 1 card(s)
You drew Potatoes
red used Colony standard project
red built a colony on Callisto
red's energy production increased by 1
blue used Water Splitting Plant action
blue used Directed Impactors action
blue added 1 asteroid(s) to Directed Impactors
green used Astrodrill action
green removed 1 asteroid(s) from Astrodrill to gain 3 titanium
green spent 3 titanium to trade with Titan
green added 1 floater(s) to Floating Habs
yellow added 1 floater(s) to Celestic
green added 2 floater(s) to Floating Habs
yellow used Deuterium Export action
yellow used Bio Printing Facility action
yellow's plants amount increased by 2
red played Lichen
red played Water to Venus
blue played Research Coordination
blue passed
green used Asteroid Hollowing action
green added 1 asteroid(s) to Asteroid Hollowing
green played Imported GHG
yellow used Celestic action
yellow added 1 floater(s) to Celestic
yellow passed
red passed
green passed
Generation 4
green bought 0 card(s)
You drew no cards
blue bought 4 card(s)
You drew Sponsors, Orbital Cleanup, Inventors Guild and Outdoor Sports
red bought 3 card(s)
You drew Ants, Earth Elevator and Fueled Generators
yellow bought 1 card(s)
You drew Lava Tube Settlement
red used Electro Catapult action
red spent 1 plants to gain 7 Mâ‚¬
red spent 9 Mâ‚¬ to trade with Pluto
red drew 2 card(s)
You drew Biomass Combustors and Wave Power
red drew 1 card(s)
You drew Rad-Suits
green drew 1 card(s)
You drew Extremophiles
blue used Development Center action
blue drew 1 card(s)
You drew Phobos Space Haven
blue played Inventors Guild
green used Astrodrill action
green added 1 asteroid(s) to Astrodrill
green played Extremophiles
yellow played Lava Tube Settlement
yellow placed city tile on row 5 position 9
yellow's plants amount increased by 1
yellow's titanium amount increased by 1
yellow spent 3 energy to trade with Titan
green added 1 floater(s) to Floating Habs
yellow added 1 floater(s) to Celestic
yellow added 2 floater(s) to Celestic
red played Wave Power
red played Fueled Generators
blue used Inventors Guild action
blue bought 0 card(s)
You drew no cards
blue played Orbital Cleanup
green spent 9 Mâ‚¬ to trade with Luna
green's megacredits amount increased by 10
green's megacredits amount increased by 2
green's megacredits amount increased by 2
red's megacredits amount increased by 2
green played Aerobraked Ammonia Asteroid
green added 2 microbe(s) to Extremophiles
yellow used Bio Printing Facility action
yellow's plants amount increased by 2
yellow used Convert Plants standard action
yellow placed greenery tile on row 5 position 8
yellow's plants amount increased by 2
red used Security Fleet action
red played Rad-Suits
blue used Convert Heat standard action
blue used Directed Impactors action
blue removed 1 asteroid(s) from Directed Impactors to raise temperature 1 step
blue's heat production increased by 1
green used Extremophiles action
green added 1 microbe(s) to Extremophiles
green used Floating Habs action
green added 1 floater(s) to Floating Habs
yellow used Deuterium Export action
yellow used Celestic action
yellow added 1 floater(s) to Celestic
red passed
blue used Convert Heat standard action
blue played Terraforming Contract
green passed
yellow played Investment Loan
yellow played Magnetic Shield
blue used Water Splitting Plant action
blue used Orbital Cleanup action
blue's megacredits amount increased by 7
yellow passed
blue played Sponsors
blue passed
Generation 5
green bought 2 card(s)
You drew Community Services and Shuttles
blue bought 3 card(s)
You drew Technology Demonstration, Cryo Sleep and Aerial Mappers
yellow bought 1 card(s)
You drew Forced Precipitation
red bought 3 card(s)
You drew Immigration Shuttles, Diversity Support and Martian Zoo
blue used Development Center action
blue drew 1 card(s)
You drew Big Asteroid
blue used Inventors Guild action
blue bought 0 card(s)
You drew no cards
green spent 9 Mâ‚¬ to trade with Luna
green's megacredits amount increased by 10
green's megacredits amount increased by 2
green's megacredits amount increased by 2
red's megacredits amount increased by 2
green used Convert Heat standard action
yellow spent 3 energy to trade with Titan
green added 1 floater(s) to Floating Habs
yellow added 1 floater(s) to Deuterium Export
yellow added 2 floater(s) to Celestic
yellow used Deuterium Export action
red played Martian Zoo
red claimed Tactician milestone
blue played Technology Demonstration
blue drew 2 card(s)
You drew Mars University and Tectonic Stress Power
blue played Mars University
blue is using their Mars University effect to draw a card by discarding a card.
You discarded Atmo Collectors
blue drew 1 card(s)
You drew Corroder Suits
green used Astrodrill action
green removed 1 asteroid(s) from Astrodrill to gain 3 titanium
green used Asteroid Hollowing action
green added 1 asteroid(s) to Asteroid Hollowing
yellow played Titan Shuttles
yellow played Forced Precipitation
red used Electro Catapult action
red spent 1 plants to gain 7 Mâ‚¬
red spent 3 energy to trade with Pluto
red drew 2 card(s)
You drew Anti-Gravity Technology and AI Central
red drew 1 card(s)
You drew Underground City
green drew 1 card(s)
You drew Medical Lab
blue played Aerial Mappers
blue played Corroder Suits
blue added 1 floater(s) to Aerial Mappers
green used Extremophiles action
green added 1 microbe(s) to Extremophiles
green used Floating Habs action
green added 1 floater(s) to Floating Habs
yellow used Bio Printing Facility action
yellow's plants amount increased by 2
yellow used Forced Precipitation action
yellow added 1 floater(s) to Forced Precipitation
red played Molecular Printing
red's megacredits amount increased by 11
red used Security Fleet action
blue used Aerial Mappers action
blue removed 1 floater(s) from Aerial Mappers to draw a card
blue drew 1 card(s)
You drew Sky Docks
blue played Sky Docks
green played Community Services
green's megacredits production increased by 3
green played Energy Saving
green's energy production increased by 3
yellow used Titan Shuttles action
yellow added 2 floater(s) to Titan Shuttles
yellow used Celestic action
yellow added 1 floater(s) to Titan Shuttles
red played Immigration Shuttles
red used Martian Zoo action
red's megacredits amount increased by 1
blue used Orbital Cleanup action
blue's megacredits amount increased by 8
blue used Water Splitting Plant action
green passed
yellow used Convert Heat standard action
yellow passed
red passed
blue played Cryo Sleep
blue is using their Mars University effect to draw a card by discarding a card.
You discarded Titan Floating Launch-pad
blue drew 1 card(s)
You drew Acquired Company
blue passed
Generation 6
blue bought 2 card(s)
You drew Mineral Deposit and Asteroid Rights
yellow bought 1 card(s)
You drew Noctis Farming
green bought 2 card(s)
You drew Giant Space Mirror and Ice Asteroid
red bought 2 card(s)
You drew Solarnet and Earth Catapult
green spent 3 energy to trade with Luna
green's megacredits amount increased by 10
green's megacredits amount increased by 2
green's megacredits amount increased by 2
red's megacredits amount increased by 2
green played Strip Mine
yellow spent 3 energy to trade with Titan
green added 1 floater(s) to Floating Habs
yellow added 1 floater(s) to Forced Precipitation
yellow added 2 floater(s) to Titan Shuttles
yellow used Bio Printing Facility action
yellow's plants amount increased by 2
red played Earth Catapult
red spent 3 energy to trade with Pluto
red drew 2 card(s)
You drew Venus Magnetizer and Venusian Animals
red drew 1 card(s)
You drew Small Asteroid
green drew 1 card(s)
You drew Local Shading
blue used Development Center action
blue drew 1 card(s)
You drew Luna Governor
blue used Inventors Guild action
blue bought 1 card(s)
You drew Pioneer Settlement
green used Astrodrill action
green added 1 asteroid(s) to Astrodrill
green played Shuttles
yellow played Noctis Farming
yellow used Celestic action
yellow added 1 floater(s) to Titan Shuttles
red used Electro Catapult action
red spent 1 plants to gain 7 Mâ‚¬
red used Convert Plants standard action
red placed greenery tile on row 3 position 3
red drew 1 card(s)
You drew Steelworks
blue played Luna Governor
blue played Acquired Company
green played Giant Space Mirror
green used Extremophiles action
green added 1 microbe(s) to Extremophiles
yellow used Convert Plants standard action
yellow placed greenery tile on row 4 position 8
yellow's plants amount increased by 1
yellow's steel amount increased by 1
yellow used Forced Precipitation action
yellow removed 2 resource(s) from yellow's Forced Precipitation
yellow increased Venus scale 1 step(s)
red used Security Fleet action
red played Ants
blue used Water Splitting Plant action
blue used Aerial Mappers action
blue added 1 floater(s) to Aerial Mappers
green passed
yellow used Titan Shuttles action
yellow added 2 floater(s) to Titan Shuttles
yellow used Deuterium Export action
red claimed Diversifier milestone
red used Martian Zoo action
red's megacredits amount increased by 2
blue used Convert Heat standard action
blue played Mineral Deposit
yellow played Titan Air-scrapping
yellow used Titan Air-scrapping action
red used Ants action
red removed 1 resource(s) from green's Extremophiles
red added 1 microbe(s) to Ants
red played Ecological Zone
red placed Ecological Zone tile on row 4 position 3
red's plants amount increased by 1
blue played Tectonic Stress Power
blue played Asteroid Rights
yellow passed
red passed
blue used Asteroid Rights action
blue removed 1 asteroid(s) from Asteroid Rights to gain 2 titanium
blue used Orbital Cleanup action
blue's megacredits amount increased by 9
blue played Phobos Space Haven
blue spent 2 energy to trade with Callisto
blue's energy amount increased by 7
red's energy amount increased by 3
blue passed
Generation 7
blue bought 2 card(s)
You drew Herbivores and Topsoil Contract
yellow bought 3 card(s)
You drew Giant Ice Asteroid, Vesta Shipyard and Industrial Microbes
green bought 2 card(s)
You drew GHG Import From Venus and Insulation
red bought 4 card(s)
You drew Cutting Edge Technology, Mercurian Alloys, Pets and Venus Soils
yellow spent 3 energy to trade with Luna
yellow's megacredits amount increased by 10
green's megacredits amount increased by 2
green's megacredits amount increased by 2
red's megacredits amount increased by 2
yellow used Celestic action
yellow added 1 floater(s) to Titan Shuttles
red played Pets
red spent 3 energy to trade with Pluto
red drew 2 card(s)
You drew Corona Extractor and Trans-Neptune Probe
red drew 1 card(s)
You drew Venus Waystation
green drew 1 card(s)
You drew Cupola City
blue used Development Center action
blue drew 1 card(s)
You drew Venusian Plants
blue played Herbivores
red's plants production decreased by 1 by blue
green spent 3 energy to trade with Enceladus
green added 4 microbe(s) to Extremophiles
green used Astrodrill action
green removed 1 asteroid(s) from Astrodrill to gain 3 titanium
yellow used Titan Shuttles action
yellow removed 9 resource(s) from yellow's Titan Shuttles
yellow removed 9 floaters to gain 9 titanium
yellow played Giant Ice Asteroid
yellow placed ocean tile on row 1 position 4
yellow's steel amount increased by 1
yellow placed ocean tile on row 2 position 4
red's plants amount decreased by 4 by yellow
red played Cutting Edge Technology
red played Mercurian Alloys
blue played Pioneer Settlement
blue built a colony on Miranda
blue added 1 animal(s) to Herbivores
blue played Space Port Colony
blue built a colony on Miranda
blue added 1 animal(s) to Herbivores
green played Deimos Down:promo
green placed ocean tile on row 1 position 1
green placed Deimos Down tile on row 9 position 5
green's steel amount increased by 2
yellow's plants amount decreased by 2 by green
green played Ice Asteroid
green placed ocean tile on row 4 position 7
green's plants amount increased by 1
green placed ocean tile on row 3 position 5
green's plants amount increased by 1
yellow used Titan Air-scrapping action
yellow removed 2 resource(s) from yellow's Titan Air-scrapping
yellow played Vesta Shipyard
red used Martian Zoo action
red's megacredits amount increased by 3
red played Venus Waystation
blue used Convert Heat standard action
blue used Convert Heat standard action
green used Convert Heat standard action
green played Eos Chasma National Park
yellow used Bio Printing Facility action
yellow's plants amount increased by 2
yellow used Forced Precipitation action
yellow added 1 floater(s) to Forced Precipitation
red played Trans-Neptune Probe
red played Corona Extractor
blue used Aerial Mappers action
blue removed 1 floater(s) from Aerial Mappers to draw a card
blue drew 1 card(s)
You drew Luna Metropolis
blue used Inventors Guild action
blue bought 0 card(s)
You drew no cards
green used Convert Plants standard action
green placed greenery tile on row 2 position 1
green's titanium amount increased by 1
green used Extremophiles action
green added 1 microbe(s) to Extremophiles
yellow used Deuterium Export action
yellow passed
red used Security Fleet action
red used Ants action
red removed 1 resource(s) from green's Extremophiles
red added 1 microbe(s) to Ants
blue used Water Splitting Plant action
blue used Asteroid Rights action
blue removed 1 asteroid(s) from Asteroid Rights to gain 2 titanium
green used Asteroid Hollowing action
green added 1 asteroid(s) to Asteroid Hollowing
green used Floating Habs action
green added 1 floater(s) to Floating Habs
red passed
blue used Orbital Cleanup action
blue's megacredits amount increased by 9
blue played Topsoil Contract
green played Insulation
green's heat production decreased by 4
green's megacredits production increased by 4
green passed
blue spent 2 energy to trade with Miranda
blue drew 1 card(s)
You drew Heather
blue drew 1 card(s)
You drew Designed Micro-organisms
blue added 2 animal(s) to Herbivores
blue played Outdoor Sports
blue used Sell Patents standard project
blue sold 1 patents
blue played Heather
blue passed
Generation 8
blue bought 2 card(s)
You drew Lunar Mining and Adaptation Technology
green bought 0 card(s)
You drew no cards
red bought 1 card(s)
You drew Penguins
yellow bought 1 card(s)
You drew Kelp Farming
red used Electro Catapult action
red spent 1 plants to gain 7 Mâ‚¬
red spent 3 energy to trade with Pluto
red drew 2 card(s)
You drew Snow Algae and Large Convoy
red drew 1 card(s)
You drew Hi-Tech Lab
green drew 1 card(s)
You drew Satellites
blue used Convert Heat standard action
blue spent 2 energy to trade with Miranda
blue drew 1 card(s)
You drew Stratospheric Birds
blue drew 1 card(s)
You drew Sister Planet Support
blue added 2 animal(s) to Herbivores
green funded Excentric award
green spent 3 energy to trade with Luna
green's megacredits amount increased by 10
green's megacredits amount increased by 2
green's megacredits amount increased by 2
red's megacredits amount increased by 2
yellow spent 3 energy to trade with Titan
green added 1 floater(s) to Floating Habs
yellow added 1 floater(s) to Forced Precipitation
yellow added 3 floater(s) to Titan Air-scrapping
yellow played Kelp Farming
red used Colony standard project
red built a colony on Miranda
red added 1 animal(s) to Martian Zoo
red played AI Central
blue used Development Center action
blue drew 1 card(s)
You drew Gene Repair
blue used Inventors Guild action
blue bought 0 card(s)
You drew no cards
green used City standard project
green placed city tile on row 2 position 2
red added 1 animal(s) to Pets
green used Greenery standard project
green placed greenery tile on row 3 position 2
yellow played Industrial Microbes
yellow used Titan Air-scrapping action
yellow removed 2 resource(s) from yellow's Titan Air-scrapping
red used AI Central action
red drew 2 card(s)
You drew Atalanta Planitia Lab and Breathing Filters
red played Atalanta Planitia Lab
red drew 2 card(s)
You drew Jovian Embassy and Extreme-Cold Fungus
blue used Water Splitting Plant action
blue used Aerial Mappers action
blue added 1 floater(s) to Aerial Mappers
green played Urban Decomposers
green added 2 microbe(s) to Extremophiles
green used Floating Habs action
green added 1 floater(s) to Floating Habs
yellow used Bio Printing Facility action
yellow's plants amount increased by 2
yellow used Forced Precipitation action
yellow removed 2 resource(s) from yellow's Forced Precipitation
yellow raised the Venus scale 1 step(s)
red played Breathing Filters
red used Security Fleet action
blue played Gene Repair
blue is using their Mars University effect to draw a card by discarding a card.
You discarded Big Asteroid
blue drew 1 card(s)
You drew Nitrophilic Moss
blue played Adaptation Technology
blue is using their Mars University effect to draw a card by discarding a card.
You discarded Nitrophilic Moss
blue drew 1 card(s)
You drew Mining Expedition
green used Asteroid Hollowing action
green added 1 asteroid(s) to Asteroid Hollowing
green used Astrodrill action
green added 1 asteroid(s) to Astrodrill
yellow used Titan Shuttles action
yellow added 2 floater(s) to Titan Air-scrapping
yellow used Deuterium Export action
red used Martian Zoo action
red's megacredits amount increased by 4
red used Ants action
red removed 1 resource(s) from green's Extremophiles
red added 1 microbe(s) to Ants
blue played Thermophiles
blue played Sister Planet Support
green used Extremophiles action
green added 1 microbe(s) to Extremophiles
green played Satellites
green's megacredits production increased by 6
yellow used Celestic action
yellow added 1 floater(s) to Titan Air-scrapping
yellow played Underground Detonations
red played Penguins
red used Penguins action
blue played Bactoviral Research
blue drew 1 card(s)
You drew Sponsored Academies
blue added 12 microbe(s) to Thermophiles
blue is using their Mars University effect to draw a card by discarding a card.
You discarded Mining Expedition
blue drew 1 card(s)
You drew Mangrove
blue played Sponsored Academies
blue is using their Mars University effect to draw a card by discarding a card.
You discarded Mangrove
blue drew 1 card(s)
You drew Stanford Torus
blue drew 3 card(s)
You drew Dusk Laser Mining, Neutralizer Factory and Advertising
green drew 1 card(s)
You drew Rego Plastics
yellow drew 1 card(s)
You drew Predators
red drew 1 card(s)
You drew Power Infrastructure
green passed
yellow funded Thermalist award
yellow passed
red played Asteroid Deflection System
red used Asteroid Deflection System action
red revealed and discarded Lagrange Observatory
blue spent 2 energy to trade with Callisto
blue's energy amount increased by 5
red's energy amount increased by 3
blue played Advertising
red played Diversity Support
red passed
blue played Dusk Laser Mining
blue played Luna Metropolis
blue's megacredits production increased by 15
red added 1 animal(s) to Pets
blue played Lunar Mining
blue's titanium production increased by 8
blue played Interstellar Colony Ship
blue played Neutralizer Factory
blue drew 1 card(s)
You drew Market Manipulation
blue played Stratospheric Birds
blue removed 1 resource(s) from blue's Aerial Mappers
blue used Orbital Cleanup action
blue's megacredits amount increased by 13
blue used Stratospheric Birds action
blue used Asteroid Rights action
blue added 1 asteroid(s) to Asteroid Rights
blue used Directed Impactors action
blue added 1 asteroid(s) to Asteroid Rights
blue used Thermophiles action
blue removed 2 resource(s) from blue's Thermophiles
blue spent 2 energy to trade with Enceladus
blue added 1 microbe(s) to Thermophiles
blue played Stanford Torus
red added 1 animal(s) to Pets
blue passed
Generation 9
blue bought 4 card(s)
You drew Warp Drive, Regolith Eaters, Local Heat Trapping and Natural Preserve
red bought 0 card(s)
You drew no cards
green bought 2 card(s)
You drew Worms and Algae
yellow bought 3 card(s)
You drew Floater Leasing, Atmoscoop and Insects
blue played Market Manipulation
blue increased Pluto colony track 1 step(s)
blue decreased Luna colony track 1 step
blue spent 2 energy to trade with Pluto
blue drew 3 card(s)
You drew Rotator Impacts, Dirigibles and Space Elevator
red drew 1 card(s)
You drew Ice Moon Colony
green drew 1 card(s)
You drew Symbiotic Fungus
green spent 3 energy to trade with Luna
green's megacredits amount increased by 7
green's megacredits amount increased by 2
green's megacredits amount increased by 2
red's megacredits amount increased by 2
green used City standard project
green placed city tile on row 5 position 3
green's plants amount increased by 2
red added 1 animal(s) to Pets
yellow used Convert Plants standard action
yellow placed greenery tile on row 6 position 8
yellow spent 3 energy to trade with Titan
green added 1 floater(s) to Floating Habs
yellow added 1 floater(s) to Celestic
yellow added 2 floater(s) to Celestic
red spent 3 energy to trade with Miranda
blue drew 1 card(s)
You drew SF Memorial
blue drew 1 card(s)
You drew Trade Envoys
red drew 1 card(s)
You drew Media Archives
red added 2 animal(s) to Penguins
red used AI Central action
red drew 2 card(s)
You drew Floater Technology and Domed Crater
blue spent 2 energy to trade with Callisto
blue's energy amount increased by 3
red's energy amount increased by 3
blue used Development Center action
blue drew 1 card(s)
You drew Carbonate Processing
green used City standard project
green placed city tile on row 3 position 4
red added 1 animal(s) to Pets
green used Greenery standard project
green placed greenery tile on row 2 position 3
yellow used Titan Shuttles action
yellow added 2 floater(s) to Titan Shuttles
yellow used Forced Precipitation action
yellow added 1 floater(s) to Forced Precipitation
red played Anti-Gravity Technology
red used Ants action
red removed 1 resource(s) from blue's Thermophiles
red added 1 microbe(s) to Ants
blue used Inventors Guild action
blue bought 0 card(s)
You drew no cards
blue played Warp Drive
blue is using their Mars University effect to draw a card by discarding a card.
You discarded Natural Preserve
blue drew 1 card(s)
You drew Miranda Resort
green used Sell Patents standard project
green sold 2 patents
green used Greenery standard project
green placed greenery tile on row 4 position 2
green's plants amount increased by 1
yellow used Deuterium Export action
yellow used Celestic action
yellow added 1 floater(s) to Titan Shuttles
red used Electro Catapult action
red spent 1 plants to gain 7 Mâ‚¬
red used Security Fleet action
blue played SF Memorial
blue drew 1 card(s)
You drew Sulphur-Eating Bacteria
blue funded Venuphile award
green used Extremophiles action
green added 1 microbe(s) to Extremophiles
green used Floating Habs action
green added 1 floater(s) to Floating Habs
yellow used Bio Printing Facility action
yellow's plants amount increased by 2
yellow played Floater Leasing
yellow's megacredits production increased by 7
red used Penguins action
red used Asteroid Deflection System action
red revealed and discarded Quantum Communications
blue played Regolith Eaters
blue is using their Mars University effect to draw a card by discarding a card.
You discarded Trade Envoys
blue drew 1 card(s)
You drew Subterranean Reservoir
blue played Dirigibles
green passed
yellow played Predators
yellow used Predators action
yellow removed 1 resource(s) from blue's Stratospheric Birds
yellow added 1 animal(s) to Predators
red used Martian Zoo action
red's megacredits amount increased by 5
red played Media Archives
red's megacredits amount increased by 18
blue used Dirigibles action
blue added 1 floater(s) to Aerial Mappers
blue used Aerial Mappers action
blue removed 1 floater(s) from Aerial Mappers to draw a card
blue drew 1 card(s)
You drew Decomposers
yellow used Titan Air-scrapping action
yellow removed 2 resource(s) from yellow's Titan Air-scrapping
yellow played Aerosport Tournament
yellow's megacredits amount increased by 9
red played Ishtar Mining
red played Jovian Embassy
blue played Local Heat Trapping
blue's plants amount increased by 4
blue used Convert Plants standard action
blue placed greenery tile on row 8 position 5
blue's steel amount increased by 2
blue added 1 animal(s) to Herbivores
yellow passed
red played Solarnet
red drew 2 card(s)
You drew House Printing and Industrial Center
red played Power Infrastructure
blue played Space Elevator
blue used Space Elevator action
red played Venus Magnetizer
red used Venus Magnetizer action
blue used Stratospheric Birds action
blue used Regolith Eaters action
blue added 1 microbe(s) to Regolith Eaters
red played House Printing
red played Hi-Tech Lab
blue played Rotator Impacts
blue used Directed Impactors action
blue added 1 asteroid(s) to Rotator Impacts
red used Hi-Tech Lab action
red spent 5 energy
red drew 1 card(s)
You drew CEO's Favorite Project
red played CEO's Favorite Project
red added 1 animal(s) to Penguins
blue used Thermophiles action
blue removed 2 resource(s) from blue's Thermophiles
blue used Rotator Impacts action
blue removed 1 resource(s) from blue's Rotator Impacts
blue removed an asteroid resource to increase Venus scale 1 step
red played Venus Soils
red added 2 microbe(s) to Ants
red played Luxury Foods
blue played Decomposers
blue spent 2 titanium to trade with Enceladus
blue added 1 microbe(s) to Decomposers
red played Venusian Animals
red played Floater Technology
blue played Sulphur-Eating Bacteria
blue used Asteroid Rights action
blue removed 1 asteroid(s) from Asteroid Rights to gain 2 titanium
red used Sell Patents standard project
red sold 3 patents
red used Floater Technology action
blue used Sell Patents standard project
blue sold 1 patents
blue used Sulphur-Eating Bacteria action
blue added 1 microbe(s) to Sulphur-Eating Bacteria
red played Industrial Center
red placed Industrial Center tile on row 4 position 5
red's plants amount increased by 1
red used Sell Patents standard project
red sold 1 patents
blue used Orbital Cleanup action
blue's megacredits amount increased by 15
blue played Miranda Resort
blue's megacredits production increased by 16
red passed
blue used City standard project
blue placed city tile on row 6 position 7
blue's plants amount increased by 1
red added 1 animal(s) to Pets
blue used Greenery standard project
blue placed greenery tile on row 5 position 7
blue's plants amount increased by 2
blue added 1 animal(s) to Herbivores
blue played Carbonate Processing
blue's energy production decreased by 1
blue's heat production increased by 3
blue passed
Final greenery placement
green placed greenery tile on row 2 position 6
green's steel amount increased by 2
This game id was g97697be343a5

**Comment by kberg** [comment]
You would not have won. The rules state that you lost at the end of your last generation.

What you are observing is a change to the app to reflect this, as detailed at https://github.com/terraforming-mars/terraforming-mars/wiki/FAQ#why-cant-i-place-greeneries-after-my-last-generation

> In solo mode, victory is decided immediately at the end of the last generation. So for instance, if you are playing the standard solo game, you will only win if you have maximized all three global parameters before placing final greeneries. In fact, placing final greeneries in solo mode does not raise the oxygen. And so, you cannot use final greenery placement to turn a loss into a win.
> 
> And so, the app behaves like so:
> 
> 1. If haven't completed your solo objectives by the final generation, you do not get to place greeneries. It serves no point.
> 
> 2. If you have completed your solo objectives by the final generation, you may place additional greeneries, which will increase your winning score.
> 
> a. When playing the TR63 variant, final greenery placement does not raise the oxygen.
>
> See https://github.com/terraforming-mars/terraforming-mars/issues/2055 for some discussion on the topic.

I'm going to close this, since it's working as intended, but you are welcome to add more to this bug.

**Comment by BeriAlpha** [comment]
This wasn't solo mode, it was a four-player game.

**Comment by kberg** [comment]
Ah, then let's reopen this and take a look. Yipe!

**Comment by kberg** [comment]
Which color were you? And if you're on the Discord, do you mind raising my attention there?

**Comment by BeriAlpha** [comment]
Blue, and I'll head over.

**Comment by BeriAlpha** [comment]
All right, this one was on me. I found a browser with an old copy of the game state still loaded, and I only had 1 plant production. I either missed an attack card, or I just made a plan and continually failed to register that it was wrong. No issue.

**Comment by kberg** [comment]
Well, thank you for letting me practice my "Sorry to have to break it to
you but you lost your solo game" spiel on you.
