### ISSUE TITLE
Android 13 scrolling issues

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#5004]
>  I doubt this is something y'all can fix but maybe it's possible - ever since the new android update the site is unusable on Chrome on my Pixel. 
>
> It's doing the "delayed scroll" thing. It's only a problem on this site but if you have other sites I can test I'm happy to. I can screen record if you need to see what I mean. The site scrolls irregularly and delayed.

https://discord.com/channels/737945098695999559/742721510376210583/1024198433051000843

**Comment by Gugatec** [comment]
The "Remove Background Image" works for me to resolve the issue (despite my phone being a reasonable high-end one)

**Comment by Gugatec** [comment]
I hear that android 14 is going to have the scroll reworked, don't think is
worth to work on a detection, as is a easy setting to change and might not
affect everyone.

**Comment by kberg** [comment]
OK, fair enough. Thanks.

**Comment by Gugatec** [comment]
I'm curious, did the work around of disab6le the background in the settings, worked for you?

**Comment by kberg** [comment]
Apparently it did!
https://discord.com/channels/737945098695999559/742721510376210583/1138828552901509312

**Comment by Gugatec** [comment]
Cool, thanks for sharing!

**Comment by leggupdown** [comment]
> The "Remove Background Image" works for me to resolve the issue (despite my phone being a reasonable high-end one)

HERO. 🏆
