### ISSUE TITLE
[enhancement] Warning message when O2, Oceans or Temperature can't be raised

### ISSUE THREAD

**Issue by joleal** [terraforming-mars/terraforming-mars#5014]
When playing cards and events that place Oceans, raise temperature or oxygen, the UI should show a warning message if either the parameter has already reached max level. 

Ex. When playing Large Convoy, if all oceans have already been placed it should show a warning (similar to when playing Fishes, for example, when only I have plants production).

**Comment by kberg** [comment]
This feature is now available. Thanks for your patience!
