### ISSUE TITLE
maximum call stack size exceeded

### ISSUE THREAD

**Issue by benmacbeg** [terraforming-mars/terraforming-mars#5030]
Please include:
1. A clear and concise description of the bug.
2. Clear steps to reproduce, and the expected behavior.
3. Any screenshots
4. Any information from  the Bug Report Dialog

URL: https://terraforming-mars.herokuapp.com/spectator?id=s3711bebab18e
Player color: blue
Step: 176
Version: 5d01ea8, built at Mon, 03 Oct 2022 05:45:10 GMT
Browser: Firefox 91
![image](https://user-images.githubusercontent.com/21361270/193761983-99eb525d-3642-46c9-a72b-5bc6c438bc8c.png)

I think I played "Énergie des Vents Solaires" (with a science, energy and space badges)  and when I had a third (?) science ressources on conference of Olympus the bug appears "maximum call stack size exceeded" in the popup. After the other player couldn't play and I could play Mines Lunaires two times... Now we can't finish the game.

thank you for your help

**Comment by kberg** [comment]
Thank you! I'll have this fixed in about 12 hours. So sorry about this.

**Comment by kberg** [comment]
Fixed by #5031
