### ISSUE TITLE
BUGS: Icons not working and also an entire prelude card

### ISSUE THREAD

**Issue by samullai2** [terraforming-mars/terraforming-mars#5040]
IMPORT OF ADVANCED GHC: Earth icon not counting
BRIBED COMMITTE: Earth icon not counting
SPECIAL DESIGN: Science icon not working
SOLAR PROBE:  Science icon not working
Also the Prelude card that gives [+2 titanium production and -5 M$] is simply NOT being able to use. I started a game and could use only 1 prelude card because of this bug.

There are many other cards on which science icons are not working

**Comment by nwai90** [comment]
Icons on event cards do not count towards your tag total. The Prelude card that gives [+2 titanium production and -5 M$] requires you to be able to afford to pay 5 M$.

**Comment by samullai2** [comment]
omg, I didn't know that LOL. Thanks!

**Comment by samullai2** [comment]
Wouldn't it be possible to send an error message and tell us to change the prelude card in order to prevent players from doing that mistake? Because I basically lost the game from Generation 1 for not paying attention to that.

**Comment by kberg** [comment]
What we need to be able to do is allow the player to undo more easily. That's just not simple, but we'll get there.
