### ISSUE TITLE
Playing Volcano/Mons card allowed when only allowable space is occupied by Erosion that player cannot afford to place a tile on 

### ISSUE THREAD

**Issue by ImTrying1** [terraforming-mars/terraforming-mars#5041]
When a player plays a volcanic tile, but the only allowable volcanic spaces are occupied by errosion/dust storms and the player cannot afford to pay the megacredits to place on top of it, the player becomes stuck on the step of selecting which tile to place their volcanic tile on. The player is forced to pick the erosion tile, then receives a message that they cannot afford to place a tile there. Since there is no way to move past this, the game cannot proceed.

<img width="533" alt="image" src="https://user-images.githubusercontent.com/10768202/194949379-2cd8647e-15bb-431e-80fa-c326e8a5cf00.png">

![image](https://user-images.githubusercontent.com/10768202/194949452-36b5dd7d-2298-449c-b15c-bd46f0d94760.png)

URL: https://terraforming-mars.herokuapp.com/spectator?id=s6bc23ea65479#board
Player color: purple
Step: 258
Version: f905f94, built at Tue, 04 Oct 2022 22:48:38 GMT
Browser: Chrome 105

**Comment by kberg** [comment]
Are you on the discord? Can you make yourself known to me if you are?

**Comment by kberg** [comment]
I triggered an undo. This is a known issue that really must be fixed.
