### ISSUE TITLE
[Moon] Earth Embassy + Point Luna bug

### ISSUE THREAD

**Issue by HenrikSteenbock** [terraforming-mars/terraforming-mars#5064]
Earth Embassy together with Point Luna should result in Moon tags giving that player a card when played. We observed when Luna Political Institute (Moon and Earth Tag) was played, that the player only got 1 card, when they should have received 2, one for the Earth tag and another one for the Moon tag.

**Comment by HenrikSteenbock** [comment]
The same behavior was also observed with other Moon tags not triggering the Point Luna effect.

For reference, here's the game link and the mentioned step is just after a played moon tag didn't trigger that effect:
URL: https://terraforming-mars.herokuapp.com/spectator?id=sf6ea020f5478
Player color: orange
Step: 672
Version: 10e27a6, built at Sat, 15 Oct 2022 15:09:09 GMT
Browser: Firefox 105

**Comment by kberg** [comment]
Thanks for the report.
