### ISSUE TITLE
Final Greenery does not trigger on exactly eight plants

### ISSUE THREAD

**Issue by hegemogy** [terraforming-mars/terraforming-mars#5103]
Nine or greater plants triggers the final greenery placement, but eight plants does not.

URL: https://terraforming-mars.herokuapp.com/spectator?id=s30c59d1439f2 Player color: red Step: 26 Version: 87ec6e7, built at Sun, 23 Oct 2022 04:02:14 GMT Browser: Safari 15

**Comment by kberg** [comment]
Thanks for the report. This is working as intended:

https://github.com/terraforming-mars/terraforming-mars/wiki/FAQ#why-cant-i-place-greeneries-after-my-last-generation

> In solo mode, victory is decided immediately at the end of the last generation. So for instance, if you are playing the standard solo game, you will only win if you have maximized all three global parameters before placing final greeneries. In fact, placing final greeneries in solo mode does not raise the oxygen. And so, you cannot use final greenery placement to turn a loss into a win.
> 
> And so, the app behaves like so:
> 
> If haven't completed your solo objectives by the final generation, you do not get to place greeneries. It serves no point.
> 
> If you have completed your solo objectives by the final generation, you may place additional greeneries, which will increase your winning score.
> 
> a. When playing the TR63 variant, final greenery placement does not raise the oxygen.
> 
> See https://github.com/terraforming-mars/terraforming-mars/issues/2055 for some discussion on the topic.
