### ISSUE TITLE
[Pathfinders] Odyssey Corporation working correctly?

### ISSUE THREAD

**Issue by ap3h3ad** [terraforming-mars/terraforming-mars#5116]
Hi,

apparently it's not possible to use the Odyssey corporation action with something like Project Inspection. We suppose this is due to the fact that the corporation action doesn't hold as finished when trying to use it with Project Inspection. Is this correct or may this be an unwanted behaviour?

[Screenshot](https://abload.de/img/bugh2i3k.png)

Cheers!

**Comment by kberg** [comment]
Hi! I'm back up for air. What do you mean by "Doesn't hold as finished?"

I'll take a look.

**Comment by kberg** [comment]
I just manually verified that it does, in fact, work.

**Comment by kberg** [comment]
... meaning that I got Odyssey to play Project Inspection.

**Comment by kberg** [comment]
I'm going to close this. Feel free to add more details if necessary.
