### ISSUE TITLE
Drafting/researching phase bug

### ISSUE THREAD

**Issue by JeremyDietrich** [terraforming-mars/terraforming-mars#5133]
This has happened twice now quite far apart in time, but it's just annoying enough that I would like to bring it up.

Sometimes when playing a game (so far only on a Heroku server for playing remotely), during the drafting/researching phase if I'm not active on the server for a bit before coming back to the page, it will show me as drafting the third card again even when it is actually research phase with all four cards drafted, and so when I try to draft the third card again it just makes me buy that one card and nothing else.

The page shows up just like drafting including with the button saying "keep", the other players also show that they are drafting, and I only have the choice of the two cards that were available at the time of the draft, with the other cards I've drafted shown below as "drafted cards". The "select cards to buy" screen does not show up. I've caught something like this a few times between the two active failures by refreshing the page, but this most recent time it still failed even after the refresh.

Sorry, I know this is probably super hard to reproduce and I don't have any way of showing it in images unless I make it happen a third time, but it's only happening about once a month (including the times I caught it).

**Comment by kberg** [comment]
Today is "make sure every open bug has a comment" day!

Yeah, I know this one. This is the same as #4044, so I'm going to close this as a duplicate.

There really isn't much we can do about this right now.
