### ISSUE TITLE
Allow manually adjusting game state

### ISSUE THREAD

**Issue by scottkennedy** [terraforming-mars/terraforming-mars#5146]
While playing, I've often run into issues that the "undo" action doesn't handle, and with a physical game, my friends and I would just manually adjust the game state by adding tokens/credits/titanium/etc.

It would be nice to have an option to adjust various state values, whether the admin can do it themselves (with a game log message), or some kind of propose/vote/approve system.

**Comment by kberg** [comment]
I've wanted the idea a few times, but I don't think it's going to happen.
Server administrators can affect rollbacks of certain kinds. Anything more
would be rife for abuse. Thanks for the suggestion, but it's probably not
going to happen.
