### ISSUE TITLE
show start hand cards in game log

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#5153]
### Discussed in https://github.com/terraforming-mars/terraforming-mars/discussions/5148

<div type='discussions-op-text'>

<sup>Originally posted by **beber-msft** November 26, 2022</sup>
please add initial kept cards from starting hand to gamelog. thank you very much.</div>

**Comment by beber-msft** [comment]
ask is to display in each personal game log the name of the initially kept cards. this already happens for any other card draws / drafts but not for the initial starting hand. reviewing the game afterwards is leaving this one missing.

**Comment by Borbarad2** [comment]
okay, understood now what the improvement should be about.

**Comment by kberg** [comment]
After thinking about this for some time, I came to realize that a player's starting hand is private information which an opponent should not get to know by downloading the game log. With that in mind, thanks for the suggestion, but I'm going to close this issue. If you have other questions please feel free to add them; I'll be notified.
