### ISSUE TITLE
[Merger] Aridor does not take additional corps into account.

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#5181]
> i played Aridor and the Merger prelude, but when i chose Vitor as a second corp, the :tag_earth: didn’t give me a :cube_mc: prod

**Comment by Jeremy-borderieux** [comment]
We had a similar issue in this game:
Green played arklight, then merger with soylent seedlings systems (plant badge) and arklight's animals were not triggered.
