### ISSUE TITLE
Helion payment timing allowing early information

### ISSUE THREAD

**Issue by Alvis1218** [terraforming-mars/terraforming-mars#5191]
When playing as Helion, and when paying for Restricted Area's action, the card is drawn before the payment method is decided. In most cases the payment method's timing is not an issue as long as the player is aware what they wish to spend, but in this case they can react to the card they draw before choosing a resource to pay with, which is not intended.

**Comment by kberg** [comment]
Fair. I'll take a look next week.

**Comment by kberg** [comment]
I'll fix this right now. Good report. Thank you.
