### ISSUE TITLE
TM has been down for 2 days

### ISSUE THREAD

**Issue by EzFlyerMars** [terraforming-mars/terraforming-mars#5193]
This is what we see when we try to open the website:

Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by waxoid** [comment]
seeing the same all day today, also for recently finished games (e.g. https://terraforming-mars.herokuapp.com/game?id=g50d488a56f02)

HNY and thanks to all the devs here for a lot of fun in 2022!

**Comment by bafolts** [comment]
Trying to remove old games and then will restart the server. The application is running out of memory when attempting to start. Deleting any game records from prior to November of 2022. I think there may be a bug with the removal of old games.

**Comment by EzFlyerMars** [comment]
> 

you're the man!! thanks to you and everyone else who's contributed to this.  My friend and I have played hundreds of games now, a-synchronously.  Going to finally stop being cheap and donate :)

**Comment by bafolts** [comment]
I am going to continue to delete older games throughout the day. This may impact game play for today. The server seems to be up again for time being. Once the older game records are deleted I expect it will be back up and running like it's old self.

**Comment by bafolts** [comment]
Seems to have stabilized. Going to close this issue. Will re-visit the process we use to remove old games as it seems to have stopped working at some point in June or July.
