### ISSUE TITLE
Potatoes issue

### ISSUE THREAD

**Issue by motoyugota** [terraforming-mars/terraforming-mars#5195]
In this game, it just let me play Potatoes with only one play resource:

URL: http://terraforming-mars.herokuapp.com/spectator?id=se52c2f178d5
Player color: purple
Step: 8
Version: bc55fff, built at Fri, 02 Dec 2022 21:16:21 GMT
Browser: Chrome 108

**Comment by kberg** [comment]
Thanks for the link. This is not a bug because you already had Viral Enhancers, which gives players a plant when playing a card with a plant tag.  Potatoes has a plant tag, so Viral Enhancers gives you the second plant, which is immediately spent.

**Comment by kberg** [comment]
Happy to help! That FAQ is phenomenal.
