### ISSUE TITLE
Make number of prelude cards configurable

### ISSUE THREAD

**Issue by jansepke** [terraforming-mars/terraforming-mars#5203]
We are drawing more corporations and prelude cards for more flexibility. The corporation number is already configurable. Would be great to also allow configuring the number of prelude cards that one can draw. The idea is not to increase the number of prelude cards one can pick.

Maybe I try to add it to https://github.com/terraforming-mars/terraforming-mars/blob/main/src/client/components/create/CreateGameForm.vue

**Comment by kberg** [comment]
Thanks for the bug. I haven't heard much on the Discord or other media that this is a meaningful request, and I've been a little concerned just many options the game has in the UI.

**Comment by Borbarad2** [comment]
I already did suggested this idea long time ago.

**Comment by jansepke** [comment]
I saw this idea on reddit but it was only once, so I would close this one. people can upvote if I'm not alone.
