### ISSUE TITLE
corrosive rain

### ISSUE THREAD

**Issue by benmacbeg** [terraforming-mars/terraforming-mars#5228]
URL: https://terraforming-mars.herokuapp.com/spectator?id=s851444e7a8c3
Player color: red
Step: 92
Version: 11a4954, built at Tue, 10 Jan 2023 15:41:14 GMT
Browser: Firefox 102

Hello,
On political event "corrosive rain" I have 2 "flotteurs" in french (clouds ?) on 2 differents cards but I lost 10mc :( I hadn't the choice.

**Comment by kberg** [comment]
Sorry for you, but the app was correct.

https://github.com/kberg/terraforming-mars-faq/wiki#corrosive-rain-immigration-to-venus
> The floaters removed for this event must both come from the same card.

**Comment by benmacbeg** [comment]
Oh ok sorry for this.
An other point, we noticed a problem with the draft with 3 players. We give
the cards to the other player that is indicated.

**Comment by kberg** [comment]
Thank you. Please don't use an existing issue to report a new bug. Someone else reported this bug https://github.com/terraforming-mars/terraforming-mars/issues/5230. If it is the same issue, then we already have some information. If it is a different issue, please open another bug.

**Comment by benmacbeg** [comment]
Ok 👌
