### ISSUE TITLE
Passing to players seems to be reversed

### ISSUE THREAD

**Issue by pandavenger** [terraforming-mars/terraforming-mars#5230]
Please include:
1. When playing a 5 player game (not sure if this is the case for other games), the passing to dialogue seems to be flipped (it shows the player name in the opposite direction you are actually passing to)
2. See above.
3. No screenshots
4. URL: https://terraforming-mars.herokuapp.com/spectator?id=s6c82f82b9616&noredirect=
Player color: yellow
Step: 562
Version: 39c09ef, built at Thu, 12 Jan 2023 14:57:51 GMT
Browser: Chrome 108

**Comment by kberg** [comment]
Figured it out. It should be going out soon.
