### ISSUE TITLE
Snow Cover event in Turmoil didn't reduce temp by 2 steps when temp was maxed

### ISSUE THREAD

**Issue by amulder87** [terraforming-mars/terraforming-mars#5250]
I'm not sure if the maximum temperature was the cause of the issue or being in a solo game or something else entirely, but resolution of the Snow Cover event in the Turmoil phase left the temperature at maximum instead of reducing it by 2 steps.

![image](https://user-images.githubusercontent.com/20569226/213375294-81d46552-dcd9-4562-9172-ebf1effe7906.png)

**Comment by kberg** [comment]
Thanks for the report, and the pull request! I appreciate it. However, I wish I responded before you started working on it.

From https://github.com/kberg/terraforming-mars-faq/wiki#snow-cover-mohole-lake

> If this event decreases temperature to 0°, this does not trigger the ocean bonus.
>
> If this event decreases temperature below 0°, nothing happens, but the ocean tile bonus may be triggered a second time when the temperature is raised again to 0° subsequently.
>
> If the temperature is at maximum (8°C), the first part of this Global Event has NO EFFECT (since Global Parameters that are at maximum cannot be affected for the remainder of the game.)

Source: https://boardgamegeek.com/thread/2334454/article/33634574#33634574

**Comment by kberg** [comment]
I've closed this issue. If for some reason you think this is mistaken, feel free to respond. I can always reopen it.

**Comment by amulder87** [comment]
Oh, good to know! I did not know that being at maximum locked them in, thanks!
