### ISSUE TITLE
Wrong message when starting server

### ISSUE THREAD

**Issue by rogerta** [terraforming-mars/terraforming-mars#5272]
I pulled, built, and ran the terraforming-mars  at git hash 39c09ef55.  When I run the server I see the following line in stdout:
```
Jan 23 18:34:28 rpi4a start_tm_server.sh[82467]: [2023-01-23 18:34:28 GMT] Starting 359d6404f, built at Fri, 12 Aug 2022 17:34:20 -0400
```
The hash does not seem correct and the date is certainly not correct.

Greping the code I see this was added to the repo in commit 9638d40ac11ef08f85ea3c618a35b294c39a60cc:
```
$ git grep 359d6404f
src/server/genfiles/settings.json:{"head":"359d6404f","builtAt":"Fri, 12 Aug 2022 17:34:20 -0400","waitingForTimeout":1000,"logLength":50}
```
Is this intended?

**Comment by kberg** [comment]
Oh, good catch. Yipe! Thanks.
