### ISSUE TITLE
New Prelude rule: "fizzle" for unplayable cards

### ISSUE THREAD

**Issue by norm** [terraforming-mars/terraforming-mars#5313]
In a recent thread on BGG, Jacob Fryxelius gave a ruling on unplayable Prelude cards that states they instead grant 15M€ — https://boardgamegeek.com/thread/2993276/article/41533232#41533232

**Comment by d-little** [comment]
This was discussed a couple of times on Discord:
* https://discord.com/channels/737945098695999559/738006783955697704/1067775870955163748
* https://discord.com/channels/737945098695999559/742826825922904225/1067473864088621179

The consensus came down to "Very low priority. One day, maybe".

Good to have a record of it here though

**Comment by kberg** [comment]
This is done.
