### ISSUE TITLE
[CEO] New Van Allen CEO from custom expansion can't claim milestones without $8MC

### ISSUE THREAD

**Issue by nabby101** [terraforming-mars/terraforming-mars#5406]
Sorry, forgot to take screenshots, but this is a pretty straightforward one, although I am unsure whether it's a bug or a slightly unclear rule.
I had $0MC and was unable to claim the Tycoon milestone despite having 15 green/blue cards.
My interpretation of Van Allen is that the milestone is free, not reimbursed, but it's possible that "you must still meet the requirements" applies to having the $8MC as well.

URL: https://terraforming-mars.herokuapp.com/spectator?id=sc03350ebb86e
Player color: orange
Step: 74
Version: bc70f33, built at Fri, 17 Feb 2023 05:58:58 GMT
Browser: Firefox 110

**Comment by d-little** [comment]
Its a bug, good catch.  Thankyou for the report

**Comment by d-little** [comment]
Resolved in #5408
