### ISSUE TITLE
MINORITY REFUGE production error

### ISSUE THREAD

**Issue by Yuger030** [terraforming-mars/terraforming-mars#5420]
URL: https://terraforming-mars.herokuapp.com/spectator?id=sf214c6f9b1b9
Player color: yellow
Step: 26
Version: 7441c56, built at Mon, 20 Feb 2023 03:35:06 GMT
Browser: Firefox 107

Play "MINORITY REFUGE" with -5 Megacredit production (shows "only be able to build the colony on Luna")
after played this card, Megacredit production shows -3 (correct is -5).

![Screenshot from 2023-02-22 14-37-28](https://user-images.githubusercontent.com/126051518/220542493-70312f0f-1554-4bf5-9a57-1edc2cc4c839.png)
![Screenshot from 2023-02-22 14-37-57](https://user-images.githubusercontent.com/126051518/220542539-81e8960c-3aff-48a3-81f8-c0d9aaf102ec.png)

**Comment by kberg** [comment]
Ah, I see the issue. Thanks.
