### ISSUE TITLE
[CEO] Ingrid tile placement bonus doesn't include ocean tiles (possibly intended)

### ISSUE THREAD

**Issue by nabby101** [terraforming-mars/terraforming-mars#5434]
"Once per game, activate this ability: when you take an action that places a tile on Mars THIS GENERATION, draw a card."

Activating the once-per-game ability of the CEO Ingrid does not draw a card when you place oceans on Mars during the turn.

I'm not sure if this is a bug or intended gameplay because as far as I can recall, the mechanic doesn't exist in any of the real expansions. Looking at the card list, apparently there are a few custom cards that have a similar effect (the corporation Curiosity II and the blue card Geological Expedition), but I haven't played with the fan-made expansions much, so I'm not sure if this behaviour is consistent with those cards as far as counting an ocean as "placing a tile on Mars."

My interpretation of this ability as worded is that it should include ocean tiles, otherwise I would expect it to follow the wording convention on cards like Land Claim ("non-reserved area").

URL: https://terraforming-mars.herokuapp.com/spectator?id=s6f969a4a6c32
Player color: orange
Step: 22
Version: 7441c56, built at Mon, 20 Feb 2023 03:35:06 GMT
Browser: Firefox 110

**Comment by d-little** [comment]
This _should_ be resolved via https://github.com/terraforming-mars/terraforming-mars/pull/5432

The main server doesnt have this fix just yet, hopefully soon.  Will keep this issue open to track reports until the fix is in, and to see if it reoccurs
