### ISSUE TITLE
The Karen CEO action is usable more than once.

### ISSUE THREAD

**Issue by jacobaagaardbennike** [terraforming-mars/terraforming-mars#5435]
Please include:
1. A clear and concise description of the bug.
The Karen CEO is usable more than once per game. (it's in beta, so I'm not sure if it is a bug).

3. Clear steps to reproduce, and the expected behavior.
Not sure exactly, after a seemingly random set of turns, it just becomes an available option again.

6. Any information from  the Bug Report Dialog
URL: https://terraforming-mars.herokuapp.com/spectator?id=sd78c9bfaa529
Player color: orange
Step: 188
Version: 7441c56, built at Mon, 20 Feb 2023 03:35:06 GMT
Browser: Chrome 110

**Comment by d-little** [comment]
This should be resolved via https://github.com/terraforming-mars/terraforming-mars/pull/5432

The main server doesnt have this fix just yet, hopefully soon. Will keep this issue open to track reports until the fix is in, and to see if it reoccurs

**Comment by kberg** [comment]
This is fixed.
