### ISSUE TITLE
Change corporation draft to be the same as project and prelude drafts

### ISSUE THREAD

**Issue by ChrisTheCat** [terraforming-mars/terraforming-mars#5440]
In a 3 player game, if you choose 3 corps per player and corporation draft, all players see the 9 corporations available. Player 1 picks a corp from 9 available. Player 2 picks a corp from 8. Player 3 picks a corp from 7, player 1 picks a corp from 6, etc.

This is slow and in an async game it's nearly impossible for players to know who drew which card.

I suggest making the corporation draft the same as the project and prelude drafts. In the given example, each player would be dealt 3 corporations, choose 1, pass 2; then choose 1, pass 1; then receive 1.

**Comment by Borbarad2** [comment]
This is already a long suggest one. See discussion on the dev channel in discord. 
We all do not like the corp selection procedure, and wish to have like a corp draft.
So your request is already made and adress, though no Issue was created for that.

**Comment by kberg** [comment]
Thanks for the bug report. The corporation draft will likely just be removed from the game altogether, sorry.
