### ISSUE TITLE
Immigrant City megacredit production increase does not appear in game log

### ISSUE THREAD

**Issue by Negrolyte** [terraforming-mars/terraforming-mars#5455]
Please include:
1. When a player has the Immigrant City city card and a city is added to the game board, the player who owns the card's mega credit production increase is not reported in game log. The production increase still occurs however.

**Comment by kberg** [comment]
Thanks for the report.

Most production increases are not automatically logged, especially if they are a value that does not vary (e.g. gain 1 MC production.) If we log too much, we'll start to risk running out of database space.

I'm going to close the issue, but if you have further questions, please feel free to ask.
