### ISSUE TITLE
SQLITE_CANTOPEN

### ISSUE THREAD

**Issue by Carontes** [terraforming-mars/terraforming-mars#5465]
I've just installed the game in a ARM64 machine but it doesn't start. The error I see in docker is this one:

`}
> terraforming-mars@1.0.0 start
> node build/src/server/server.js
[2023-03-13 17:20:16 GMT+0000] Connecting to SQLite database.
[2023-03-13 17:20:16 GMT+0000] UNCAUGHT EXCEPTION [Error: SQLITE_CANTOPEN: unable to open database file] {
  errno: 14,
  code: 'SQLITE_CANTOPEN'`

Is there a way to fix it or it's not meant to work on ARM processors?

**Comment by kberg** [comment]
This is just your local machine? What machine is it?

**Comment by Carontes** [comment]
Yes it's my local RPi 4 8GB. I've also installed node(17.9.0) and npm(8.5.5) and running them

**Comment by bafolts** [comment]
We use sqlite3. Does that download the binary for arm64?

https://www.npmjs.com/package/sqlite3

**Comment by bafolts** [comment]
> Unfortunately, [node-pre-gyp](https://github.com/mapbox/node-pre-gyp) cannot differentiate between armv6 and armv7, and instead uses arm as the {arch}. Until that is fixed, you will still need to install sqlite3 from [source](https://www.npmjs.com/package/sqlite3#source-install).

**Comment by kberg** [comment]
Also note that our app works with Node versions 14 to 16.

**Comment by Carontes** [comment]
Downgraded node(16.19.1), now npm(8.19.3) and sqlite3(3.34.1) but still the same error

**Comment by bafolts** [comment]
You could try using postgres or local fs db versus the sql lite default.

If you provide POSTGRES_HOST or LOCAL_FS_DB when starting the server those databases should be used instead. Not sure why the default sqlite is failing but one of those other two should work.

**Comment by Carontes** [comment]
Sadly I don't have enough skill to do what you said because I don't know where to start from. If there's a guide for that or someone could provide a kind of guide I'll do that with pleasure

**Comment by kberg** [comment]
> Sadly I don't have enough skill to do what you said because I don't know where to start from. If there's a guide for that or someone could provide a kind of guide I'll do that with pleasure

Not that I can think of off the top of my head. If you are doing this just to play locally, then you can use the version that just stores files on disk.

Create a file on the top directory called `.env` with this one line

`LOCAL_FS_DB=on`

(If the file already exists, just add another line with the content I mention above.

You won't be using SQLite, and while `LOCAL_FS_DB` is ideally meant for development, you should be just fine.

**Comment by Carontes** [comment]
I created the .env file with the suggested line. I ran the commands
`npm install
npm run build
npm run start`
And if I reach the localhost:8080 the game appears but if I close the ssh window the game is not reachable. The Docker version doesn't work as well (the container doesn't start when I run the commands via ssh, that's normal). So is there a way to leave the server running? I prefer to run the game via Docker since I'm familiar with it

**Comment by kberg** [comment]
There's really not much support for Docker, though you might get some answers from the Discord. I'm going to close this issue because I suspect this is a Docker issue. Feel free to add comments or ask to reopen this if you think it will help.
