### ISSUE TITLE
Eco Sabotage did not consider the influences

### ISSUE THREAD

**Issue by Tafareeeeel** [terraforming-mars/terraforming-mars#5474]
After I produced 5 plants, the Eco Sabotage event was resolved. I had 2 influences, even so, I started the generation with only 3 plants

**Comment by kberg** [comment]
Link to game, please?

**Comment by Tafareeeeel** [comment]
https://terraforming-mars.herokuapp.com/player?id=pf112befdac2a

Em ter., 14 de mar. de 2023 às 22:22, Robert Konigsberg <
***@***.***> escreveu:

**Comment by kberg** [comment]
Which player were you in the game?

**Comment by kberg** [comment]
I tested the game with some extra debugging information:

```
Name     current influence max removed
DeMarchi 3         1       4   0
Navate   5         1       4   1
Gil      6         2       5   1
Tomas    5         0       3   2
```

And it looks like Eco Sabotage did everything correctly.

**Comment by Tafareeeeel** [comment]
> I tested the game with some extra debugging information:
> 
> ```
> Name     current influence max removed
> DeMarchi 3         1       4   0
> Navate   5         1       4   1
> Gil      6         2       5   1
> Tomas    5         0       3   2
> ```
> 
> And it looks like Eco Sabotage did everything correctly.

I was the blue one, and I had 2 party leaders
