### ISSUE TITLE
Special Design proxy card should be excluded from the Community deck?

### ISSUE THREAD

**Issue by puuj** [terraforming-mars/terraforming-mars#5480]
We started a game (on a personal server) that used the Community expansion. One of the cards dealt during the initial draft was the Special Design proxy (from commit #5445 ). The behavior was that players would see one fewer card in their draft selection, as the proxy card does not render. I'm not sure what the expected behavior is, but it seems that there should be some sort of logic to exclude Special Design proxy from the deck and then sub it in during the Playwrights action? I manually modified the game state to replace it with Special Design to prevent us from having to restart.

**Comment by kberg** [comment]
Yes, I need help fixing this, and I would love a copy of your game.

Is it on Heroku? Is it SQLite or Postgres?

**Comment by puuj** [comment]
Sent on Discord, but since I have a bunch of other stuff in my build it might not work automatically. I think the root cause is that if it's in the manifest, it ends up in the deck. Not sure if the filter or replace functionality is the right way to approach this, or there should be a class of cards that are known but not included in the Deck. This would be helpful for some other fun ideas like creating a "Happy Birthday" card that gets inserted into a player's hand on their birthday but otherwise does not exist in the deck.

**Comment by kberg** [comment]
Thanks for this. Fixed!
