### ISSUE TITLE
[Ares] Great Dam places two tiles

### ISSUE THREAD

**Issue by 167kamon** [terraforming-mars/terraforming-mars#5494]
The newly added Ares Great Dam places two tiles: one in an ocean reserved spot (as Protected Valley, Mohole Area, etc.), and one in the normal ocean-adjacent spot. I'm assuming that this was not intentional.
![great dam](https://user-images.githubusercontent.com/8723722/227606138-74ccac37-942f-4a9b-a473-b7d19497f1ae.png)

**Comment by kberg** [comment]
Thanks. This is now fixed.
