### ISSUE TITLE
In solo play, the initial cards drawn to set the neutral cities are removed from the game instead of discarded

### ISSUE THREAD

**Issue by andystager** [terraforming-mars/terraforming-mars#5507]
Unless I had really bad luck with the shuffle the second time through the deck, this is what I observed. Can you confirm?

**Comment by kberg** [comment]
Here's a solo game I set up to verify

![image](https://user-images.githubusercontent.com/413481/227758223-3977e579-f5e0-4a15-8232-78e4ddd3e80f.png)

Here's the discard pile:

![image](https://user-images.githubusercontent.com/413481/227758238-be41eb66-3810-4045-91d2-2afb3ac61d15.png)

**Comment by kberg** [comment]
And Underground City appeared later:

![image](https://user-images.githubusercontent.com/413481/227758556-2fef74b7-b82c-4005-aff1-ab85c5c7ee24.png)

**Comment by kberg** [comment]
Granted, I forced the situation by removing most of the project cards, but I think without more information, it sounds like, as you say, bad luck.

**Comment by andystager** [comment]
Thanks for checking. They took anti grav technology and I kept waiting for it to come up!
