### ISSUE TITLE
Ocean City Tile doesn't count as an Ocean for Estate Dealer Award

### ISSUE THREAD

**Issue by vscheff** [terraforming-mars/terraforming-mars#5520]
If the Ocean City should count as an Ocean, then I should have 4 tiles adjacent to Oceans.
![image](https://user-images.githubusercontent.com/98859370/228576050-2a39a2e4-4b70-4228-9efd-772b4bc73176.png)

However, the Estate Dealer shows me having only 3 tiles adjacent to Oceans:
![image](https://user-images.githubusercontent.com/98859370/228576415-4a349a42-32d6-4ced-953c-859df65a2633.png)

**Platform Information**
URL: https://terraforming-mars.herokuapp.com/spectator?id=s74f2074d450b
Player color: red
Step: 98
Version: a8b107c, built at Tue, 28 Mar 2023 14:23:55 GMT
Browser: Firefox 111

**Comment by nwai90** [comment]
I checked the game link, agree that there is no bug

**Comment by vscheff** [comment]
Do tiles not get double counted? Like if I have a tile next to two oceans, does that not count as 2?

**Comment by kberg** [comment]
Nope! It says "tile adjacent to ocean tiles"  not "most adjacencies between your tiles and oceans"

**Comment by kberg** [comment]
Gonna close this issue. Feel free to add comments if you have more questions.
