### ISSUE TITLE
Game ending, mismatch between rules

### ISSUE THREAD

**Issue by oja89** [terraforming-mars/terraforming-mars#5532]
Base Game rules state:
"When all three global parameters (ocean, tempe-
rature, and oxygen) have reached their goals, the game ends
at the end of that generation. "

However in Turmoil:
"The Solar Phase
The Solar phase takes place after the Production phase each generation:
STEP 1: Game End Check
Check the end game conditions: if temperature, oxygen, and oceans are all maxed out, the
game ends and final scoring begins with normal conversion of plants. No further steps in the
Solar phase are executed."

For example Hydrogen Processing Plant (Pathfinders) decreases Oxygen.
But not, if the Terraforming is completed.

Should the game ending condition check be moved to the end of generation?

**Comment by kberg** [comment]
I don't understand the problem. I think you're saying that Hydrogen Processing Plant removes one oxygen, which means during a generation global parameters were maximized, and then not.

But I don't know what the app is doing, and what you think it should be doing.

**Comment by oja89** [comment]
The app does not reduce oxygen if it has been maxed. 
I thought it was because of the status of terraforming (we already got the "Mars is terraformed" message.
So that rule part was not needed here.

But it seems that the app checks if it has been maxed, and if it is, doesn't allow decreasing it?

In /src/Game.ts, row 1119
```
  public increaseOxygenLevel(player: Player, increments: -1 | 1 | 2): undefined {
    if (this.oxygenLevel >= constants.MAX_OXYGEN_LEVEL) {
      return undefined;
```

It seems that there has been some earlier discussion about decreasing temp after it has been maxed. #3736

**Comment by kberg** [comment]
Does this help?

From the rulebook:
> If a global parameter is at its maximum, it may not be affected again for the rest of the game.

![image](https://user-images.githubusercontent.com/413481/229327528-0bce5a93-92d7-424e-a655-e7a4cd50f5b0.png)

**Comment by kberg** [comment]
I am closing this issue. Please feel free to add comments if you have anything to add or think it should be reopened.
