### ISSUE TITLE
CEO Lowell does not work if the CEO deck is empty/reshuffled during that action

### ISSUE THREAD

**Issue by pandavenger** [terraforming-mars/terraforming-mars#5546]
Please include:
1. Lowell fizzles and does not count as an action.
2. Start a new game with 4 CEOs and 5 Players. Use Lowell (used gen 7, but not sure if gen matters).
3. ![image](https://user-images.githubusercontent.com/1500800/229652260-76008b59-3fb1-47c1-98ef-7df062a12492.png)

URL: https://terraforming-mars.herokuapp.com/spectator?id=secd792a86185
Player color: yellow
Step: 383
Version: 648b01c, built at Sat, 01 Apr 2023 02:28:32 GMT
Browser: Chrome 111

**Comment by d-little** [comment]
Looks like CEO discard is not implemented.  Unchosen CEOs are always sent to the void.  That should be resolved, and then we can look at Lowell
