### ISSUE TITLE
CEO Van Allen is not gaining 3MC on opponent milestone claim

### ISSUE THREAD

**Issue by d-little** [terraforming-mars/terraforming-mars#5548]
URL: https://terraforming-mars.herokuapp.com/spectator?id=sb9d359a17c6
Player color: red
Step: 125
Version: 648b01c, built at Sat, 01 Apr 2023 02:28:32 GMT
Browser: Firefox 111

**Comment by kberg** [comment]
This was fixed last week. /whew!
