### ISSUE TITLE
Maria CEO might be broken

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#5576]
> Maria CEO seems to be broken. Used it. Selected Iapetus II. It didnt build a colony. Tried to build my own and it wouldnt let me select it. Cant trade with colony either.

https://discord.com/channels/737945098695999559/742721510376210583/1093977555930976376

**Comment by Vulptrix** [comment]
I think it's broken for any Colony that doesn't generate resource at the begining of the game.
Namely Enceladus, Titan, Miranda, Iapetus II, Venus.
