### ISSUE TITLE
Possible incompatibility between Collegium Copernicus and Cryo Sleep

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#5579]
https://discord.com/channels/737945098695999559/742826825922904225/1094691916253245450

>  My opponent canNOT trade with 2 data from Copernicus with Cryo-Sleep out. Is this meant to be doable? Posting here instead of bug channel cuz I'm not sure if this is intended. Seems like she should be able to use 2 data for a trade.

I have stored a local copy of the game. This should work as the reporter expected.

**Comment by kberg** [comment]
>  Update: Asked for a screenshot. Turns out it actually -does- let her trade. She just didn't know it because it still says "3 Data" instead of "2 Data." She successfully traded using 2 data by selecting that option. So this seems to be a very minor bug. Just the wrong number is displayed. 
[

**Comment by d-little** [comment]
Floating Launch Pad doesnt work that way; Cryosleep doesnt reduce the cost of resources on the card: https://boardgamegeek.com/thread/2120011/titan-floating-launch-pad-cryosleep-trade-free 

('Confirmed' by Fryx)

Im pretty sure in this instance the discounted cost on Copernicus from Cryo-Sleep is a bug itself!


![image](https://user-images.githubusercontent.com/2050250/230812354-8fbb70b1-1d73-4cc3-9785-030ce4a19802.png)

**Comment by kberg** [comment]
Copernicus does not discount Titan Floating Launch Pad as is. Is there a bug?

**Comment by d-little** [comment]
> Copernicus does not discount Titan Floating Launch Pad as is. Is there a bug?

No, it's working as intended.

But by extension why would Cryosleep discount the trade for Collegium Copernicus?  Cryosleep doesnt affect resources on cards, just the 'raw' trade resources (9MC, 3Energy, 3Titanium)
