### ISSUE TITLE
Error when claiming milestone

### ISSUE THREAD

**Issue by Negrolyte** [terraforming-mars/terraforming-mars#5582]
Occurred when trying to claim the Firestarter milestone in generation 4. The first click did nothing, then the second click triggered an error message. The milestone was claimed twice and no money was subtracted. Nothing appeared in the game log. Similar thing happened to the Generalist milestone when claimed by another player later. The 3rd milestone couldn't be claimed in the game.

See game https://terraforming-mars.herokuapp.com/the-end?id=p4a9b8ced6df4

![image](https://user-images.githubusercontent.com/20636101/230801740-615fb099-6cc6-4e1b-864d-b6fa80e7c9cd.png)

**Comment by kberg** [comment]
A fix is just now being submitted. Really sorry about this one.
