### ISSUE TITLE
Inventrix Company's global requirement ability bug

### ISSUE THREAD

**Issue by adamvarhegyi** [terraforming-mars/terraforming-mars#5583]
Hi,

I was playing **Inventrix**. This company **can change any requirement by 2 points in any direction.**

Mars was **-8 C° and I could play "TREES" card which have a -4 C°** or warmer requirement.

-8 +2 is only -6

I had NO OTHER cards which could manipulate requirement.

Is it counted double or something?

Here you can see the screenshot which I merged from 2 screens but they are from the very same turn:

![bug_1](https://user-images.githubusercontent.com/11267706/230890609-e1a15415-a533-401b-9b85-7c02c1166b8a.png)

**Comment by d-little** [comment]
Inventrix gives +/- 2 _steps_ for each global requirement.  The Temperature requirements are 2 degrees per step, so +-4 degrees
