### ISSUE TITLE
Event tags?

### ISSUE THREAD

**Issue by JamesinIA** [terraforming-mars/terraforming-mars#5594]
It appears that the event tags are not being counted in the summary bar.

URL: https://terraforming-mars.herokuapp.com/spectator?id=se8b547fed71
Player color: red
Step: 14
Version: a590cad, built at Wed, 12 Apr 2023 22:17:53 GMT
Browser: Chrome 111

**Comment by kberg** [comment]
That is correct. Events, once played, do not count in the game any further.
So, unless I'm missing something, there's no bug here.

**Comment by kberg** [comment]
https://github.com/terraforming-mars/terraforming-mars/wiki/Rulebooks
