### ISSUE TITLE
Did not count science tag 

### ISSUE THREAD

**Issue by rever86c** [terraforming-mars/terraforming-mars#5595]
URL: https://terraforming-mars.herokuapp.com/spectator?id=se925df2b87d8
Player color: red
Step: 9
Version: a590cad, built at Wed, 12 Apr 2023 22:17:53 GMT
Browser: Chrome 98

<img width="1194" alt="didn't count science tag #2" src="https://user-images.githubusercontent.com/83919168/231864654-9fc3bf5c-7801-4b04-8d10-5282b710e306.PNG">

Science tag from card Mars University or Invention Contest was not accounted.

Please refer to attached screenshot.

Thanks,
Rafal

**Comment by kberg** [comment]
Events are played and not used for the rest of the game, with the exception
of their VPs. Unless you have any other information, this doesn't look like
a bug to me.
