### ISSUE TITLE
minor: Hydrogen To Venus asks which card to add 0 floaters to

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#5598]
This question used to be skipped.

<img width="400" alt="Screen Shot 2023-04-16 at 8 07 38 AM" src="https://user-images.githubusercontent.com/934551/232322088-8d648a04-31a4-4881-8d78-b408a93d0ae5.png">

URL: https://terraforming-mars.herokuapp.com/spectator?id=s146d42f7db03
Player color: blue
Step: 36
Version: 0292905, built at Sun, 16 Apr 2023 04:39:12 GMT
Browser: Chrome 111

**Comment by kberg** [comment]
Thanks. A fix is out.
