### ISSUE TITLE
Represent used action cards without dimming the full card?

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#5603]
It's useful to know which action cards have already been used this generation. Currently that's shown by dimming the entire card. This has a couple negatives:

* when choosing where to put resources, it makes it look like you can't pick that card (but just removing that graying would lose useful information)
* I'm still hopeful that #1607 could one day happen, which would block on this

imho the ideal way to depict a used action card is to put a player-cube on it. That has the side benefit that when someone plays the physical game for the first time they will already know what they're supposed to do.

Second best would be something that dims only the actions themselves, or the full interior of the card, but doesn't dim the tags.

**Comment by kberg** [comment]
A player cube is a good idea. @d-little, your thoughts?

**Comment by kberg** [comment]
![image](https://user-images.githubusercontent.com/413481/235367963-ba023bb3-ed33-44ab-b1f1-dd14362cf05a.png)

**Comment by kberg** [comment]
I'd make the cube bigger, and maybe even place it up and to the right a bit. But this is worth adding to the experimental UI.

**Comment by kberg** [comment]
Wow, I didn't realize how simple that was going to be.

**Comment by d-little** [comment]
Im going to be perfectly honest:
* This 'fixes' something that doesnt exist
* It only introduces problems

> when choosing where to put resources, it makes it look like you can't pick that card (but just removing that graying would lose useful information)

Do we ever offer cards like this which cannot be picked? If so, that sounds like the root issue to me.  We shouldnt be offering up cards for a selection which cannot be selected

> A player cube is a good idea. @d-little, your thoughts?

This will only cause problems for my colourblind friends and obscures important information. 

The dimming was intuitive and obvious when I first started playing ("Oh, right, those are the cards I've already used. OK.").  Switching to a cube is the exact same situation, "A cube? Oh, thats resources so far? that's a card I've already used. OK." It's change for the sake of change, which will only introduce issues. 

We are not limited to the components a physical boardgame, why not throw text over the top. "USED" (I'm not a fan of that either, for the exact same reasons)

**Comment by kevinb9n** [comment]
Player cube was one idea. I like physicality a lot. If going with that, I at least think the cube would need to be bigger than shown, and imho the best place to put it would be wherever it's mostly likely to be on top of the red action arrows on the card. But if that idea creates an accessibility issue, throw it out for sure.

> Do we ever offer cards like this which cannot be picked? If so, that sounds like the root issue to me.

At least one example: standard projects. But I think my point is the same anyway? When asked to choose between 3 things and two are brightly lit and one is gray, I *think* that many users are going to first perceive that as that they can't choose the third. I'm not offering a proof of that or anything; you can just decide what you think.

> It's change for the sake of change

Well look, I just explain what I think is good about a change, and then you can disagree with it, that's all fine. I think "change for the sake of change" would be when no reasons are given in the first place...

Anyway though, I was also going to say that I think it matters what the devs think about #1607; if that's a no then this issue becomes pretty unimportant overall.

**Comment by HenAlm** [comment]
Alternative could be "tapping" ala MTG to graying out.

**Comment by kberg** [comment]
> Alternative could be "tapping" ala MTG to graying out.

That's an interesting idea actually, but this is the simplest thing to do.
