### ISSUE TITLE
Cartel not counting correct number of Earth Tags

### ISSUE THREAD

**Issue by vscheff** [terraforming-mars/terraforming-mars#5604]
1. Had a player play the card "Cartel", with the cards "Business Contacts" and "Market Manipulation" already in play. This should have increased their megacredits production by 3. However, "Cartel" only increased their megacredits production by 1.

2. Play "Business Contacts" and "Market Manipulation", then play "Cartel".

3.
![image](https://user-images.githubusercontent.com/98859370/233177654-68b71589-d746-46a3-8534-ec5b821af431.png)
![image](https://user-images.githubusercontent.com/98859370/233177785-4642d24c-25c2-41dc-9856-d97ac7d4853d.png)

4.
URL: https://terraforming-mars.herokuapp.com/spectator?id=s895cb32c4c5c
Player color: blue
Step: 88
Version: 0292905, built at Sun, 16 Apr 2023 04:39:12 GMT
Browser: Firefox 111

**Comment by vscheff** [comment]
Oh wow, I never knew this one. Good to know!

**Comment by kevinb9n** [comment]
If it makes you feel better it is the # 2 most common "rule I didn't know" in the world :-)
