### ISSUE TITLE
CEO Duncan incorrect VP after finished game

### ISSUE THREAD

**Issue by jottikus** [terraforming-mars/terraforming-mars#5646]
In a game where CEO Duncan is played, sometime after the game has finished the VP amount is changed.
Example
Duncan is played Gen 10 and thus nets -3 VP (7 - X, where X = 10).
This is reflected correctly during the game and when viewing the end screen directly on game end but then after some time it changes.

Here you can see that Duncan provides 8 VP even though it was played like described above.
![image](https://user-images.githubusercontent.com/132375571/235706257-c6f490e5-57da-4002-a240-33869ab7c8d1.png)

This also effects the players end game score and potential standings
https://terraforming-mars.herokuapp.com/the-end?id=p90b7914b40e3

**Comment by kberg** [comment]
Confirmed this was played at Gen 10. The issue is that `generationPlayed` is not serialized.
