### ISSUE TITLE
Issue with playing game with seed

### ISSUE THREAD

**Issue by soundofm11-github** [terraforming-mars/terraforming-mars#5661]
Just started a new game but used the seed from a game we just finished and the date for expiration on the game is 14 May (7 vice 14 days) not complaining just bringing it to your attention.  Think the site is awesome and thanks for all the work.  Game id is gb7e1ad6263dd.

**Comment by kberg** [comment]
Thanks for the report. Sorry about that one!

**Comment by kberg** [comment]
I've fixed the bug, but it won't change your game, I'm sorry.
