### ISSUE TITLE
Splice / Pharmacy Union interaction

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#5674]
In this scenario I've played Splice->Merger->PharmacyUnion, and now have *just* enough money to play a card that has both a science and microbe tag on it.

<img width="506" alt="Screen Shot 2023-05-09 at 9 49 25 AM" src="https://github.com/terraforming-mars/terraforming-mars/assets/934551/a64c28bb-3f9b-4510-9ab1-60bb06945f4d">

I think the player is supposed to be able to choose to lose the up-to-4-MC *before* gaining the Splice bonus, so in this example I would end up with 2 MC instead of 0.

**Comment by kberg** [comment]
I'm trying to work to a solution on this. It's tricky. Even without Merger, #3126 provides a similar problem, but it's not the same. I laid out a possible solution in https://github.com/terraforming-mars/terraforming-mars/issues/3126#issuecomment-2211247110

That proposal supports a more exhaustive solution than what is necessary here. So let's resolve less complicated case here.

In the merger case we could carve out a custom solution like "If I'm using Merger to combine PU to Splice, resolve them in the other order." But we can do a little better than that.

So how about this:

If the active player has PU, and a played card has microbes, and either
1. Splice is in play (anywhere)
2. Active player has GMO Contract
3. Fan expansion conditions (active player is Faraday, Greens policy 03 is in effect)
then push Pharmacy Union up to the front of action resolution order.

**Comment by kberg** [comment]
Turns out the solution was even simpler. Defer Splice correctly.
