### ISSUE TITLE
Cost reductions without the tag

### ISSUE THREAD

**Issue by HenAlm** [terraforming-mars/terraforming-mars#5690]
Not a bug, but enchancement suggestion.

There is the information on top of page for which tags you have and where cost reductions based on the tags you have. It only shows the tag if you have it, but not if you have a reduction. With Quantum Extractor you can get a reduction to space tags without having a space tag. If this happens the top part could show the tag even if you don't have them as you now have the cost reduction. I'll attach a screenshot of the situation.

![image](https://github.com/terraforming-mars/terraforming-mars/assets/3198073/095be6b1-950d-4cd4-8e7d-974b9500f582)

**Comment by HenAlm** [comment]
Maybe something like this to src/client/components/overview/PlayerTags.vue line 204

`         if (entry.count === 0 && entry.discount != 0) {
          if (this.hideZeroTags || concise) {
            return false;
          }
        }
`

**Comment by kberg** [comment]
Good observation. Would you like to make the change, or shall I?

**Comment by HenAlm** [comment]
I don't have testing setup so I don't know if that works, it was my guess :). So please go ahead.
