### ISSUE TITLE
Merger visualization problem 

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#5702]
When a player view shows two rows of corporations, the tags are offset.

![image](https://github.com/terraforming-mars/terraforming-mars/assets/413481/04331ce0-7aea-483b-8f33-ef438fdaab96)

In this example, the player with two corporations has a strange visual effect on the right side.

**Comment by Borbarad2** [comment]
This would be a nice solution for that issue:
![grafik](https://github.com/terraforming-mars/terraforming-mars/assets/105346182/0dfe3655-62a0-491b-84a5-ab9398402025)
