### ISSUE TITLE
Wrong russian plant converting description

### ISSUE THREAD

**Issue by Seerus** [terraforming-mars/terraforming-mars#5711]
In Russian localization, in the description of the action of converting plants to greenery, the requirement is "7 plants", not 8. At the same time, the action itself requires the presence of 8 plants. If Ecoline Corporation is selected, then the description requires 8 plants, but the correct 7 are used.
In other languages the description is correct.
Steps:
1. Select the Russian language of the game;
2. Accumulate 8 plants

Russian language:
![image](https://github.com/terraforming-mars/terraforming-mars/assets/5024232/92781eb7-54a8-46fa-8866-9b4f2df0bae0)

English language:
![image](https://github.com/terraforming-mars/terraforming-mars/assets/5024232/96067d7f-0479-4f05-b028-564900b3c4f6)

With selected "Ecoline" 
![Снимок экрана от 2023-05-21 10-59-14](https://github.com/terraforming-mars/terraforming-mars/assets/5024232/f2d33adb-4c60-41ba-9cfe-661ddec98a7b)

--------------------------------------------------
URL: https://terraforming-mars.herokuapp.com/spectator?id=sd2662d10a19b
Player color: red
Step: 12
Version: f6e0804, built at Mon, 15 May 2023 13:57:57 GMT
Browser: Chrome 110

**Comment by Borbarad2** [comment]
Hi,
I am not a russian speaking person.
Although I already found the mistake. Should I fixed it for you?

**Comment by tltneon** [comment]
Whoa. My bad, I'll fix it

**Comment by Borbarad2** [comment]
No problem for me.
Your pull request is correct and that will fix the issue.
After your pull request is merged that issue could be closed.
