### ISSUE TITLE
Improved Italian Translations

### ISSUE THREAD

**Issue by pocc** [terraforming-mars/terraforming-mars#5727]
A document by steenhabbo#2474 #ITALY. Please message this user in discord for clarifications. Formatted from https://docs.google.com/document/d/1Useg_38h_mMf33R_ph9dhS6zkqVdoABW86cRlD9_Gp8/mobilebasic

Note : *This is based on all the official cards that I possess.
Cards here are translated in Italy by Ghenos.
They haven’t translated yet “Anniversary Promo Pack 2021,2022,2023” so for those cards having them in English is correct.
If you want me to translate them how I would do it, I will do it in future.*

# Fixing to be done in translations :

## Venus Next:

- [x] **Dirigibles**: Dirigibili. Missing Italian description :
(Azione : aggiungi 1 Galleggiante ad una carta QUALUNQUE. Effetto : quando giochi un simbolo Venere, i Galleggianti collocati su questa carta possono essere usati per pagare, e ciascuno vale 3 M€)

- [ ] **Space Port Colony**: Colonia dello Spazioporto. Remove the ending “)” and add in the description :
PV per ogni coppia di Colonie in gioco)

- [x] **Capital**: Capitale. Missing italian description :
(Richiede almeno 4 tessere Oceano. Colloca questa tessera. Diminuisci la tua produzione di Energia di 2 livelli e incrementa la tua produzione di M€ di 5 livelli.)

- [x] **Commercial District**: Distretto Commerciale. Missing italian description :
(Piazza questa tessera. Diminuisci la tua produzione di Energia di 1 livello e incrementa la tua produzione di M€ di 4 livelli)

- [ ] **Viral Enhancers**: Amplificatori Virali. Missing italian description :
(Effetto : quando giochi una carta contenente un simbolo Pianta, Microbo o Animale, inclusa questa, ottieni una Pianta oppure aggiungi 1 Risorsa A QUELLA CARTA)

- [ ] **Spin-off Department**: Dipartimento Spin-Off. Missing italian description :
(Effetto : QUANDO GIOCHI UNA CARTA CON UN COSTO DI PARTENZA MAGGIORE O UGUALE A 20 M€, pesca una carta)

- [ ] **Natural Preserve**: Riserva Naturale. Missing italian description :
(Il livello di Ossigeno deve essere minore o uguale al 4%. Colloca questa tessera in modo che NON SIA ADIACENTE AD ALCUNA ALTRA TESSERA. Incrementa la tua produzione di M€ di 1 livello)

- [ ] Flussi di lava. Missing italian description :
(Aumenta la Temperatura di 2 livelli e colloca questa tessera IN UNA DELLE SEGUENTI POSIZIONI : THARSIS THOLUS, ASCRAEUS MONS, PAVONIS MONS, ARSIA MONS)

- [ ] Towing a Comet. To translate the title in :
TRAINARE UNA COMETA

- [ ] PUNTAMENTO ALLE COMETE. To fix the title in : PUNTARE ALLE COMETE
Also change the description in :
(Azione : spendi 1 risorsa Titanio per aggiungere 1 risorsa Asteroide ad una QUALUNQUE CARTA o rimuovi 1 risorsa Asteroide da questa carta per poter collocare una tessera oceano)

- [ ] Self-Replicant Robot. To translate the title in :
ROBOT AUTO-REPLICANTI

- [ ] Idrogeno Importato. Cause of the word “oppure” which is really long “3 🍃” gets cut.
In this scenario, and also in the other cards I suggest to use “or” like in English.
In italian there is also the word “o” which is similar, but it could be both inclusive and exclusive, so it could create confusion. So “OPPURE” -> “OR” would fix the problem.

Otherwise people, like me, could lose a game just because they thought to spend a single energy resource, but it was 2 which were needed.

Same thing has to be done with the blue promo card : Struttura di Bio stampaggio

![image](https://github.com/terraforming-mars/terraforming-mars/assets/10995145/b5c89acb-99c2-45d5-84aa-2522827e14c0)
![image](https://github.com/terraforming-mars/terraforming-mars/assets/10995145/e4b1a493-a968-4ded-904a-182b9bb4a19c)

- [ ] Generatori di campo magnetico. Missing italian description :
(Diminuisci la tua produzione di energia di 4 livelli e incrementa la tua produzione di Piante di 2 livelli. Incrementa il tuo TT di 3 Livelli)

- [ ] Generatori di campo magnetico. Missing italian description below :
Azione : ottieni 1M€ per ogni Animale su questa carta)

- [ ] Methane from Titan. To translate the title in : METANO DA TITANO

- [ ] Tute anti-radiazioni. Missing italian description below :
(Richiede che ci siano in gioco almeno 2 Città. Incrementa la tua produzione di M€ di 1 livello)

- [ ] Città a cupola di campo. To fix the title in : CITTȦ PROTETTA DA CAMPO MAGNETICO

- [ ] Infrastrutture per l’energia. Missing italian description below :
(Azione : spendi un qualunque ammontare di Energia per ottenere la medesima quantità di M€)

- [ ] Area Mohole. Missing italian description below :

(Incrementa la tua produzione di Calore di 4 livelli. Colloca questa tessera SU UN’AREA RISERVATA ALLE TESSERE OCEANO)

- [ ] Stabilimento neutralizzatori. To fix the title in : STABILIMENTO NEUTRALIZZATORE

- [ ] Ripulire il luogo dello schianto. Fix the title : SISTEMAZIONE DEL SITO DELL’IMPATTO

- [ ] Detonazioni sotterranee. Missing italian description below :
(Azione : spendi 10 M€ per incrementare la tua produzione di Calore di 2 livelli)

- [ ] Zona Nucleare. Missing italian description below :
(Colloca questa tessera e incrementa la Temperatura di 2 livelli)

- [ ] Area estrazione mineraria. Missing italian description below :

(Colloca questa tessera su un’area contenente un bonus di piazzamento di Acciaio o Titanio, adiacente ad un’altra delle tue tessere. Incrementa la tua produzione di quella Risorsa di 1 livello)

- [ ] Asteroide ammonizzato aerofrenato. Missing italian description below :
(Aggiungi 2 Microbi ad UN’ALTRA carta. Aumenta la tua produzione di Calore di 3 livelli e la tua produzione di Piante di 1 livello)

- [ ] Termofili. Missing italian 2nd description below :
(Azione : Scarta 2 Microbi collocati su questa carta per incrementare Venere di 1 livello)

- [ ] Water import from europa. Fix the title : IMPORTAZIONE D’ACQUA DA EUROPA

- [ ] Impatti direzionati. Fix the title : DISPOSITIVI D’URTO GUIDATI

- [ ] Misurazioni sottocrosta. Fix the title : MISURAZIONI SOTTO-CROSTA

- [ ] Psicrofili. Missing italian 2nd description below :
(Effetto : quando giochi una carta con un simbolo Pianta, i Microbi collocati qui possono essere utilizzati come se valessero 2 M€ ciascuno)

- [ ] Cometa per venere. Missing italian description below :
(Incrementa Venere di 1 livello. Rimuovi fino a 4 M€ da un giocatore che abbia in gioco un simbolo Venere)

- [ ] Centrale IA. Missing italian description below :
(Azione : pesca 2 carte)

- [ ] Scudo magnetico. Missing italian description below :

(Richiede 3 simboli Potenza. Incrementa il tuo TT di 4 livelli)

- [ ] Search for life. Fix the title : RICERCA DELLA VITA
+ remove the line “Oxygen must be…” which is already above it in italian

- [ ] Scavo asteroidale. Fix the title : ESCAVAZIONE DEGLI ASTEROIDI

- [ ] Diritti di estrazione mineraria. Missing italian description below :
(Colloca questa tessera su un’area con un bonus di piazzamento di Acciaio o di Titanio. Incrementa la corrispondente Produzione di 1 livello)

- [ ] Importazione di nutrienti. Fix the title : SOSTANZE NUTRITIVE IMPORTATE

—---------------------------------------------------------------------------------------------------------------

# PRELUDES

- [ ] Rete di ricerca. Fix the title : NETWORK DI RICERCA

The 5 anniversary Prelude included in Promo Pack 2022 haven’t been translated yet so, as I said in the beginning, I could translate them myself and, when posted official by ghenos, update you and fix them)

—---------------------------------------------------------------------------------------------------------------

# CORPORATIONS

In all the corporations there are written : EFFECT or ACTIONS in blue.
This has to be fixed with “EFFETTO” AND “AZIONE”

Valley Trust. Missing italian description below :

(Effetto : quando giochi una carta con un simbolo Scienza, la paghi 2 M€ in meno)

Astrodill. Missing italian description above :

(Inizi con 35 M€ e 3 risorse Asteroide su questa carta)

Polyphemos. Missing italian description above :
(Effetto : quando acquisti una carta da aggiungere alla tua mano, inclusa la mano iniziale, la paghi 5 M€ invece di 3 M€)

Aridor : Colony should be called COLONIA (but it’s not that important if hard to do it)

Splice : It’s impossible to read the first part because it’s covered by the below one.
Same with Pharmacy Union

Factorum. Missing italian description below :
(Azione : incrementa di 1 livello la tua produzione di Energia SE NON POSSIEDI RISORSE ENERGIA, oppure spendi 3M€ per pescare una carta con un simbolo Edificio)

Arcadian Communities. Fix the title in COMUNITÀ ARCADICHE
Also in the description all the time is used the word “COMUNITÀ” is never written correctly. It has been used A + ‘ instead of À

Credicor. Missing italian description below :
(Effetto: dopo aver pagato per una carta o per un progetto Standard con un costo base maggiore o uguale a 20 M€, guadagni 4 M€)

Mons Insurance. Missing italian description :
(Inizi con 48 M€. Incrementa la tua produzione di M€ di 4. TUTTI GLI ALTRI GIOCATORI DIMINUISCONO LA PROPRIA PRODUZIONE DI M€ DI 2. L’EFFETTO SPECIFICATO QUI SOTTO, IN QUESTO CASO, NON VIENE ATTIVATO)
Effetto : quando un giocatore causa ad un altro giocatore una diminuzione di produzione o una perdita di risorse, paga alla “vittima” 3 M€; se non li possiedi, paga la cifra più alta possibile)

Tharsis Republic. Missing italian description above  :

(Inizi con 40 M€. Come prima azione del gioco, posiziona una tessera Città)

Lakefront Resorts.  Missing italian description :

(Effetto : quando viene collocata una tessera Oceano, incrementa la tua produzione di M€ di 1 livello. Effetto : il tuo bonus di Posizionamento per la collocazione di tessere adiacenti agli Oceani è di 3 M€ invece di 2 M€)

_____________________________________________________________________

# Turmoil

## PASSING TO TURMOIL :

Movimento della Diaspora. Missing italian description :
(Richiede che i Rossi siano al Governo, o che tu abbia almeno 2 Delegati all’interno di quel Partito. Ottieni 1M€ per ogni simbolo Gioviano in gioco)

Political alliance. Fix the name in : Alleanza Politica

________________________________________________________________________

## GLOBAL EVENTS (TURMOIL)

Almost every name hasn’t been translated :

Mud slides -> SLAVINE DI FANGO
Miners on strike -> MINATORI IN SCIOPERO

Improved Energy templates -> MODELLI ENERGETICI MIGLIORATI

Homeworld support -> SUPPORTO DEL PIANETA NATALE

Global Dust Storm -> TEMPESTA DI SABBIA GLOBALE

Generous funding -> FINANZIAMENTI GENEROSI

Volcanic eruptions -> ERUZIONI VULCANICHE

War on Earth -> GUERRA SULLA TERRA

Successfull organism -> ORGANISMI BEN RIUSCITI

Strong society -> SOCIETÀ FORTE

Sponsored project -> PROGETTI SPONSORIZZATI

Election -> ELEZIONE

Eco Sabotage -> ECO-SABOTAGGIO

Dry deserts -> DESERTI ARIDI

Solarnet shutdown -> ERUZIONE SOLARE

Riots -> RIVOLTE

Revolution -> RIVOLUZIONE  

Red influence -> INFLUENZA ROSSA  

Productivity -> PRODUTTIVITÀ

Paradigm Breakdown -> ROTTURA DEL PARADIGMA

Solarnet shutdown ->  ARRESTO DELLA SOLARNET

Pandemic -> PANDEMIA

Scientific community -> COMUNITÀ SCIENTIFICA

Snow cover -> MANTO NEVOSO

Diversity -> DIVERSITÀ

Industria mineraria di asteroidi -> ATTIVITÀ MINERARIA SU ASTEROIDE

Acquifier released by public council -> FALDA ACQUIFERA RILASCIATA DAL CONSIGLIO PUBBLICO

Venus infrastructure -> INFRASTRUTTURA SU VENERE

Microgravity Health Problems -> PROBLEMI DI SALUTE DA MICROGRAVITÀ

Jovian Tax Rights -> SGRAVI FISCALI SU GIOVE

Corrosive Rain -> PIOGGIA CORROSIVA

Cloud Societies : SOCIETÀ DELLE NUVOLE

Spin-Off products : PRODOTTI SPIN-OFF

—-----------------------------------------------------------------------------------------------------------

![image](https://github.com/terraforming-mars/terraforming-mars/assets/10995145/daf28463-2cc4-4f23-aa45-4cb9dd2d7174)

In the main menu “How to play” -> COME GIOCARE
—----------------------------------------------------------------------------------------------------------

To HEROKUAPP PROGRAMMER. A document by steenhabbo#2474 #ITALY
Simone Migliarini, Pisa.

**Comment by pocc** [comment]
I'm going to focus on just the promos for Italian first.

**Comment by kberg** [comment]
What's the next step here?

**Comment by kberg** [comment]
I'm going to close this bug, @pocc, happy to reopen it as you need.
