### ISSUE TITLE
Game does not start

### ISSUE THREAD

**Issue by Tafareeeeel** [terraforming-mars/terraforming-mars#5785]
The game says it's not my turn to play, but in turn order I'm the current player

https://terraforming-mars.herokuapp.com/player?id=p5d30957ddc99

**Comment by kberg** [comment]
I won't be able to look at it for several hours, but I will.

**Comment by kberg** [comment]
Yellow has not chosen their cards. Seems like it's working as intended. Warning, though, if the server restarts, everybody might have to select their card again. It's one of those things the app doesn't do well.
