### ISSUE TITLE
can t use titane to play a card

### ISSUE THREAD

**Issue by benmacbeg** [terraforming-mars/terraforming-mars#5801]
I can't play my card satellite because I can't use my titane

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s3e45739a808d",
  "color": "blue",
  "step": 364,
  "version": "b40f402",
  "builtAt": "Fri, 16 Jun 2023 05:39:53 GMT",
  "browser": "Firefox 102",
  "language": "fr",
  "experimental_ui": false
}

**Comment by kberg** [comment]
I can't reproduce the issue.
