### ISSUE TITLE
Default selection is pass turn rather than use played action cards

### ISSUE THREAD

**Issue by Vesperindustrial** [terraforming-mars/terraforming-mars#5803]
As of at least a few days ago, the default selection action is to finish/pass your turn where previously it selected by default to use an action from a played action card. This makes it far too easy to accidentally pass your turn when you wanted to use actions. Personally have done this unintentionally for multiple games already.

I can see the annoyance that was probably originally presented when you no longer want to use action cards. A suggestion from me would be you should be able to have an ability to mark them that way instead or something and dim them and if they are all dimmed THEN have the default not to be on that option.

This was tested on solo mode.

**Comment by kberg** [comment]
Click the gear in the corner of the app, and click "Report A Bug." Can you copy the text box into this bug, please?

**Comment by Vesperindustrial** [comment]
{
  "url": "http://terraforming-mars.herokuapp.com/",
  "version": "b40f402",
  "builtAt": "Fri, 16 Jun 2023 05:39:53 GMT",
  "browser": "Firefox 114",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Thanks for the bug report. I've fixed it.

**Comment by Vesperindustrial** [comment]
That was quick, thank you!
