### ISSUE TITLE
No valid place to move Gagarin Mobile Base

### ISSUE THREAD

**Issue by tdragon-fp** [terraforming-mars/terraforming-mars#5815]
I'm asked to move my Gagarin Mobile Base after a Metallic Asteroid is placed by my opponent. The only valid place is the middle of the map, but when trying to move the base there I got an error
![image](https://github.com/terraforming-mars/terraforming-mars/assets/16756941/f333a608-0d46-4e14-b02e-0269f460da8d)

I am unable to continue the game.

Bug Report Dialog:
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=se4a026e513af",
  "color": "yellow",
  "step": 154,
  "version": "ea5b331",
  "builtAt": "Sat, 17 Jun 2023 18:11:39 GMT",
  "browser": "Chrome 114",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Thanks, this should be fixed, though possibly not for your game.
