### ISSUE TITLE
When selected card is changed, reserveUnits are not updated. 

### ISSUE THREAD

**Issue by puuj** [terraforming-mars/terraforming-mars#5840]
Found this bug in a game. The player has a card with reserved titanium as the first in the sort order. Switching to a different card preserves the reserved titanium preventing them from spending all their titanium. Solution would be to add
`this.reserveUnits = this.card.reserveUnits ?? Units.EMPTY;` in the cardChanged() callback.

https://github.com/terraforming-mars/terraforming-mars/blob/a98b5e3dbf9b74e8f6ab1186826e5e1aeeb2817c/src/client/components/SelectProjectCardToPlay.vue#L267

**Comment by kberg** [comment]
Fixed.
