### ISSUE TITLE
Tagless-cards count is confused, probably by Pharmacy Union

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#5847]
Here's all my played cards

<img width="1067" alt="Screen Shot 2023-07-10 at 1 19 56 PM" src="https://github.com/terraforming-mars/terraforming-mars/assets/934551/1c4d1c58-2187-4a89-9ac7-ebf35053eb03">

Here's my dashboard

<img width="707" alt="Screen Shot 2023-07-10 at 1 17 34 PM" src="https://github.com/terraforming-mars/terraforming-mars/assets/934551/dbf69163-7ff0-44c3-9504-95bdda9c4dc0">

I count only 2 tagless cards, not 3. I suspect the flipped PharmU is being counted as one of them?

(This might be pilot error, but if it's a real bug then it's the first real bug found by solarnet!)

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s26bbad4e2ece",
  "color": "blue",
  "step": 9,
  "version": "b675f6e",
  "builtAt": "Fri, 07 Jul 2023 02:03:44 GMT",
  "browser": "Chrome 114",
  "language": "en",
  "experimental_ui": true
}

**Comment by kberg** [comment]
You are correct. Good job, Solarnet!

**Comment by kevinb9n** [comment]
Thanks! It's such a small thing, but still, I've dreamed of this day :-)
