### ISSUE TITLE
-2 adjacency "bonus" when player has insufficient funds

### ISSUE THREAD

**Issue by DocmoPS** [terraforming-mars/terraforming-mars#5855]
**Game ID g4a6657f70247** (pertinent expo: ares)

### Observe that I have 0 gold and am trying to place this card.

> ![image](https://github.com/terraforming-mars/terraforming-mars/assets/67963679/fc15c6a6-cca2-4115-b468-1bc7bb89abd0)

### Observe also that my only legal space to place this card is next to my other card which requires adjacency "bonus" of -2 gold (which I don't have).

> ![image](https://github.com/terraforming-mars/terraforming-mars/assets/67963679/94f20be0-d00a-49dd-961f-724ab00ce9fb)

**Comment by Borbarad2** [comment]
Old and known bug, never solved. But well known.

**Comment by kberg** [comment]
Thanks for the report. This should now be fixed.
