### ISSUE TITLE
Promo Card "Double Down" fizzled?

### ISSUE THREAD

**Issue by r4bBit-s** [terraforming-mars/terraforming-mars#5859]
Started a new game and played the card "Double Down" in the prelude phase, but it didn't work properly. 
The game log just says: "DOUBLE DOWN fizzled. [Player] gains 15 M€."
Did I misunderstand the card? Or do i have to play the other card first? I thought i have to play double down first...? Is production not a "direct effect"? I am confused 😅
<img width="439" alt="TM_game_log" src="https://github.com/terraforming-mars/terraforming-mars/assets/134416776/7ec3060c-5589-40e8-90e5-9abc587cf3dd">
<img width="208" alt="TM_double_down_card" src="https://github.com/terraforming-mars/terraforming-mars/assets/134416776/b49e71f1-dc7e-4c7d-bb7d-4b356e00e364"> 
<img width="210" alt="TM_dome_farming_card" src="https://github.com/terraforming-mars/terraforming-mars/assets/134416776/10d6c6fa-a298-47fa-b9e3-dc44d86a6abf">

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s9a40e0848086#actions",
  "color": "yellow",
  "step": 17,
  "version": "b675f6e",
  "builtAt": "Fri, 07 Jul 2023 02:03:44 GMT",
  "browser": "Safari 16",
  "language": "en",
  "experimental_ui": false
}

**Comment by kevinb9n** [comment]
Ouch. This might bite someone occasionally but I do think it has to work this way, since as far as I understand it, whenever you'd _rather_ have 15 MC than to double your other prelude you're allowed to do it in this order.

**Comment by kberg** [comment]
Agreed. Still, a warning seems merited.
