### ISSUE TITLE
Biolab science tag doesn't count to total

### ISSUE THREAD

**Issue by Schmittma** [terraforming-mars/terraforming-mars#5867]
See attached images for the cards that were played. This was initially found due to a player not being able to play "Tectonic Stress Power" which requires 2 science tags.

Cards played:
![image](https://github.com/terraforming-mars/terraforming-mars/assets/20574467/1271a8c2-e7ae-495a-ad10-f653c1b273c6)

Resource bar also only shows one science tag while all others seem to match:
![image](https://github.com/terraforming-mars/terraforming-mars/assets/20574467/dcc97ec2-0525-4a08-a306-03ae4de10366)

**Comment by kberg** [comment]
It's not Biolab, it's Invention Contest. Event tags are not counted.
Everything is working as expected.
