### ISSUE TITLE
forced to decrease your own production (visual issue)

### ISSUE THREAD

**Issue by PranavKoduri** [terraforming-mars/terraforming-mars#5871]
1) The card "Power Supply Consortium" from Corporate Era forces you to decrease your own energy production if all your opponents have 0 energy production. It increased your own production, but it didn't decrease it after. It just makes it a visual bug, but it would be helpful to have an option to "decrease nobody" to not cause confusion.
2) You should be able to just not decrease any energy production instead of forcing to decrease your own.
3)
Before:
![image](https://github.com/terraforming-mars/terraforming-mars/assets/61212259/e202ed9d-8cb4-4ffa-a698-f9db0d606b82)
![image](https://github.com/terraforming-mars/terraforming-mars/assets/61212259/abdff587-90e0-49bd-907e-2d85a24d5624)

After:
![image](https://github.com/terraforming-mars/terraforming-mars/assets/61212259/a9170e61-8092-4363-abab-0d7084bc5a7a)
![image](https://github.com/terraforming-mars/terraforming-mars/assets/61212259/85eec4bc-1cb6-47cd-8742-a82c23096d1a)

4)
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s8820411973a2#board",
  "color": "red",
  "step": 89,
  "version": "aaa8209",
  "builtAt": "Sun, 30 Jul 2023 02:56:09 GMT",
  "browser": "Chrome 115",
  "language": "en",
  "experimental_ui": false
}

**Comment by d-little** [comment]
This is working as intended.

Production changes are mandatory, not optional.  Even if you're the only one with that production.
![image](https://github.com/terraforming-mars/terraforming-mars/assets/2050250/cb33e48e-d22a-4aa2-b285-66650b7c4b5b)

Removing resources is optional, but not the Production of resources.

**Comment by kberg** [comment]
Oh hi. I thought I added a comment here. You're right. But also I'm working on how to provide a visual cue here. So I'm gonna leave this open for now.

**Comment by kberg** [comment]
This is now fixed. 
![image](https://github.com/terraforming-mars/terraforming-mars/assets/413481/9f51ecbe-2e32-4dfd-bd11-d4e97b75814d)
