### ISSUE TITLE
Stuck Mars Game

### ISSUE THREAD

**Issue by Shaydie** [terraforming-mars/terraforming-mars#5879]
We are playing Mars and one of us played Gagarin Mobile Base. I'm trying to put the last tile down and it's freezing up because he is on it and there's nowhere for him to move away.

http://terraforming-mars.herokuapp.com/player?id=p570a17ce39e4#cards
![marsgamestuck](https://github.com/terraforming-mars/terraforming-mars/assets/112154905/124d415e-a957-4ea2-bab7-a8437ff46f01)

**Comment by kberg** [comment]
I unstuck the game. Thanks for the tip.

**Comment by Shaydie** [comment]
Thank you! 🙏

Sent from my iPhone

On Aug 23, 2023, at 7:37 AM, Robert Konigsberg ***@***.***> wrote:

﻿

I unstuck the game. Thanks for the tip.
