### ISSUE TITLE
Power supply consortium was played without anyone having energy production

### ISSUE THREAD

**Issue by Schmittma** [terraforming-mars/terraforming-mars#5882]
The card power supply consortium was played while no person in the game had energy production. Additionally, this gave the player who played the card an energy production.

The game log from the game below shows the player "Der Jochen" acquiring 2 energy production until generation 5. There he played underground city which removed the 2 energy production. Followed up by playing power supply consortium, which did not remove any energy production from anyone. The player was then able to use this energy production in generation 6.

As far as my understanding goes, production changes are mandatory.

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=sbfa0f6301f58",
  "color": "pink",
  "step": 356,
  "version": "c722005",
  "builtAt": "Tue, 22 Aug 2023 14:37:33 GMT",
  "browser": "Chrome 116",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Huh. I think you're right. I don't know if it ever worked that way.

**Comment by kberg** [comment]
But huh, this is interesting. According to the FAQ:
https://github.com/kberg/terraforming-mars-faq/wiki#power-supply-consortium-160-ce
"While
the production effects of the card are MANDATORY, they can be resolved in
any order. As such, if no player has energy production, this card can still
be played to raise your own energy production and then reduce it again
(i.e., if you required the tag, etc..)"

**Comment by kberg** [comment]
So, here's what happens when nobody has production -- nobody loses production, and player will gain 1 energy production.

What WILL happen ongoing is: active player will gain production, and then immediately lose that production.
