### ISSUE TITLE
Red Spot Observatory drawing cards from other players hands

### ISSUE THREAD

**Issue by pandavenger** [terraforming-mars/terraforming-mars#5886]
Please include:
1. Among other cards, an Earth Elevator and Cartel were drawn from other players hands
2. Unfortunately, the players of this game simply asked me to use my github account to report, and did not provide clear reproduction steps.
3. Any screenshots
4. {
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s39e49ca398ea&noredirect=",
  "color": "blue",
  "step": 648,
  "version": "c722005",
  "builtAt": "Tue, 22 Aug 2023 14:37:33 GMT",
  "browser": "Chrome 116",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Hi. I've read this a couple of times, and this just doesn't look possible. Can you describe in detail what you saw versus what you heard, and so on?

**Comment by kberg** [comment]
I'm going to close this. I'll still get updates, but given how unlikely I think this is, it's a fine choice. I'll reopen if there's enough evidence.
