### ISSUE TITLE
Anti-desertification shows 5 MC but gives 3 MC

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#5924]
EDIT: the starting money at bottom is accurate; it really did give only 3 MC. I had first reported this like it was a problem with the starting money calculator.

<img width="300" alt="image" src="https://github.com/terraforming-mars/terraforming-mars/assets/934551/85862e5d-ae45-4d31-a1f6-98e7279a127d">

**Comment by kberg** [comment]
Thanks, this is fixed.
