### ISSUE TITLE
Buying "Air scrapping" standard project with Aurorai softlocks the game

### ISSUE THREAD

**Issue by Schmittma** [terraforming-mars/terraforming-mars#5936]
Stuck in the following screen after trying to purchase Air Scrapping with Aurorai corporation:
![image](https://github.com/terraforming-mars/terraforming-mars/assets/20574467/5a528c31-4166-441d-9f46-1dfd8d62424b)

At the time i had 0 Money but 7 data on the Aurorai Corporation:
![image](https://github.com/terraforming-mars/terraforming-mars/assets/20574467/754cdc8b-7de1-4ec2-8b05-5c71539da8f8)

Reloading the page does not resolve this issue.
This issue can be seen by entering my player with the following game link: 
https://terraforming-mars.herokuapp.com/player?id=p8d5dc64c58c2

Game information:
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s6debf2adaa21#cards",
  "color": "pink",
  "step": 12,
  "version": "1e75772",
  "builtAt": "Tue, 12 Sep 2023 01:57:20 GMT",
  "browser": "Chrome 116",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
I'll look into the bug. In the meantime, let's see if you can continue (I
did a soft reset.)
