### ISSUE TITLE
Palladin Shipping (corporation) effect applying to all players

### ISSUE THREAD

**Issue by Erostal** [terraforming-mars/terraforming-mars#5960]
Hello,

The Palladin Shipping corporation has an effect of "Effect: When you play a space event, gain one titanium". Most effects only act for the player who has played the card (unless otherwise stated), but this effect seems to affect all players, e.g. when a player who isn't Palladin plays a space event, they get a titanium. I'm assuming this is an error, or if not I'd recommend the text on the card be updated to specify this.

Cheers,
-Rob

PS - thanks for making this website, my friend group loves it (and making it free!). Looking forward to trying more of the fan made expansions you've added

**Comment by Erostal** [comment]
If you want the game id to verify, the game id was gcb3a1c0a1f40

**Comment by kberg** [comment]
Huh. This makes no sense. But thanks, I'll keep an eye on it.

**Comment by kberg** [comment]
Ah, I see it. Fixing now.
