### ISSUE TITLE
Two Bugs Related to Beta Prelude 2 Corporation "Sagitta"

### ISSUE THREAD

**Issue by nabby101** [terraforming-mars/terraforming-mars#5970]
Hello,

Just reporting two bugs related to one of the new corporations, Sagitta.

The text on the card reads: "When you play a card with no tags, gain 4 MC."
My understanding is that it should include itself, and the player should gain 4 MC when playing the corporation, similar to Vitor and Manutech. However, that is not the current way it works on here.

The corporation also draws a card with no tags, but the card I drew in my most recent game was Diversity Report, a card with an event tag.
Notably, cards with an event tag and no other tags work correctly when played (gaining 1 MC, not 4).

Thanks for all the work you do!

Bug Report Dialog:

  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s91e7065b51ab",
  "color": "orange",
  "step": 17,
  "version": "32a6c23",
  "builtAt": "Mon, 18 Sep 2023 04:24:20 GMT",
  "browser": "Firefox 117",
  "language": "en",
  "experimental_ui": false

**Comment by kberg** [comment]
Thanks for the report.

> The text on the card reads: "When you play a card with no tags, gain 4 MC."

Text usually says "including this card" when the card being played applies, so my guess is this doesn't apply.

> The corporation also draws a card with no tags, but the card I drew in my most recent game was Diversity Report, a card with an event tag.

This event tag ruling is really something. OK, I'll look into this.

**Comment by kberg** [comment]
Yeah, gonna fix it. Also raised this at https://boardgamegeek.com/thread/3154781/article/42974332#42974332

**Comment by nabby101** [comment]
> Thanks for the report.
> 
> > The text on the card reads: "When you play a card with no tags, gain 4 MC."
> 
> Text usually says "including this card" when the card being played applies, so my guess is this doesn't apply.

I think "including this" is supposed to be part of the text. I went back and looked at the image of the card revealed, and there's a big space that's covered up between:
"When you play a card with no tags" ------------------ "gain 4 MC."

The space looks about the right size, and I can't think of anything else that would be written in the middle of that sentence.

![image](https://github.com/terraforming-mars/terraforming-mars/assets/12789345/c619d145-4c2f-4494-87ee-eb97c68aab3c)

**Comment by kberg** [comment]
I'll buy that.

**Comment by kevinb9n** [comment]
Good fix. There was a card "Diaspora Movement" that did forget to include "including this", and it was ruled that it's supposed to include itself anyway because that's just how the game mechanics work. So those 2 words are just reminder text.
