### ISSUE TITLE
[Prelude2] Focused Organization not discarding card

### ISSUE THREAD

**Issue by bobertstark** [terraforming-mars/terraforming-mars#5989]
Playtesting the beta Prelude2 and noticed whenever I used the prelude Focused Organization action, the selected card was not discarded from hand

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s8c6b76b6b986",
  "color": "red",
  "step": 6,
  "version": "3e89d4d",
  "builtAt": "Wed, 20 Sep 2023 03:41:39 GMT",
  "browser": "Chrome 116",
  "language": "en",
  "experimental_ui": false
}

**Comment by kevinb9n** [comment]
Seconded

**Comment by kberg** [comment]
Ah, I see it. Going to use this as an opportunity to clean things up.

**Comment by bobertstark** [comment]
Awesome, thanks for the quick fix!
