### ISSUE TITLE
Spire seems to not add a resource to itself

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#5990]
<img width="646" alt="image" src="https://github.com/terraforming-mars/terraforming-mars/assets/934551/45e749ab-de72-4c3a-9aa6-a565dc02bc49">

<img width="518" alt="image" src="https://github.com/terraforming-mars/terraforming-mars/assets/934551/09407aed-b170-45ac-896e-7c2810e83244">

Expected: 2 resources on Spire, one being from playing Spire itself.

**Comment by kberg** [comment]
Thanks. Fixing momentarily.
