### ISSUE TITLE
Mars Nomads gave immediate bonus

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#6009]
I played Mars Nomads and placed the yellow cube. I was immediately given the placement bonus for the map area I put the cube on.

<img width="389" alt="image" src="https://github.com/terraforming-mars/terraforming-mars/assets/934551/61645c0c-c581-467e-ab5b-bec1283caace">

It should only give that bonus when moving the cube with the card's action.

**Comment by kberg** [comment]
Thanks, I missed that.
