### ISSUE TITLE
Mars Nomads not giving ocean-adjacency bonuses

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#6010]
When taking the Mars Nomads action it should be "as if placing a special tile there", so ocean adjacency bonuses should be paid out as well (and whatever else like from Ares tiles).

**Comment by kberg** [comment]
And the Ares costs, too? Hmm. Let's start with the ocean bonuses for the moment.

**Comment by kberg** [comment]
Other possible tile-placement impact

```
class GreensPolicy02 implements Policy {
  readonly id = 'gp02' as const;
  readonly description = 'When you place a tile, gain 1 plant';
  readonly isDefault = false;

  onTilePlaced(player: IPlayer) {
    player.stock.add(Resource.PLANTS, 1);
  }
}
```

```
class KelvinistsPolicy04 implements Policy {
  readonly id = 'kp04' as const;
  readonly description = 'When you place a tile, gain 2 heat';
  readonly isDefault = false;

  onTilePlaced(player: IPlayer) {
    player.stock.add(Resource.HEAT, 2);
  }
}
```

```

class MarsFirstPolicy01 implements Policy {
  readonly isDefault = true;
  readonly id = 'mfp01' as const;
  readonly description = 'When you place a tile ON MARS, gain 1 steel';

  onTilePlaced(player: IPlayer, space: Space) {
    if (space.tile && space.spaceType !== SpaceType.COLONY && player.game.phase === Phase.ACTION) {
      player.stock.add(Resource.STEEL, 1);
    }
  }
}
```

and 
![image](https://github.com/terraforming-mars/terraforming-mars/assets/413481/773182db-daa2-4533-8e39-8b6a6c2ba5fe)
![image](https://github.com/terraforming-mars/terraforming-mars/assets/413481/024be440-62a3-4ee9-b657-92e821ed53cd)

**Comment by kberg** [comment]
Where's the "as if playing a special tile" reference come from, @kevinb9n?

**Comment by kberg** [comment]
Actually, #6014 is going to fix this nicely. I just need to make a special tile!

**Comment by kevinb9n** [comment]
Alas, I think that fix might have reintroduced #6009, and has a couple of strange visual effects as well: my player cube shows up, and the hex outline of the area disappears.

**Comment by kevinb9n** [comment]
Oh, and it's forcing me to put my greenery tile next to it. So these are all behaviors appropriate to a tile that don't fit here.

**Comment by kberg** [comment]
Ugh.

**Comment by kberg** [comment]
OK, thanks. Let's leave this open for now

**Comment by kberg** [comment]
This should be fixed now.
