### ISSUE TITLE
An action from a played card is not available

### ISSUE THREAD

**Issue by vnatalya** [terraforming-mars/terraforming-mars#6043]
Hello!

I've played card ATMO COLLECTORS. 
AR: ATMO COLLECTORS action is not available.

Please view the game info:
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=sb851edb6a043",
  "color": "red",
  "step": 15,
  "version": "ac145b3",
  "builtAt": "Tue, 26 Sep 2023 14:12:56 GMT",
  "browser": "Chrome 116",
  "language": "en",
  "experimental_ui": false
}

Screenshots: 
<img width="827" alt="Screenshot 2023-09-26 at 17 42 08" src="https://github.com/terraforming-mars/terraforming-mars/assets/10325113/ae7d6753-16da-4b85-84f9-b661e5374abc">
ots: 
 
<img width="368" alt="Screenshot 2023-09-26 at 17 41 53" src="https://github.com/terraforming-mars/terraforming-mars/assets/10325113/fd81df80-9e5c-4187-80af-0c5b0ad30501">

ER: I can use ATMO COLLECTORS action once per generation. 

Browser: Google Chrome
Version 116.0.5845.187 (Official Build) (arm64) 
MacOS

**Comment by terraformerG** [comment]
Same here with Deuterium export. Game id g7ea295adc138

**Comment by Yuger030** [comment]
same here with Forced Precipitation and Local Shading.

![Screenshot from 2023-09-27 16-33-36](https://github.com/terraforming-mars/terraforming-mars/assets/126051518/55a1eccb-ab84-43d9-985f-01d876a5bf18)

![Screenshot from 2023-09-27 16-33-53](https://github.com/terraforming-mars/terraforming-mars/assets/126051518/b98463c4-c84c-4238-a105-f1ceb7db399d)



Bug Report:
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s97ad914584f",
  "color": "yellow",
  "step": 13,
  "version": "7b6cc3d",
  "builtAt": "Wed, 27 Sep 2023 05:35:32 GMT",
  "browser": "Firefox 117",
  "language": "en",
  "experimental_ui": false
}

**Comment by vnatalya** [comment]
Same with the next game. Clearing cache and history helps. 
It seems like some of the custom settings might cause this issue, as it starts reproducing every time I update the settings to the next:
<img width="401" alt="Screenshot 2023-09-27 at 12 13 04" src="https://github.com/terraforming-mars/terraforming-mars/assets/10325113/870fd501-2b5d-4171-92ae-ba12d72b511c">

**Comment by kberg** [comment]
These error reports are all occurring around times when the server is
reset. That might be the common theme here.

**Comment by terraformerG** [comment]
I restarted the game using the same ID, and it happened again (several times).

**Comment by terraformerG** [comment]
Laptop (Safari on MacBook Pro.)

**Comment by terraformerG** [comment]
Yep, started a new game gebf418a65651 now. Same problem with Asteroid Rights.

**Comment by Earthling-25** [comment]
Actions from Blue Cards - "Perform and action of a played card" are no longer available.  No blue cards can be used once played at the moment.

**Comment by kberg** [comment]
Got it. The issue is with a bug with how learner mode was processed. A fix is on its way.

**Comment by kberg** [comment]
This should do it. Please inform me if this is still an issue. I'm really sorry about this one!
