### ISSUE TITLE
suddenly lets me pay for building card using plant

### ISSUE THREAD

**Issue by terraformerG** [terraforming-mars/terraforming-mars#6050]
https://terraforming-mars.herokuapp.com/player?id=p61b233dc1792
Suddenly, out of nowhere, Im given option to pay for Tectonic stress power using plants as currency worth 3 M€ ??

**Comment by terraformerG** [comment]
Update: tried to switch from safari to firefox. No paying with leaves, but stuck trying to play the card. Back on safari, everything works. Go figure

**Comment by kberg** [comment]
It's not safari. i rolled back the server. Accidentally pushed something
forward. Thanks for the report and sorry for the inconvenience.

**Comment by kberg** [comment]
This should be fixed now.
