### ISSUE TITLE
Titanium is worth only 3mc when Unity is in power

### ISSUE THREAD

**Issue by Dienekes7** [terraforming-mars/terraforming-mars#6068]
Hello,

Ti is worth only 3mc and Unity is in power. 

Here is the spectator link to the game:

https://terraforming-mars.herokuapp.com/spectator?id=se92c40c2d7c8

Not sure if we have missed anything that would prevent the Ti mc increase or even if there is a card that can do that.

thanks if you can help with this problem.

Kind regards, Neil

**Comment by kberg** [comment]
Thanks for this. It was fixed not long after you reported it.
