### ISSUE TITLE
Player is unable to use United Mars Initiative action despite meeting requirements.

### ISSUE THREAD

**Issue by vscheff** [terraforming-mars/terraforming-mars#6144]
1. A player is unable to use the action of _United Mars Initiative_, despite having raised their TR by 4 during the generation. The player placed an ocean tile and played _Magnetic Field Generators_ this generation. They have not previously used the action this generation. However, the UI is not giving them the option to use the action from their corporation.
2. Supposedly this is the second time this has occurred this game. The player believes the corporations ability may only work if you use it the same turn you increased your TR.
3.
Florian plays _United Mars Initiative_ as their corporation card
![image](https://github.com/terraforming-mars/terraforming-mars/assets/98859370/d8f25d26-2bbd-45d4-97e3-ac87840020b8)

Florian places an ocean tile
![image](https://github.com/terraforming-mars/terraforming-mars/assets/98859370/dbf42a66-8a1a-46da-bf01-2c88d5832377)

Florian plays _Magnetic Field Generators_
![image](https://github.com/terraforming-mars/terraforming-mars/assets/98859370/80f28a4c-7dd4-4f58-9c55-edea3bb00c2b)

Florian is unable to use their corporations action
![image](https://github.com/terraforming-mars/terraforming-mars/assets/98859370/0c3bc6a1-496f-46a9-9704-193098eb82a1)

4.
```
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=sd814f53e8bd3",
  "color": "green",
  "step": 251,
  "version": "18a0713",
  "builtAt": "Thu, 19 Oct 2023 15:09:46 GMT",
  "browser": "Firefox 118",
  "language": "en",
  "experimental_ui": false
}```

**Comment by kberg** [comment]
This is a great writeup. I haven't been able to identify this issue. Let's see how this goes.

**Comment by kberg** [comment]
This was a short-term issue because of code that won't apply to new games. Sorry about that.
