### ISSUE TITLE
No milestones can be claimed by one of the gamers

### ISSUE THREAD

**Issue by Paleolama** [terraforming-mars/terraforming-mars#6145]
Please include:
Milestonse can be claimed only by one gamer, although the other one should be able to

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s74d0392b2fa6",
  "color": "green",
  "step": 61,
  "version": "18a0713",
  "builtAt": "Thu, 19 Oct 2023 15:09:46 GMT",
  "browser": "Firefox 117",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Are you certain? Testing locally I can see the other player can claim a milestone: 
![image](https://github.com/terraforming-mars/terraforming-mars/assets/413481/cc6bce4e-821a-4bdb-b5bc-9d17e18a0c01)

**Comment by kberg** [comment]
In their current game state they only have 4M€. If they gain 4 more M€ they can claim the Builder.

**Comment by Paleolama** [comment]
Only one could claim milestones, the other couldn’t, although they matched the requirements. Wiadomość napisana przez Robert Konigsberg ***@***.***> w dniu 26.10.2023, o godz. 13:52:﻿
In their current game state they only have 4M€. If they gain 4 more M€ they can claim the Builder.

**Comment by kberg** [comment]
Have the other player get 4MC, they should get the Builder award.

**Comment by kberg** [comment]
Unless there is more information, I am going to close the bug. If you find this happens again, please add information here.
