### ISSUE TITLE
Placing Natural Preserve doesn't increase production for mining guild

### ISSUE THREAD

**Issue by ChuanyuanLiu** [terraforming-mars/terraforming-mars#6184]
![image](https://github.com/terraforming-mars/terraforming-mars/assets/24912454/1600bcea-7f90-4e6b-9b42-fcc1c889c062)

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s81e36395a713",
  "color": "red",
  "step": 5,
  "version": "11eb164",
  "builtAt": "Fri, 03 Nov 2023 15:08:11 GMT",
  "browser": "Chrome 118",
  "language": "en",
  "experimental_ui": true
}

**Comment by kberg** [comment]
WAI; the steel production occurred, it just wasn't logged. We don't log everything. We would run out of disk space.
