### ISSUE TITLE
Mining Expedition does not count towards Warmonger award

### ISSUE THREAD

**Issue by ap3h3ad** [terraforming-mars/terraforming-mars#6189]
The Warmonger award states:

"Most cards that reduce other players' resources or production".

In terraforming-mars/src/server/awards/terraCimmeria/Warmonger.ts in the method _autoInclude_ every card is included that has a _removeAnyPlants_-behaviour. The card Mining Expedition states the following:

behavior: {
        stock: {steel: 2},
        global: {oxygen: 1},
        removeAnyPlants: 2,
      },

Therefore it should count towards the award. In our current game it did not. 

Cheers!

**Comment by kberg** [comment]
If the game somehow still exists I can verify this, but I'm confident it works. A local test verifies this. Perhaps I fixed it in recent days? Going to close this in the meantime.
