### ISSUE TITLE
not counting all the tags

### ISSUE THREAD

**Issue by Beerrund** [terraforming-mars/terraforming-mars#6202]
While enjoying playing on heroku a lot, I am noticing off late that some tags - science, Earth etc - are not counted correctly, hence I can't play certain cards even though I met the requirements. This makes it hard to plan a card strategy.

**Comment by kberg** [comment]
Can you please give an example from the app?

**Comment by Beerrund** [comment]
i just finished a game. It seems the problem lies with the orange cards. It does count the "Arrows" but nothing that is placed next to it.

**Comment by kberg** [comment]
Thanks for your report. This is working correctly. Please review https://github.com/terraforming-mars/faq/wiki#do-tags-on-event-cards-have-any-effects, particularly the last line.

**Comment by Beerrund** [comment]
Still the same: on Orange Cards only the Event Tgs (arrows) are counted.

**Comment by kberg** [comment]
Where do you think arrows count?

**Comment by Beerrund** [comment]
In the bar on top, where the number of each type of tags is recorded. If you play an Orange card with e.g. an Earth Tag, a Titanium Tag and an Event Tag (the Arrow), only the Event Tag is recorded, not the Earth Tag and the Titanium Tag, nor does it have any effect on cards that either require a certain amount of tags (Titanium, Science) or provide a certain reward for each tag of a certain type.

**Comment by kberg** [comment]
> Message ID: <terraforming-mars/terraforming-mars/issues/6202/1807247408@
> github.com>
>
Sorry, I need a real example, from a real game, that I can recreate, and
not a written summary.

**Comment by Beerrund** [comment]
The id of this game is g181ee0b973e0

in this game that I just started I played 2 Orange Earth-tag cards (Business Contacts  & Imported GHG), but only the 1 from my corporation (Teractor) is recorded. Hence if I woud now play Cartel I would up my MC production by only 2 i.o. 4.

**Comment by d-little** [comment]
From your descriptions these cards are behaving exactly as intended.

It looks like you may not have fully understood the rules around Event
tags. (
https://github.com/terraforming-mars/faq/wiki#do-tags-on-event-cards-have-any-effects
)

Could you please confirm that you've read and understood the rules? And
then again if the issue you're experiencing is outside these effects?

**Comment by Beerrund** [comment]
I don't understand. If I play a card with three tags on it, then I 'have' those tags: all three of them. So these should be counted and recorded, to either fulfill a requirement for other cards (e.g. science tags) or pay-outs (e.g. Earth tags for Cartel). So it shouldn't matter if I obtain the amount by choosing a corporation card or playing a green, blue or orange card. All played tags should count. And for orange cards they don't.

**Comment by d-little** [comment]
> And for orange cards they don't.

This is Correct.

I do strongly recommend you read the rules of the game, and the FAQ linked
twice previously.  As far as you've described, this is behaving as expected.

Unless you can confirm that you've read the rules and that this is _not_
the expected behaviour,  the issue remains resolved.

**Comment by kberg** [comment]
> Unless you can confirm that you've read the rules and that this is _not_ the expected behaviour,  the issue remains resolved.

Yes, this. Fortunately this isn't a bug in the game.

**Comment by Beerrund** [comment]
I do apologize. It appears I have missed this completely up till now - and hence have also played the table top version wrongly, counting the tags on Event cards towards other cards.

Thank you so much for your patience!

**Comment by kberg** [comment]
No problem. It's easy to misunderstand. I've made the same mistake as you.
Go have fun!

**Comment by Beerrund** [comment]
thank you!
Will do ;-)
