### ISSUE TITLE
TECHNOLOGY DEMONSTRATION card does not result in the science tag being awarded despite being marked on the card

### ISSUE THREAD

**Issue by next86** [terraforming-mars/terraforming-mars#6219]
Please include:
1. A clear and concise description of the bug.
Playing the "TECHNOLOGY DEMONSTRATION" card does not result in the science tag being awarded despite being marked on the card
3. Clear steps to reproduce, and the expected behavior.
🕑The ruling bonus is: Gain 1 M€ for each Plant, Microbe and Animal tag you have
🕑The ruling policy is: When you place a greenery tile, gain 4 M€
🕑A neutral delegate was added to the Reds party
🕑A neutral delegate was added to the Greens party
💬Good luck Next!
Generation 1
🕑Josz's megacredits production increased by 4
🕑Next's megacredits production decreased by 2
🕑Snajper's megacredits production decreased by 2
🕑Josz played MONS INSURANCE
🕑Josz kept 4 project cards
🕑Snajper's titanium production increased by 1
🕑Snajper drew 1 card(s)
🕑Snajper played POINT LUNA
🕑Snajper kept 6 project cards
🕑Next played VALLEY TRUST
🕑Next kept 7 project cards
🕑Josz played METALS COMPANY
🕑Josz's megacredits production increased by 1
🕑Josz's steel production increased by 1
🕑Josz's titanium production increased by 1
🕑Josz played SUPPLIER
🕑Josz's energy production increased by 2
🕑Josz's steel amount increased by 4
🕑Snajper played ACQUIRED SPACE AGENCY
🕑Snajper's titanium amount increased by 6
🕑4 card(s) were discarded
🕑Snajper drew ASTEROID MINING and COMET FOR VENUS
🕑Snajper played ORBITAL CONSTRUCTION YARD
🕑Snajper's titanium production increased by 1
🕑Snajper's titanium amount increased by 4
🕑Next played UNMI CONTRACTOR
🕑Next drew 1 card(s)
💬You drew ICE CAP MELTING
🕑Next played NEW PARTNER
🕑Next's megacredits production increased by 1
🕑Next played BUSINESS EMPIRE
🕑Next's megacredits production increased by 6
🕑Josz played SOLETTA
🕑Josz's heat production increased by 7
🕑Josz sent 1 delegate(s) in Kelvinists area
🕑Snajper played ADVANCED ALLOYS
🕑Snajper played COMET AIMING
🕑Next played ANTI-DESERTIFICATION TECHNIQUES
🕑Next's steel production increased by 1
🕑Next's plants production increased by 1
🕑Next's megacredits amount increased by 3
🕑Next played TECHNOLOGY DEMONSTRATION
🕑Next drew 2 card(s)
5. Any screenshots
![bug](https://github.com/terraforming-mars/terraforming-mars/assets/11598184/00dbec74-da2f-461e-b302-6a454e55874a)

6. Any information from  the Bug Report Dialog
 {
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s5430c35b247f",
  "color": "green",
  "step": 10,
  "version": "ea490c9",
  "builtAt": "Fri, 10 Nov 2023 06:28:53 GMT",
  "browser": "Chrome 119",
  "language": "en",
  "experimental_ui": false
}

**Comment by Borbarad2** [comment]
This card is an event card, thus the tags are only valid in the moment of play, and are not awarded after playing that card, because event cards are face down after playing and thus the tags are not visible anymore. See basic rules for more clarification.

**Comment by kberg** [comment]
Thanks for the explanation!
