### ISSUE TITLE
It stop working while using actions

### ISSUE THREAD

**Issue by MCKohan** [terraforming-mars/terraforming-mars#6231]
It says "cannot use countable without a counter", so if i try to use an action to take cards or anything it apears that message, but if i try with one that have options it stay crashed in the selection phase.

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=sd585caee274d#cards",
  "color": "blue",
  "step": 429,
  "version": "38c69c7",
  "builtAt": "Wed, 15 Nov 2023 04:39:00 GMT",
  "browser": "Chrome 119",
  "language": "en",
  "experimental_ui": true
}

**Comment by kberg** [comment]
If you're using the Underworld expansion, it is under development. That
means things are broken. Sorry.
