### ISSUE TITLE
Wrong counting of science symbols?

### ISSUE THREAD

**Issue by theKamikater** [terraforming-mars/terraforming-mars#6233]
I wasnt able to play the card "Mass Converter" which requires 5 science symbols even though there are 5 science symbols in my played cards area. The top counter showed 4 science symbols.
Cards played with science symbols:
"olympus conference" "research" "invention contest" "robotic workforce"
research has 2 symbols on card

![Screenshot 2023-11-17 103822](https://github.com/terraforming-mars/terraforming-mars/assets/39584547/868c4d82-b9f6-46db-b761-46392a932477)

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s49b0715b9be9",
  "color": "orange",
  "step": 28,
  "version": "38c69c7",
  "builtAt": "Wed, 15 Nov 2023 04:39:00 GMT",
  "browser": "Firefox 119",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Thanks for your report. This is working as intended. Events, once played, do not count for tags.
