### ISSUE TITLE
Playwrights reply into Special Design doesn't work.

### ISSUE THREAD

**Issue by jasonmastbaum** [terraforming-mars/terraforming-mars#6249]
On a game tonight I tried to do Playwrights' replay action to use Special Design so that I could play Stratospheric Birds while Venus was on 8 and it wouldn't let me play Stratospheric Birds. I had floaters and enough money. When Venus was subsequently raised to 12 it let me play the card.

**Comment by kberg** [comment]
Link to game?

**Comment by kberg** [comment]
Closing from lack of response. Feel free to add more data if you have it.

**Comment by jasonmastbaum** [comment]
This was the game link, not sure if you can get anything out of this at this point though: https://rebalakefak.herokuapp.com/game?id=g3578dd1771be

**Comment by kberg** [comment]
Gotcha. This GitHub repo is not for that server.

**Comment by jasonmastbaum** [comment]
Oops sorry about that, I got here because their homepage About Us link points to this repo.
