### ISSUE TITLE
Cannot finish local deployment

### ISSUE THREAD

**Issue by Yiyuiii** [terraforming-mars/terraforming-mars#6255]
The current version [a8b152f](https://github.com/terraforming-mars/terraforming-mars/commit/a8b152f4f8a642c1c557861a39f9d8fcc699384d) of main branch cannot be made by npm due to some error, and also docker made by andrewsav/terraforming-mars cannot start normally, therefore I cannot finish local deployment and I believe this was some coding error. Hope someone can fix this.

**Comment by kberg** [comment]
Please provide the errors you got.

**Comment by Yiyuiii** [comment]
I just successfully run on Ubuntu 20.04, and on Raspberry 4B with `npm cli & npm run lint`. Maybe my something wrongly installed - -
