### ISSUE TITLE
The Virus card is not counting the Microbe tag.

### ISSUE THREAD

**Issue by MikkelFrid** [terraforming-mars/terraforming-mars#6261]
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s6e65a9e74c16",
  "color": "orange",
  "step": 50,
  "version": "3e99407",
  "builtAt": "Fri, 24 Nov 2023 05:11:01 GMT",
  "browser": "Chrome 119",
  "language": "en",
  "experimental_ui": false
}
<img width="1326" alt="image" src="https://github.com/terraforming-mars/terraforming-mars/assets/8225933/67cc5bba-129f-4f76-98b5-71648d8fad5e">

**Comment by kberg** [comment]
Tags on event cards are not counted. This is correct.
