### ISSUE TITLE
Problem with the card : wetlands

### ISSUE THREAD

**Issue by Stephds3** [terraforming-mars/terraforming-mars#6265]
the tile of this card counts as a forest and an ocean. for the reward: the one who has the most cities earning victory points. The wetlands tile should be taken into account in the calculation.
Currently it is not.

**Comment by kberg** [comment]
Please provide a link to the game where this problem is happening.

**Comment by Stephds3** [comment]
https://terraforming-mars.herokuapp.com/the-end?id=pc6da8b36da7f

**Comment by kberg** [comment]
That seems legitimate. I'll take a look tonight. But, why is it reporting 4
instead of 3?

**Comment by Stephds3** [comment]
Normally for the urbanist reward, the red player must be at 7 and the purple player at 5.
