### ISSUE TITLE
Docker image fails to start due to NPM permission issue

### ISSUE THREAD

**Issue by mmomjian** [terraforming-mars/terraforming-mars#6278]
As of this morning, the server will no longer start due to `/.npm` ownership issues. I am not sure which commit caused this issue, I run the nightly version and it just stopped working today. I tried recreating the container, since there are no persisted volumes I assumed that would fix the permission issue but it still doesn't start the container as a non-root user.

Error from `docker logs tmars`:

```
> terraforming-mars@1.0.0 start
> node build/src/server/server.js

npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /.npm
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 11045:11045 "/.npm"
```

Below is my version info from the browser, and the docker compose file. If I remove the `user:` setting, it runs fine. I tried changing the environment variable `npm_config_cache`, but I still get the same error other than it now asking to chown `/.npm2`.

```
{
  "url": "https://<redacted>/",
  "version": "7498dddb2",
  "builtAt": "Thu, 30 Nov 2023 16:36:30 -0500",
  "browser": "Chrome 119",
  "language": "en",
  "experimental_ui": false
}
```

docker-compose:
```
    tmars:
        container_name: tmars
        hostname: tmars
        restart: unless-stopped
        user: '11045:11045'
        security_opt:
            - 'no-new-privileges:true'
        labels:
            homepage.group: Media
            homepage.name: Terraforming Mars
            homepage.icon: si-starship
            homepage.href: '${tmarsurl}'
        environment:
#          npm_config_cache: '/.npm2'
          MAX_GAME_DAYS: '99992'
          COMPRESS_COMPLETED_GAMES_DAYS: '30'
          PORT: '55043'
          HOST: '${tmars_host}'
          GAME_CACHE: 'sweep=auto;eviction_age=30m;sweep_freq=5m'
          STATS_ID: '${tmars_statspw}'
          SERVER_ID: '${tmars_serverpw}'
          POSTGRES_HOST: '${tmars_pglogin}'
          CERT_PATH: '${fullchain}'
          KEY_PATH: '${privkey}'
        volumes:
            - '${certvol}'
            - '${curlvol}'
        ports:
            - '55043:55043'
        networks:
            <redacted>:
                ipv4_address: <redacted>
        image: 'andrewsav/terraforming-mars:latest'
```

**Comment by kberg** [comment]
I know absolutely nothing about docker. The best thing I can suggest is that you ensure that the prior release still works.

**Comment by kberg** [comment]
Also, have you considered running the command in your output?

**Comment by kberg** [comment]
I'll reopen this after you run the command in the error message presented to you. In the meantime, this is reasonable to close.

**Comment by AndrewSav** [comment]
Hey @d4nyl0 changing your local `docker-compose.yaml` to tailor for your needs is absolutely fine, you should go for it. I would be reluctant to make a change in the official repo to run as root the `user: 0` bit. What I personally do: use a bind mount instead of volume and set the required permissions straight on the file system.
