### ISSUE TITLE
Wrong player asked to remove corruption for Hired Raiders (Underworld)

### ISSUE THREAD

**Issue by Maelstrom1** [terraforming-mars/terraforming-mars#6279]
[Link to game here, gen 9](https://terraforming-mars.herokuapp.com/spectator?id=sf62ccdd08737)
what it says on the tin. Player name Jacob tried to steal money from player name Nick. However, Jacob was asked if they wanted to remove a corruption to block Jacob from stealing money. Obviously, they said no and the money was stolen. Nick was never given that option.

**Comment by kberg** [comment]
Thanks for the catch. Will fix.
