### ISSUE TITLE
Problem on the moon 

### ISSUE THREAD

**Issue by Blaku91** [terraforming-mars/terraforming-mars#6289]
Please include:
1. A clear and concise description of the bug.
2. Clear steps to reproduce, and the expected behavior.
3. Any screenshots
4. Any information from  the Bug Report Dialog
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s55d561e9b806",
  "color": "green",
  "step": 548,
  "version": "78e5e5d",
  "builtAt": "Wed, 06 Dec 2023 01:25:11 GMT",
  "browser": "Chrome 120",
  "language": "pl",
  "experimental_ui": false
}

**Comment by kberg** [comment]
What's the issue? This doesn't tell me what was wrong.

**Comment by kberg** [comment]
Closing the bug for lack of details. Please add more if you would like me to reopen it.
