### ISSUE TITLE
Corp Gagarin gives bonus to active player instead of Gagarin player

### ISSUE THREAD

**Issue by ssimeonoff** [terraforming-mars/terraforming-mars#6290]
**Steps**
- as a non-Gagarian player, place a tile over the base
- as Gagarin player, move to base to a new tile

**Expected** 
New tile bonus to be gives to the Gagarin player.

**Observed**
The bonus is given to the active player.

**Comment by kberg** [comment]
Good report, thank you. Easy fix.
