### ISSUE TITLE
Rulebook links are broken

### ISSUE THREAD

**Issue by sgbench** [terraforming-mars/terraforming-mars#6291]
The rulebook links on [the wiki page](https://github.com/terraforming-mars/terraforming-mars/wiki/Rulebooks) are broken. It seems Fryx Games reorganized their website or something.

**Comment by kberg** [comment]
Thanks. I'll look at this in a day or so.

**Comment by kberg** [comment]
The website is updated, as you probably know. The only link I can find is the one for the base game. The expansions are not yet visible due to what seems to be an error in their website. Those will have to remain broken for now.

**Comment by sgbench** [comment]
That's a bummer. Going forward, would it be feasible to host copies of the
rulebooks in the repo? Or would that be legally problematic? I'm guessing
it wouldn't be, since Fryx made them publicly available on their website.

**Comment by kberg** [comment]
I don't know about legally problematic. But it's just something I don't
want to do.

**Comment by lukenofurther** [comment]
How about linking to the board game geek versions of the rulebooks? e.g. https://boardgamegeek.com/filepage/135533/final-english-rules

**Comment by kberg** [comment]
It's an option, sure, but I'm confident new links will appear soon enough on their site.

**Comment by kberg** [comment]
I used the links from 1j1ju.com. Only Hellas and Elysium is missing.

**Comment by kberg** [comment]
Found one.
