### ISSUE TITLE
Stuck game of Terraforming Mars

### ISSUE THREAD

**Issue by Shaydie** [terraforming-mars/terraforming-mars#6296]
Hello. I'm trying to put a habitat on the moon and it keeps saying all the spaces are occupied and I can't exit it to complete the game. Can you help me get it unstuck? https://terraforming-mars.herokuapp.com/player?id=pcf244d65e316#actions

![marserrorgame](https://github.com/terraforming-mars/terraforming-mars/assets/112154905/f4a04c1d-2f34-47e3-8a97-7a4910e9153c)

 {
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s9e30c5893cff#cards",
  "color": "orange",
  "step": 938,
  "version": "9151e4e",
  "builtAt": "Fri, 15 Dec 2023 20:59:30 GMT",
  "browser": "Chrome 120",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Can you tell me the specific action you're taking that triggers the issue?

**Comment by kberg** [comment]
Also, what is the specific error? I don't think the error says all spaces are occupied if the screenshot suggests otherwise. Sorry, I need more specific details to be able to help you.

**Comment by Shaydie** [comment]
Yes. I’m playing a card that lets me put down a habitat. Apparently there aren’t any spaces, it’s showing the ones that are already placed, but they are flashing as if it’s a space I can use. Then I get an error message and have to refresh the page. After that, the same hexes are flashing even though they have habitats in them already. I can’t get out of that loop.

Sent from my iPhone

On Dec 16, 2023, at 10:41 AM, Robert Konigsberg ***@***.***> wrote:

﻿

Can you tell me the specific action you're taking that triggers the issue?

**Comment by Shaydie** [comment]
I refreshed it twice this morning and it is unstuck. Thank you!
________________________________

**Comment by Shaydie** [comment]
the card was Habitat 14.
________________________________

**Comment by kberg** [comment]
I didn't do anything. The server restarted, and I suppose we won't know why that happened. Thanks though.
