### ISSUE TITLE
Spire Corp - Didn't trigger when playing Merger

### ISSUE THREAD

**Issue by FunkyFrankyPedro** [terraforming-mars/terraforming-mars#6297]
I didn't receive a Science resource on the Spire Corporation in the following scenario:
1. I picked Spire as a Corp, which granted a Science resource on it
2. I picked a Prelude with 2 tags, which granted a second Science resource
3. I picked the Merger Prelude as the second one, and selected the Ecotec Corp, which has two tags, but it didn't trigger the Science resource to be added.

The science resources were added correctly to Spire for the rest of the game

**Comment by kberg** [comment]
Please click the gear button and then click report bug.

**Comment by FunkyFrankyPedro** [comment]
This is what I get:
{
  "url": "https://terraforming-mars.herokuapp.com/",
  "version": "a653b1a",
  "builtAt": "Sun, 17 Dec 2023 16:52:42 GMT",
  "browser": "Chrome 120",
  "language": "en",
  "experimental_ui": false
}

I don't have access to that game anymore though

**Comment by kberg** [comment]
Thanks.
