### ISSUE TITLE
Astra Mechanica is not compatible with Price Wars

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#6300]
https://discord.com/channels/737945098695999559/1157191624045117551/1187498436648501429

I have an underworld bug, possibly
I played price wars in gen 10
Then I got it back with astra mechanica, and played again in gen 11
Then in gen 12, the titan/steel value remained the same as if I had played price wars again, but I didn't
Any chance this could be looked at?
https://terraforming-mars.herokuapp.com/spectator?id=s7557b9f042a8
Here is the spectator link

**Comment by kberg** [comment]
I think the right solution is to reduce the values when the card is drawn back into hand.

**Comment by Valmonzo** [comment]
Your discord link doesn't work

**Comment by kberg** [comment]
> Your discord link doesn't work

Looks like it works fine. You sure?

**Comment by Valmonzo** [comment]
> > Your discord link doesn't work
> 
> Looks like it works fine. You sure?

It works, my bad !
