### ISSUE TITLE
Modify displayed requirements when Inventrix / Adaptation Technology are in play

### ISSUE THREAD

**Issue by illicitonion** [terraforming-mars/terraforming-mars#6302]
In the same way that cost discounts are displayed on cards:

<img width="52" alt="Screenshot 2023-12-23 at 20 27 07" src="https://github.com/terraforming-mars/terraforming-mars/assets/1131704/661792d3-fa79-4ffb-9947-edf1673b235b">

If Inventrix or Adaptation Technology is in play, it would be great to show that global requirements limits are also modified, rather than needing to calculate the difference myself.

Currently, just the "for everyone" global requirement is shown not factoring in that one player may have different requirements.

**Comment by kberg** [comment]
Hey there. I can see why this could be useful. How do you think this could be addressed visually? I feel like the cards are already pretty crammed.

**Comment by kberg** [comment]
Hmm...

![image](https://github.com/terraforming-mars/terraforming-mars/assets/413481/85d29fc7-7aab-4520-8e9d-788dde34d649)
![image](https://github.com/terraforming-mars/terraforming-mars/assets/413481/c7d3fd8d-9f45-49da-a832-3bd2c2235803)

**Comment by illicitonion** [comment]
It feels like the horizontal bar itself has quite a bit of horizontal space? Maybe something like this, with a prettier arrow?

<img width="282" alt="Screenshot 2023-12-27 at 00 25 02" src="https://github.com/terraforming-mars/terraforming-mars/assets/1131704/99b675fa-2845-4420-a3b6-bd33249cb21b">

**Comment by illicitonion** [comment]
Or even no arrow?

<img width="277" alt="Screenshot 2023-12-27 at 00 28 14" src="https://github.com/terraforming-mars/terraforming-mars/assets/1131704/68c18454-b02e-45bc-ae98-091c153b3ec0">

**Comment by kberg** [comment]
That might be the best option. My thoughts are a) I regret that it's using a different visual language from the cost component and b) this can't disrupt translations.

**Comment by kberg** [comment]
This would be a bit of work, but could be doable, though I'd add it to the experimental UI feature set to start. The easier bits are defining changes to `CardModel` and the UI. The tricky part might be calcuating this information up-front. This would make a good collaborative effort if you're interested. Otherwise it's just a little too tricky to start to work through on my own.

**Comment by illicitonion** [comment]
I've got an end-to-end prototype working you can see in https://github.com/terraforming-mars/terraforming-mars/pull/6320 (the first commit is just a refactor to make some data easier to access, the second has the feature), and it's left me with one main question to explore:

How to represent requirement bonuses in `CardModel`?

The `Player` models these as `GlobalParameter` -> `number`.

It feels like the two reasonable options in `CardModel`
1. We could basically forward a `Map<GlobalParameter, number>` (or `Map<RequirementType, number>`) in `CardModel` and merge that with the `CardRequirementDescriptor`s in the `CardRequirementComponent`.
2. We could modify the `ClientCard` to add a `modifiedRequirements: Array<CardRequirementDescriptor>` in addition to `requirements: Array<CardRequirementDescriptor>`.

It's a little odd that `CardModel` has a `calculatedCost?: number` whereas `ClientCard` has `cardDiscount?: OneOrArray<CardDiscount>` - that doesn't give great guidance for how to model requirements modifiers...

The prototype I put together just forwards a `Map<RequirementType, number>` and lets the client worry about what to do with it. Happy to switch to the other model if that makes sense, but would appreciate a sketch of the relevant type signatures you have in mind.

**Comment by kberg** [comment]
@illicitonion did you see my responses to your code review? I saw no responses to mine, so I closed it for now. But if you're interested in further pursuing it, please let me know.

**Comment by kberg** [comment]
If you want to work on this, just let me know.
