### ISSUE TITLE
 "Lawsuit" not properly counting towards "Warmonger" award

### ISSUE THREAD

**Issue by Erostal** [terraforming-mars/terraforming-mars#6326]
This is a follow-up from ticket #6310 which I believe was closed incorrectly. I'll just be pasting the comments from that ticket below:

=====
Hello,

In a recent game it appears that the "Lawsuit" card isn't counting (or at least isn't displayed counting) towards the "Warmonger" award.

In the below linked game, the Red player plays Fish, Birds, Biomass Combustors, Deimos Down, and Lawsuit (Lawsuit played in Gen 7). The counter for the Warmonger award shows 4, while I believe it should be showing 5. We couldn't verify if it actually counted or not as the 2nd place in the award was at 3 cards.

This may have something to do with how Lawsuit is played - it going into another player's played event stack?

Thanks for all your work on this tool!

Game ID: g420be0779238
Game Log attached
[Terraforming Game Log.txt](https://github.com/terraforming-mars/terraforming-mars/files/13812933/Terraforming.Game.Log.txt)
=====
Thanks for the report. Events don't count towards awards. Closing as I believe this is not a bug.
=====
I don't believe this is correct for the Warmonger award. The description reads "Play the most cards that reduce other players' resources or production", not something along the lines of "Have the most cards in play that reduce...". Comparing this to the description of Celebrity which reads "Have the most project cards in play with a base of at least 20 ME (not events)." which specifically excludes events as well as specifying the "in play".

Also if it's not counting events there is still an issue, as the only 2 cards the red player had in play that reduce others were Birds and Fish, which would total up to 2, not the shown 4. Similarly, the green player has a count of 3, but only 1 blue or green card that reduces (Asteroid Mining Consortium), but including events does have 3.

**Comment by kberg** [comment]
Yeah right. I meant to reopen it. I have to read this carefully, thank you for all your details. My silence does not match my gratitude.

**Comment by Erostal** [comment]
No worries on that front. I was just assuming that once a ticket closed you might not get updates/responses on it (as that's how other systems I've worked with go) and didn't want to forget the issue.

Y'all are the real heroes - you're putting the in work for this great service, it was the holidays. Thank you

**Comment by kberg** [comment]
ref: https://discord.com/channels/737945098695999559/742721510376210583/1210612367080165406 for another such card

**Comment by kberg** [comment]
Viz https://github.com/terraforming-mars/terraforming-mars/issues/6310#issuecomment-1992173294 events don't count toward awards, so I am removing events from eligibility.
