### ISSUE TITLE
[BUG] Forced to decrease your own resource / production when no other players have any resource / production to decrease

### ISSUE THREAD

**Issue by kevinmachstudio** [terraforming-mars/terraforming-mars#6332]
Unless this is not actually a bug, for cards that allow you to decrease another player's resource / production, if no other player has that resource / production to decrease, you are forced to decrease your own

**Comment by kberg** [comment]
That's correct. What's the bug?

**Comment by kevinmachstudio** [comment]
Ah I see it in the rulebook, makes sense now, it's not a bug. Closing this issue. Thanks!
