### ISSUE TITLE
darkside mining syndicate bug

### ISSUE THREAD

**Issue by DocmoPS** [terraforming-mars/terraforming-mars#6337]
**A clear and concise description of the bug.**
darkside mining syndicate didn't calculate titanium production correctly.  I should have received 4 bumps but got just 2.  

**reproduce**
mining rate starts at 5.  play the card.  it should bump mining to 6.  this bump bonus should give 1 titanium production.  then the card itself should yield another 3 (1 per 2 mining rate)

https://terraforming-mars.herokuapp.com/game?id=g9668b7829aa1 happened in gen8

<img width="313" alt="image" src="https://github.com/terraforming-mars/terraforming-mars/assets/67963679/848e8389-06e0-4d8e-83d2-751d08b045fe">

**Comment by DocmoPS** [comment]
woops re-read the card and now i understand :D

**Comment by kberg** [comment]
Thank you!
