### ISSUE TITLE
Science badges count

### ISSUE THREAD

**Issue by Bibilome** [terraforming-mars/terraforming-mars#6342]
There is an issue with the badges count. I played 5 space badges but the count is just 3.

Here is the link :
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s47d7c0e8890d",
  "color": "red",
  "step": 20,
  "version": "4f0ac1b",
  "builtAt": "Thu, 04 Jan 2024 05:02:46 GMT",
  "browser": "Firefox 119",
  "language": "fr",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Not an issue: https://github.com/terraforming-mars/terraforming-mars/wiki/FAQ#why-arent-tags-on-my-event-card-taken-into-consideration

**Comment by Bibilome** [comment]
Thank you so much for the explanation, you're the best !
