### ISSUE TITLE
[Community Colony] Leavitt science tag not activating tag-dependant effects.

### ISSUE THREAD

**Issue by 167kamon** [terraforming-mars/terraforming-mars#6349]
Building a colony on Leavitt does not activate certain things that are supposed to activate upon gaining a science tag.

Pharmacy Union does not activate to remove a disease or flip.
Aridor does not activate to raise money production if this is your first science tag. Subsequent science tags from cards do activate Aridor, even though they are no longer your first.
CEO Faraday does not activate if this is your 5th science tag, and subsequent science tags from cards do NOT activate him. If the Leavitt tag was not your 5th, it still counts towards the total if your 5th is reached with a card.
Venusian Animals does not get an animal.

**Comment by kberg** [comment]
Thanks. Can you provide a link to a game where you had this issue?

**Comment by 167kamon** [comment]
Here's a quick demonstration of Pharmacy and Aridor not triggering.
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s9f927f1e361c",
  "color": "red",
  "step": 4,
  "version": "f1c9e1d",
  "builtAt": "Sun, 07 Jan 2024 07:32:25 GMT",
  "browser": "Firefox 121",
  "language": "en",
  "experimental_ui": false
}

**Comment by 167kamon** [comment]
Venusian Animals not activating:
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=sb339f3f085a7",
  "color": "red",
  "step": 12,
  "version": "f1c9e1d",
  "builtAt": "Sun, 07 Jan 2024 07:32:25 GMT",
  "browser": "Firefox 121",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Confirmed. :/ I see why. That might be tricky.

**Comment by kberg** [comment]
This is fixed
