### ISSUE TITLE
[Underground] Underground Shelters not scoring correctly

### ISSUE THREAD

**Issue by Maelstrom1** [terraforming-mars/terraforming-mars#6350]
https://terraforming-mars.herokuapp.com/the-end?id=p6dae52b1b91

Not only does the card not score the 1 point shown, it does not properly score for excavated areas around cities. Player name Tommy had one city with all seven tiles adjacent+city excavated, and the card scored 0.

We noticed scoring issues in a prior game (one month ago) had similar issues upon close inspection.

**Comment by kberg** [comment]
I'm sorry, it was a typo on the card. I'm changing the card to say "your cities score 1 VP per 3 excavation markers **YOU have** in that city space and adjacent spaces.'"

In other words, it only scores for YOUR excavation markers.
