### ISSUE TITLE
API Documentation Request

### ISSUE THREAD

**Issue by Christian-Prather** [terraforming-mars/terraforming-mars#6356]
Hello, 
Firstly let me say this is one heck of impressive software. I love this game its so awesome to see others do as well. 

I am currently toying with the idea of making a reinforcement agent to play the game and was wondering if there are any API docs that I may be missing or how much of a request it would be to have them created. 

I can see the general GET and POST  http endpoints but don't have a clear picture of what the request and response info is that the server is expecting / returning. 

I know I could use some reverse engineering to find this info but as I am sure to develop the game in the first place those API's must be documented somewhere. I figured I would ask first.
Thank you

**Comment by kberg** [comment]
I appreciate your thoughts. Thanks for that. There aren't any API docs, nor am I planning to write any. But the major endpoints you're probably interested in are `player`, `waitingFor`, and `input`. I think.

I think you'll probably need to reverse engineer this one, though.

A caveat: API compatibility is not a feature I plan to maintain, so it might change without notice. But the big API syntax rewrites were about a year ago. Some more may come soon, but I hope they aren't disruptive.

**Comment by kberg** [comment]
Your best bet for questions might be to jump on the Discord, just because it's easier to have conversations there. Either way, good luck.
