### ISSUE TITLE
Aridor corp. not recognizing available colonies

### ISSUE THREAD

**Issue by rekagiday** [terraforming-mars/terraforming-mars#6384]
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=sbc3fbe421868",
  "color": "purple",
  "step": 4,
  "version": "cec5d2e",
  "builtAt": "Sat, 27 Jan 2024 17:15:59 GMT",
  "browser": "Chrome 121",
  "language": "hu",
  "experimental_ui": false
}

The available colonies were not shown upon selecting Aridor from playing the Merger prelude card, and none were added to the colonies list after choosing Aridor as the second corporation. It happened in 2-man gameplay, with 6 pre-selected colonies, and only 5 were in play after playing Aridor. 
![image](https://github.com/terraforming-mars/terraforming-mars/assets/25591118/1bd5d580-cf1c-4b23-83e0-e09a860fb381)

**Comment by kberg** [comment]
If you're preselecting a limited set of colonies, those are the only ones available. It's unfortunate that someone chose Aridor.
