### ISSUE TITLE
Media group not providing 3M€ as expected when playing an event card.

### ISSUE THREAD

**Issue by Oliv-zibuth** [terraforming-mars/terraforming-mars#6408]
Please include:
1. Media group card does not provide 3M€ as expected when playing an event card.

2. Play Media group card then Permafrost extraction.
Expected behavior : The player should receive 3M€ after playing Permafrost extraction.
Observed behavior : The player does not receive 3M€ after playing permafrost extraction.
Also observed after playing Big Asteroid.
Maybe linked to issue : Optimal Aerobraking was played just before Media Group (Third screenshot) and was working correctly after Big Asteroid.

3. Screenshots : 
![image](https://github.com/terraforming-mars/terraforming-mars/assets/95378406/a0bfada4-4e94-42fb-b98d-dc5525840966)
![image](https://github.com/terraforming-mars/terraforming-mars/assets/95378406/4a8ad1c4-1d45-47da-9cfd-bb43686e0f47)
![image](https://github.com/terraforming-mars/terraforming-mars/assets/95378406/7c5efd0a-d671-433f-89cf-b0de86bfbe9f)

4. Any information from  the Bug Report Dialog
{
  "url": "http://terraforming-mars.herokuapp.com/spectator?id=s695384ecb234",
  "color": "red",
  "step": 137,
  "version": "b584fef",
  "builtAt": "Sun, 11 Feb 2024 10:10:55 GMT",
  "browser": "Firefox 122",
  "language": "en",
  "experimental_ui": false
}

**Comment by Borbarad2** [comment]
Media Gruop is working perfectly. The M€ amount you get from Media Group is not logged, that's why you might have not notice it. 
And yes, it should be logged to avoid that kind of bug messages.
