### ISSUE TITLE
Starting Resource Production

### ISSUE THREAD

**Issue by soundofm11-github** [terraforming-mars/terraforming-mars#6425]
I not 100% sure this is a bug but the last 2 games I started I noticed everyone started with +1 production of every basic resource (MC, Steel, Titanium, Plants, Power and Heat).  The first game was a beginner game so I thought maybe they changed it so it was a bit easier, but my current game is not, and I still see the extra production.  The game ID is gf3b28501a6da.  The other game I started is purged now I could provide you my player ID from it if it would do you any good, but I don't have the game ID.

I started a 3rd game just to see if the same thing happened, but it was fine.

Not a huge deal but I thought it was weird.  Thanks, love the site.

**Comment by kberg** [comment]
Thanks for the report. The game is correct. You are playing without the Corporate Era, which gives players +1 production a simpler card set.
