### ISSUE TITLE
Payment issue

### ISSUE THREAD

**Issue by KonHeim** [terraforming-mars/terraforming-mars#6450]
Please include:
1. A clear and concise description of the bug.
2. Clear steps to reproduce, and the expected behavior.
3. Any screenshots
4. Any information from  the Bug Report Dialog

I’m unable to pay to buy cards.
I could pay with steel either, but its not working neither way.
I can pay for things, where I’m not asked to choose payment method, like flying to colonies, for energies.
![IMG_3959](https://github.com/terraforming-mars/terraforming-mars/assets/39599407/21bd5986-a614-4e98-8fa1-fbaf8068c824)

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s4b6434297723",
  "color": "blue",
  "step": 121,
  "version": "0a7fac6",
  "builtAt": "Mon, 26 Feb 2024 22:12:34 GMT",
  "browser": "Safari 16",
  "language": "hu",
  "experimental_ui": false
}

**Comment by Borbarad2** [comment]
Is this a still valid issue?

**Comment by KonHeim** [comment]
No

Borbarad2 ***@***.***> (időpont: 2024. júl. 3., Sze, 10:13)
ezt írta:

**Comment by kberg** [comment]
I haven't looked into this.

**Comment by kberg** [comment]
I've scanned the payment code, and agree this should not be an issue. Thank you!
