### ISSUE TITLE
Empty project deck with global event that puts floaters on a card makes the game stuck

### ISSUE THREAD

**Issue by sanyassh** [terraforming-mars/terraforming-mars#6455]
Please see https://terraforming-mars.herokuapp.com/player?id=pe12834fed7dc for logs or smth. When I resolve the event and put floaters on some card and click "Add resources", the game says "Error with input: unexpected empty project deck". After that I am not able to do anything in the game. I reload the page, the generation is increased and that's all. It is 21st generation now and it seems infinite. Sadly, this error prevented me from getting something like 2000+ vps in 12 generations in solo game...

**Comment by kberg** [comment]
Duplicate of #5163
