### ISSUE TITLE
Game stuck after playing New Venice

### ISSUE THREAD

**Issue by kberg** [terraforming-mars/terraforming-mars#6457]
https://discord.com/channels/737945098695999559/742721510376210583/1212796235778363453

![image](https://github.com/terraforming-mars/terraforming-mars/assets/413481/98dabb86-f3eb-4099-b3df-9f3bb1dc20dc)

https://terraforming-mars.herokuapp.com/spectator?id=sad087039fbf7

**Comment by Borbarad2** [comment]
Is this issue now solve, too? and could it be closed?
Because issue #6605: "New Venice is not compatible with Martian Lumber Corp" is closed now. https://github.com/terraforming-mars/terraforming-mars/issues/6605
