### ISSUE TITLE
Soil Enrichment stuck

### ISSUE THREAD

**Issue by terraformerG** [terraforming-mars/terraforming-mars#6469]
I had PSYCHROPHILES with 3 microbe resources and played SOIL ENRICHMENT by spending all of them.
These were the only microbe resources I had, so I ended up with 
"Select card to remove 1 microbe from"
and no option to chose, thus the game was stuck.

**Comment by kberg** [comment]
Click the gear icon, then click Report a Bug. Copy that information into
this bug, please. That way i can try to see what's going on.
