### ISSUE TITLE
Playing Neutrinograph or taking Microgravimetry action is not available if all tiles are identified

### ISSUE THREAD

**Issue by sanyassh** [terraforming-mars/terraforming-mars#6471]
I wanted to use Microgravimetry to just put lots of data on it to get VPs, but the action is not available. Also, Neutrinograph, which seems to be able to help with it (allows to re-identify), cannot be played from my hand. Is it intended behaviour of these cards?

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=se4dc8f02592a",
  "color": "green",
  "step": 647,
  "version": "d3eef72",
  "builtAt": "Sat, 02 Mar 2024 17:57:02 GMT",
  "browser": "Chrome 122",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
It's a bug that Neutrinograph can't be played when all spaces are identified, since its effect takes place before the step identifying two spaces. I can fix that. If it were playable, then Microgravimetry should work. Should be easy enough to fix in the next day or two.
