### ISSUE TITLE
Allow for real-time play

### ISSUE THREAD

**Issue by matthiasGmayer** [terraforming-mars/terraforming-mars#6478]
I suggest a fast-paced game mode option, where instead of going in turns during the action phase, each player is allowed to take actions until they pass. This would be perfect for games, where you don't care about optimizing every last victory point, but instead want a short game. It would also introduce a dynamic element in each round, where players might race to e.g. raise the temperature to get the bonus.

**Comment by Borbarad2** [comment]
Hi, are you German?

**Comment by matthiasGmayer** [comment]
Yes.

**Comment by kberg** [comment]
@matthiasGmayer I appreciate the feature request. Thank you. While I can see the interest in such a feature, I don't see implementing it. This is the kind of thing that is probably best made in a separate fork.

Have you actually played this way? Is this your local meta or something that is looked for in general by the community?

**Comment by ChillyTheEevee** [comment]
I can assure this is absolutely the kind of feature that my friend group would love to toy around with! Often when we would play Mars together, we would end up getting burnt out near the end of a 3+ hour session and just start taking turns in this way. It surprisingly introduces some really interesting dynamics!

**Comment by ChillyTheEevee** [comment]
This type of feature would bring back lots of great memories

**Comment by kberg** [comment]
Got it. I'll stick to my suggestion about have a good different fork that implements your feature.
