### ISSUE TITLE
Mars Nomads placement restriction

### ISSUE THREAD

**Issue by terraformerG** [terraforming-mars/terraforming-mars#6479]
Small thing, but nevertheless... When playing Mars Nomads and with only 5 M€ left, it is forbidden to chose a "pay 6M€ to place an ocean" as the initial position. This should not be so, since you're only triggering Nomads effect after playing its action, NOT after playing a card.

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s82d0a4de393f",
  "color": "blue",
  "step": 77,
  "version": "d168945",
  "builtAt": "Mon, 04 Mar 2024 16:55:17 GMT",
  "browser": "Safari 16",
  "language": "en",
  "experimental_ui": false
}Please include:
1. A clear and concise description of the bug.
2. Clear steps to reproduce, and the expected behavior.
3. Any screenshots
4. Any information from  the Bug Report Dialog

**Comment by kberg** [comment]
This is a small thing, but it makes sense, and should be a simple fix.
Thanks.
