### ISSUE TITLE
Prelude Science tags not counting towards Project requirements

### ISSUE THREAD

**Issue by rugvedpund** [terraforming-mars/terraforming-mars#6485]
Please include:
1. A clear and concise description of the bug.
Prelude card w/ Science tag is not included in the total tags played so far

2. Clear steps to reproduce, and the expected behavior.
[Corp] UNMI w/ [Prelude] Io Research Outpost (1 Science Tag)
Play: [Project] Tech Demo (1 Science Tag)
Have: [Project] Plantation (Requires: 2 Science Tags)
Have: Sufficient $MC to play [Project] Plantation

Expected: Can play [Project] Plantation
Bug: Cannot play [Project] Plantation

4. Any screenshots
![image](https://github.com/terraforming-mars/terraforming-mars/assets/72617859/631684df-a91b-47e8-ba0e-c70c60663bc2)
![image](https://github.com/terraforming-mars/terraforming-mars/assets/72617859/0b0cd59f-6c4c-4ea8-a82f-358fdbeca274)

6. Any information from  the Bug Report Dialog
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s7bfdc9ef4f35#actions",
  "color": "red",
  "step": 6,
  "version": "d168945",
  "builtAt": "Mon, 04 Mar 2024 16:55:17 GMT",
  "browser": "Firefox 123",
  "language": "en",
  "experimental_ui": false
}

**Comment by Borbarad2** [comment]
Event cards do not count against you tag count.!
Thus no bug!!

**Comment by rugvedpund** [comment]
Oh that's totally my fault. Thank you for your response, and my apologies for the spam issue. Have a great day!
