### ISSUE TITLE
Add a text box for strategy notes for each player 

### ISSUE THREAD

**Issue by hjklapp** [terraforming-mars/terraforming-mars#6492]
When playing drawn out games, it can be difficult to remember the strategy (and get caught by flashy cards while drafting ;) ). 

I propose to include a text box for each player, where they can write down some hints what they plan to do. 

It would even more useful, if it could be committed to the database even when other choices are not. This happens when not all players select there starting cards between server restarts. Then all players have to choose again, and in this situation a note with a plan for the game would be very helpful. 

Of course notes could be taken in a separate app, but it would be a nice quality of life feature to have the notes on the same page. 

For the entered text, autosave would be nice, however a save button is also fine.

**Comment by kberg** [comment]
Thanks for the suggestion, I appreciate it.

If it does get implemented it won't happen for quite some time. This is something you can do just fine with a document in the cloud, and I'd like to avoid having any kind of arbitrary data on our servers.
