### ISSUE TITLE
Feature request: allow undo passing in solo game.

### ISSUE THREAD

**Issue by sanyassh** [terraforming-mars/terraforming-mars#6494]
I had a perfect solo game, but something went wrong with the page and I accidentally passed. I really need to undo passing and take lots of actions in previous generation. Is it possible to implement?

**Comment by kberg** [comment]
Sorry for not responding: no, not really. Once you pass you see all the cards. I could add an "are you sure you want to pass" confirmation for new players.

**Comment by kberg** [comment]
If the confirmation was trivial I'd add it, but it's just a bit more work than I think is worth it. A confirmation isn't bad, but I'm closing this for now.
