### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Clement-Fiquet** [terraforming-mars/terraforming-mars#6495]
Hi there,

I'm totally new on the open source community but after playing i want to help this project. I've been reading "Contributing" and "Readme" and i don't really understand how to contribute. As a french i want to help with the translation, some cards, mostly moon related are not translate.

Are you looking for some help and how can i start working for you ?

Have a great day

**Comment by kberg** [comment]
I wrote a starter doc for you. Sorry it's not simple. Follow up with questions.

https://github.com/terraforming-mars/terraforming-mars/wiki/Translations

**Comment by Borbarad2** [comment]
As K9 said check the wiki.
I would recommend start to use the already existing french translation, and improve it with help of the German translation.

**Comment by Clement-Fiquet** [comment]
Hi there,
Thanks for your reply, a friend taught me how to create a commit and some
of the basics. What is your opinion about generating translations ? We want
to try to generate it but we need your permission, if you're not ok with
that we can do this manually

**Comment by kberg** [comment]
There is already a French translation. If you want to add to it, please do.

**Comment by Titozzz** [comment]
(Friend here), the question was, can we generate the missing translations using ChatGPT (or any other model) ?
I believe it should be fairly straightforward to give the current dictionary and train the prompt to get satisfying results

**Comment by kberg** [comment]
When you provide a pull request you are attesting that the context meets our license requirements (GPL3.) I cannot tell you whether Chat GPT's output (or any other tool) is permissible. No matter the source, i expect the person submitting translations is certain the translations are correct.

Sorry, I hope that helps.

**Comment by Titozzz** [comment]
Sounds good, thanks for your answer

**Comment by kberg** [comment]
Any plans for progress?

**Comment by kberg** [comment]
I am closing this issue. I think it's a good bit of work to do, but the issue can be closed and we can still have conversation. If you decide you want to work on this, please reply. If not, then thank you for considering it.
