### ISSUE TITLE
Include tag percentages on cards which indicate a tag.

### ISSUE THREAD

**Issue by 707090** [terraforming-mars/terraforming-mars#6498]
As a new player, I would find it helpful if cards indicated the commonality of the tags which are involved. For example, in the Search for Life card, it would be helpful to me if it instead said:
"Action: Spend 1 M€ to reveal the top card of the deck. If that card has a microbe tag **(27%)**, add a science resource here.)"

This would also be helpful for understanding the difficulty of requirements. For example Anti-Gravity Technology could say "
(Requires 7 science tags **(18%)**.)".

This would also be helpful when playing with expansions changes the ratio of various tags, since it could dynamically adjust the percentage shown to the current card list.

Pros:
It would be easier to tell how common each tag is in the given game for situations like requirements.

Cons:
It would make the text on many cards slightly longer.
It may be hard to dynamically change card text every game? (I have not looked into how this app is coded yet)

**Comment by kberg** [comment]
I agree that would be helpful. I'm not sure it would be so easy. I'll keep this open as an feature request, but it'll be tricky to do.

**Comment by kberg** [comment]
Actually, this is of pretty limited use (other than generally learning tag distributions.) There's probably another way to do this without disrupting the game.

**Comment by 707090** [comment]
Could you clarify what you mean by "without disrupting the game"? Are you thinking like adding an on-hover effect or something?

**Comment by kberg** [comment]
Thinking this through, I'm going to close it. It gets complicated when corporations have tags, preludes have tags. etc.
