### ISSUE TITLE
Mining Guild doesn't work on the moon 

### ISSUE THREAD

**Issue by Titozzz** [terraforming-mars/terraforming-mars#6509]
Mining Guild passive doesn't active for placement on the moon.
It might be too strong if it worked but it should be specified that it doesn't as it's unexpected and plan breaking 😂 
Can make a PR if needed to document the card

Debug data:
```
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s8436c865b526",
  "color": "yellow",
  "step": 22,
  "version": "8cb9a67",
  "builtAt": "Wed, 20 Mar 2024 15:41:02 GMT",
  "browser": "Chrome 123",
  "language": "fr",
  "experimental_ui": true
}
```

**Comment by Borbarad2** [comment]
There is a rule for it:

Compatibility issues

    Philares and Mining Guild do not trigger when tiles are placed on the moon. This is an intentional decision to prevent them from being overpowered.

https://github.com/terraforming-mars/terraforming-mars/wiki/The-Moon#compatibility-issues

**Comment by Titozzz** [comment]
Alright, should I add a comment on the card text ? Or I can just close that issue

**Comment by kberg** [comment]
I am very reluctant to add text to official cards. I'm thinking of an alternative.

**Comment by Borbarad2** [comment]
I think, just close the issue.

**Comment by Titozzz** [comment]
Feel free to close. Happy to help if needed.

**Comment by kberg** [comment]
Like I said, I think I have a solution, but it will take a while.
