### ISSUE TITLE
Browser tab crashes when attempting to view opponent's played cards

### ISSUE THREAD

**Issue by ERamseth** [terraforming-mars/terraforming-mars#6531]
Please include:
1. A clear and concise description of the bug.

While playing, when I clicked on the "show" button under the blue-green-red icon to see my opponent's played cards, the browser tab crashes. Possibly related: opponent had over 50 cards played

2. Clear steps to reproduce, and the expected behavior.

Click on the "show" button under the blue-green-red icon in the opposing player "tray" to show played cards.

3. Any screenshots

No

4. Any information from  the Bug Report Dialog

Not possible since tab crashes

This is on iPad. 

iPadOS 16.6.1
iPad model name: 9th generation
Firefox 124.2
Safari version 16.6

**Comment by ERamseth** [comment]
Game is here (but I guess will be purged by 14 Apr 2024)

https://terraforming-mars.herokuapp.com/spectator?id=s7baf1a0d24f3

**Comment by kberg** [comment]
I can't reproduce this, sorry. I assume it isn't still an issue.
