### ISSUE TITLE
Random cards from show up in predlude choice

### ISSUE THREAD

**Issue by phcqmfd** [terraforming-mars/terraforming-mars#6577]
When choosing add additional card, cards choosen, then some of these cards show put in the prelude choices when playing with an initial draft draft

**Comment by kberg** [comment]
There isn't really any information in your report that I can use to find it any problems.

Please provide 1. a link to the game, 2. which cards you did not expect, and 3. why didn't you expect them?

**Comment by phcqmfd** [comment]
happens on any game where the additional cards are added.  The cards show up as ceo card that you get to select as a CEO or prelude.  Here are links to a of game where it happens.  I happens with every game that I created using CEOs and additional cards 

https://terraforming-mars.herokuapp.com/player?id=ped8dbae73d5c  you will notice that space war games shows up as a CEO card

https://terraforming-mars.herokuapp.com/player?id=p67699bff8de1 you will notice that whales shows up as a CEO card

**Comment by kberg** [comment]
Screenshot:

![image](https://github.com/terraforming-mars/terraforming-mars/assets/413481/e3e913c8-c7f9-4cd7-a0a8-40f9fd5c5e1c)

Game options: 
![image](https://github.com/terraforming-mars/terraforming-mars/assets/413481/32876d7b-78e7-4fd1-84e0-9b3bf1228869)

This must have come from https://github.com/terraforming-mars/terraforming-mars/pull/6502, written by @rvangrinsven

@rvangrinsven this isn't working. Can you please take a look?

**Comment by kberg** [comment]
Looks like #6586 is a good candidate.
