### ISSUE TITLE
Provide visual tip that a colony is unplayable when resource types are not yet in play

### ISSUE THREAD

**Issue by blazcowicz** [terraforming-mars/terraforming-mars#6583]
When playing with Colonies, if Titan is in the game, it doesn't seem to work at all. The white cube doesn't appear, and Titan itself isn't offered as a choice with both colonies actions. It essentially means you are playing with one less colony.

Of course it can be avoided by relaunching a game when Titan has been drawn, but on my last game it handicapped a player that wanted to score off floaters. It would be really nice if it could be fixed or if it was possible to exclude it when selecting the Colonies expansion to avoid the hassle.

![Titan](https://github.com/terraforming-mars/terraforming-mars/assets/1914226/9364bf86-16ae-4df0-a7ac-b0108137b45f)

**Comment by Borbarad2** [comment]
No bug, worked as intended. 
A colony with a special resource is not active as long nobody could/is able to hold that kind of resource. The colony gets active as soon someone played a card which could hold that kind of resource. 
Miranda is another good example of this behaviour.

**Comment by blazcowicz** [comment]
Sorry for the false alarm then! I haven't played with Colonies that often and I guess I had missed that instruction in the rulebook.
 
It could be nice if the game indicated this with a label, an icon or in its description though (something like "this Colony enters the game the first time a player a matching card" or something).

**Comment by kberg** [comment]
@blazcowicz I can understand why you might ask for that. It seems like something worth adding in what we have as "learner mode" but I don't see doing it any time soon.

**Comment by kberg** [comment]
One option: 
![image](https://github.com/user-attachments/assets/54b171bf-f909-4f65-9b20-23cb8227d2b9)
