### ISSUE TITLE
Can't claim Firestarter milestone via floaters when playing Stormcraft Incorporated

### ISSUE THREAD

**Issue by tamasrobertmezei** [terraforming-mars/terraforming-mars#6646]
Stormcraft Incorporated should be able to convert floaters to heat resources, and thus possibly claim the Firestarter award even when possessing fewer than 20 heat resources.

**Comment by kberg** [comment]
Thanks for your report.

For the same reason that Stormcraft Incorporated does not apply to Thermalist, I think it does not apply here as well.

https://boardgamegeek.com/thread/2108715/article/30672335#30672335

**Comment by kberg** [comment]
I'm going to close this issue, but if you want to reopen it, please feel free to add more comments and help me see any flaws in my understanding.
