### ISSUE TITLE
Unable to build a colony on Leavitt, still credited with the colony build bonus

### ISSUE THREAD

**Issue by Erostal** [terraforming-mars/terraforming-mars#6664]
When a player attempted to build a colony on Leavitt, the game produced an error, but credited the player with a science tag which is the build bonus for Leavitt. He attempted to build the colony twice more, producing the same error, and each time was given the science tag (e.g. he got three science tags but no colony). Unfortunately I didn't capture the error message, but hopefully you can pull it from the Game ID.

It seems like the build got stuck partway through it's execution. The only result seems to have been the extra science tags. We didn't attempt to build any more colonies on Leavitt, but when trading with it he wasn't prompted for its colony bonus.

Game ID: g85fe33dd7942
Game log attached
[TFM Game Log May 5, 2024.txt](https://github.com/terraforming-mars/terraforming-mars/files/15214819/TFM.Game.Log.May.5.2024.txt)

Thanks for such a great service!

**Comment by kberg** [comment]
The error would be useful, actually. Any chance you could recall it?

**Comment by Erostal** [comment]
The player didn’t recall the specifics, but got back to me with “Something about the count being incorrect and it couldn’t increase the number.”

Sorry - next time I’ll have them capture it in the moment.

**Comment by kberg** [comment]
Which player, and when did it occur? The log doesn't mention it, unfortunately.

**Comment by kberg** [comment]
I found it, was it Nadeem during generation 8?

**Comment by Erostal** [comment]
Correct, Nadeem in Gen 8.

**Comment by kberg** [comment]
Thanks. I see the error and I am correcting it. Lucky Nadeem.
