### ISSUE TITLE
merge the first action

### ISSUE THREAD

**Issue by jijiqw** [terraforming-mars/terraforming-mars#6672]
The first action is still just one action, but many things can happen in that action, just as when you play a card with multiple effects.

https://boardgamegeek.com/thread/2874012/article/40859020#40859020

**Comment by kberg** [comment]
Is there a bug?

**Comment by jijiqw** [comment]
yeah, there may be . as the article comment :

> 
>  I played Valley Trust. I played my two preludes then did the first automatic action to get a third prelude. I picked Merger. That gave me Philares. So, I decided I needed to immediately take ITS first action (place a greenery tile).
> Not a big deal in solo really, but got me thinking about if this happens in multiplayer does all of that count as one first action or two? 

that should count as one action , then I could have another action  in  my first turn . 

In another scenario, if I play two preludes,  MERGER and DOUBLE DON, and I have three corp with initial actions,  then I will not be able to build colonies or other things in the first round, which will have a significant impact

**Comment by kberg** [comment]
Can you share a link to the game where the problem occurred?

**Comment by jijiqw** [comment]
https://terraforming-mars.herokuapp.com/game?id=g3ce3da1018a6
https://terraforming-mars.herokuapp.com/player?id=p2c600b3581b9
I  just created a game

**Comment by jijiqw** [comment]
the Red player  took 2 'first action' then auto end turn

**Comment by kberg** [comment]
Sorry for the long delay. I see it now, and I have a fix.
