### ISSUE TITLE
Selection Error/Bug

### ISSUE THREAD

**Issue by yhj410** [terraforming-mars/terraforming-mars#6677]
Please include:
1. During Card Buying Phase, the cards I selected to buy got discarded, and the one's un-highlighted got bought out.
2. Around Generation 3, attempt to buy two cards, and see if the correct two cards get bought out.

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=se16a379ad09a#cards",
  "color": "orange",
  "step": 87,
  "version": "59f73f5",
  "builtAt": "Thu, 09 May 2024 13:26:17 GMT",
  "browser": "Chrome 124",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
This seems very unlikely. I have tested this at generation 3 and everything worked as expected. If you have more information I will reopen this bug.
