### ISSUE TITLE
Prelude Cloud Vortex effect becomes available whenever game reloads 

### ISSUE THREAD

**Issue by Vulptrix** [terraforming-mars/terraforming-mars#6679]
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s5d28c3968f91",
  "color": "red",
  "step": 196,
  "version": "59f73f5",
  "builtAt": "Thu, 09 May 2024 13:26:17 GMT",
  "browser": "Chrome 124",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Thanks for this report. I see now that the issue is that the card isn't being serialized correctly. :/
