### ISSUE TITLE
Tag count not showing on dashboard correctly

### ISSUE THREAD

**Issue by angw135** [terraforming-mars/terraforming-mars#6691]
Please include:
1. A clear and concise description of the bug.
Tags not appearing right, even though I have 2 space tags, only one is showing. The person I'm playing with had a similar issue, they had 9 science tags, only 4 on the board.
3. Clear steps to reproduce, and the expected behavior.
4. Any screenshots
<img width="872" alt="terraforming mars" src="https://github.com/terraforming-mars/terraforming-mars/assets/41014992/e1edfb30-e329-4d98-a6b3-be9966879a03">

6. Any information from  the Bug Report Dialog

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=sf0bea96dac78",
  "color": "green",
  "step": 44,
  "version": "e4b943a",
  "builtAt": "Fri, 24 May 2024 04:08:10 GMT",
  "browser": "Chrome 125",
  "language": "en",
  "experimental_ui": false
}

**Comment by d-little** [comment]
Tags on Events are not counted. You will notice that your Space and Earth tags are also affected.

https://github.com/terraforming-mars/terraforming-mars/wiki/FAQ#why-arent-tags-on-my-event-card-taken-into-consideration
