### ISSUE TITLE
Drafting fail

### ISSUE THREAD

**Issue by theeagle1968** [terraforming-mars/terraforming-mars#6693]
Please include:
1. When going to drafting, it jumps right to research, says I can't afford cards, and gives no options. Same for all players. 
2.  To reproduce, simply open game. https://terraforming-mars.herokuapp.com/player?id=p45832e80010
3.  See screenshot
4
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s61835f5dc98a",
  "color": "green",
  "step": 223,
  "version": "8c7929d",
  "builtAt": "Mon, 27 May 2024 14:57:19 GMT",
  "browser": "Chrome 125",
  "language": "en",
  "experimental_ui": false
}
![Screenshot_20240527-101900_Chrome](https://github.com/terraforming-mars/terraforming-mars/assets/118016446/d365fce8-544b-4250-a5be-e8b0bf391b49)

**Comment by kberg** [comment]
Thank you. I am initiating a rollback, but the game will be broken for a bit. See https://discord.com/channels/737945098695999559/743789409396195329/1244682575285321810

**Comment by kberg** [comment]
OK, here's what's happening: When moving from the currently deployed version to the one which causes this error, the internal data format has changed. That's fine, there's some migration code. But for some reason, it's not migrating from the old version to `player.needsToDraft`. A good test and a little time and this should be fine.

**Comment by kberg** [comment]
Fixed with #6699
