### ISSUE TITLE
Unexpected server response 

### ISSUE THREAD

**Issue by Dienekes7** [terraforming-mars/terraforming-mars#6694]
Hi,

We seem to have lost another 4 player game to an unexpected server response. I only started this one yesterday. I would usually have the game ID accessible but that information has been lost too. Is it still 15 days to finish games?

This is the third game in 3 days that has dropped out. Have these issues been reported to you by others and is there a fix, please?

Thanks, Neil

**Comment by kberg** [comment]
Thanks for the report. https://discord.com/channels/737945098695999559/743789409396195329/1244682575285321810 Closing this for now.

**Comment by Dienekes7** [comment]
Thank you. I don't use discord though. Is this something you can look into please? I don't really want to start games, get 3 gens in and lose them. Thanks, Neil

**Comment by Dienekes7** [comment]
Working again, thank you
