### ISSUE TITLE
Unexpected server response: Not found

### ISSUE THREAD

**Issue by Ercole1986** [terraforming-mars/terraforming-mars#6695]
Twice in a row, the game server for a 4-player game stops working after approximately two days of gameplay, displaying the error "tu teść." The first occurrence was around May 24, 2024 (game link: "http://terraforming-mars.herokuapp.com/player?id=pdfca956f236"), and the second one happened today, May 27, 2024 (game link: "http://terraforming-mars.herokuapp.com/player?id=pbeaff7dee06b"). The main page works flawlessly. For the second game, it stopped working around 2 AM according to the time indicated on the main page. (For me, it was around 4 PM 😅). I'm not a programmer, so unfortunately, I can't provide any more detailed information. 
![Screenshot_20240527_190504_com huawei browser](https://github.com/terraforming-mars/terraforming-mars/assets/147085405/620fb0a4-f910-40d2-a0c5-d0f61025e048)

**Comment by kberg** [comment]
Thanks for the report. https://discord.com/channels/737945098695999559/743789409396195329/1244682575285321810 Closing this for now.
