### ISSUE TITLE
Double city after reloading

### ISSUE THREAD

**Issue by Fdavidtr** [terraforming-mars/terraforming-mars#6698]
My friend was able to put a free city just reloading the page when she had to place her city

![image](https://github.com/terraforming-mars/terraforming-mars/assets/9017067/71f48e2f-633d-465d-985b-826786d8eb44)
(the image is cut but it is 9th generation)
We are not sure if it was an eventual bug or something easy to reproduce
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s9e414eb851e5#board",
  "color": "red",
  "step": 108,
  "version": "e4b943a",
  "builtAt": "Fri, 24 May 2024 04:08:10 GMT",
  "browser": "Chrome 125",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Thanks, I will look.

**Comment by kberg** [comment]
The issue was that the player placed on the temperature space but did not have the 3MC. For some reason it still placed the city and allowed the player to place another one. OK, thank you.
