### ISSUE TITLE
Mars Math(?) Bug where Mars Math player eats other cards from draft and can draft 5 cards.

### ISSUE THREAD

**Issue by pandavenger** [terraforming-mars/terraforming-mars#6703]
Reproduction (possibly): Merge Mars Math + Viron. Do Double Mars Math Action on the first term.

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=sc0dad76a173a",
  "color": "yellow",
  "step": 102,
  "version": "8fbfe01",
  "builtAt": "Sat, 01 Jun 2024 10:11:45 GMT",
  "browser": "Firefox 126",
  "language": "en",
  "experimental_ui": false
}

![image](https://github.com/terraforming-mars/terraforming-mars/assets/1500800/1685b943-69d4-444c-b940-12d6f2a1c8a8)

This player should have 2 cards to choose from here:
![image](https://github.com/terraforming-mars/terraforming-mars/assets/1500800/691f149e-9b9e-4238-a74b-b9d391425e9c)

**Comment by kberg** [comment]
Sorry about this one! I rewrote drafting to make more sense, but obviously broke a couple of things along the way. My apologies.

**Comment by kberg** [comment]
This is fixed and will be deployed momentarily.
