### ISSUE TITLE
Underworld: Player should see potential loss when deciding to spend corruption 

### ISSUE THREAD

**Issue by puuj** [terraforming-mars/terraforming-mars#6711]
Currently, when a player is attacked and might lose a resource, the prompt to spend corruption to avoid the loss doesn't inform the player of what the potential loss would be. For example: Player A has 2 cards with microbes, Tardigrades and Regolith Eaters, is attacked  by Player B's Ants.  Player A would spend corruption to block an attack on Regolith Eaters but not on Tardigrades. Currently the only way to determine this is an out-of-game message. If the log showed the potential attack or the prompt showed the potential attack, that would simplify the decision.

**Comment by kberg** [comment]
The player can't see it from the game log?

**Comment by puuj** [comment]
Here's the log. The line "B removed 1 resources from A's Tardigrades" did not show up until after the corruption choice was made.
![image](https://github.com/terraforming-mars/terraforming-mars/assets/58322/72dd05ae-aec9-4319-9233-fdd5586ff863)

**Comment by kberg** [comment]
When you're right, you're right.

**Comment by kberg** [comment]
![image](https://github.com/user-attachments/assets/dc05d2a3-9592-41c9-9821-4e67e6d63354)
![image](https://github.com/user-attachments/assets/6299494b-be02-406d-b8dc-cdbb6eddce8e)
