### ISSUE TITLE
Cannot only use Prelude 2

### ISSUE THREAD

**Issue by puuj** [terraforming-mars/terraforming-mars#6712]
The Game Setup dialog allows Prelude 2 to be selected independently of Prelude. However, when only Prelude 2 is selected , there is no Prelude draft which is unexpected. Either selecting Prelude 2 should auto-select Prelude or all logic about preludes should check both the preludeExtension and prelude2Expansion options.

**Comment by Borbarad2** [comment]
No, please not. I really like, that you can play Prelude2 without the need of the prelude cards included. 
Thus both option are avaialable: Playing Prelude2 with or without prelude cards. Nice.

**Comment by kberg** [comment]
Hi - I figured this could come up. And now that you mention it, automatically selecting prelude when selecting prelude2 makes sense. Players can unselect it. And I'll have to make sure that it doesn't trigger uploaded JSON.

**Comment by kberg** [comment]
That's correct. But that's how preludes are selected already.
