### ISSUE TITLE
Active player unable to take actions after long delay

### ISSUE THREAD

**Issue by CGGranda** [terraforming-mars/terraforming-mars#6720]
I took one action, which did get processed, then left due to an internet outage.  When the internet went out, I had just clicked on the confirm button to send the free delegate per turn. The outage caused the button to confirm to spin, as though it were thinking. After closing the window and coming back 17 hours later, I am still the active player, but neither myself nor the second player can take any actions.

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s234eca15c676",
  "color": "red",
  "step": 174,
  "version": "1bbef63",
  "builtAt": "Fri, 07 Jun 2024 02:42:08 GMT",
  "browser": "Opera 109",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
I currently see that the player Grayson may take an action. Whatever happened, I probably can't find out now, so I'm closing the bug. Enjoy the game!
