### ISSUE TITLE
Feature request: option to require "end turn" after second action

### ISSUE THREAD

**Issue by dwballance** [terraforming-mars/terraforming-mars#6721]
My play group is finding that the automatic passing feature means that it is not possible to "undo" the second action. My suggestion is to add a game config that requires the "end turn" action be selected after completing the second action. (this would also be helpful on mobile device games where the risk of fat-fingering the second action is higher!)

Thanks for an amazing implementation!

**Comment by kberg** [comment]
I hear you. In my opinion the appropriate change is to make auto pass available even when it is not your turn. This is going to take some significant internal work, surprisingly. Rather than take on two significant changes, I'd rather move toward that one.

I'm closing this for now, but if you feel strongly about this, please reply to this issue.

**Comment by dwballance** [comment]
That is also a useful enhancement. Am I correct that it doesn't alter the current behavior of undo only applying to the first action? (My suggestion isn't an urgent one, btw. I can certainly live with "plan more carefully", lol!)

--Dennis
________________________________

**Comment by kberg** [comment]
This behavior doesn't interfere with undo.

**Comment by dwballance** [comment]
Will there eventually be a way to undo the second action in a turn, before the next player has taken their first action?

--Dennis
________________________________

**Comment by kberg** [comment]
I don't see such a feature for a while. My view of the undo that exists now is that it was hacked together because it was necessary, but it's less than ideal. I have a generally untested replacement feature (which used to be available in solo games, but was turned off due to a lack of feedback.)

**Comment by dwballance** [comment]
Gotcha, thanks!

--Dennis
________________________________
