### ISSUE TITLE
Incorrect ocean bonus given for placing an ocean between two other oceans

### ISSUE THREAD

**Issue by PhilShih** [terraforming-mars/terraforming-mars#6732]
In this game, there was an ocean tile on Row 2 position 6. I played Ice asteroid to place two oceans, which I put at row 1 position 4 and row 1 position 5. For the second ocean placed, it was next to two other ocean tiles so I should have received 4 megacredits for this, however I received 3 instead.

<img width="973" alt="Screenshot 2024-06-12 at 1 20 52 PM" src="https://github.com/terraforming-mars/terraforming-mars/assets/8762699/67ddaa31-886f-42dd-98e1-34345d095b47">
<img width="819" alt="Screenshot 2024-06-12 at 1 20 58 PM" src="https://github.com/terraforming-mars/terraforming-mars/assets/8762699/cde7b897-c81b-43cb-b9db-83dda1a4383f">

Bug Report Dialog:
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=sa0435b27f1e8",
  "color": "red",
  "step": 112,
  "version": "9118498",
  "builtAt": "Sun, 09 Jun 2024 10:36:40 GMT",
  "browser": "Chrome 125",
  "language": "en",
  "experimental_ui": false
}

**Comment by PhilShih** [comment]
Turns out it was a misunderstanding. The 3 credits I received in the log was from the card Media Group. I didn't realize that the ocean credit bonus doesn't show up in the log.

**Comment by kberg** [comment]
That's fair.
