### ISSUE TITLE
Card render bugs 

### ISSUE THREAD

**Issue by puuj** [terraforming-mars/terraforming-mars#6733]
After the latest changes, several cards render incorrectly. See Adhai, Ambient, and Arklight below.
<img width="1058" alt="image" src="https://github.com/terraforming-mars/terraforming-mars/assets/58322/f8a6ec9c-e5a5-4402-9e85-86f8b153e14b">

**Comment by kberg** [comment]
Thanks for the warning. I tested these! But they're broken, so I rolled
back.
