### ISSUE TITLE
mining guild not triggering when placing for alloy adjacency bonus in Ares

### ISSUE THREAD

**Issue by phillipfung3** [terraforming-mars/terraforming-mars#6734]
The title says it all
Me as mining guild placed a greenery next to mining right (steel) under Ares expansion, and the mining guild ability on gaining a steel production did not trigger, below is the log
![image](https://github.com/terraforming-mars/terraforming-mars/assets/172607360/4df1192d-cfc5-4ff1-9f62-45a6be48c46f)

it should trigger according to Ares FAQ

In my memory it triggered properly before, just suddenly it doesn't work anymore
We are playing on all official expansion (exclude turmoil), and moon, Ares, CEO

**Comment by kberg** [comment]
Click on the gear. Click on Report a Bug. Can you supply that information
please?

**Comment by phillipfung3** [comment]
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=se582fa1b50b3#cards",
  "color": "green",
  "step": 71,
  "version": "9118498",
  "builtAt": "Sun, 09 Jun 2024 10:36:40 GMT",
  "browser": "Chrome 125",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Looking this over, I think you are correct. The FAQ says at https://github.com/terraforming-mars/terraforming-mars/wiki/Ares

> Q: Is the special ability of the Mining Guild corporation triggered by adjacency bonus.
> 
> A: Yes. But if placing a tile grants bonus steel or titanium from several sources, the Mining Guild may still only increase their steel production 1 step for placing that tile.

But I think this is going to be pretty tricky.
