### ISSUE TITLE
CEO Neil seems not triggering on opponent playing moon tag

### ISSUE THREAD

**Issue by phillipfung3** [terraforming-mars/terraforming-mars#6748]
So I'm using Neil, I played a moon tag and received 1MC, which is totally correct
but when another player played moon tag (mare imbrium mine and rover driver union) it doesn't seems to trigger
for sure it is not just "missing in the log" as my MC didn't increase 
![image](https://github.com/terraforming-mars/terraforming-mars/assets/172607360/28ba751c-efc5-423d-95e0-e6d614206a12)
![image](https://github.com/terraforming-mars/terraforming-mars/assets/172607360/e611fdb4-88ab-437f-a1e0-5e64da5caa2b)
![image](https://github.com/terraforming-mars/terraforming-mars/assets/172607360/8aed0545-0f4a-4719-943a-24638fd012e5)
![image](https://github.com/terraforming-mars/terraforming-mars/assets/172607360/c48f769b-305b-45bd-9f89-2f3804003eda)

I know you need this :)
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=sa02dd2ac9d80",
  "color": "green",
  "step": 239,
  "version": "a15010e",
  "builtAt": "Sat, 15 Jun 2024 12:39:17 GMT",
  "browser": "Chrome 125",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Good spot. You're right, it didn't work correctly. I'm putting out a fix
right now. Thanks for the report.
