### ISSUE TITLE
Fail to block RECKLESS DETONATION with corruption available

### ISSUE THREAD

**Issue by Zzacko0** [terraforming-mars/terraforming-mars#6754]
Please include:
1. A clear and concise description of the bug.
In generation 8, pink player with 2 corruption played RECKLESS DETONATION and remove black player's 3 steel whose 1 corruption available was not able to be used for blocking the removal action. No option was given to the black player

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=sc1246b363032#cards",
  "color": "black",
  "step": 456,
  "version": "a15010e",
  "builtAt": "Sat, 15 Jun 2024 12:39:17 GMT",
  "browser": "Chrome 126",
  "language": "en",
  "experimental_ui": true
}

**Comment by kberg** [comment]
Thanks for this. I will look.
