### ISSUE TITLE
Initial draft returning AndOptionsResponse instead of SelectInitialCardsResponse

### ISSUE THREAD

**Issue by puuj** [terraforming-mars/terraforming-mars#6755]
Initial draft is returning an AndOptions object rather than a SelectInitialResponse object on the latest main branch. Since the rewrite of SelectInitialResponse hasn't made it to Heroku, can't reproduce on the official server. 
Specifically I am getting a "Not a valid SelectInitialCardsResponse" popup. Tracking that down and figuring what the response is via a debug statement: 

```
 if (!isSelectInitialCardsResponse(input)) {
      console.log(input);
      throw new InputError('Not a valid SelectInitialCardsResponse');
    }
```

yields
```
[2024-06-21 10:54:07 PDT] {
  type: 'and',
  responses: [
    { type: 'card', cards: [Array] },
    { type: 'card', cards: [Array] },
    { type: 'card', cards: [Array] }
  ]
}
```

I believe the type should be `initialCards` so this is breaking down somewhere along the way.

**Comment by kberg** [comment]
Yeah, the fix should be to change SelectInitialCards.vue, passing
'initialCards' where it passes 'and'.

I can't change that until Sunday unless you might want to send a PR? :-)

**Comment by puuj** [comment]
PR sent. Working on my end.
