### ISSUE TITLE
Public spaceline didn't provide MC production

### ISSUE THREAD

**Issue by phillipfung3** [terraforming-mars/terraforming-mars#6775]
![Screenshot_20240630_221634_Samsung Internet](https://github.com/terraforming-mars/terraforming-mars/assets/172607360/6088456c-eac6-4c1a-9972-107d0b243108)

as shown in screenshot, after playing public spaceline, gold production didn't increase 2 as shown on card
checked my actual gold income, for sure it didn't increase as well

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s5bcc8913eab2",
  "color": "green",
  "step": 243,
  "version": "fcb6b87",
  "builtAt": "Sat, 29 Jun 2024 13:11:58 GMT",
  "browser": "Chrome 121",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Wow, how did I miss that
