### ISSUE TITLE
Glitch during card draft, only able to purchase one card instead of four

### ISSUE THREAD

**Issue by Erostal** [terraforming-mars/terraforming-mars#6810]
This issue occurred while playing a two player game, during the second generation when drafting cards. While selecting the second card for the draft, both players experienced a freeze/hang on locking in the second card. After 5-10 seconds, both of the players refreshed the browser, which then jumped them to the card buying stage of the draft, however there was only one card available to purchase (see attached photo). The card was the first card selected from the draft, but the other 3 were effectively gone/discarded for both players. This issue did not recur in the following generations.

Debug Info:
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=sa6dcfc26d2e2&noredirect=",
  "color": "orange",
  "step": 396,
  "version": "d8e9413",
  "builtAt": "Fri, 12 Jul 2024 19:55:34 GMT",
  "browser": "Firefox 127",
  "language": "en",
  "experimental_ui": false
}

[TFM Game Log July 13, 2024.txt](https://github.com/user-attachments/files/16203645/TFM.Game.Log.July.13.2024.txt)
![Gen 2 Draft Issue](https://github.com/user-attachments/assets/843d1744-3452-4185-904d-be6a7032f572)

**Comment by kberg** [comment]
Thank you for your very detailed response. I'll take a look today.
