### ISSUE TITLE
Mars Nomad placement bonus is not removed from map

### ISSUE THREAD

**Issue by peonmodel** [terraforming-mars/terraforming-mars#6818]
After receiving the placement bonus for Mars Nomad, the bonus is not removed, enabling a re-visit for the same bonus again, this is especially broken when visiting the 3-cards placement bonus, its also against the theme as it promotes the nomads to alternate between just a few good locations

![Screenshot 2024-07-15 113019](https://github.com/user-attachments/assets/cf2ff570-772e-47d5-875f-074f2ae1251e)
initial state, 5 plants & 2 cards in hand

![Screenshot 2024-07-15 113101](https://github.com/user-attachments/assets/9912c27c-519a-4369-bf20-1b063e9a7a98)
after visiting the 2 plants placement spot, 7 plants in hand, note that the original spot still have the 1 card & the new spot still have the 2 plants

![Screenshot 2024-07-15 113222](https://github.com/user-attachments/assets/bb5c762a-9523-493c-97c9-925f9468f2c6)
going to the 3 cards spot increased cards in hand to 5 now, placement bonus is still not removed

i verified that it wasnt just a graphical glitch, i have gotten the same bonus on the same location more than once

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s3489af573e7a",
  "color": "red",
  "step": 10,
  "version": "2a19186",
  "builtAt": "Sun, 14 Jul 2024 17:08:09 GMT",
  "browser": "Chrome 126",
  "language": "en",
  "experimental_ui": true
}

**Comment by kberg** [comment]
I'm pretty sure that's how it's supposed to work. It's not an actual tile.
It's just a marker. So I think this is a disagreement on what the rule
actually is.

**Comment by peonmodel** [comment]
o yes, i was later informed that there was a rule clarification on BGG forum, but cant seemed to find the URL

please close the issue

**Comment by kberg** [comment]
Thanks for taking the time to report, and also to respond.
