### ISSUE TITLE
Co-Leadership during Action Phase results in player Free-for-All

### ISSUE THREAD

**Issue by ZoeILevine** [terraforming-mars/terraforming-mars#6821]
Please include:
1. All three players were able to take as many actions as they wanted whenever they wanted.
2. Unclear when in the game it started, nor is it clear exactly what caused it. But after a bit (I think after everyone passed), it went back to normal
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=scfc11dad0e1a",
  "color": "purple",
  "step": 198,
  "version": "2a19186",
  "builtAt": "Sun, 14 Jul 2024 17:08:09 GMT",
  "browser": "Chrome 126",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Can you be more specific? Which generation did this occur? And can you be
more specific about what you mean about "whenever they wanted" and "as many
actions as they want?"

**Comment by ZoeILevine** [comment]
I believe it was generation 7.

Normally each player who has not passed gets the opportunity to take up to 2 actions in turn order. Instead, all 3 players were able to take multiple (more than 2) actions, and were not limited to having them go consecutively (I was taking actions at the same time as the other two players). Does that help?

**Comment by kberg** [comment]
It does... but... It makes no sense at all! Anyway, I'll see what I can
find out. Thanks.

**Comment by kberg** [comment]
Sure looks like it was Generation 7.  I mean, this is wild:

[180/343]: purple used Board of Directors action
[180/344]: purple removed 1 resource(s) from purple's Board of Directors
[180/345]: purple played Co-leadership
[180/346]: purple played Asimov
[181/347]: purple used Junk Ventures action

**Comment by kberg** [comment]
Possible similar issue with https://terraforming-mars.herokuapp.com/spectator?id=s19c141ab620c

**Comment by kberg** [comment]
OK I found it. The issue is the combination of Board of Directors and Co-Leadership. (Prelude 2 + CEO)

The short version is that Co-Leadership takes the CEO in hand. Then the app thinks "Oh, you have a CEO. It's probably gen 1 CEO Phase" and then the game's state is entirely invalid.

**Comment by kberg** [comment]
This is fixed.
