### ISSUE TITLE
Unexpected Application is playable even though no card can be discarded

### ISSUE THREAD

**Issue by peonmodel** [terraforming-mars/terraforming-mars#6834]
Unexpected Application: discard a card to terraform Venus 1 step
this card should not be playable if there is no card to discard

![Screenshot 2024-07-17 104945](https://github.com/user-attachments/assets/11ce7836-3282-4b78-a369-967f60ea9f9d)
initial state: Venus at 16, only 1 card in hand (Unexpected Application), Unexpected Application is playable even though i do not fulfil the condition of having another card to discard

![Screenshot 2024-07-17 105026](https://github.com/user-attachments/assets/b1f4db90-29a5-46c2-8d81-503836a5567c)
Played Unexpected Application, bypassing the additional cost of removing a card, Venus is now at 18

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s45830d73aa4f",
  "color": "red",
  "step": 99,
  "version": "20792f5",
  "builtAt": "Tue, 16 Jul 2024 22:53:26 GMT",
  "browser": "Chrome 126",
  "language": "en",
  "experimental_ui": true
}

**Comment by kberg** [comment]
Thank you! I noticed this and hoped it wouldn't be seen for a while. But yeah I'll fix it now.
