### ISSUE TITLE
Server Crashing while drafting causes hard lock game state

### ISSUE THREAD

**Issue by jsmith613** [terraforming-mars/terraforming-mars#6839]
Please include:
1. A clear and concise description of the bug.
When in the first drafting round of a new generation, the game server crashed.  Upon reload, both players were shown no cards to draft.  We are shown the 'keep' button, but upon pressing the button, an error occurs.
2. Clear steps to reproduce, and the expected behavior.
- Start a new generation with drafting enabled
- Crash the server
- Reload the game
- Shown no cards to draft
- Hit Keep button
- Shown input error
3. Any screenshots
![Screenshot(18)](https://github.com/user-attachments/assets/33ed77ba-a2c9-4d1c-a4e2-cf8e63b2ab33)
![Screenshot(19)](https://github.com/user-attachments/assets/0ce93e31-091d-43f1-bbf2-b4b9fa9941b8)
4. Any information from  the Bug Report Dialog
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s7593ad0c9913",
  "color": "blue",
  "step": 64,
  "version": "20792f5",
  "builtAt": "Tue, 16 Jul 2024 22:53:26 GMT",
  "browser": "Firefox 128",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Thank you. I'm glad this was fixable.
