### ISSUE TITLE
suggestion: clarify description on Gaia city

### ISSUE THREAD

**Issue by phillipfung3** [terraforming-mars/terraforming-mars#6854]
ok this is not a bug
currently, description of Cave city specifies "Regular placement restriction still apply"

yet for Gaia city the description only says it have to be in a space with excavation marker
If someone happens to have both Cave city and Gaia city on hand, it would be easy for them to think Gaia city bypass normal city placement rule and can be placed adjacent to other cities. Yet I tested that it is not true and it respect normal placement rule.

I would suggest to specify "Regular placement restriction still apply" on Gaia city description just to be aligned. Thanks
![image](https://github.com/user-attachments/assets/1df69af9-62a1-4b01-b93a-2aed16293802)

**Comment by kberg** [comment]
Good question. I'm asking here: https://boardgamegeek.com/thread/2907313/article/44634570#44634570

**Comment by kberg** [comment]
Answered, You are right. Clarifying the card now.
