### ISSUE TITLE
Not able to play cards despite having playable cards in hand

### ISSUE THREAD

**Issue by doubleodenis** [terraforming-mars/terraforming-mars#6855]
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=sca6193feead9#actions",
  "color": "red",
  "step": 24,
  "version": "0ddc963",
  "builtAt": "Sat, 20 Jul 2024 01:36:34 GMT",
  "browser": "Chrome 126",
  "language": "en",
  "experimental_ui": false
}

![image](https://github.com/user-attachments/assets/d7b9e74e-495d-4e0f-b2a7-a2018222fa90)

I'm not able to play certain cards even though they have no requirements and I had enough resources/money to play them. It looked like I was capped to playing only 3 card options. Though in this case I couldn't play any.

**Comment by kberg** [comment]
Thanks for your report.

Three cards are unplayable just looking at your game state:
* Ganymede Colony - you can't afford it.
* Black Polar Dust - you can't afford it.
* Building Industries - you don't have the energy production.

The last one, Mining Area, requires that you already have a tile adjacent to one with a steel or titanium bonus. I can't see your map, but I'm certain that's the case.

Please add comments if you think this issue deserves further analysis.
