### ISSUE TITLE
Card List page doesnt filter awards & milestones by expansions

### ISSUE THREAD

**Issue by peonmodel** [terraforming-mars/terraforming-mars#6858]
this isnt a bug in the game, just the card list reference page

![Screenshot 2024-07-22 101049](https://github.com/user-attachments/assets/55216bbb-4410-4597-81d9-e64717f07f8f)
as attached, despite filtering out the non-official expansions, e.g. Moon, it still shows the lunar milestones

as unlike the cards which has the expansion icon on them, the awards/milestones doesnt, there is no way to tell if not already familiar with the game

**Comment by kberg** [comment]
Yeah. Those could use a touch-up. Thanks.
