### ISSUE TITLE
Venus tag missing?

### ISSUE THREAD

**Issue by djuelam** [terraforming-mars/terraforming-mars#6861]
Venus tags don't appear in player dashboards (at least when not playing with venus expansion) but I believe still count toward all card effects when counting tags.

**Comment by kberg** [comment]
I'd love to be able to help but can you please provide more information? Click the gear, click Report a bug, and copy the contents.

Also, please tell me which player and card you think is not being represented.

Thanks!

**Comment by kberg** [comment]
Closing for now. Feel free to add comments if you have more information to add, I'll see them.
