### ISSUE TITLE
SPECIAL DESIGN card not counting as a science tag "during play"

### ISSUE THREAD

**Issue by GeoffreyHull** [terraforming-mars/terraforming-mars#6862]
According to the rules. Page 10  section 3) Place the card (see illustration below).

```
Events (red cards, C) are collected in a personal pile
face down after being played. Their tags only apply while
being played (for example using the discount on card E when
playing a space event).
```
The science tag of the card should be counted until i have "used" it.

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s7e3549bf88c7",
  "color": "orange",
  "step": 99,
  "version": "62c25a3",
  "builtAt": "Sun, 21 Jul 2024 18:06:04 GMT",
  "browser": "Chrome 126",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
This is a degree of semantics, and while I understand your perspective, I think the semantics don't fall in your favor. After you play the card, you turn it face down. The fact that you keep it face up to remember the effect is not the same thing as the _entire_ card remaining in effect.

https://github.com/terraforming-mars/faq/wiki#do-tags-on-event-cards-have-any-effects

**Comment by kberg** [comment]
I'm closing the issue. If you think this is a mistake, and you have additional information, feel free to add it, and if it merits reopening I'll be happy to do it!
