### ISSUE TITLE
MUSK CEO employed twice

### ISSUE THREAD

**Issue by Farra96** [terraforming-mars/terraforming-mars#6863]
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s6f5b346ff16b",
  "color": "green",
  "step": 65,
  "version": "62c25a3",
  "builtAt": "Sun, 21 Jul 2024 18:06:04 GMT",
  "browser": "Chrome 126",
  "language": "en",
  "experimental_ui": false
}

For some reason, I manage to use the CEO twice in two consecutive genration.
It happened to already use MUSK ceo, and worked normally. This time, as visible in the log, it was utilized twice.

**Comment by kberg** [comment]
Thanks. I won't be able to look any time soon, but I hope to get to it by
this weekend.

**Comment by Farra96** [comment]
Thank you for coding this game for free online, you are amazing guys

**Comment by kberg** [comment]
I have looked at this game and I do not see Musk in play.

**Comment by kberg** [comment]
I'm closing since there has been no response. If you have more information, please let me know and I can reopen this.
