### ISSUE TITLE
Lunar Magnate award doesn't count Hostile Takeover tiles

### ISSUE THREAD

**Issue by ecureuiloeil** [terraforming-mars/terraforming-mars#6864]
Lunar Magnate award seems to not count moon tiles chosen by Hostile Takeover player, only crediting the original owner of the tiles. Since the two tiles are co-owned, the award should also count for the Hostile Takeover player.

We noticed this in two games.

**Comment by kberg** [comment]
Please provide a link to one of the games. If you still have an active
game, click the gear, then click Report a Bug, and paste that information
here.

Thanks!

**Comment by ecureuiloeil** [comment]
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s5cb98cc14926",
  "color": "green",
  "step": 273,
  "version": "62c25a3",
  "builtAt": "Sun, 21 Jul 2024 18:06:04 GMT",
  "browser": "Chrome 126",
  "language": "en",
  "experimental_ui": true
}
