### ISSUE TITLE
Game autopassed turn after trading with Leavitt.

### ISSUE THREAD

**Issue by pandavenger** [terraforming-mars/terraforming-mars#6867]
Please include:
1. Game autopassed my turn. It wasn't a misclick as I had already done 2 actions.
2. Do 1 Action, Trade With Leavitt, Refresh twice before trading. Browser was freezing up before this occurred
3. ![image](https://github.com/user-attachments/assets/9590ccdb-70ef-40d3-b1e9-476b1031cf47)
4. {
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=sea7d8fb4e5eb",
  "color": "yellow",
  "step": 323,
  "version": "d79227e",
  "builtAt": "Sat, 27 Jul 2024 02:28:20 GMT",
  "browser": "Firefox 128",
  "language": "en",
  "experimental_ui": true
}

**Comment by kberg** [comment]
I'm going to close this. There hasn't been much in the way of complaints or feedback in a while, so I think making it an experimental feature is enough for the time being.
