### ISSUE TITLE
Impossible to see black on black background

### ISSUE THREAD

**Issue by Maelstrom1** [terraforming-mars/terraforming-mars#6896]
![image](https://github.com/user-attachments/assets/c9bfe2c1-1d13-4f7e-82d6-aa7b2310b9a0)
You can't see black when waiting on the user. Maybe change the color for this part to grey or add a white outline?

**Comment by Borbarad2** [comment]
This issue came back with the fix: Now it looks like this: 
![grafik](https://github.com/user-attachments/assets/81baec9d-4ed7-484f-9f51-e58598bfbc6a)

You can't see colors when waiting on the user.
