### ISSUE TITLE
Floating Refinery (Prelude 2) unable to continue game because not enough floaters to remove

### ISSUE THREAD

**Issue by peonmodel** [terraforming-mars/terraforming-mars#6913]
Game is unable to be continued as there is no available cards to be selected

Floating refinery 2nd option to remove 2 floaters from a card did not check for whether there is any eligible cards with 2+ floaters on it

![Screenshot 2024-08-08 224824](https://github.com/user-attachments/assets/07e04ca4-7592-42db-b231-5c75ebdbafb2)
no eligible cards with floater

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s303b233c9f14",
  "color": "red",
  "step": 23,
  "version": "eced6f5",
  "builtAt": "Thu, 08 Aug 2024 04:39:36 GMT",
  "browser": "Chrome 127",
  "language": "en",
  "experimental_ui": true
}

**Comment by kberg** [comment]
Refresh your browser, and you should be OK.
