### ISSUE TITLE
World Government Advisor locks the game

### ISSUE THREAD

**Issue by GrankinAlexey** [terraforming-mars/terraforming-mars#6926]
1. The "World Government Advisor" action is possible when Mars is terraformed, however, it requires choosing from 0 options. It is not possible to continue the game because of that.
2. Solo mode, Preludes(2), World Government Advisor, Use its action after all parameters are maxed out.
3. ![image](https://github.com/user-attachments/assets/1ed86e14-fc19-49ca-80ec-a72069542ebb)
![image](https://github.com/user-attachments/assets/37cf60ff-2f94-4bfb-ba32-7b25a12554f7)
4. 
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s36a41205982f",
  "color": "green",
  "step": 26,
  "version": "3b00cce",
  "builtAt": "Fri, 09 Aug 2024 19:32:02 GMT",
  "browser": "Chrome 127",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Thanks. I'll fix that tonight and you'll be able to finish the game. Sorry
about that.
