### ISSUE TITLE
Cultural metropolis 

### ISSUE THREAD

**Issue by next86** [terraforming-mars/terraforming-mars#6933]
![brave_screenshot_terraforming-mars herokuapp com (5)](https://github.com/user-attachments/assets/3380da3d-fd5b-4376-bd2c-f189d21fadc5)
Please include:
1. A clear and concise description of the bug.
game link: https://terraforming-mars.herokuapp.com/the-end?id=pf347b0f80a57
In the 10th generation of the game, I received the "Cultural metropolis" project card. I couldn't use it despite having two delegates in Unity, having the resources to use it, and having space on the board to place a city.
3. Clear steps to reproduce, and the expected behavior.
In generation 10, I already had two delegates in Unity from previous generations. By playing a card above 20ME, I received an additional project card thanks to the previously thrown "Spin-off Department" card, and it was the "Cultural metropolis" card. However, I couldn't use it, even though I had the resources to deploy it, 2 delegates in Unity, and space on the board to build a city. There's only one thing I'm not sure about - whether I had enough free delegates. The "Cultural metropolis" card sends two more. But should this block the issuance of the card? It would be logical to expose as much as possible and lose the rest (as with terraforming Mars - heat, oceans, O2).
4. Any screenshots
5. Any information from  the Bug Report Dialog
I couldn't use the card so no error report either

Thank you in advance for your efforts to make this game possible and it works incredibly well, thanks to which I have a lot of fun with my friends :) best regards

**Comment by maserion** [comment]
It looks like you had only 1 free delegate and due to this you cannot play this card.
![image](https://github.com/user-attachments/assets/2e72fb93-6905-4c89-82da-34b1720fad35)

**Comment by kberg** [comment]
Thanks, I'm closing this. If you have more information to add, I'll read it.
