### ISSUE TITLE
Prelude 2: Floating Refinery bug (cannot add floaters to itself)

### ISSUE THREAD

**Issue by nabby101** [terraforming-mars/terraforming-mars#6935]
Hello,

It appears that the card Floating Refinery from the new Prelude 2 expansion is currently bugged.

It cannot activate the first ability to add a floater to itself if it has 0 floaters. Interestingly, it seems to have no issue if it already has a floater on the card.

I didn't get the debug info while I was in the game, but if this helps:

Game ID: gb7d87ac30fb9
https://terraforming-mars.herokuapp.com/the-end?id=p5c5462a6ea82

In the above game, it was played on gen 1, came into play with 1 floater on it, and then activated to add a second floater. On gen 2, it was activated to remove both floaters from itself to gain 1 titanium and 2 MC. After that, it did not show up under "perform an action from a played card."

This same bug also happened in a game I played yesterday.

Thanks for all you do.

![image](https://github.com/user-attachments/assets/d37dc017-39aa-4a7b-866c-d4118688ea6b)

**Comment by alfmorente** [comment]
I found the same bug in this game. It was a solo game, and if there isn't a floater in the card, the first action cannot be activated.
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=sf9bd88ae6e06",
  "color": "orange",
  "step": 52,
  "version": "787f31d",
  "builtAt": "Tue, 13 Aug 2024 03:42:05 GMT",
  "browser": "Chrome 127",
  "language": "es",
  "experimental_ui": false
}
