### ISSUE TITLE
Suitable Infrastructure Not Always Working - "Turn" v. "Action"?

### ISSUE THREAD

**Issue by Ruduen** [terraforming-mars/terraforming-mars#6936]
Please include:
1. A clear and concise description of the bug.
Suitable Infrastructure does not always seem to trigger. I've had it happen at least twice - once after a trade with Europa, and once at the point of this. The exact cause is uncertain, though I have a guess (see 2). 

2. Clear steps to reproduce, and the expected behavior.
Not completely sure - this may be related to taking two production-increasing actions on the same turn, but I have not yet been able to test this to confirm.

3. Any screenshots
None Available

4. Any information from  the Bug Report Dialog
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s3046884ebe16",
  "color": "blue",
  "step": 153,
  "version": "787f31d",
  "builtAt": "Tue, 13 Aug 2024 03:42:05 GMT",
  "browser": "Chrome 127",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Thanks. This isn't enough information to address things. I wish it was. If you have more information, please feel free to add comments to this bug and I will reopen it.
