### ISSUE TITLE
Bug: CEO Gordon didn't provide MC on building City

### ISSUE THREAD

**Issue by phillipfung3** [terraforming-mars/terraforming-mars#6937]
Pink player is using Gordon as CEO which provide MC when placing greenery or city tiles
but in this game the MC is not provided when placing city tiles
![image](https://github.com/user-attachments/assets/c8a6d890-e249-4ee2-8988-4f01a50baf3b)
![image](https://github.com/user-attachments/assets/14f026ac-cbf0-4a43-a43a-950988223b4d)
![image](https://github.com/user-attachments/assets/c0e96207-0b51-442a-8235-830ed779ac27)

placing greenery is functioning normally
![image](https://github.com/user-attachments/assets/23940d38-bd6d-4471-8d6a-59eb4afda7b9)

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s802b3c70795e",
  "color": "green",
  "step": 236,
  "version": "787f31d",
  "builtAt": "Tue, 13 Aug 2024 03:42:05 GMT",
  "browser": "Chrome 127",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
@phillipfung3 was recyclon at all involved in this, or was that just the screenshot?

**Comment by kberg** [comment]
I'm just testing this, and it seems to be happening.
![image](https://github.com/user-attachments/assets/4632f37a-e052-4441-9f90-17992fb7d1ce)

**Comment by kberg** [comment]
Oh I see! Ocean City was the problem. Which is hilarious because before I realized it, I saw that in the code. OK, this is an easy fix. Thanks for the report!
