### ISSUE TITLE
Prelude 2: Suitable Infrastructure bug (does not give rebate on power plant standard project)

### ISSUE THREAD

**Issue by nabby101** [terraforming-mars/terraforming-mars#6950]
Hello,

It appears that the prelude card "Suitable Infrastructure" is not giving the $2MC rebate when increasing energy production through the power plant standard project.

This bug does not appear to be related to all energy production, but I was unable to determine whether the standard project city action has the same problem. I would guess that it does.

Thanks

  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s660f8e4d8f05",
  "color": "orange",
  "step": 101,
  "version": "68153eb",
  "builtAt": "Sat, 24 Aug 2024 04:36:01 GMT",
  "browser": "Firefox 129",
  "language": "en",
  "experimental_ui": false

![image](https://github.com/user-attachments/assets/81db9ad4-c2b1-42b9-b0aa-2e810d35a80e)

**Comment by kberg** [comment]
I've confirmed that it is working, it is just not logged.
