### ISSUE TITLE
bug: Block attack with corruption when there is no attack

### ISSUE THREAD

**Issue by phillipfung3** [terraforming-mars/terraforming-mars#6962]
![IMG-20240902-WA0006](https://github.com/user-attachments/assets/b1a631a5-9386-4746-a12b-d27cbce456e7)
![Screenshot_20240902_104558_Samsung Internet](https://github.com/user-attachments/assets/08b3677c-12bb-4d33-baf8-8764c77fb880)

Grey player played road piracy and chose to attack Yellow and pink. It can be read from the log that a total of 6 steel have already been stolen
it then asked blue player whether he would wish to block with corruption despite he is not being targeted, and corruption can really be spent in this situation.
then I (green) was being asked the same question, I chose not to block, and nothing is lost.

the game have already been purged so I can't copy the gear thingy that you would need

**Comment by kberg** [comment]
Thanks. Easy fix.
