### ISSUE TITLE
Card "private security" effect 

### ISSUE THREAD

**Issue by Ercole1986** [terraforming-mars/terraforming-mars#6967]
Please include:
1. A clear and concise description of the bug.
At generation 6 player "Next" played card "private security". At generation 7 player "Josz" played card "small animals" and choose player "Next" to decrease his plant production what shouldn'd be possible becouse player "Next" has protection for basic resources production (card description: "OPPONENTS MAY NOT REMOVE YOUR BASIC RESOURCE PRODUCTION"). 

2. Clear steps to reproduce, and the expected behavior.
🕑Josz played SMALL ANIMALS
🕑Josz's megacredits amount increased by 2
🕑Next's plants production decreased by 1 by Josz

https://terraforming-mars.herokuapp.com/spectator?id=s939389a58377
3. Any screenshots
![Screenshot_20240910_151335_com huawei browser](https://github.com/user-attachments/assets/c5cdedc8-7478-4805-8320-10d53fe81884)
4. Any information from  the Bug Report Dialog
🕑Josz played SMALL ANIMALS
🕑Josz's megacredits amount increased by 2
🕑Next's plants production decreased by 1 by Josz

Best regards, player Next :)

**Comment by kberg** [comment]
Did this game include the Private Security card without the Pathfinders expansion? There's an optimization in the code to include omit this behavior when Pathfinders is out of play.

**Comment by kberg** [comment]
Thanks. This is actually not a bug. Private Security only protects a player's production, for standard resources and not other resources.

**Comment by Ercole1986** [comment]
Yes, the "private security" card was added separately, without the
Pathfinder expansion. So I understand that the aforementioned code did not
work correctly because it did not prevent the addition of this card?

pt., 13 wrz 2024 o 22:14 Robert Konigsberg ***@***.***>
napisał(a):

**Comment by kberg** [comment]
No, it worked correctly. Private Security does not protect animals. I just fixed a separate issue.
