### ISSUE TITLE
Game length reduced to 10 days

### ISSUE THREAD

**Issue by Dienekes7** [terraforming-mars/terraforming-mars#6969]
Hi, 

I play this great game on your great platform with 3 friends. About a year ago we were having some difficulties with lost games when the time to play them was reduced to 10 days. We were losing perhaps 8 of 10. You, helpfully, extended that out to 15 days and then we lost maybe 1 game total. It would seem that the game length has again reduced to 10 days.

Is there any possibility of extending it again to 15 days please?  It would enable the 4 of us, who are based in all corners of the globe, to continue to play and finish the game.

thanks and kind regards, Neil

**Comment by kberg** [comment]
Here's more about the problem: https://discord.com/channels/737945098695999559/743789409396195329/1280711242914463808

and also 

https://discord.com/channels/737945098695999559/743789409396195329/1282460913345101958

In short this isn't going to happen for some time. I am sorry about that.

**Comment by Dienekes7** [comment]
Thanks for getting back to me. Sorry, i don't use discord. I assume that games, especially solo games, get left open after a bad opening draw, and create a backlog on your servers. Perhaps if games are not touched in say 3 days they could be purged. If there is no action in 3 days it is likely the game is forgotten. 

Sad to hear this is not going to happen for sometime, can't see our 4 player games being done in 10 days.

thanks, Neil

**Comment by kberg** [comment]
Abandoned solo games aren't big source of space. But I can understand why
you might think so.
