### ISSUE TITLE
Nomads can be moved to a space reserved by Arcadian Communities

### ISSUE THREAD

**Issue by lostgrail** [terraforming-mars/terraforming-mars#6971]
You can move Nomads marker onto a space reserved by Arcadian Communities. The wording of Nomads is explicitly “non-reserved, empty area”, so this behaviour is incorrect.

The initial placement is correct, I was blocked in placing the nomads by my Arcadian markers.

Before moving Nomads (note Nomads is already in an illegal placement):
![IMG_7986](https://github.com/user-attachments/assets/64a4053d-b6f6-4dff-930c-9b8bda798c2b)

After moving the Nomads:
![IMG_7987](https://github.com/user-attachments/assets/a40c3ddc-9412-4ff6-ab88-aa02c78176c5)

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s675f955a0dca",
  "color": "red",
  "step": 78,
  "version": "7ac1cb2",
  "builtAt": "Fri, 13 Sep 2024 20:23:24 GMT",
  "browser": "Safari 17",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Thanks. It'll be a while before I fix this. But I'll be happy to get a PR
that does so.

**Comment by lostgrail** [comment]
No rush on my end. I just submit bugs as I find them :)

**Comment by Borbarad2** [comment]
And I can add: 
Bug report Mars Nomads: You could still move your mars nomads onto hazard tiles.
{
  "url": "http://terraforming-mars.herokuapp.com/spectator?id=s2e6d11c43c96",
  "color": "red",
  "step": 471,
  "version": "a7ea436",
  "builtAt": "Sun, 08 Sep 2024 21:58:12 GMT",
  "browser": "Firefox 130",
  "language": "en",
  "experimental_ui": true
}
