### ISSUE TITLE
Aphrodite not adding Megacredits

### ISSUE THREAD

**Issue by ninjapixie87** [terraforming-mars/terraforming-mars#6974]
Not getting Megacredits from the card "Aphrodite" when raising Venus terraforming one step. I also had the card "Venus Contract" in play, and was getting credits from that one.

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=sbdbff6e98eee",
  "color": "red",
  "step": 45,
  "version": "7ac1cb2",
  "builtAt": "Fri, 13 Sep 2024 20:23:24 GMT",
  "browser": "Chrome 128",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Aphrodite does reward MC. It just doesn't log it.
