### ISSUE TITLE
Ares rulebook link in wiki is broken

### ISSUE THREAD

**Issue by nyddogghr** [terraforming-mars/terraforming-mars#6978]
Hi,
The link for the ares rulebook in the wiki (https://github.com/terraforming-mars/terraforming-mars/wiki/Ares) is currently broken. The original file has been deleted.
Instead of using https://www.dropbox.com/s/3akc8e6lt3vqrdf/TM%20-%20Ares%20Expansion%20v1-0.pdf?dl=0, could you update it to https://drive.google.com/file/d/1oHS2MEqCASMlA9ZX0ICffVW9H5sOimRl/view? This is a very recent (today) link from the BGG post.
Could it be stored in the repo somewhere maybe, to avoid this issue in the future?

**Comment by kberg** [comment]
Done, thanks. Storing this stuff on gh is not a bad idea, but that's for another day.
