### ISSUE TITLE
Venus Shuttles + Floating Trade hub

### ISSUE THREAD

**Issue by PlovieJ** [terraforming-mars/terraforming-mars#6981]
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=sce48fad5346a#cards",
  "color": "green",
  "step": 188,
  "version": "7ac1cb2",
  "builtAt": "Fri, 13 Sep 2024 20:23:24 GMT",
  "browser": "Firefox 130",
  "language": "en",
  "experimental_ui": false
}

I played Venus Shuttles and had 1 card from the same expansion (prelude 2 beta) that fit the requirements (=venus card that can accept floaters). However, this one card is my prelude card (floating trade hub).
I expected the 2 floaters from playing the Venus Shuttles to be placed on that prelude card, but that didn't happen. There was no mention in the log or option for me to choose a card (I didn't have a regular card that fit the requirements).

As I type this out, I realize I might be absolutely stupid and that this requirement means that it's supposed to have a Venus tag and not that it comes from or is to be used with the venus expansion.
Usually this is actually worded more explicitly with "with a venus tag" or whatever, so this is misleading.

EDIT: this was in Generation 12

**Comment by kberg** [comment]
I believe that is correct "on a Venus card" means any card with a Venus
tag. Same for cards that say "On a Jovian card".
