### ISSUE TITLE
completely removing a player token from lunar mine by hostile takeover followed by lunar mine urbanization

### ISSUE THREAD

**Issue by phillipfung3** [terraforming-mars/terraforming-mars#6982]
so in this case, hostile takeover was played, then the taken over mine got converted to the mine habitat dual tile
![image](https://github.com/user-attachments/assets/de9409be-a9d6-466b-924d-f044ce1759b8)

and this is what happen
![image](https://github.com/user-attachments/assets/d0568837-5c9a-4222-8f12-4f47a6f61645)

now the original owner of the mine got completely kicked out, not sure is this how it is intended to work?

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=sd296616281ce",
  "color": "green",
  "step": 649,
  "version": "7ac1cb2",
  "builtAt": "Fri, 13 Sep 2024 20:23:24 GMT",
  "browser": "Chrome 128",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
I see you have stopped play. I can try to fix this if you give me a day,
and then roll it back. Maybe.

**Comment by phillipfung3** [comment]
thank you for fixing it
do you suggest we hold the game until you done fixing?
afterall for now it only affect scoring, I don't have anything to play that require I own a mine

**Comment by kberg** [comment]
I have a fix. If you are OK with leaving it alone and adjusting scores in your head, I'd be grateful. It would save me about 30 minutes.
