### ISSUE TITLE
Neptunian Power Consultants Unexpectedly Shows Dialog from Ice Asteroids Second Ocean

### ISSUE THREAD

**Issue by Ruduen** [terraforming-mars/terraforming-mars#6996]
Please include:
1. A clear and concise description of the bug.
Neptunian Power Consultants should not give a selection when there are not enough resources available. However, after another player played Ice Asteroid, I spent enough MC/Steel to buy the first ocean reaction, putting me down to 1 MC and 0 Steel. However, the dialog still asks whether or not I want to spend. (Actually spending is not possible

2. Clear steps to reproduce, and the expected behavior.
See Above

3. Any screenshots
Not available

4. Any information from  the Bug Report Dialog
 {
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s1109a23f9fc1",
  "color": "blue",
  "step": 57,
  "version": "0e10d8d",
  "builtAt": "Wed, 25 Sep 2024 22:00:13 GMT",
  "browser": "Chrome 129",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Thanks! That seems like a reasonable thing to fix.

**Comment by Borbarad2** [comment]
Seems similar, or identical to issue #6643

**Comment by kberg** [comment]
Yes, closing that one.
