### ISSUE TITLE
TR reduction due to Turmoil expansion not shown in log

### ISSUE THREAD

**Issue by tmtcam-042** [terraforming-mars/terraforming-mars#6997]
## Bug description:
TR loss due to Turmoil expansion not showing in log.

## Screenshot:
![image](https://github.com/user-attachments/assets/cc0dc30b-541e-4527-8e27-22e1da1267ec)

## Bug Dialog
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s9dc131f13c93#cards",
  "color": "green",
  "step": 48,
  "version": "0e10d8d",
  "builtAt": "Wed, 25 Sep 2024 22:00:13 GMT",
  "browser": "Chrome 129",
  "language": "en",
  "experimental_ui": true
}

**Comment by kberg** [comment]
That's correct. But, it's not a bad idea to add that.

**Comment by kberg** [comment]
We don't log _everything_ because it would consume too much storage and the log would get too busy. So we lean a lot on you just expecting most cards do what you think they should do.

But this seems OK to add.
