### ISSUE TITLE
Game frozen

### ISSUE THREAD

**Issue by Wookyee3** [terraforming-mars/terraforming-mars#7013]
No player could play and the time was frozen for all 4 players. 

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s270456115216",
  "color": "yellow",
  "step": 90,
  "version": "98529c9",
  "builtAt": "Sat, 05 Oct 2024 14:25:08 GMT",
  "browser": "Chrome 129",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Games are automatically deleted after nine days to save disk space. Next time you play you'll there's a message about that at the bottom of the page, and on the initial game page.
