### ISSUE TITLE
Compatibility issue of Comet Aiming and Whale

### ISSUE THREAD

**Issue by phillipfung3** [terraforming-mars/terraforming-mars#7024]
Setting:
In this case, I have both Whale and Comet aiming
all 9 sea tiles have been placed, there is 1 asteroid on comet aiming, and several titanium resources

Action:
then when I use the action of Comet aiming, it did not give the choice to place an ocean, and forced me to spend one titanium to add an extra asteroid on asteroid aiming.

I believe I should have a choice to pick place an ocean and to add an animal to whale?

p.s. 
I did an extra test on this
if I spend all my titanium, Comet aiming will be hidden from available action list

![image](https://github.com/user-attachments/assets/86fcb60b-6ab6-43bd-a6e7-889fc6a74d5c)
![image](https://github.com/user-attachments/assets/c883738f-550a-40a4-a164-0446dcef4094)

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s25511f6e737f#cards",
  "color": "green",
  "step": 601,
  "version": "802e83b",
  "builtAt": "Thu, 10 Oct 2024 02:58:35 GMT",
  "browser": "Chrome 129",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Thanks. Whale is a tough one, you know? I'll fix this one.

**Comment by phillipfung3** [comment]
predictable, afterall it's some weird mechanism
btw since water to europa action is still available despite all seas being placed, I believe comet aiming got something to be tweaked too?

**Comment by kberg** [comment]
Thanks for understanding.

Yeah, it's not terribly difficult. I'm just sorry it needs focus.
