### ISSUE TITLE
[Feature request] Warning when overspending on trading

### ISSUE THREAD

**Issue by Maelstrom1** [terraforming-mars/terraforming-mars#7034]
When a player doesn't have energy, it defaults to titanium rather than money. However, a player could have advanced alloys when unity is in power,  and it being the default can lead to waste. Could there be an internal check of player titanium cost vs money cost and throw up a popup when spending titanium is actually less cost effective?

**Comment by kberg** [comment]
Or prefer money to titanium?

**Comment by kberg** [comment]
I could see the argument both ways, really. After all, 3 titanium could be more valuable than 3 MC, but only if you're buying space cards. If not, the trade is a good place for it.

I''m not sure that a warning makes sense here. Take the odds of it being unintentional, and the amount of intrusion the player has to deal with to confirm that yes, they want to trade with titanium. You see my point?

**Comment by kberg** [comment]
@Maelstrom1 I'm going to close this for now, but if you respond, I'll see it.
