### ISSUE TITLE
Waited player color no longer displayed

### ISSUE THREAD

**Issue by nyddogghr** [terraforming-mars/terraforming-mars#7036]
Hi, I just started a new game this week and the icons showing the waited players are only grey. They used to work at least 3 weeks ago.
Here it is:
![image](https://github.com/user-attachments/assets/8e40ffd0-9aba-4a18-b27d-daed5d15d341)
I'm using experimental UI, but this also happens without it.
When several players are waited, there are several grey icons.
Regards

**Comment by frankmariette** [comment]
Hi @kberg, I looked into this issue and found that the cause is this change #7021. Specifically, the change here makes it so a class is added for a color instead of the color name. Can we revert this PR? If not I can make one to change it back to using a color.

**Comment by kberg** [comment]
No, I'm just going to fix it.

**Comment by frankmariette** [comment]
Thanks for fixing this!
