### ISSUE TITLE
Inconsistent behaviour by Board of Directors (it doesnt show the prelude card discarded)

### ISSUE THREAD

**Issue by peonmodel** [terraforming-mars/terraforming-mars#7042]
According to the latest changelog

> Warn when you can't play the prelude drawn by Board of Directors.

it doesnt show the prelude it discarded, unlike Business network, it shows the card but its unavailable to buy

when less than 12 mc, it shows the warning, yet after tapping, it just log "You drew and discarded a prelude" without showing the prelude card discarded

it will not have been a problem if there is a way to see the cards in the discard pile (not sure whats the official ruling, are those public knowledge? or at least let player see their own discard pile)

`{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s6538fe707f68",
  "color": "red",
  "step": 14,
  "version": "b55e56c",
  "builtAt": "Sun, 20 Oct 2024 04:55:26 GMT",
  "browser": "Chrome 130",
  "language": "en",
  "experimental_ui": true
}`

**Comment by kberg** [comment]
The discard pile is private knowledge. The player should know what they drew.

**Comment by kberg** [comment]
At least, the project discard pile is private knowledge. I don't think there's an official ruling about the prelude discard pile. But yeah this is correct.
