### ISSUE TITLE
It doesn't show "Play cards" action 

### ISSUE THREAD

**Issue by diegoamolina** [terraforming-mars/terraforming-mars#7045]
It's my turn, I have 8 megacredits and the card "Industrial Center" of cost 4 with no requisites, but the "Play cards" action doesn't show.
I already press F5 but still the same.

screenshot:
![Terra error](https://github.com/user-attachments/assets/8f2208d8-2b2a-4188-aa78-d2f6c9e78dee)

code:
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s8e64c635ba9c",
  "color": "green",
  "step": 3,
  "version": "b55e56c",
  "builtAt": "Sun, 20 Oct 2024 04:55:26 GMT",
  "browser": "Firefox 131",
  "language": "en",
  "experimental_ui": false
}

**Comment by Borbarad2** [comment]
You did not have a city at that moment in play. Thus you can't play Industrial Center

**Comment by kberg** [comment]
@diegoamolina if you think @Borbarad2's assessment is wrong, please add comments. Otherwise I am closing this issue.
