### ISSUE TITLE
Colonies selection doesnt show selected colony (the tick mark for selected card is missing)

### ISSUE THREAD

**Issue by peonmodel** [terraforming-mars/terraforming-mars#7067]
As seen in the screenshot below, the MIRANDA colony is selected for removal, but theres not being shown as being selected, there used to be a yellow highlight with the tick icon to indicate selection

![Screenshot 2024-10-30 105754](https://github.com/user-attachments/assets/f1271c01-baac-4153-b5f9-744a5bfc1521)

i am using the latest MS Edge browser, but problem also persist on Brave & Firefox, quite sure its the 28 October update that broke it

it doesnt work for ALL colonies selection, for initial removal, Aridor ability, trading & building colonies

```
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s8259b84f3c58",
  "color": "red",
  "step": 1,
  "version": "345e777",
  "builtAt": "Tue, 29 Oct 2024 00:57:57 GMT",
  "browser": "Chrome 130",
  "language": "en",
  "experimental_ui": true
}
```

**Comment by kberg** [comment]
Thanks. I am working on it. A recent change move an HTML element one level
down, which made it no longer match with the CSS that expected it to be at
its original level.

**Comment by kberg** [comment]
Rolled back the feature. :sob:
