### ISSUE TITLE
sabotage bypassed corruption check

### ISSUE THREAD

**Issue by phillipfung3** [terraforming-mars/terraforming-mars#7090]
Blue played Sabotage, it didn't ask if green want to block with corruption

![Screenshot_20241124_172302_Samsung Internet](https://github.com/user-attachments/assets/b4eb2fa5-6bff-42fa-8b5e-2e315ddeb045)

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=sc5b8f5c5d775",
  "color": "green",
  "step": 979,
  "version": "b7c0bf5",
  "builtAt": "Sun, 03 Nov 2024 19:05:44 GMT",
  "browser": "Chrome 125",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Thanks for your Underworld bugs. Some of them are pretty tough to fix. This isn't. :D
