### ISSUE TITLE
Playing a card when part of action cannot be done

### ISSUE THREAD

**Issue by phillipfung3** [terraforming-mars/terraforming-mars#7091]
In this game the all non reserved board space have been occupied and all underground resources identified
now pink have land claim and geological survey on hand, but both card cannot be played

for land claim it can be understood as the only effect of the card is unavailable
but for geological survey a player can still benefit from the data, just that there is no more tiles to be identified

so I would like to question if part of the card action cannot be done (except those that deduct resources or production), does it make it unplayable?

An example that i would like to bring up:
when all sea tiles have been placed, a card that would grant a sea tile can still be played.
There is a difference between the two cases where there is s still available spaces for sea tiles. But then the lack of sea tile should have made 'placing a sea tile' impossible, but that wouldn't kill the card

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=sc5b8f5c5d775",
  "color": "green",
  "step": 979,
  "version": "b7c0bf5",
  "builtAt": "Sun, 03 Nov 2024 19:05:44 GMT",
  "browser": "Chrome 125",
  "language": "en",
  "experimental_ui": false
}

**Comment by phillipfung3** [comment]
screen cap for your reference

![IMG-20241124-WA0002](https://github.com/user-attachments/assets/e311105a-87d8-42be-9ddc-2804f14235a0)
![Screenshot_20241124_172246_Samsung Internet](https://github.com/user-attachments/assets/71fd7705-4733-428a-9156-800b7f58726f)

**Comment by kberg** [comment]
Hi, thanks for your report.

The rules are pretty clear that all parts of an action must be completed, or the action cannot be taken. There are three exceptions:

1. Raising global parameters already at their maximum: https://github.com/terraforming-mars/faq/wiki#can-you-perform-an-action-that-raises-a-global-parameter-that-has-already-been-maxed-out
2. Removing resources from another player.
3. Adding resources of a type to cards when there are no cards.

Oceans do fall in that first group. Nothing else does. I understand what you are asking, but I do not think this issue merits a fourth exception.

I hope that makes sense.

I am closing this issue. Please feel free to add comments. I will read them.
