### ISSUE TITLE
This game id was g53dc01f19bf2. Неверно отработал финальный подсчет очков поиска жизни

### ISSUE THREAD

**Issue by Ros-lab-afk** [terraforming-mars/terraforming-mars#7121]
После первого успешного поиска жизни, второй был добавлен картой 'добавить юнит на карту, на которой уже есть юнит". После этого было ещё обнаружено 4 жизни. Но защитало только одну первую.

Лог ниже

[Export_07-12-2024_17-17.txt](https://github.com/user-attachments/files/18048887/Export_07-12-2024_17-17.txt)

**Comment by kberg** [comment]
"Search For Life" does not score like other cards. "Search for life" gives
3 points if it has one or more resources. It does not give 3 points for
each resource.
