### ISSUE TITLE
Generalist Milestone should require Corporate Era

### ISSUE THREAD

**Issue by puuj** [terraforming-mars/terraforming-mars#7123]
When the Corporate Era mode/expansion is not chosen, all players start with one of each production. This means the first player will immediately be able to claim Generalist. While not documented anywhere, I think Generalist should only be compatible when Corporate Era is selected.

**Comment by kberg** [comment]
https://github.com/terraforming-mars/faq/wiki#generalist-em says

> This requires at least 2 production in all 6 standard resources in the Standard game (as you start with 1 production of all resources) or at least 1 production in all 6 standard resources in the Corporate Era game at the time when the milestone is claimed.

Here is the code for Generalist:

```
  public getScore(player: IPlayer): number {
    let score = 0;
    const requiredProduction = player.game.gameOptions.corporateEra ? 0 : 1;

    if (player.production.megacredits > requiredProduction) score++;
    if (player.production.steel > requiredProduction) score++;
    if (player.production.titanium > requiredProduction) score++;
    if (player.production.plants > requiredProduction) score++;
    if (player.production.energy > requiredProduction) score++;
    if (player.production.heat > requiredProduction) score++;

    return score;
  }
```

Which, even if you can't read it fully, can see that corporate era is taken into account.

Closing. Feel free to reopen if you have further thoughts.
