### ISSUE TITLE
Tharsis Corp not receiving money if Rover Construction is also owned.

### ISSUE THREAD

**Issue by kziegler92** [terraforming-mars/terraforming-mars#7131]
When playing as Tharsis corporation, if also have the Rover Construction card enabled you will not receive 3 money from the tharsis corporation for placing a city. You will only get the 2 money from the rover construction card.

**Comment by kberg** [comment]
Click the gear on the bottom left of the app. Click "Report a bug" and
paste that information here. No screenshot necessary.

**Comment by kziegler92** [comment]
{
  "url": "https://golemfoundry.com/tm/player?id=p1e55d4ef43c8#cards",
  "color": "green",
  "step": 128,
  "version": "a69dd6430",
  "builtAt": "Wed, 11 Dec 2024 22:48:42 -0500",
  "browser": "Firefox 133",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Ah, sorry. This github project cannot support custom deployments.

**Comment by kberg** [comment]
Note that not every resource gain is logged. If you're just looking at the log, that's not going to be enough.

The log is kept short to keep the database size low and to reduce visual log pollution.
