### ISSUE TITLE
[Ares] "Land Claimed" hazard tile forcing adjacent greenery placement.

### ISSUE THREAD

**Issue by 167kamon** [terraforming-mars/terraforming-mars#7136]
I was playing as Arcadian Communities and reserved a dust storm tile, before I had placed any tile on the board. The game seemed to believe that that tile was my tile on the board, forcing me to place my greenery next to it. I couldn't even place over it.

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s5acfddadb98b",
  "color": "green",
  "step": 46,
  "version": "3686960",
  "builtAt": "Fri, 13 Dec 2024 19:45:57 GMT",
  "browser": "Firefox 133",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
What was the action that placed the greenery?

**Comment by 167kamon** [comment]
It was just converting plants to greenery. I started a new game and tried a standard project greenery and it happened then too.

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=sae51a0e34d8",
  "color": "red",
  "step": 2,
  "version": "3686960",
  "builtAt": "Fri, 13 Dec 2024 19:45:57 GMT",
  "browser": "Firefox 133",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment]
Thanks. I see the issue. Clever, and weird. Odd choice for you to land
claim a dust storm, but AOK.
